### ISSUE TITLE
labels aren't being added to node through Add RKE cluster

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#10909]
**Rancher versions:** 2.0 master 1/17

**Steps to Reproduce:**
1.  Go to Add a new node in RKE cluster
2.  Configure DO machine and add the label foo=bar
3.  Finish creating the RKE cluster

**Results:**  The label is not saving

**Comment by deniseschannon** [comment]
Since labels are put on machines before RKE is even called, I think this is more of a machine provisioning issue.

**Comment by StrongMonkey** [comment]
should be fixed in master now

**Comment by tfiduccia** [comment]
Version - 2.0 master 3/3
Not fixed - added a DO RKE cluster.  the template had labels, but when I created a cluster, it didn't add them.

**Comment by StrongMonkey** [comment]
@tfiduccia i made another fix which should address this issue now. The fix should be in master now.

**Comment by tfiduccia** [comment]
Version - 2.0 master 3/6
Verified fixed
