### ISSUE TITLE
Docker version for nodes are reported as "unknown".

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#11044]
Rancher versions: 2.0 build from jan 20 night

Steps to reproduce the problem:
Create RKE cluster and wait for it to become "Active".

In Nodes detail page , under "system information" notice that Docker version is reported as "unknown".

<img width="1018" alt="screen shot 2018-01-22 at 8 59 46 am" src="https://user-images.githubusercontent.com/4266958/35233495-2e1ef70c-ff53-11e7-9aa9-b08996f2023e.png">

API reports dockerVersion as "unknown".

http://<ip>:8080/v3/machines/cluster-t5tq9:machine-vhf2p
```
"os": {
"dockerVersion": "Unknown",
"kernelVersion": "4.4.0-109-generic",
"operatingSystem": "Ubuntu 16.04.1 LTS"
}
```

**Comment by StrongMonkey** [comment]
https://github.com/kubernetes/kubernetes/issues/57010 Related to this issue. Will properly get fixed in higher k8s version (> 1.8.4).

**Comment by deniseschannon** [comment]
@StrongMonkey still broken with k8s v1.8.5

<img width="582" alt="screen shot 2018-01-23 at 6 00 35 am" src="https://user-images.githubusercontent.com/11410997/35279743-d0d66f66-0002-11e8-8ed0-6b33302fd372.png">

**Comment by superseb** [comment]
It's fixed in v1.8.6 (https://github.com/rancher/rancher/issues/10653#issuecomment-353570123)

**Comment by deniseschannon** [comment]
Fixed with `k8s:v1.8.7-rancher1-1` image that is now the default image.

**Comment by deniseschannon** [comment]
Fixed in master when using the k8s:v1.8.7-rancher1-1 image.
