### ISSUE TITLE
Notifiers are showing in all clusters

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#11574]
**Rancher versions:** 2.0 master 2/22

**Steps to Reproduce:**
1.  Create a notifier
2.  Switch clusters and go to notifier page

**Results:**  the notifier is showing up.  Notifiers should be cluster specific and only show for the cluster I create it for.

**Comment by vimniky** [comment]
Fixed

**Comment by tfiduccia** [comment]
Version - 2.0 master 2/23
Not sure if this wasn't merged or not.  But it's still an issue

**Comment by tfiduccia** [comment]
Version - 2.0 master 2/26
Verified fixed
