### ISSUE TITLE
Workload ports not working when network policy is enabled

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#11726]
**Rancher versions:** 2.0 master 2/27

**Steps to Reproduce:**
1.  Create a RKE Digital Ocean cluster
2.  After it's fully active go to workloads
3.  Create a workload
  Image = nginx
  Add Port - Nodes running on Pod
  Source port = 1100
  Container port = 80
4.  Save and wait for workload pod to be active
5.  Go to Nodes and put <IP>:1100

**Results:**  Nginx never show up.

**Comment by alena1108** [comment]
Should get resolved once new UI for ports is in @loganhz

**Comment by loganhz** [comment]
@alena1108 `NodePort` works but `HostPort` doesn't create `publicEndpoint`. Can you have a look, please?

**Comment by alena1108** [comment]
@moelsayed @galal-hussein rancher side is resolved - k8s gets programmed correctly - could you validate that rke doesn't have any bugs preventing ports from access (similar to https://github.com/rancher/rancher/issues/11776)

**Comment by moelsayed** [comment]
@alena1108 The PublicEndpoint for HostPort workloads are still not being created. Also, pods created don't have a `hostPort` configuration

**Comment by moelsayed** [comment]
Also, HostPort endpoints don't work with network policy enabled.

**Comment by leodotcloud** [comment]
Root cause: The underlying k8s network policy has a default deny when a policy is configured and everything that's allowed needs to be whitelisted. Currently only pods from the same project are whitelisted. Hence any other traffic is denied.

**Comment by tfiduccia** [comment]
Version - 2.0 master 3/19
Verified fixed
