### ISSUE TITLE
DO cluster stuck in "removing" state(waiting on controller.cattle.io/cluster-scoped-gc) for ever.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#12054]
**Rancher versions: v2.0.0-alpha21

Steps to reproduce the problem:
Had created a cluster with 1 DO host.
Had created many projects and deployed few workloads on them.
Noticed that there were 2 hosts at some point , 1 in "Unavailable" state and 1 in "active" state.
Removed this cluster.
Node is stuck in "removing" state forever with error message - "waiting on controller.cattle.io/cluster-scoped-gc"

**Comment by sangeethah** [comment]
```
2018-03-08T04:38:55.065149958Z 2018/03/08 04:38:55 [ERROR] problem retrieving user for CRTB map[removed:2018-03-08T04:38:54Z annotations:map[lifecycle.cattle.io/create.cluster-crtb-sync_cluster-pxlwv:true lifecycle.cattle.io/create.mgmt-auth-crtb-controller:true] clusterId:cluster-pxlwv .removed:true namespaceId:cluster-pxlwv state:removing type:/v3/schemas/clusterRoleTemplateBinding creatorId:user-ck2dj uuid:e15f74c7-2268-11e8-a124-0242ac110002 id:cluster-pxlwv:clusterroletemplatebinding-hl5j7 roleTemplateId:cluster-member transitioning:yes transitioningMessage:waiting on controller.cattle.io/mgmt-auth-crtb-controller created:2018-03-08T00:37:28Z name:clusterroletemplatebinding-hl5j7 userId:user-frzrq] from cache during CRTB transformation: user.management.cattle.io "user-frzrq" not found
2018-03-08T04:38:55.074021074Z 2018/03/08 04:38:55 [ERROR] problem retrieving user for CRTB map[name:clusterroletemplatebinding-k4gpm namespaceId:cluster-pxlwv clusterId:cluster-pxlwv roleTemplateId:cluster-owner creatorId:user-ck2dj id:cluster-pxlwv:clusterroletemplatebinding-k4gpm transitioningMessage:waiting on controller.cattle.io/mgmt-auth-crtb-controller state:removing transitioning:yes uuid:0cd0ad28-2269-11e8-a124-0242ac110002 userId:user-qvllk created:2018-03-08T00:38:41Z removed:2018-03-08T04:38:54Z annotations:map[lifecycle.cattle.io/create.cluster-crtb-sync_cluster-pxlwv:true lifecycle.cattle.io/create.mgmt-auth-crtb-controller:true] .removed:true type:/v3/schemas/clusterRoleTemplateBinding] from cache during CRTB transformation: user.management.cattle.io "user-qvllk" not found
2018-03-08T04:38:55.080870225Z 2018/03/08 04:38:55 [ERROR] problem retrieving user for CRTB map[removed:2018-03-08T04:38:55Z type:/v3/schemas/clusterRoleTemplateBinding clusterId:cluster-pxlwv state:removing name:clusterroletemplatebinding-lk9b7 creatorId:user-bb8rl uuid:28769a96-2268-11e8-a124-0242ac110002 roleTemplateId:cluster-member id:cluster-pxlwv:clusterroletemplatebinding-lk9b7 transitioning:yes created:2018-03-08T00:32:18Z .removed:true annotations:map[lifecycle.cattle.io/create.cluster-crtb-sync_cluster-pxlwv:true lifecycle.cattle.io/create.mgmt-auth-crtb-controller:true] userId:user-mqtmq transitioningMessage:waiting on controller.cattle.io/mgmt-auth-crtb-controller namespaceId:cluster-pxlwv] from cache during CRTB transformation: user.management.cattle.io "user-mqtmq" not found
2018-03-08T04:38:55.088399268Z 2018/03/08 04:38:55 [INFO] cluster [cluster-pxlwv] provisioning: [hosts] Removing cleaner container on host [159.65.47.116]
2018-03-08T04:38:55.100849588Z 2018/03/08 04:38:55 [ERROR] problem retrieving user for CRTB map[state:removing uuid:170d0cdd-2269-11e8-a124-0242ac110002 type:/v3/schemas/clusterRoleTemplateBinding namespaceId:cluster-pxlwv id:cluster-pxlwv:clusterroletemplatebinding-m84kr name:clusterroletemplatebinding-m84kr roleTemplateId:cluster-member creatorId:user-qvllk transitioning:yes removed:2018-03-08T04:38:55Z annotations:map[lifecycle.cattle.io/create.mgmt-auth-crtb-controller:true lifecycle.cattle.io/create.cluster-crtb-sync_cluster-pxlwv:true] clusterId:cluster-pxlwv userId:user-f68cj .removed:true transitioningMessage:waiting on controller.cattle.io/mgmt-auth-crtb-controller created:2018-03-08T00:38:58Z] from cache during CRTB transformation: user.management.cattle.io "user-f68cj" not found
```

**Comment by Rwalker83** [comment]
I also have this issue. This was a brand new cluster. It had had no workloads or containers ever deployed to it.

**Comment by cjellick** [comment]
@sangeethah do you recall if you ever removed users from this rancher deployment?

**Comment by cjellick** [comment]
Should be fixed with @nathan-jenan-rancher's user clean up code that was merged.
If you repro again, please keep the setup around for me to investigate

**Comment by sangeethah** [comment]
@cjellick This issue is still reproducible . But i dont see the error messages relating to  " problem retrieving user for CRTB map" . I had this cluster that was stuck in "updating" state because of this issue - https://github.com/rancher/rancher/issues/12220. When I tried to remove this cluster , It gets stuck in "removing" state for the same reason "waiting on controller.cattle.io/cluster-provisioner-controller"

<img width="1359" alt="screen shot 2018-03-23 at 12 25 43 pm" src="https://user-images.githubusercontent.com/4266958/37849543-548c367c-2e95-11e8-988a-8a9e7de04a27.png">

**Comment by alena1108** [comment]
@sangeethah seems like it's a different controller - cluster provisioner -removal process holding up the removal now. I'll look into it

**Comment by alena1108** [comment]
There were a couple of issues fixed on RKE side for connections not timing out. That *theoretically* could have caused cluster being stuck in Removing state:

https://github.com/rancher/rke/pull/446
https://github.com/rancher/rke/pull/445

@sangeethah if this issue happens again, could you include rancher logs from the moment cluster.remove command was issued? And reopen the issue.

**Comment by alena1108** [comment]
Looks like the "waiting on controller.cattle.io/cluster-provisioner-controller" issue is being tracked in https://github.com/rancher/rancher/issues/12254, closing this bug for now as initial issue `waiting on controller.cattle.io/cluster-scoped-gc` is not seen anymore
