### ISSUE TITLE
Unable to create persistent volume "Local Disk Path" from Rancher UI and API

### ISSUE THREAD

**Issue by mysim1** [rancher/rancher#12284]
**Rancher server version -** 
DockerHub: master (26 march 2018)

**Rancher agent version -**
DockerHub: master (26 March 2018)

**Steps to reproduce the problem in the Rancher UI:**
- Create a PKE Cluster
- Add Worker, Etcd, Controlplane node(s)
- Navigate to Cluster Dashboard / Storage / Persistent Volumes
- fill in form, make sure to select 'Local Disk Path'

**User is presented with this error message:**
```Validation failed in API: PersistentVolume "data" is invalid: spec: Required value: must specify a volume type```

**Steps to reproduce the problem in the Rancher API:**
because the UI creation generates the wrong JSON payload for the Rancher API to process, I have taken the liberty of correcting that payload and running 
```
curl -i -X POST https://rancherhost/v3/clusters/cluster-gdbhc/persistentvolume \
  -H "Content-Type: application/json" \
  -H "Authorization: Basic dG9rZW4tNGhtMng6czlkYnh6Zzg0bGw3ZjVtbXZtbTRsNjJwbmI3ZDhqOHN4c3Q2dHdsMm1xNTJ0NHY1a2M2cXJi" \
  --data-binary "./persistvolumes.json"
```

*** persistvolumes.json content: ***
```
{
  "type": "persistentVolume",
  "accessModes": ["ReadWriteOnce"],
  "name": "data",
  "local": {
    "type": "localObjectReference",
    "path": "/opt/rancher/volume"
  },
  "capacity": {
    "storage": "10Gi"
  }
}
```
API error (statuscode 422):
```
PersistentVolume \"data\" is invalid: [spec.local: Forbidden: Local volumes are disabled by feature-gate, metadata.annotations: Required value: Lo
cal volume requires node affinity]
```
Using Kubectl I could try to enable that feature-gate. But Kubectl isn't functional because of https://github.com/rancher/rancher/issues/12283

**Docker version: (`17.03.2`)**

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
ubuntu 16.04 LTS

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
Bare-metal

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single Node Rancher

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Default RKE

**Results:**
I did find out the specific pem file is missing.

**Comment by mysim1** [comment]
Any workaround? I prefer to continue experimenting with Rancher asap.

**Comment by Ilya-Kuchaev** [comment]
I can create one with
volume.yml
``` 
kind: PersistentVolume
apiVersion: v1
metadata:
  name: volume1
  labels:
    type: local
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/volume1"
```
kubectl create -f volume.yml

**Comment by huanga** [comment]
@deniseschannon @zionwu This one also looks like it is related to #12410

**Comment by zionwu** [comment]
@Ilya-Kuchaev @huanga The yaml file is for host path volume, which is the `Local Node Path` in Rancher UI and it is different from `Local Node Path` mentioned by @mysim1 .

**Comment by huanga** [comment]
@zionwu > I thought it was related because I thought the type filed was being eaten by some middle layer. Looks like I was wrong reading deeper into the details. My bad!

**Comment by jonasborn** [comment]
+1

**Comment by BalaBalaYi** [comment]
with 2.0.0 beta3 ，1.10 k8s, customer type on virtualmachine:
Local Node Dist shows:
![image](https://user-images.githubusercontent.com/23303886/39049447-0f93f938-44d4-11e8-8370-b2c5bbffbcea.png)

Local Node Path shows:
![image](https://user-images.githubusercontent.com/23303886/39049471-2525ef54-44d4-11e8-9701-9b0fb02a45d8.png)

**Comment by deniseschannon** [comment]
@zionwu this is fixed in master now, right?

**Comment by zionwu** [comment]
@deniseschannon This is a different issue. The one I fixed is for the `Local Node Path`, of which the yaml is [here](https://raw.githubusercontent.com/kubernetes/website/master/docs/tasks/configure-pod-container/task-pv-volume.yaml)

This issue is for the `Local Node Disk`, of which the yaml is [here](https://kubernetes.io/docs/concepts/storage/volumes/#local) . From the  error message `Local volumes are disabled by feature-gate, metadata.annotations: Required value: Local volume requires node affinity]` ,  it is saying to use this feature we have to enable it by setting the feature-gate `--feature-gates=PersistentLocalVolumes=true`.

**Comment by deniseschannon** [comment]
@mysim1 based on what I'm reading about feature-gates for PersistentLocalVolumes, it is turned on by default with k8s 1.10. 

Can you try again with k8s 1.10, which is available in Rancher 2.0.0

**Comment by jotolo** [comment]
This still happening in v2.0.2
![screenshot_20180527_111642](https://user-images.githubusercontent.com/6193238/40587610-882e99f6-619f-11e8-9f41-f5ce6bf0ed10.png)
This is what I'm using on my Ubuntu Server
![screenshot_20180527_111853](https://user-images.githubusercontent.com/6193238/40587629-ce9043ea-619f-11e8-9b5d-0f28108e1196.png)

**Comment by StrongMonkey** [comment]
closing as this is a duplicate of https://github.com/rancher/rancher/issues/13864
