### ISSUE TITLE
Broken ingress host path DNS validation in 2.0 UI

### ISSUE THREAD

**Issue by marcusianlevine** [rancher/rancher#12334]
**Rancher versions:**
rancher/server: 2.0.0.preview-23

**Infrastructure Stack versions:**
kubernetes: 1.8.9

**Docker version: (`docker version`,`docker info` preferred)**
17.3.2

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
Ubuntu 16.04.1 LTS

**Type/provider of hosts:**
AWS EC2

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single control plane host, single compute plane host

**Steps to Reproduce:**

Add a host to an Ingress with a `-` in the DNS name from the GUI

**Results:**
```Validation failed in API: Ingress.extensions "kubernetes-dashboard-kdsyu" is invalid: spec.backend.serviceName: Invalid value: "kube-system/kubernetes-dashboard-kdsyu": a DNS-1035 label must consist of lower case alphanumeric characters or '-', start with an alphabetic character, and end with an alphanumeric character (e.g. 'my-name', or 'abc-123', regex used for validation is '[a-z]([-a-z0-9]*[a-z0-9])?')```

Looks like the regex pattern needs an escape character to interpret the `-` inside the square brackets as a literal `-` instead of it's special meaning as a range

**Comment by vincent99** [comment]
The hyphen doesn't need to be escaped when it's at the beginning or end of range.  That error is straight from k8s, and because the value is `kube-system/kubernetes-dashboard-kdsyu` and slash is not allowed.  That field is for the default service to send requests that match no other rule too.

But I'm not sure how you got that value in the first place, that looks like something setting an old-style reference to `[stack name]/[service name]`.

**Comment by alena1108** [comment]
This issue should be fixed as UI now filters out workload/services from the different namespace (k8s doesn't support cross namespace linking for ingress services). With services/workload only from the same namespace, the issue should be gone.

@sangeethah @soumyalj can we re-test on the very latest.

**Comment by sangeethah** [comment]
Tested with latest build from master.

This issue is still reproducible.
Any update done to an ingress that has "Target Backend" set to "Service" fails with this error 

```	
Validation failed in API: Ingress.extensions "test1" is invalid: spec.rules[0].http.backend.serviceName: Invalid value: "default/newwork": a DNS-1035 label must consist of lower case alphanumeric characters or '-', start with an alphabetic character, and end with an alphanumeric character (e.g. 'my-name', or 'abc-123', regex used for validation is '[a-z]([-a-z0-9]*[a-z0-9])?')
```

Same as issue tracked in https://github.com/rancher/rancher/issues/12644

**Comment by alena1108** [comment]
Ok, here are the most simple steps to repro:

1) create ingress with *service*
2) Click edit. Do not change any params, just hit save. 

I've tried by modifying the path for service based ingress; there issue doesn't happen. NO issue is present for workload based ingress either.

**Comment by sangeethah** [comment]
Tested with latest build from mater.

Able to update ingress that has "Target Backend" set to "Service" successfully.
