### ISSUE TITLE
Unable to get past cluster creation when using vSphere provider.

### ISSUE THREAD

**Issue by shawnmbradley** [rancher/rancher#12384]
[controlPlane] Failed to bring up Control Plane: Failed to verify healthcheck: Failed to check https://localhost:6443/healthz for service [kube-apiserver].

I can connect to the console on the VM and get an OK response when using CURL.

Please let me know if there is more information I can provide.  I have been trying to deploy a cluster with multiple releases of Rancher2.0 for a few days now.

Things I have tried:
vSphere 6.5 cluster
vSphere 6.5 cluster, more resources per node in cluster
vSphere 6.5 cluster, a single node in cluster

I have also tried the items above on a single ESXi host.

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `master` UI: `v2.0.28` |
|Access|`local` `admin`|
|Route|`authenticated.cluster.index`|

**Comment by superseb** [comment]
Can you share the complete logging from the `rancher/server` container when this is attempted?

**Comment by jaikumarm** [comment]
am running into the same issue, on vsphere 6.0 cluster rancher 2.0 with boot2docker iso.

here is the failure logs from the rancher/server

`
E0405 19:39:50.688436       1 generic_controller.go:204] ClusterRoleTemplateBindingController cluster-mx6dk/creator [mgmt-auth-crtb-controller] failed with : couldn't create role cluster-owner: roles.rbac.authorization.k8s.io "cluster-owner" already exists
2018/04/05 19:39:50 [INFO] ClusterController cluster-mx6dk completed with dropped err: [cluster-provisioner-controller] failed with : waiting for etcd and controlplane nodes to be registered
2018/04/05 19:39:51 [INFO] ClusterController cluster-mx6dk completed with dropped err: [cluster-provisioner-controller] failed with : waiting for etcd and controlplane nodes to be registered
2018/04/05 19:39:51 [INFO] ClusterController cluster-mx6dk completed with dropped err: [cluster-provisioner-controller] failed with : waiting for etcd and controlplane nodes to be registered
2018/04/05 19:39:51 [INFO] ClusterController cluster-mx6dk completed with dropped err: [cluster-provisioner-controller] failed with : waiting for etcd and controlplane nodes to be registered
2018/04/05 19:39:51 [INFO] ClusterController cluster-mx6dk completed with dropped err: [cluster-provisioner-controller] failed with : waiting for etcd and controlplane nodes to be registered
2018/04/05 19:39:51 [INFO] stdout: Creating CA: management-state/node/nodes/kube-test10-n1/certs/ca.pem
2018/04/05 19:39:52 [INFO] stdout: Creating client certificate: management-state/node/nodes/kube-test10-n1/certs/cert.pem
2018/04/05 19:39:52 [INFO] stdout: Running pre-create checks...
2018/04/05 19:39:58 [INFO] stdout: Creating machine...
2018/04/05 19:39:58 [INFO] stdout: (kube-test10-n1) Image cache directory does not exist, creating it at management-state/node/nodes/kube-test10-n1/cache...
2018/04/05 19:39:58 [INFO] stdout: (kube-test10-n1) Downloading management-state/node/nodes/kube-test10-n1/cache/boot2docker.iso from http://10.6.200.5/Linux/boot2docker.v17.03.2-ce.iso...
2018/04/05 19:39:58 [INFO] stdout: (kube-test10-n1) 0%!.(MISSING)..10%!.(MISSING)..20%!.(MISSING)..30%!.(MISSING)..40%!.(MISSING)..50%!.(MISSING)..60%!.(MISSING)..70%!.(MISSING)..80%!.(MISSING)..90%!.(MISSING)..100%!(NOVERB)
2018/04/05 19:39:58 [INFO] stdout: (kube-test10-n1) Generating SSH Keypair...
2018/04/05 19:40:04 [INFO] stdout: (kube-test10-n1) Creating VM...
2018/04/05 19:40:04 [INFO] stdout: (kube-test10-n1) Uploading Boot2docker ISO ...
2018/04/05 19:40:05 [INFO] stdout: (kube-test10-n1) adding network: DATA-VLAN200-DVPG
2018/04/05 19:40:05 [INFO] stdout: (kube-test10-n1) Reconfiguring VM
2018-04-05 19:40:06.950367 I | mvcc: store.index: compact 101348
2018-04-05 19:40:06.951677 I | mvcc: finished scheduled compaction at 101348 (took 1.001815ms)
2018/04/05 19:40:10 [INFO] stdout: (kube-test10-n1) Waiting for VMware Tools to come online...
2018/04/05 19:41:23 [INFO] stdout: (kube-test10-n1) Provisioning certs and ssh keys...
2018/04/05 19:41:23 [INFO] stdout: Waiting for machine to be running, this may take a few minutes...
2018/04/05 19:41:24 [INFO] stdout: Detecting operating system of created instance...
2018/04/05 19:41:24 [INFO] stdout: Waiting for SSH to be available...
2018/04/05 19:41:24 [INFO] stdout: Detecting the provisioner...
2018/04/05 19:41:25 [INFO] stdout: Provisioning with boot2docker...
2018/04/05 19:41:27 [INFO] stdout: Copying certs to the local machine directory...
2018/04/05 19:41:29 [INFO] stdout: Copying certs to the remote machine...
2018/04/05 19:41:31 [INFO] stdout: Setting Docker configuration on the remote daemon...
2018/04/05 19:41:33 [INFO] stdout: Checking connection to Docker...
2018/04/05 19:41:33 [INFO] stdout: Docker is up and running!
2018/04/05 19:41:33 [INFO] stdout: To see how to connect your Docker Client to the Docker Engine running on this virtual machine, run: docker-machine env kube-test10-n1
2018/04/05 19:41:34 [INFO] Generating and uploading node config kube-test10-n1
2018/04/05 19:41:34 [INFO] Provisioning cluster [cluster-mx6dk]
2018/04/05 19:41:34 [INFO] Creating cluster [cluster-mx6dk]
2018/04/05 19:41:34 [INFO] Generating and uploading node config
2018/04/05 19:41:34 [INFO] cluster [cluster-mx6dk] provisioning: Building Kubernetes cluster
2018/04/05 19:41:34 [INFO] cluster [cluster-mx6dk] provisioning: [dialer] Setup tunnel for host [10.6.203.225]
2018/04/05 19:41:34 [INFO] cluster [cluster-mx6dk] provisioning: [network] Deploying port listener containers
2018/04/05 19:41:34 [INFO] [network] Pulling image [alpine:latest] on host [10.6.203.225]
2018/04/05 19:41:35 [INFO] cluster [cluster-mx6dk] provisioning: [network] Successfully pulled image [alpine:latest] on host [10.6.203.225]
2018/04/05 19:41:35 [INFO] cluster [cluster-mx6dk] provisioning: [network] Successfully started [rke-etcd-port-listener] container on host [10.6.203.225]
2018/04/05 19:41:36 [INFO] cluster [cluster-mx6dk] provisioning: [network] Successfully started [rke-cp-port-listener] container on host [10.6.203.225]
2018/04/05 19:41:36 [INFO] cluster [cluster-mx6dk] provisioning: [network] Successfully started [rke-worker-port-listener] container on host [10.6.203.225]
2018/04/05 19:41:36 [INFO] cluster [cluster-mx6dk] provisioning: [network] Port listener containers deployed successfully
2018/04/05 19:41:36 [INFO] cluster [cluster-mx6dk] provisioning: [network] Running control plane -> etcd port checks
2018/04/05 19:41:37 [INFO] cluster [cluster-mx6dk] provisioning: [network] Successfully started [rke-port-checker] container on host [10.6.203.225]
2018/04/05 19:41:37 [INFO] cluster [cluster-mx6dk] provisioning: [network] Running control plane -> worker port checks
2018/04/05 19:41:37 [INFO] cluster [cluster-mx6dk] provisioning: [network] Successfully started [rke-port-checker] container on host [10.6.203.225]
2018/04/05 19:41:38 [INFO] cluster [cluster-mx6dk] provisioning: [network] Running workers -> control plane port checks
2018/04/05 19:41:38 [INFO] cluster [cluster-mx6dk] provisioning: [network] Successfully started [rke-port-checker] container on host [10.6.203.225]
2018/04/05 19:41:38 [INFO] cluster [cluster-mx6dk] provisioning: [network] Removing port listener containers
2018/04/05 19:41:39 [INFO] cluster [cluster-mx6dk] provisioning: [remove/rke-etcd-port-listener] Successfully removed container on host [10.6.203.225]
2018/04/05 19:41:39 [INFO] cluster [cluster-mx6dk] provisioning: [remove/rke-cp-port-listener] Successfully removed container on host [10.6.203.225]
2018/04/05 19:41:39 [INFO] cluster [cluster-mx6dk] provisioning: [remove/rke-worker-port-listener] Successfully removed container on host [10.6.203.225]
2018/04/05 19:41:39 [INFO] cluster [cluster-mx6dk] provisioning: [network] Port listener containers removed successfully
2018/04/05 19:41:39 [INFO] cluster [cluster-mx6dk] provisioning: [certificates] Attempting to recover certificates from backup on host [10.6.203.225]
2018/04/05 19:41:40 [INFO] cluster [cluster-mx6dk] provisioning: [certificates] Successfully started [cert-fetcher] container on host [10.6.203.225]
2018/04/05 19:41:40 [INFO] cluster [cluster-mx6dk] provisioning: [certificates] No Certificate backup found on host [10.6.203.225]
2018/04/05 19:41:40 [INFO] cluster [cluster-mx6dk] provisioning: [certificates] Generating CA kubernetes certificates
2018/04/05 19:41:41 [INFO] cluster [cluster-mx6dk] provisioning: [certificates] Generating Kubernetes API server certificates
2018/04/05 19:41:41 [INFO] cluster [cluster-mx6dk] provisioning: [certificates] Generating Kube Controller certificates
2018/04/05 19:41:42 [INFO] cluster [cluster-mx6dk] provisioning: [certificates] Generating Kube Scheduler certificates
2018/04/05 19:41:42 [INFO] cluster [cluster-mx6dk] provisioning: [certificates] Generating Kube Proxy certificates
2018/04/05 19:41:43 [INFO] cluster [cluster-mx6dk] provisioning: [certificates] Generating Node certificate
2018/04/05 19:41:44 [INFO] cluster [cluster-mx6dk] provisioning: [certificates] Generating admin certificates and kubeconfig
2018/04/05 19:41:44 [INFO] cluster [cluster-mx6dk] provisioning: [certificates] Generating etcd-10.6.203.225 certificate and key
2018/04/05 19:41:45 [INFO] cluster [cluster-mx6dk] provisioning: [certificates] Temporarily saving certs to control host [10.6.203.225]
2018/04/05 19:41:45 [INFO] [certificates] Pulling image [rancher/rke-cert-deployer:v0.1.1] on host [10.6.203.225]
2018/04/05 19:41:46 [INFO] cluster [cluster-mx6dk] provisioning: [certificates] Successfully pulled image [rancher/rke-cert-deployer:v0.1.1] on host [10.6.203.225]
2018/04/05 19:41:52 [INFO] cluster [cluster-mx6dk] provisioning: [certificates] Saved certs to control host [10.6.203.225]
2018/04/05 19:41:52 [INFO] cluster [cluster-mx6dk] provisioning: [reconcile] Reconciling cluster state
2018/04/05 19:41:52 [INFO] cluster [cluster-mx6dk] provisioning: [reconcile] This is newly generated cluster
2018/04/05 19:41:52 [INFO] cluster [cluster-mx6dk] provisioning: [certificates] Deploying kubernetes certificates to Cluster nodes
2018/04/05 19:41:57 [INFO] cluster [cluster-mx6dk] provisioning: Successfully Deployed local admin kubeconfig at [management-state/rke/rke-147228844/kube_config_cluster.yml]
2018/04/05 19:41:57 [INFO] [etcd] Pulling image [rancher/coreos-etcd:v3.0.17] on host [10.6.203.225]
2018/04/05 19:41:57 [INFO] cluster [cluster-mx6dk] provisioning: [certificates] Successfully deployed kubernetes certificates to Cluster nodes
2018/04/05 19:41:57 [INFO] cluster [cluster-mx6dk] provisioning: Pre-pulling kubernetes images
2018/04/05 19:41:57 [INFO] cluster [cluster-mx6dk] provisioning: Kubernetes images pulled successfully
2018/04/05 19:41:57 [INFO] cluster [cluster-mx6dk] provisioning: [etcd] Building up Etcd Plane..
2018/04/05 19:41:59 [INFO] cluster [cluster-mx6dk] provisioning: [etcd] Successfully pulled image [rancher/coreos-etcd:v3.0.17] on host [10.6.203.225]
2018/04/05 19:42:00 [INFO] cluster [cluster-mx6dk] provisioning: [etcd] Successfully started [etcd] container on host [10.6.203.225]
2018/04/05 19:42:00 [INFO] cluster [cluster-mx6dk] provisioning: [etcd] Successfully started [rke-log-linker] container on host [10.6.203.225]
2018/04/05 19:42:01 [INFO] cluster [cluster-mx6dk] provisioning: [remove/rke-log-linker] Successfully removed container on host [10.6.203.225]
2018/04/05 19:42:01 [INFO] [sidekick] Pulling image [rancher/rke-service-sidekick:v0.1.0] on host [10.6.203.225]
2018/04/05 19:42:01 [INFO] cluster [cluster-mx6dk] provisioning: [etcd] Successfully started Etcd Plane..
2018/04/05 19:42:01 [INFO] cluster [cluster-mx6dk] provisioning: [controlplane] Building up Controller Plane..
2018/04/05 19:42:01 [INFO] cluster [cluster-mx6dk] provisioning: [sidekick] Successfully pulled image [rancher/rke-service-sidekick:v0.1.0] on host [10.6.203.225]
2018/04/05 19:42:01 [INFO] [controlplane] Pulling image [docker.io/rancher/k8s:v1.8.9-rancher1-1] on host [10.6.203.225]
2018/04/05 19:42:37 [INFO] cluster [cluster-mx6dk] provisioning: [controlplane] Successfully pulled image [docker.io/rancher/k8s:v1.8.9-rancher1-1] on host [10.6.203.225]
2018/04/05 19:42:40 [INFO] cluster [cluster-mx6dk] provisioning: [controlplane] Successfully started [kube-apiserver] container on host [10.6.203.225]
2018/04/05 19:42:40 [INFO] cluster [cluster-mx6dk] provisioning: [healthcheck] Start Healthcheck on service [kube-apiserver] on host [10.6.203.225]
2018/04/05 19:43:31 [INFO] ClusterController cluster-mx6dk completed with dropped err: [cluster-provisioner-controller] failed with : backing off failure, delay: 30s
2018/04/05 19:43:31 [INFO] ClusterController cluster-mx6dk completed with dropped err: [cluster-provisioner-controller] failed with : backing off failure, delay: 30s
2018/04/05 19:44:01 [INFO] Provisioning cluster [cluster-mx6dk]
2018/04/05 19:44:01 [INFO] Creating cluster [cluster-mx6dk]
2018/04/05 19:44:01 [INFO] cluster [cluster-mx6dk] provisioning: Building Kubernetes cluster
2018/04/05 19:44:01 [INFO] cluster [cluster-mx6dk] provisioning: [dialer] Setup tunnel for host [10.6.203.225]
2018/04/05 19:44:01 [INFO] cluster [cluster-mx6dk] provisioning: [network] Deploying port listener containers
2018/04/05 19:44:02 [INFO] cluster [cluster-mx6dk] provisioning: [network] Successfully started [rke-worker-port-listener] container on host [10.6.203.225]
2018/04/05 19:44:02 [INFO] cluster [cluster-mx6dk] provisioning: [network] Port listener containers deployed successfully
2018/04/05 19:44:02 [INFO] cluster [cluster-mx6dk] provisioning: [network] Running control plane -> etcd port checks
2018/04/05 19:44:02 [INFO] cluster [cluster-mx6dk] provisioning: [network] Successfully started [rke-port-checker] container on host [10.6.203.225]
2018/04/05 19:44:03 [INFO] cluster [cluster-mx6dk] provisioning: [network] Running control plane -> worker port checks
2018/04/05 19:44:03 [INFO] cluster [cluster-mx6dk] provisioning: [network] Successfully started [rke-port-checker] container on host [10.6.203.225]
2018/04/05 19:44:03 [INFO] cluster [cluster-mx6dk] provisioning: [network] Running workers -> control plane port checks
2018/04/05 19:44:04 [INFO] cluster [cluster-mx6dk] provisioning: [network] Successfully started [rke-port-checker] container on host [10.6.203.225]
2018/04/05 19:44:04 [INFO] cluster [cluster-mx6dk] provisioning: [network] Removing port listener containers
2018/04/05 19:44:04 [INFO] cluster [cluster-mx6dk] provisioning: [remove/rke-etcd-port-listener] Successfully removed container on host [10.6.203.225]
2018/04/05 19:44:04 [INFO] cluster [cluster-mx6dk] provisioning: [remove/rke-cp-port-listener] Successfully removed container on host [10.6.203.225]
2018/04/05 19:44:04 [INFO] cluster [cluster-mx6dk] provisioning: [remove/rke-worker-port-listener] Successfully removed container on host [10.6.203.225]
2018/04/05 19:44:04 [INFO] cluster [cluster-mx6dk] provisioning: [network] Port listener containers removed successfully
2018/04/05 19:44:04 [INFO] cluster [cluster-mx6dk] provisioning: [certificates] Attempting to recover certificates from backup on host [10.6.203.225]
2018/04/05 19:44:09 [INFO] cluster [cluster-mx6dk] provisioning: [certificates] Certificate backup found on host [10.6.203.225]
2018/04/05 19:44:09 [INFO] cluster [cluster-mx6dk] provisioning: [reconcile] Rebuilding and updating local kube config
2018/04/05 19:44:09 [INFO] cluster [cluster-mx6dk] provisioning: Successfully Deployed local admin kubeconfig at [management-state/rke/rke-609555995/kube_config_cluster.yml]
2018/04/05 19:44:09 [INFO] cluster [cluster-mx6dk] provisioning: [reconcile] Reconciling cluster state
2018/04/05 19:44:09 [INFO] cluster [cluster-mx6dk] provisioning: [reconcile] This is newly generated cluster
2018/04/05 19:44:09 [INFO] cluster [cluster-mx6dk] provisioning: [certificates] Deploying kubernetes certificates to Cluster nodes
2018/04/05 19:44:14 [INFO] cluster [cluster-mx6dk] provisioning: Successfully Deployed local admin kubeconfig at [management-state/rke/rke-609555995/kube_config_cluster.yml]
2018/04/05 19:44:14 [INFO] cluster [cluster-mx6dk] provisioning: [certificates] Successfully deployed kubernetes certificates to Cluster nodes
2018/04/05 19:44:14 [INFO] cluster [cluster-mx6dk] provisioning: Pre-pulling kubernetes images
2018/04/05 19:44:15 [INFO] cluster [cluster-mx6dk] provisioning: Kubernetes images pulled successfully
2018/04/05 19:44:15 [INFO] cluster [cluster-mx6dk] provisioning: [etcd] Building up Etcd Plane..
2018/04/05 19:44:15 [INFO] cluster [cluster-mx6dk] provisioning: [etcd] Successfully updated [etcd] container on host [10.6.203.225]
2018/04/05 19:44:16 [INFO] cluster [cluster-mx6dk] provisioning: [etcd] Successfully started [rke-log-linker] container on host [10.6.203.225]
2018/04/05 19:44:16 [INFO] cluster [cluster-mx6dk] provisioning: [remove/rke-log-linker] Successfully removed container on host [10.6.203.225]
2018/04/05 19:44:16 [INFO] cluster [cluster-mx6dk] provisioning: [etcd] Successfully started Etcd Plane..
2018/04/05 19:44:16 [INFO] cluster [cluster-mx6dk] provisioning: [controlplane] Building up Controller Plane..
2018/04/05 19:44:16 [INFO] cluster [cluster-mx6dk] provisioning: [sidekick] Sidekick container already created on host [10.6.203.225]
2018/04/05 19:44:16 [INFO] cluster [cluster-mx6dk] provisioning: [healthcheck] Start Healthcheck on service [kube-apiserver] on host [10.6.203.225]
E0405 19:45:06.851316       1 generic_controller.go:204] ClusterController cluster-mx6dk [cluster-provisioner-controller] failed with : [controlPlane] Failed to bring up Control Plane: Failed to verify healthcheck: Failed to check https://localhost:6443/healthz for service [kube-apiserver] on host [10.6.203.225]: Get https://localhost:6443/healthz: Failed to dial ssh using address [10.6.203.225:22]: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain
2018/04/05 19:45:06 [INFO] ClusterController cluster-mx6dk completed with dropped err: [cluster-provisioner-controller] failed with : backing off failure, delay: 1m0s
2018-04-05 19:45:06.954172 I | mvcc: store.index: compact 101961
2018-04-05 19:45:06.955669 I | mvcc: finished scheduled compaction at 101961 (took 1.141036ms)
2018/04/05 19:45:07 [INFO] ClusterController cluster-mx6dk completed with dropped err: [cluster-provisioner-controller] failed with : backing off failure, delay: 1m0s
2018/04/05 19:45:21 [ERROR] Error during subscribe websocket: close sent
2018/04/05 19:45:21 [ERROR] Unknown error: websocket: close sent
`

then it tries re-provision the cluster a few times with the same result and then finally giving up.

**Comment by jbalonso** [comment]
I suggest pulling a fresh copy of `rancher/server:preview`, as I was stuck on this same issue just yesterday and I _think_ that's what got me past to the next one. I have a "working" config  with:

* vSphere provider
* `rancher/server:preview` with hash `8b58d90842b4`
* `boot2docker.iso` from url `https://github.com/boot2docker/boot2docker/releases/download/v17.03.2-ce/boot2docker.iso` (the same version you have)
* Kubernetes version `v1.8.10-rancher1-1`
* Network Provider: `Canal`
* Manually intervening in the booted `boot2docker` instance to run `mount --make-shared /`, which is a separate issue.

**Comment by deniseschannon** [comment]
vSPhere isn't working due to this: https://github.com/rancher/rancher/issues/12205

**Comment by gaui** [comment]
Yep, having the same issue on our vSphere. @jbalonso how do you intervene boot2docker to run extra commands?

**Comment by jbalonso** [comment]
@gaui : I opened a console via the vcenter web interface and typed them into the boot2docker root console. It's not exactly scalable.

**Comment by gaui** [comment]
@jbalonso Fixed in master d62c1a9

**Comment by krishofmans** [comment]
I tried the docker hub master tag yesterday on a vsphere 6.5 with a 17.03.2 boot2docker iso and it still failed to come up.

**Comment by gaui** [comment]
@krishofmans Try this one:
https://github.com/gaui/boot2docker-rootfs-mount-fix/releases/tag/17.03.2-ce

**Comment by krishofmans** [comment]
@gaui thanks that works, are there plans to provide this custom boot2docker as a default iso in rancher 2? Shouldn't the cluster provisioning work with all "defaults"? Or provide a better iso selection than there is now.

**Comment by gaui** [comment]
@krishofmans This should've been a part of  d62c1a9 in my opinion. 

Ping @superseb

**Comment by vincent99** [comment]
We're working on it, this isn't closed, and we never claimed it was fixed yet.

**Comment by deniseschannon** [comment]
With share-mnt fix in master, this shoud be fixed.

**Comment by gaui** [comment]
@deniseschannon I tried d62c1a9 and it didn't work. If you've got no changes other than that, then no it's not fixed. That's why I made https://github.com/gaui/boot2docker-rootfs-mount-fix/releases/tag/17.03.2-ce

**Comment by superseb** [comment]
@gaui There have been ~50 commits to `master` since that commit. If you can test the latest master, that would help.

**Comment by zchef2k** [comment]
I just pulled the rancher/server:master and it still appears to not work with v17.03.2-ce

`[workerPlane] Failed to bring up Worker Plane: Failed to start [kubelet] container on host [10.100.50.150]: Error response from daemon: linux mounts: Path /var/lib/rancher is mounted on / but it is not a shared mount.`

**Comment by gaui** [comment]
No, `rancher/server:master db4b81a3aef4` still fails with:

```
[workerPlane] Failed to bring up Worker Plane: Failed to start [kubelet] container on host [10.100.50.150]: Error response from daemon: linux mounts: Path /var/lib/rancher is mounted on / but it is not a shared mount.
```

Worked with https://github.com/gaui/boot2docker-rootfs-mount-fix/releases/tag/17.03.2-ce

**Comment by zchef2k** [comment]
@adingilloRancher I'm having a hard time here. What versions of b2d and kubernetes did you use in your validation exercise? I still get the mount failure with v17.03.2/v1.10.1in :master.

**Comment by adingilloRancher** [comment]
Reopening... as of today experiencing mount failure issue.  Was not present on 4/23/18

@zchef2k k8S v1.9.5 when validated on 4/20. (Still seeing failure on any version)

**Comment by adingilloRancher** [comment]
Build:
v2.0.0-rc1

Verified ability to create a new cluster and edit cluster. Verified ability to use any version of RKE to create cluster.
