### ISSUE TITLE
Validation error, add certificate to load balancer

### ISSUE THREAD

**Issue by Gambler13** [rancher/rancher#12644]
**Rancher versions:**
rancher/server: 2.0 beta

**Infrastructure Stack versions:**
Kubernetes 1.8.10

**Steps to Reproduce:**
1. Open existing load balancer (already contains 2 service backends, dex-idp and whoami, default namespace)
2. Edit load balancer
3. Add new certificate
4. Choose certificate
5. Save

**Results:**
Validation failed in API: Ingress.extensions "lb1" is invalid: [spec.rules[0].http.backend.serviceName: Invalid value: "default/dex-idp": a DNS-1035 label must consist of lower case alphanumeric characters or '-', start with an alphabetic character, and end with an alphanumeric character (e.g. 'my-name', or 'abc-123', regex used for validation is '[a-z]([-a-z0-9]*[a-z0-9])?'), spec.rules[0].http.backend.serviceName: Invalid value: "default/whoami": a DNS-1035 label must consist of lower case alphanumeric characters or '-', start with an alphabetic character, and end with an alphanumeric character (e.g. 'my-name', or 'abc-123', regex used for validation is '[a-z]([-a-z0-9]*[a-z0-9])?')]

![image](https://user-images.githubusercontent.com/24626221/38639421-6dd2d9ec-3dd1-11e8-8e3f-86a021e4fcbc.png)

The error doesn't occur, without certificate.
Perhaps related to #12334

**Comment by tkuther** [comment]
I can confirm this. Happens when the ingress already has a certificate, too.
1. create ingress with certificate -> saves successfully
2. edit that ingress (e.g. just change the target port) -> saving throws above mentioned error.

So editing an ingress seems broken when it already has a certificate set or you're going to add one.

**Comment by alena1108** [comment]
This issue should be fixed as UI now filters out workload/services from the different namespace (k8s doesn't support cross namespace linking for ingress services). With services/workload only from the same namespace, the issue should be gone.

@sangeethah @soumyalj can we re-test on the very latest.

**Comment by sangeethah** [comment]
Tested with latest build from master.

This issue is still reproducible:

Create a Ingress that has "Target Backend" set to "Service".
Edit load balancer and add a certificate to this ingress.

Ingress update fails with following errors:

```	
Validation failed in API: Ingress.extensions "mynewcheck" is invalid: spec.rules[0].http.backend.serviceName: Invalid value: "default/santest1": a DNS-1035 label must consist of lower case alphanumeric characters or '-', start with an alphabetic character, and end with an alphanumeric character (e.g. 'my-name', or 'abc-123', regex used for validation is '[a-z]([-a-z0-9]*[a-z0-9])?')
```

**Comment by alena1108** [comment]
Ok, here are the most simple steps to repro:

create ingress with service
Click edit. Do not change any params, just hit save.
I've tried by modifying the path for service based ingress; there issue doesn't happen. NO issue is present for workload based ingress either.

**Comment by sangeethah** [comment]
Tested with latest build from master.

This issue is still reproducible:

Create a Ingress that has "Target Backend" set to "Service".
Edit load balancer and add a certificate to this ingress. 
Able to add certificates successfully.
