### ISSUE TITLE
Active Directory authentication provider bind behavior deviates from standard approach

### ISSUE THREAD

**Issue by Overv** [rancher/rancher#12729]
**Rancher versions:**
rancher/server: v2.0.0-beta1
rancher/agent: N/A

**Behavior:**

The Active Directory authentication provider authenticates users the following way:

1. Bind as service account username with service account password
2. Bind as login username with login password
3. Look up the actual user entry with a filter `login attribute = username`

Whereas all other LDAP-related authentication projects do it this way:

1. Bind as service account username with service account password
2. Look up the DN of the user entry with a filter `login attribute = username`
3. Bind to the looked up DN using the login password

Why was the provider programmed to use the username directly as bind DN? This makes it pretty much impossible to use any login attribute other than `entryDN`. It also requires access control to be set up in such a way that all users can read all other users, because it needs access to the people OU. Normally only the service account needs this kind of access, because that's the context in which the user is actually looked up.

I would like to contribute to the Active Directory authentication provider to support this "normal" access pattern to make it compatible with standard LDAP systems. Is anyone else working on this or can I add this? I would also like to know the reasons for setting it up this way.

**Comment by cjellick** [comment]
Thanks for both the issue and the PR. Ultimately, I think your approach is better. But, we may not merge it right away because verifying and validating it will take cycles away from our QA team, which is currently under a time crunch.
I think as soon as we can free up a QA resource to test it, we'll merge and test it.

My understanding is that ultimately what you are trying to get at is general LDAP support. In the past (ie in our 1.6 version of rancher) we saw enough difference between AD and other LDAP providers to warrant a separate backend for it. But, when we pull in other LDAP providers, we'll look to the approach you suggest as a way to reuse more code across providres.

**Comment by cjellick** [comment]
closing as we've implemented specific support for other ldap providers

**Comment by Overv** [comment]
@cjellick I still don't understand why they have to be different plugins.
