### ISSUE TITLE
Port mapping does not update in UI after updating

### ISSUE THREAD

**Issue by zhaoyao91** [rancher/rancher#13426]
I created a workload with random port mapping, and then update it to a fixed port. but the UI still display the old one.

![image](https://user-images.githubusercontent.com/3808838/39902264-c8797bf4-54ff-11e8-8a27-28e7d6e337d4.png)

![image](https://user-images.githubusercontent.com/3808838/39902679-fc205818-5501-11e8-8ce0-6e3439c1f655.png)

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v2.0.0` UI: `v2.0.41` |
|Access|`local` `admin`|
|Route|`containers.index`|

**Comment by zhaoyao91** [comment]
:(, I found the actual port mapping does not change, still 31311...

**Comment by loganhz** [comment]
I can reproduce this issue in rancher/rancher:master 05/11.

Steps:

1. create a workload with a random NodePort
2. upgrade the workload with a specific node port

Results:

The new port is updated in API but publicEndpoints doesn't get updated.

![image](https://user-images.githubusercontent.com/21168270/39955207-9735ec68-55fd-11e8-98bf-6690239c6561.png)
![image](https://user-images.githubusercontent.com/21168270/39955209-9ac46ada-55fd-11e8-9d26-de173297c750.png)

**Comment by orangedeng** [comment]
We are not updating node port because this issues here `https://github.com/kubernetes/kubernetes/issues/58892`.
It will cause api server crash when updating node port. 
Code in here https://github.com/rancher/rancher/blob/master/pkg/controllers/user/workload/workload.go#L177

cc @alena1108

**Comment by dankeder** [comment]
According to the last comment in that issue (https://github.com/kubernetes/kubernetes/issues/58892#issuecomment-360947235) it is already fixed. Can the code for changing nodeport be uncommented now, or is there some other issue that's preventing that?

Btw. Rancher silently ignoring the nodeport change really took me by surprise and I spent a while figuring it out. I'm still in the phase of learning all the quirks so thanks for your comment and a link to the relevant part of code.

**Comment by alena1108** [comment]
@dankeder the fix is backported to k8s 1.8.6 that we currently use as a vendor dependency, going to update rancher + put a proper fix

**Comment by sangeethah** [comment]
Tested with v2.0.3-rc1

This issue is still reproducible.

When I remove the node scheduling rule as part of upgrade ,I dont see pods getting recreated.
Also when I view the workload details,  the node scheduling rules are still present.

**Comment by sangeethah** [comment]
Tested with v2.0.3-rc1

Able to upgrade a workload created with random port mapping to use a fixed port.
