### ISSUE TITLE
Change scale in UI breaks fieldRef env parameters

### ISSUE THREAD

**Issue by combl** [rancher/rancher#15178]
**Rancher versions:**
rancher/server or rancher/rancher: 2.0.7

I'm trying to setup a RabbitMq cluster. I'm defining env variables in yaml like so:

`env:
          - name: MY_POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: RABBITMQ_USE_LONGNAME
            value: "true"
          # See a note on cluster_formation.k8s.address_type in the config file section
          - name: RABBITMQ_NODENAME
            value: "rabbit@$(MY_POD_IP)"
          - name: K8S_SERVICE_NAME
            value: "rabbitmq"
          - name: RABBITMQ_ERLANG_COOKIE
            value: "mycookie" `

The initial start of the replicas is successfull. Now I increment the scale in kubectl with
`kubectl scale statefulset/rabbitmq --namespace=test-rabbitmq --replicas=3`

The new pod comes up everything is fine. Now I increment the scale in Rancher UI. The new pod fails to start:
`/usr/lib/rabbitmq/bin/rabbitmq-server: 1: eval: MY_POD_IP: not found`

I checked the yaml of the new pod:
`- env:
    - name: K8S_SERVICE_NAME
      value: rabbitmq
    - name: RABBITMQ_ERLANG_COOKIE
      value: mycookie
    - name: RABBITMQ_NODENAME
      value: rabbit@$(MY_POD_IP)
    - name: RABBITMQ_USE_LONGNAME
      value: "true"
    - name: MY_POD_IP
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: status.podIP`

Some kind of reordering happened. Is it necessary that the fieldRef variable is defined before its usage? Or is there another problem resulting in not finding MY_POD_IP? The reordering didn't happen when scaling via kubectl.

Kind regards
Chris

**Comment by loganhz** [comment]
Thanks for your report!

Fixed in v2.1.0

**Comment by loganhz** [comment]
Hi @FleischKarussel  `/reopen` doesn't work. Which version did you reproduce it?

**Comment by FleischKarussel** [comment]
Sorry, was about to write my experience, didn't expected an answer that quick. ;)

I still experience this issue with Rancher 2.1.0 with a deployment auf AWX 2.1.0 and its RabbitMQ.

Normal | Pulling | pulling image "ansible/awx_rabbitmq:3.7.4" | 5 minutes ago
Normal | Pulled | Successfully pulled image "ansible/awx_rabbitmq:3.7.4" | 5 minutes ago
Warning | BackOff | Back-off restarting failed container | a minute ago

`
/opt/rabbitmq/sbin/rabbitmq-server: eval: line 1: MY_POD_IP: not found
`

**Comment by loganhz** [comment]
How did you deploy the `ansible/awx_rabbitmq:3.7.4` ?  From a YAML file?

**Comment by FleischKarussel** [comment]
through the official ansible-playbook method using kubectl from another host.
awx_rabbitmq is part of that deployment.

https://github.com/ansible/awx/blob/2.1.0/installer/roles/kubernetes/templates/deployment.yml.j2

**Comment by loganhz** [comment]
@FleischKarussel Did you update the workload or scale the workload in Rancher UI ? 

Can you try to use kubectl to deploy the deployment and view YAML of the newly created workload ?

I guess `MY_POD_IP` is missing in the YAML.

**Comment by FleischKarussel** [comment]
@loganhz Yes I did scale the workload from 1 to 0 for testing reasons and because I had to modify the resource limits a little bit.
I'll let you know when I had a chance to redeploy the workload.

**Comment by loganhz** [comment]
@FleischKarussel Please click the version at bottom left corner to check if the User Interface version is `v2.0.77`
If it's not, please clear your browser cache.  There is an UI cache issue which has been fixed.

**Comment by FleischKarussel** [comment]
Seems to be looking good

Component | Version
-- | --
Rancher | v2.1.0
User Interface | v2.0.77
Helm | v2.10.0-rancher4
Machine | v0.15.0-rancher1-1

**Comment by loganhz** [comment]
I can not reproduce this issue in 2.1.0.

Please provide the YAML before you scale it down and the YAML after you scale it down and update the resource limit in Rancher UI
