### ISSUE TITLE
ConfigMaps not mapping Properly

### ISSUE THREAD

**Issue by Skater101b** [rancher/rancher#15186]
**Rancher versions:**
rancher/server or rancher/rancher: 2.0.6
rancher/agent or rancher/rancher-agent: 2.0.5

**Infrastructure Stack versions:**
healthcheck:
ipsec:
network-services:
scheduler:
kubernetes (if applicable):

**Docker version: (`docker version`,`docker info` preferred)**
17.5.0

**Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)**
Centos 7.5

**Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)**
VM esxi

**Setup details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single node master external DB

**Environment Template: (Cattle/Kubernetes/Swarm/Mesos)**
Kubernetes

**Steps to Reproduce:**
SETUP
1. Create a redis deployment using kubernetes/redis:v1 OR quay.io/smile/redis:4.0.2
2. Set the environment variable MASTER = true
3. Container launches successfully. 

ConfigMap
Create a configmap of either 

redis-configmap1
maxmemory 2mb
maxmemory-policy allkeys-lru

redis-configmap2
cluster-enabled yes
cluster-config-file node.conf

1. Edit Deployment
2. Volumes >> Add Mount >> ConfigMap

I can either choose all keys or select keys. When I choose all keys and put in redis.conf as the sub path to the /redis-master mount point. Redis can't start because the conf has an invalid declaration. This is because the redis.conf has only a single line in it. 

EXAMPLE redis.conf <-- using redis-configmap2
yes

That's it. Rancher seems to only put the value and skip the key. Funny thing, if I change my configmap to be this.
KEY .                        VALUE
cluster-enabled       cluster-enabled yes

Then it will actually put the entire line cluster-enabled yes and redis will start. So that's an issue.
but not the MAIN issue here. Getting to that.

I tried "All keys"

It did the same thing, it updated the redis.conf with just the value and not the key. 

BUTTT it's only updating the config with a single value from the configmap and ingoring all the rest.  That is the issue. Despite having 3 values in my config map, only one is being written to the file. 

This could be a config issue on my side, but it also overwrites the entire file. it's not appending. 

I can see in vanilla kubernetes that this works and my configmap redis-config looks like this.
apiVersion: v1
data:
  redis-config: |+
    maxmemory 2mb
    maxmemory-policy allkeys-lru

kind: ConfigMap
metadata:
  creationTimestamp: 2018-08-22T11:46:06Z
  name: example-redis-config
  namespace: default
  resourceVersion: "1992"
  selfLink: /api/v1/namespaces/default/configmaps/example-redis-config
  uid: f455e7fe-a600-11e8-a761-080027b183b4

In rancher, it doesn't have that redis-config: |+ which is what I think is causing it to overwrite the file. Except when I edit the yaml to match somewhat, it just adds redis-config as a new key value. 

Here is the rancher configMap where under data I have appendonly yes as the value so it actually puts the key and value and it's only putting one line in redis.conf "appendonly yes" Not the other three.

apiVersion: v1
data:
  appendonly: appendonly yes
  cluster-config-file: cluster-config-file nodes.conf
  cluster-enabled: cluster-enabled yes
kind: ConfigMap
metadata:
  annotations:
    field.cattle.io/creatorId: user-d72bt
  creationTimestamp: 2018-08-22T15:39:58Z
  name: redis-cluster
  namespace: ns-redis
  resourceVersion: "4338534"
  selfLink: /api/v1/namespaces/ns-redis/configmaps/redis-cluster
  uid: 9ffb8d55-a621-11e8-924e-00505683c6b7

**Results:**
Not what I expected. 

I read the docs and the next steps link takes me to deploying workloads. Which doesn't talk about configMaps. So I am a bit stuck here.

**Comment by vincent99** [comment]
We don't do anything special, it's a native config map.  You're creating two very different things though, 

> redis-configmap1
> maxmemory 2mb
> maxmemory-policy allkeys-lru

Is I assume you putting those into 2 rows in the UI.  So that's a map with many keys for individual config options and their corresponding values.

The one you're saying does work is 

> redis-config: |+
> maxmemory 2mb
> maxmemory-policy allkeys-lru

Which is a *single* key named `redis-config`, and a single (multiline) value that happens to be config keys and their various values as a string

**Comment by Skater101b** [comment]
I created a configMap in kubernetes using a file as the datasource that had two entries in it. 
maxmemory 2mb
maxmemory-policy allkeys-lru

The config map kubernetes produces for me has a single key and a multiline string as you mentioned.

When I add those two lines as separate entries in the Rancher UI. Each one being a key/value which makes sense to me. Rancher splits them up and doesn't work.  I can't imagine that the use case for configMaps was to simply allow a person to put a single entry into a single file while over writing it's contents. 
Either way that poses the question:
How does one get a multiline string to appear in a config file via a ConfigMap that Rancher creates via the UI? Doesn't seem possible, unless I am totally missing something here.

**Comment by Skater101b** [comment]
I would expect the name of the config to be the key and the key/value pairs defined within rancher as a multi-string line associated with it. 

So that I could apply all key value pairs to a config file. At the current moment it uses the key in key/value pairs as a key but forces you to put the actual "key/value" you want in the config file under the value. There also isn't a way to define a multiline string. I tried editing the yaml directly and it didn't work. Which leaves me with the ability to only add a single declarative value for a configuration in which the value defined in the ui is the actual key/value (confusing) This has be a defect right?

**Comment by vincent99** [comment]
`redis-config` isn't the name of the config map, even in your working example (`name: example-redis-config`).  It's a config map named "example-redis-config" which contains one key "redis-config" which has a multi-line string value.  You cannot generate the same output as that using multiple actual keys and values instead of one.

The value field in the UI accepts newlines.  Just hit enter.

**Comment by massimo-cannavo** [comment]
So this is what I did to get it to work. It's kind of a work around I guess.

**redis-config**
```
root@massimo-server:~# cat redis-config
maxmemory 2mb
maxmemory-policy allkeys-lru
```

Create a ConfigMap from the file above (**correct format**)
```
root@massimo-server:~# kubectl create configmap redis-config \
  --from-file=redis-config -n redis
   
configmap/redis-config created
```
Verify that the ConfigMap was created in the correct format.
```
root@massimo-server:~# kubectl get configmap redis-config -n redis -o yaml
apiVersion: v1
data:
  redis-config: |
    maxmemory 2mb
    maxmemory-policy allkeys-lru​
kind: ConfigMap
metadata:
  creationTimestamp: 2018-09-07T23:27:50Z
  name: redis-config
  namespace: redis
  resourceVersion: "2924"
  selfLink: /api/v1/namespaces/redis/configmaps/redis-config
  uid: a2d6342f-b2f5-11e8-845e-1a5afddf1632
```
Now it's time to deploy a Redis workload.
```
Docker Image: kubernetes/redis:v1
Environment Variables: Master = true
Volumes ConfigMap:
  Volume Name: redis-config
  Config Map Name: redis-config
  Items: Select Specific Keys
    Key: redis-config
    Path: redis.conf​
  Mount Point: /redis-master
```
Those are the settings that I configured when deploying the Redis workload. You can also confirm the output using kubectl.
```
root@massimo-server:~# kubectl get pod -n redis -o yaml
apiVersion: v1
items:
- apiVersion: v1
  kind: Pod
  metadata:
    annotations:
      cni.projectcalico.org/podIP: 10.42.0.14/32
    creationTimestamp: 2018-09-07T23:47:09Z
    generateName: redis-master-7d5b9cfd8b-
    labels:
      pod-template-hash: "3816579846"
      workload.user.cattle.io/workloadselector: deployment-redis-redis-master
    name: redis-master-7d5b9cfd8b-8wvgm
    namespace: redis
    ownerReferences:
    - apiVersion: extensions/v1beta1
      blockOwnerDeletion: true
      controller: true
      kind: ReplicaSet
      name: redis-master-7d5b9cfd8b
      uid: 55c467cf-b2f8-11e8-845e-1a5afddf1632
    resourceVersion: "4553"
    selfLink: /api/v1/namespaces/redis/pods/redis-master-7d5b9cfd8b-8wvgm
    uid: 55cabc5b-b2f8-11e8-845e-1a5afddf1632
  spec:
    affinity: {}
    containers:
    - env:
      - name: MASTER
        value: "true"​
      image: kubernetes/redis:v1
      imagePullPolicy: Always
      name: redis-master
      resources: {}
      securityContext:
        allowPrivilegeEscalation: false
        privileged: false
        readOnlyRootFilesystem: false
        runAsNonRoot: false
      stdin: true
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      tty: true
      volumeMounts:
      - mountPath: /redis-master
        name: redis-config​
      - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        name: default-token-bxbmz
        readOnly: true
    dnsPolicy: ClusterFirst
    nodeName: massimo-server
    restartPolicy: Always
    schedulerName: default-scheduler
    securityContext: {}
    serviceAccount: default
    serviceAccountName: default
    terminationGracePeriodSeconds: 30
    tolerations:
    - effect: NoExecute
      key: node.kubernetes.io/not-ready
      operator: Exists
      tolerationSeconds: 300
    - effect: NoExecute
      key: node.kubernetes.io/unreachable
      operator: Exists
      tolerationSeconds: 300
    volumes:
    - configMap:
        defaultMode: 256
        items:
        - key: redis-config
          path: redis.conf
        name: redis-config
        optional: false
      name: redis-config​
    - name: default-token-bxbmz
      secret:
        defaultMode: 420
        secretName: default-token-bxbmz
  status:
    conditions:
    - lastProbeTime: null
      lastTransitionTime: 2018-09-07T23:47:09Z
      status: "True"
      type: Initialized
    - lastProbeTime: null
      lastTransitionTime: 2018-09-07T23:47:19Z
      status: "True"
      type: Ready
    - lastProbeTime: null
      lastTransitionTime: 2018-09-07T23:47:09Z
      status: "True"
      type: PodScheduled
    containerStatuses:
    - containerID: docker://ff14b309c1c6e1330f2ba26511fd427032a59cdfcc31d961b2ceec03f9fc794d
      image: kubernetes/redis:v1
      imageID: docker-pullable://kubernetes/redis@sha256:8da3f7cbe05e3446215a6931f1c125c38bde03383145fcc3292319bab5b1a6cf
      lastState: {}
      name: redis-master
      ready: true
      restartCount: 0
      state:
        running:
          startedAt: 2018-09-07T23:47:19Z
    hostIP: 165.227.25.105
    phase: Running
    podIP: 10.42.0.14
    qosClass: BestEffort
    startTime: 2018-09-07T23:47:09Z
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
```

**Comment by deniseschannon** [comment]
Using v2.0.7, I was able to add a multiline ConfigMap using the UI as @vincent99 described. 

Talking with @massimo-cannavo, this was broken in v2.0.6 but is now fixed in v2.0.7.

**Comment by Skater101b** [comment]
I went from 2.0.6 to 2.0.8 and the issue still persists. 

I have a redis-config with multilines.
![redis1](https://user-images.githubusercontent.com/8505334/45495696-bf988080-b741-11e8-81f8-b974898b9131.png)


Then I have attached it to the deployment.
![redis2](https://user-images.githubusercontent.com/8505334/45495719-cde69c80-b741-11e8-948e-d42595be9925.png)


When I start redis I get this error.
![redis3](https://user-images.githubusercontent.com/8505334/45495725-d3dc7d80-b741-11e8-901b-98a306892a05.png)


That is indicating that it's taking "cluster-enabled yes" not as a key value but as a single key without a value and the error messages wraps it in quotes as if it's a single string. 

Am I missing something here?

**Comment by Skater101b** [comment]
I tried for the heck of it, commenting out the values in the config. 
#cluster-enabled yes 
etc
etc

and it worked, it added it to the redis.conf. Since it was commented out it all looks fine.
![redis4](https://user-images.githubusercontent.com/8505334/45496739-2028bd00-b744-11e8-9909-93e05fd631a6.png)


but if I don't comment it out, I get the error I got above.

**Comment by Skater101b** [comment]
I tried it without the directive cluster-enabled yes and it all works just fine. So you can DISREGARD THIS. 

Thanks for the help.
