### ISSUE TITLE
Rancher UI environment variables interpolation order

### ISSUE THREAD

**Issue by gferreux** [rancher/rancher#16148]
**Rancher versions:**
rancher/rancher:v2.0.6

**Environment Template: Kubernetes**

**Steps to Reproduce:**
Rancher ui order (and reorder) environment variables as simple (value=x) first then special (that use valueFrom) at the end.
If you define a simple variable that use interpolation of a special variable like:

```
- name: MEMCACHED_HOST
  valueFrom:
    fieldRef:
      apiVersion: v1
      fieldPath: status.hostIP
- name: MEMCACHED_URL
  value: $(MEMCACHED_HOST):5000
```

the order (that is necessary for the interpolation to work) is preserved if you Edit YAML, but when you Upgrade via the UI, the YAML will become:

```
- name: MEMCACHED_URL
  value: $(MEMCACHED_HOST):5000
- name: MEMCACHED_HOST
  valueFrom:
    fieldRef:
      apiVersion: v1
      fieldPath: status.hostIP
```

**Results:**
The interpolation fail and the container will see: `MEMCACHED_URL="$(MEMCACHED_HOST):5000"` without interpolation

gz#9725
gz#10539
gz#16638

gz#16888

**Comment by cjellick** [comment]
@StrongMonkey is this a UI issue or a backend catalog issue?

**Comment by StrongMonkey** [comment]
@cjellick most likely a type mapper issue in workload api. we don't sort the map base on name.

**Comment by ivanfilippov** [comment]
Looks like this was an issue in kubectl as well, but was fixed, see here: https://github.com/kubernetes/kubernetes/issues/40373

According to that issue, constant ordering of env variables is part of the kubernetes API spec.

**Comment by matfiz** [comment]
I could also reproduce it, still an issue in 2.2.1

**Comment by isikemre** [comment]
It's still an issue on v2.2.3.
After saving environment variables from the UI, the order changes.
Then k8s cannot use $(SOME_ENV_VAR) (because the it's decelerated above)

**Comment by switchboardOp** [comment]
Still an issue in v2.2.4

**Comment by digger18** [comment]
Will this ever be fixed?

**Comment by junkiebev** [comment]
Still in issue on 2.3.2

**Comment by cjellick** [comment]
I think it fell off our radar. Thanks for the bump. I'll ping the necessary ppl to try to get this prioritized.

**Comment by cjellick** [comment]
@vincent99 @westlywright do you know of some technical reason why we have to reorder these?

**Comment by vincent99** [comment]
@cjellick Environment is a map in the API.  So there isn't really an order to reorder, but JS preserves key order so I would guess it's probably Go breaking it-as-a-service.

**Comment by ecarlotti** [comment]
> @vincent99 @westlywright do you know of some technical reason why we have to reorder these?

@cjellick sorry to bump into the conversation, but the technical reason in my opinion is that if not correctly ordered, this can break environment values assignment, giving them incorrect values. This may make containers that are working in other environments not to work in Rancher without customization.

A simple example would be to compose a URI var from a list of environment variables stored into a config map or a secret. In the default ordering, as it is now, config maps and secrets are posted AFTER the container environment variables in the .yaml file, so by the time the environment vars are being defined in the container, variables from config maps and secrets do not exist yet, so variables dependency has to be taken into consideration when writing the .yaml file, as kubernetes  doesn't do that automatically.

Look at the attached [nosqlclient-clone.yaml](https://github.com/rancher/rancher/files/3874172/nosqlclient-clone.yaml.txt) file for this exact situation: I simply cloned a working workload (where I had customized the variables order so that it worked) and it doesn't works anymore because of the ordering variables were defined does not allow it to work.

**Comment by dorsany** [comment]
if it's not possible to preserve the order of the environments, is it possible atleast to sort the environment variables that has ```fieldPath```  to be first in the ```env:``` list?
such as: ```fieldPath: metadata.namespace```,```fieldPath: metadata.name```, ```fieldPath: status.podIP```, ```fieldPath: status.hostIP``` and etc...

in that case it will fix the issue above:
```
- name: MEMCACHED_HOST
  valueFrom:
    fieldRef:
      apiVersion: v1
      fieldPath: status.hostIP
- name: MEMCACHED_URL
  value: $(MEMCACHED_HOST):5000
```

**Comment by vincent99** [comment]
Craig was asking if there's a reason that _we_ are reordering them, and the answer is no, but the data structure it's exposed as is a map which has no actual "order".  To fix it it needs to be expressed in our API as an array (and therefore ordered) of objects instead of a map.

**Comment by ecarlotti** [comment]
@vincent99, thanks a lot for the clarification and sorry for the misinterpretation of Craig's question - It is hard for us outside the project and without knowledge of the actual code to clearly understand those. In this case I could have understood but I missed it completely...

Still trying to contribute and in order to be 100% fail proof, besides keeping the order you'll need to check for dependencies between all env vars / secrets / config maps in order to discover the proper declaration order.

Again, thanks for the hard work and for the amazing product - From now on I'll do my best to help and stay away from the tech talks so I don't disturb you guys anymore!

**Comment by vincent99** [comment]
Once it's an array, it would be up to the user to express them in an order that resolves the way they want (as it is in the normal k8s API).  There's no reason for us to get involved trying to detect and dependencies and reorder things.

I do not think that is actually even possible in the general case, because I think you can technically redefine a variable midway through, like (pseudo-syntax)

```
- A=foo
- B=$A
- A=bar
- C=$A
```

should eventually result in `A=bar`, `B=foo`, `C=bar` being given to the pod.

**Comment by ecarlotti** [comment]
Got it, and you're of course right. The only thing I would like to point out is about secrets and config maps. As far as I'm aware of, those never have any inputs coming from environment vars. If that assumption is correct, both should be declared always PRIOR to environment vars also as ordered lists as you suggest, and if I may, secrets should always be declared FIRST as they can be used by both config maps and env vars but have no dependencies at all.

**Comment by Angelinsky7** [comment]
I excactly hit what @ecarlotti said.... It would be cool to have first secrets, configs then envs as a first step (feature). Then maybe a custom ordering where user could choose.

**Comment by fbrbovic** [comment]
Is there a workaround for this issue?

**Comment by Angelinsky7** [comment]
@fbrbovic you can edit the yaml directly and order the env entries manually but if you then edit again with the ui, the order will be reset (and you'll need to edit the yaml again)

**Comment by TechnoChimp** [comment]
Please fix this. We ended up breaking our LinkerD deployment by pressing the re-deploy button.

**Comment by jeroenhartgers** [comment]
Still a LARGE issue with RabbitMQ HA in 2.3.6 ( cannot upgrade to 2.4.x-2.4.4 due to memory issues)
Redeploy will kill this.


```
containers:
    - env:
        - name: HOSTNAME
          valueFrom:
            fieldRef:
             apiVersion: v1
             fieldPath: metadata.name
         - name: RABBITMQ_NODENAME
            value: rabbit@$(HOSTNAME).rabbitmq-internal.fluffle.svc.cluster.local
```

**Comment by Cediddi** [comment]
This issue has been moving from milestone to milestone. I hope it'll land on 2.4.12.

**Comment by deniseschannon** [comment]
The original proposed fix was not the proper solution. The most recent proposal is to change the Norman API to handle the correct type for environment variables, but this would end up breaking the API for any users using it for workloads, so trying to find the right release vehicle to make this breaking API change.

**Comment by bmalynovytch** [comment]
Still an issue.
More and more chart rely on those variables, which leads to more and more frustration.

**Comment by dnoland1** [comment]
haven't tried it myself, but got a report that the environment variables are also reordered when a "Pause Orchestration" is selected for a deployment and is later unpaused.

**Comment by vincent99** [comment]
@dnoland1  Any update to the workload in the Ui is going to send a complete copy of the definition and cause this, it doesn't really matter what action you're talking.

The problem here is fixing this is a breaking API change (changing a field's type), which we can't just make in a patch release.  And any mitigation for that to preserve backwards compatibility means any client using the original style will re-break the order without knowing it.

In 2.6 the "Cluster Explorer" is going to be the default UI, and it uses an API that doesn't have this problem in the first place (including the version shipping now). But the old behavior still has to be dropped from the /v3/workloads API to prevent users of it from breaking things.

**Comment by boindil** [comment]
> @dnoland1 Any update to the workload in the Ui is going to send a complete copy of the definition and cause this, it doesn't really matter what action you're talking.
> 
> The problem here is fixing this is a breaking API change (changing a field's type), which we can't just make in a patch release. And any mitigation for that to preserve backwards compatibility means any client using the original style will re-break the order without knowing it.
> 
> In 2.6 the "Cluster Explorer" is going to be the default UI, and it uses an API that doesn't have this problem in the first place (including the existing 2.5.x versions). But the old behavior still has to be dropped from the /v3/.../workloads API to prevent users of it from breaking things.

@vincent99 does that mean it should already work in the explorer view? I agree on actions like "redeploy", but using "Edit Config" destroys my order all the time when saving ...

**Comment by w3blogfr** [comment]
I also have the same issue.

I agree with @dorsany, 

if rancher always put all value "valueFrom" before environment variable in the yaml, it should solve the problem easily without need to upgrade the web interface.

**Comment by PennyScissors** [comment]
The API fields `environment` and `environmentFrom` has been deprecated in favor of Kubernetes' native fields `env` and `envFrom` to fix this issue. What this means is that anything within Rancher that uses the mappers (maps our custom type to k8s and vice versa) for workload environment variables will be affected, and therefore validated so that the k8s native fields are used instead.

What's affected:
1. UI (text fields in the UI) - The Ember UI needs to be updated to use the k8s types (issue for [this](https://github.com/rancher/rancher/issues/30683) here). Once that's done, the UI shouldn't really ever hit the validator because the user can't make the change to use the deprecated fields in the UI.
2. API view or requests - Using the old `environment` and `environmentFrom` fields will go through the validation and result in failure. The expectation is to use the k8s native fields `env` and `envFrom` moving forward.

What's unaffected:
1. UI (Edit as YAML) - This doesn't go through the mappers, or our validation. The interaction is with k8s directly and k8s will validate that the k8s native fields `env` and `envFrom` are being used. So the behavior should remain unchanged.
2. kubectl - Same as above

Upgrading from Rancher v2.5 to v2.6 with existing workloads - the expectation in this case is that the workload's environment variables will not be mapped into our custom types anymore and will instead come straight from k8s with its type unchanged. Here an example:

Workload's env vars in Rancher v2.5 before upgrading
![image](https://user-images.githubusercontent.com/8951271/121107041-0d8c2700-c7bc-11eb-9767-7bd349c6842f.png)

Same workload's env vars in Rancher v2.6 after upgrading
![image](https://user-images.githubusercontent.com/8951271/121107031-0a913680-c7bc-11eb-8ed8-0f8362efe913.png)

cc @Sowmya (This info might be useful for testing this issue).

**Comment by gaktive** [comment]
There's forthcoming discussion about changing how the UI handles this. @nwmac will setup a meeting shortly to go over options so UI won't work on this until then.

**Comment by anupama2501** [comment]
Verified on rancher server master-head c1151f6

**Fresh install:**
1. Create an rke2 cluster from dashboard with 3 worker, 1 etcd, 1cp
2. Create a config map from the cluster with a key=key and value=bar
3. Deploy a workload in the cluster
4. In the workload deployment → general → Environment variables → select the config map that was created in the above step from the API .
5. Add the key pair created above in the containers:
``` {"envFrom":[{"configMapRef":{"name":"au-cm"}}],"image":"ranchertest/mytestcontainer","name":"au-correct-config"} ``` 
Environment variables are created with `env` 
6. Edit as yaml of the workload and change the env to environment and envFrom to environmentFrom
7. The workload did not result in any error. If we redeploy the workload, the environment values will be disregarded and no environment variables are added in the pod. 
8. Deploy a workload with environment and environmentFrom variables as follows for config maps:
```{"environmentFrom":[{"configMapRef":{"name":"au-cm"}}],"image":"ranchertest/mytestcontainer","name":"au-incorrect-config"}  ```
9. In the yaml file add the variables environment and environmentFrom with the env data present and click on save
10. Verified the workload creation failed with an error: ```"message": "field `environmentFrom` is deprecated, please use Kubernetes native fields `env` and `valueFrom` for the container's environment variables"```

**Verified the above scenarios for secrets and key-pair. works as expected**

**Fresh install interpolation order:**
1. deploy a workload, from default project with rancher image=ranchertest/mytestcontainer from API
2. once the workload is deployed, from the API added the variables as follows: 
```
- env:
  - name: MEMCACHED_HOST
    valueFrom:
      fieldRef:
        apiVersion: v1
        fieldPath: status.hostIP
  - name: MEMCACHED_URL
    value: $(MEMCACHED_HOST):5000
```
3. Redeployed the workload  → multiple times
4. Verify the order is not changed and is reflected as presented above.
5. Edit as yaml and change the env to environment and envFrom to environmentFrom.
6. Verify that the saving the yaml file will not result in an error as mentioned in the above configmap scenario and the environment variables are disregarded
7. Deployed anotehr workload from the API and added the same values as above by replacing env to environment and envFrom to environmentFrom.
8. Verified the deployment errored out: ``` "message": "field `environmentFrom` is deprecated, please use Kubernetes native fields `env` and `valueFrom` for the container's environment variables"```


**Upgrade Scenario:** 

Waiting on the issue https://github.com/rancher/rancher/issues/33221 to be resolved.

**Comment by anupama2501** [comment]
Verified upgrade test case on v2.5.8 and pst-upgrade: master-head ad099ee

1. Create an rke1 cluster from emberUI with 3 worker, 1 etcd, 1cp on rancher server v2.5.8
2. Create a config map c1 and secret s1 from the cluster with a key=key and value=bar -wk1
3. Deploy a workload in the cluster
4. In the workload deployment → general → Environment variables → select the config map that was created in the above step.
5. Verified from the API requests for the fields environment variables are `environment` and `environmentFrom`
6. In workload - wk2, add the secret s1 created from step2
7. Add interpolation order  to the workload - wk3 with the config as follows and redeployed the workload and verified the order changed:
```
- env:
  - name: MEMCACHED_HOST
    valueFrom:
      fieldRef:
        apiVersion: v1
        fieldPath: status.hostIP
  - name: MEMCACHED_URL
    value: $(MEMCACHED_HOST):5000
```
8. Add a key-pair in the environment variables in a workload and create - wk4
9. Import yaml in a workload with environment variables: environment and environmentFrom - wk5
10. Create 3 secrets and 3 config maps in the cluster before upgrade
11. Upgrade rancher server to latest master-head and verify by redeploying all the workloads multiple times.
12. Verified no error is seen and all the workloads have the env variables applied with the prefix `env`
13. Verified the pods of the workloads and see the env variables.
```
kubectl exec wk1-85bcd875c4-jfg98 -- printenv

key=secret1
```
14. Verified the interpolation order in the workload by redeploying multiple times and see the order is reflected as present before the upgrade.
15. Changed the interpolation order of the env variables and redeployed it multiple times.
16. Verified the order is not changed

**Comment by jeroenhartgers** [comment]
Thank you for your efforts. What is important to know, is if you REDEPLOYED this with **cluster manager** or **cluster explorer**???

With cluster explorer, this has worked since Rancher 2.5.7.
For me, with cluster manager in Rancher 2.5.8 it does NOT work. I am fully aware that cluster manager is legacy and will be discarded in the future. So, in order to redeploy this from the GUI, I always use cluster explorer now.

If you only use kubectl, this is never a problem however.

**Comment by anupama2501** [comment]
Hi @jeroenhartgers I redeployed it via postman using v3 API as the cluster manager button is hidden and the workload creation will not be fixed for ember UI  from 2.6
