### ISSUE TITLE
Bad Catalog App install causes thousand of app revisions

### ISSUE THREAD

**Issue by tylerstapler-wf** [rancher/rancher#17168]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
1. Deploy an app that does not install correctly
```
{
"actions": {
"rollback": "…/v3/project/c-ncmr5:p-4prw9/apps/p-4prw9:eva-default?action=rollback",
"upgrade": "…/v3/project/c-ncmr5:p-4prw9/apps/p-4prw9:eva-default?action=upgrade"
},
"annotations": {
"lifecycle.cattle.io/create.helm-controller_c-ncmr5": "true"
},
"answers": {
"environment.EVA_SERVER_MODE": "TRANSACTORS_NODE",
"environment.EVA_TAG_INPUTS": "true",
"environment.EVA_TRANSACTORS_CONFIG": "/files/transactors.clj",
"environment.EVA_TRANSACTORS_EXIT_ON_CONFIG_CHANGE": "true",
"environment.EVA_TRANSACTOR_GROUPS": "default/eva-admin/rrs-identity/rrs-permissions/rrs-ring/rrs-streams/xbrl",
"environment.LOGBACK_CONFIG": "/files/logback-configuration.xml",
"environment.LOGBACK_LOG_LEVEL": "DEBUG",
"environment.TRACE_SAMPLING": "1",
"environment.USE_STD_OUT_TELEMETRY": "true",
"files.eva-server-transactors-clj": "REDACTED (Base64 encoded file)",
"files.logback-configuration": "REDACTED (Base64 encoded file)",
"ingress.clusterDomain": "wk-dev.wdesk.org",
"secrets.ACTIVEMQ_PASSWORD": "REDACTED",
"secrets.EVA_STORAGE_SQL_PASSWORD": "REDACTED"
},
"appRevisionId": "apprevision-dc6xx",
"baseType": "app",
"conditions": [ 2 items
{
"lastUpdateTime": "2018-12-17T20:05:45Z",
"status": "True",
"type": "Migrated"
},
{
"lastUpdateTime": "2018-12-18T19:04:16Z",
"message": "failed to install app eva-default. Error: UPGRADE FAILED: Deployment.apps \"eva-default\" is invalid: spec.template.spec.containers[0].image: Required value\n",
"reason": "Error",
"status": "False",
"type": "Installed"
}
],
"created": "2018-12-17T20:05:45Z",
"createdTS": 1545077145000,
"creatorId": "u-rvglz",
"externalId": "catalog://?catalog=wk-rancher-catalog&template=eva&version=v1.2.5",
"id": "p-4prw9:eva-default",
"labels": {
"cattle.io/creator": "norman"
},
"links": {
"remove": "…/v3/project/c-ncmr5:p-4prw9/apps/p-4prw9:eva-default",
"revision": "…/v3/project/c-ncmr5:p-4prw9/apps/p-4prw9:eva-default/revision",
"self": "…/v3/project/c-ncmr5:p-4prw9/apps/p-4prw9:eva-default",
"update": "…/v3/project/c-ncmr5:p-4prw9/apps/p-4prw9:eva-default"
},
"name": "eva-default",
"namespaceId": null,
"notes": "---\n# Source: eva/templates/NOTES.txt\nYour release is named eva-default.\n\nTo learn more about the release, try:\n\n  $ helm status eva-default\n  $ helm get eva-default\n\nExternal Service Routing:\n\nInternal Service DNS:\n  - eva-default\n  - eva-default.workiva\n  - eva-default.workiva.svc.cluster.local\n\n",
"projectId": "c-ncmr5:p-4prw9",
"prune": false,
"state": "installing",
"targetNamespace": "workiva",
"transitioning": "error",
"transitioningMessage": "failed to install app eva-default. Error: UPGRADE FAILED: Deployment.apps \"eva-default\" is invalid: spec.template.spec.containers[0].image: Required value\n",
"type": "app",
"uuid": "23de02c3-0237-11e9-ace3-0ed8cb0751ea"
}
```

**Result:**
On an interval(16min ish) a failed rancher app install will continuously create new revisions in the namespace that is being deployed to. The app reports that it is "installing" and continues to create these revisions until it slows down the performance of the rancher UI and Kubernetes its self. We saw one case where there were over two thousand revisions of the app in a rarely used cluster. 

```
eva-default.v1                         1         3h
eva-default.v10                        1         1h
eva-default.v11                        1         1h
eva-default.v12                        1         1h
eva-default.v13                        1         58m
eva-default.v14                        1         41m
eva-default.v15                        1         24m
eva-default.v16                        1         8m
eva-default.v2                         1         1h
eva-default.v3                         1         1h
eva-default.v4                         1         1h
eva-default.v5                         1         1h
eva-default.v6                         1         1h
eva-default.v7                         1         1h
eva-default.v8                         1         1h
eva-default.v9                         1         1h
```

**Other details that may be helpful:**
I searched our splunk logs for rancher logs with the correct app name. Doesn't look like there's any substentive data there. Just the repeated deploys.
[eva-default-rancher-logs.txt](https://github.com/rancher/rancher/files/2692257/eva-default-rancher-logs.txt)

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.1.1
- Installation option (single install/HA): HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Imported 
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
type: cloud 
machine: m5.4xlarge 16 cores cpu and 64G ram
- Kubernetes version (use `kubectl version`): 

```
Server Version: version.Info{Major:"1", Minor:"10+", GitVersion:"v1.10.11-eks", GitCommit:"6bf272
14b7e3e1e47dce27dcbd73ee1b27adadd0", GitTreeState:"clean", BuildDate:"2018-12-04T13:33:10Z", GoVe
rsion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker (use `docker info`):

```
sudo docker info
Containers: 34
 Running: 31
 Paused: 0
 Stopped: 3
Images: 20
Server Version: 17.06.2-ce
Storage Driver: overlay2
 Backing Filesystem: xfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 6e23458c129b551d5c9871e5174f6b1b7f6d1170
runc version: 810190ceaa507aa2727d7ae6f4790c76ec150bd2
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.14.77-86.82.amzn2.x86_64
Operating System: Amazon Linux 2
OSType: linux
Architecture: x86_64
CPUs: 16
Total Memory: 61.48GiB
Name: ip-10-32-3-174.us-west-2.compute.internal
ID: HVVB:6VHO:TWDP:RT5Y:QMVV:DY6M:3EPS:X4Z3:HKIH:RL7P:5Y37:AI37
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Comment by bitfisher** [comment]
I wonder if there is any option to limit the number of app revision?
Something like setting Tiller's [history-max](https://helm.sh/docs/using_helm/#initialize-helm-and-install-tiller) as option in [Rancher Server Chart](https://github.com/rancher/rancher/blob/master/chart/values.yaml)?

**Comment by loganhz** [comment]
Fixed in https://github.com/rancher/rancher/pull/19079 It will be released in 2.2.4

**Comment by avestuk** [comment]
Are there any steps that can be taken to rectify this issue? I've got a cluster with 240501  apprevision resources in it which is breaking the kube-apiserver.

**Comment by bmalynovytch** [comment]
Issue still exists on a fresh 2.5.2 (Docker).
Got more than 300k app revisions (don't really know how many as the instances crashes before showing them all).
