### ISSUE TITLE
Global DNS UI: DNS Provider description field is ignored by the server

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rancher#17546]
Version: master 2.2 (1/22/19) HA setup

**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
- Create a Global DNS Provider. Enter something in the optional description field.
- Edit it after creation. The text in that description field is now gone.

**Result:**
If you inspect the http upon creation we have sent the description to the server but it seems as though it may have ignored it. I don't see the description in the server response.
It may also be worth noting that I don't see us referencing the description anywhere in the UI.

**Environment information**
- 2.2 (1/22/19) HA set up on 3 ec2 nodes on supported Ubuntu

**Comment by davidnuzik** [comment]
Backend issue has been fixed #18098 now we just need to show description in UI API and in the UI (in cloud credentials rows) and fix the issue where when I create a description and then edit it is removed. 

The api allows me to edit an existing cloud credential to add a description, but when I do it does not show up in the UI API. See #18098

**Comment by westlywright** [comment]
@davidnuzik The description field still doesn't exist for the schema. Something is not right on the backend because we should not be required to update the API UI for a field to show up in the schema. I don't think rancher/rancher#18098 was completed correctly.

**Comment by westlywright** [comment]
This is not a UI issue. The UI sends the description field correctly but the backend is not saving it. Removing UI from the ticket.
