### ISSUE TITLE
Fluentd config file format changes automatically

### ISSUE THREAD

**Issue by kingsd041** [rancher/rancher#18476]
**What kind of request is this (question/bug/enhancement/feature request):** bug

**Rancher version:** rancher/rancher:master 02/28

**Steps to reproduce (least amount of steps as possible):**
Enter the following configuration in the advanced mode of the fluentd logging target
```
<match  * >
    @type forward
    compress gzip
    tls_allow_self_signed_cert true
    tls_verify_hostname true
    client_cert_auth true
    <security>
      self_hostname "#{Socket.gethostname}"
      shared_key true
    </security>
    <server>
      name xxx.xx.xcom
      host xxx.xxx.com
      port 24224
      shared_key mypass
      username  user1
      password  password
      weight  100
    </server>
</match>
```
Then enter the key and certificate in `Client Private Key` and `Client Certificate` and `CA Certificate PEM`. At this point, the fluentd file config has changed, like the following, <security> and <server> disappeared
```
<match *>
  @type forward
  compress gzip
  tls_allow_self_signed_cert true
  tls_verify_hostname true
  client_cert_auth true
  name xxx.xxx.com
  host xxx.xxx.com
  port 24224
  shared_key true
  username user1
  password password
  weight 100
  self_hostname "#{Socket.gethostname}"
  tls_client_private_key_path /fluentd/etc/config/ssl/project_c-d9k8s_p-5l954_client-key.pem
  tls_client_cert_path /fluentd/etc/config/ssl/project_c-d9k8s_p-5l954_client-cert.pem
  tls_cert_path /fluentd/etc/config/ssl/project_c-d9k8s_p-5l954_ca.pem
</match>
```
Note: The format of the fragranced config file changes each time you enter a value for a key or certificate.

**Comment by kingsd041** [comment]
@n313893254 Reproducible in other logging targets

**Comment by davidnuzik** [comment]
Version: Master 2.2 (3/1/19)
Confirmed issue. I tested per the steps and now the tls_* content is added before the first <asdf> found. I also tested this with the other logging targets.
You can see the placement is corrected now and even if I make changes add/remove and try to break it it still works as expected:
```
<match *>
  @type forward
  compress gzip
  tls_allow_self_signed_cert true
  tls_verify_hostname true
  client_cert_auth true
  tls_client_private_key_path /fluentd/etc/config/ssl/cluster_c-qvvrr_client-key.pem
  tls_client_cert_path /fluentd/etc/config/ssl/cluster_c-qvvrr_client-cert.pem
  tls_cert_path /fluentd/etc/config/ssl/cluster_c-qvvrr_ca.pem
  <security>
      self_hostname "#{Socket.gethostname}"
      shared_key true
    </security>
    <server>
      name xxx.xx.xcom
      host xxx.xxx.com
      port 24224
      shared_key mypass
      username  user1
      password  password
      weight  100
    </server>
</match>
```

**Comment by 1Shiroyuuki1** [comment]
Issue still exist under Rancher Version 2.4.8. Fluentd config are changing automatically.

**Comment by 1Shiroyuuki1** [comment]
This Issue still exists under Rancher v2.4.8 with Fluentd v1.0
