### ISSUE TITLE
Dark Theme UI: Text box should be gray on hover and focus and entered text should be white

### ISSUE THREAD

**Issue by davidnuzik** [rancher/rancher#18502]
Version: Master 2.2 (3/1/19)

**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
- Enable dark theme. Find a text box such as Cluster Name when creating a cluster.
- Hover over the text box. Select it to get focus. Notice hover and select to focus makes the box white and text white. Now type something the text is gray.

**Result:**
This should be reversed. When you hover over the text box it should be the gray color and the helptext should be gray. Only when we actually input our own text should this be white so it's clear this is text we have entered and it helps to improve contrast.

Related to: rancher/rancher#18125  

**Other details that may be helpful:**
Dark theme on no action:
![image](https://user-images.githubusercontent.com/45179589/53653186-fb4bd780-3c07-11e9-8ba0-a66cd0af77e1.png)

On hover or select text box:
![image](https://user-images.githubusercontent.com/45179589/53653201-069f0300-3c08-11e9-8cb7-50aa962000b5.png)

On type text (field not null):
![image](https://user-images.githubusercontent.com/45179589/53653225-161e4c00-3c08-11e9-8205-c676496a50fc.png)

**Comment by davidnuzik** [comment]
If this is expected behavior could we perhaps just tweak it some so that the text you type in is brighter and perhaps on hover/select text box it's not so bright white? Similar to #18125 can get a little confusing from end-user perspective. When I click in the Cluster Name text box it looks like it typed in e.g. sandbox for me and I need to delete that to type in something.

**Comment by cjellick** [comment]
minor, moving out of v2.2

**Comment by davidnuzik** [comment]
Version: Master 2.2 (3/11/19) HA Setup
Re-opening issue. This is fixed except for that we have lost our darker no action / normal state of the text box. I think this might be because of https://github.com/rancher/ui/pull/2740/commits/644b242a23bd808b657e85428cdf9bdba198732e#diff-01727b98cb1adb7bf2bf4d8527959ea4R83

Upon no action the text box should look like:
![image](https://user-images.githubusercontent.com/45179589/54142485-0a3f4080-43e5-11e9-9599-b4702538c799.png)

But it now looks like this:
![image](https://user-images.githubusercontent.com/45179589/54142498-13301200-43e5-11e9-97d3-b03b4899df4a.png)

**Comment by lvuch** [comment]
resolved here: https://github.com/rancher/ui/pull/2678

**Comment by davidnuzik** [comment]
@lvuch I still see issue described in comment above https://github.com/rancher/rancher/issues/18502#issuecomment-471630395

Or is this an expected change?
I will say it's a little easier to read the brighter text anyway... So I don't think it's that big of a deal just an unexpected change I think.

**Comment by davidnuzik** [comment]
Reopening. The fix doesn't appear to have changed anything.
I expected the old darker text when a text box with helper text in it is not selected. When I click in the text box the helper text gets brighter (weird).

Please contact me via slack if any other info is needed as far as what the expectations are.

**Comment by davidnuzik** [comment]
(Currently waiting for PR to merge; is not ready for testing)

**Comment by davidnuzik** [comment]
I'm moving out of test. PR is not merged yet.

**Comment by davidnuzik** [comment]
Version: master-head (v2.3) (9/3/19)

We now have placeholder (inactive) text similar to how it was before. This resolves the issue.

No action (placeholder text shown, and text box is not active/selected)
![image](https://user-images.githubusercontent.com/45179589/64206447-3ea13000-ce4f-11e9-8ebc-8e2944478477.png)

Select text box (placeholder text is now brighter now that field is in focus)
![image](https://user-images.githubusercontent.com/45179589/64206490-54165a00-ce4f-11e9-9133-51e5e89aa4fd.png)

Typed text is bright white (whether text box is active/selected or not):
![image](https://user-images.githubusercontent.com/45179589/64206529-6b554780-ce4f-11e9-95e3-2276c729eb3f.png)
