### ISSUE TITLE
Rancher Global DNS cloudflare record cannot be proxied

### ISSUE THREAD

**Issue by Negashev** [rancher/rancher#19251]
**What kind of request is this (question/bug/enhancement/feature request):**
Rancher Global DNS (cloudflare DNS record cannot be proxied)

**Steps to reproduce (least amount of steps as possible):**
- Create Rancher HA 2.1.7 ( from rke 0.2.0 ) update rancher to 2.2.0 (by helm)
- create Global DNS Provider cloudflare
- make dns record on project

**Result:**
log from rancher-external-dns
```
time="2019-03-28T17:17:50Z" level=error msg="failed to update record: error from makeRequest: HTTP status 400: content \"{\\\"success\\\":false,\\\"errors\\\":[{\\\"code\\\":1004,\\\"message\\\":\\\"DNS Validation Error\\\",\\\"error_chain\\\":[{\\\"code\\\":9041,\\\"message\\\":\\\"This DNS record cannot be proxied - click the cloud icon to turn it gray to proceed\\\"}]}],\\\"messages\\\":[],\\\"result\\\":null}\"" action=UPDATE record=SECURE.DOMAIN.COMPANY ttl=120 type=A zone=9426cb70f936d46d0fd705d38661b6a8
time="2019-03-28T17:17:50Z" level=info msg="Changing record." action=UPDATE record=SECURE.DOMAIN.COMPANY ttl=1 type=TXT zone=9426cb70f936d46d0fd705d38661b6a8
```

**Other details that may be helpful:**
Ufter upgrade app `systemapp-service-discovery`

`cloudflare.proxied=false`
helps for a while

After some time, the application is updated and deletes the key `cloudflare.proxied`
**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.2.0
- Installation option (single install/HA): HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): OpenShift
- Machine type (cloud/VM/metal) and specifications (CPU/memory): 3VM (4cpu 8gb)
- Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.11", GitCommit:"637c7e288581ee40ab4ca210618a89a555b6e7e9", GitTreeState:"clean", BuildDate:"2018-11-26T14:38:32Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.4", GitCommit:"c27b913fddd1a6c480c229191a087698aa92f0b1", GitTreeState:"clean", BuildDate:"2019-02-28T13:30:26Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker version (use `docker version`):

```
Client:
 Version:           18.09.4
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        d14af54266
 Built:             Wed Mar 27 18:35:44 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.4
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.8
  Git commit:       d14af54
  Built:            Wed Mar 27 18:01:48 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

**Comment by prachidamle** [comment]
@Negashev does the record successfully get created in Cloudflare just with proxying disabled? Or it does not get created anytime?

Also some checks to do:
- Does your Cloudflare zone have proxying capabilities?
- If the DNS record is for a private IP, proxying won't be allowed

Also wanted to note this CloudFlare ticket: https://community.cloudflare.com/t/dns-update-error/2655

Note the comment from CloudFlare team for the error 9041 that you see in the logs:
https://community.cloudflare.com/t/dns-update-error/2655/2

Do you think this might be the case?

**Comment by Negashev** [comment]
@prachidamle Ues, record successfully created in Cloudflare with proxying disabled.

**Comment by prachidamle** [comment]
@Negashev so does this mean maybe your Cloudflare zone does not have proxying capabilities? So you want all records to be created with cloudflare.proxied off?

**Comment by Negashev** [comment]
@prachidamle I want all records to be created with cloudflare.proxied off

**Comment by prachidamle** [comment]
@Negashev thanks, for my understanding: is this a requirement because "your Cloudflare zone does not have proxying capabilities"?

**Comment by Negashev** [comment]
@prachidamle No, it's because I don't want my traffic to go through a cloudflare proxy, I want my requests to go straight to my servers

**Comment by prachidamle** [comment]
@Negashev Question about this workaround you tried:
```
Ufter upgrade app systemapp-service-discovery

cloudflare.proxied=false
helps for a while

After some time, the application is updated and deletes the key cloudflare.proxied ```

Trying to understand why your external-dns app is getting updated overriding your setting, are you updating the GlobalDNSProvider details?

**Comment by Negashev** [comment]
@prachidamle, No, I create one record and upgrade service with proxy=false and after one hour dns service rollback auto (I did not do it myself)

**Comment by alena1108** [comment]
@prachidamle we should add this parameter to the cloudFlare config on the GlobalDNSProvider. Lets check what other params from CloudFlare and Route53 can be exposed.

**Comment by prachidamle** [comment]
@Negashev the service rollsback periodically, because it is a system app that is managed by Rancher using a helm chart - what we will be doing to help here is exposing the parameters on the GlobalDNSProvider itself that should update the system app underneath.

**Comment by Negashev** [comment]
@prachidamle Great, waiting for the update!

**Comment by sangeethah** [comment]
Reopening this issue with findings from - https://github.com/rancher/rancher/issues/19712#issuecomment-488077538

**Comment by alena1108** [comment]
The fix is available in the latest master build

**Comment by sangeethah** [comment]
Tested with rancher server version from master - `03c40d64`

When a GDN provider is created with "Proxy Setting" set to "no" , the GDNS entry that gets created for this provider have proxy settings off as expected.

When a GDN provider is created with "Proxy Setting" set to "yes" , the GDNS entry that gets created for this provider have proxy settings on as expected.

When the "Proxy Setting" for a existing GDN provider is toggled between "yes" and "no" , we see the external dns provider pod restart as expected.

**Comment by abhi1693** [comment]
@sangeethah  This issue still exists on rancher `v2.4.5`. I created a provider with Proxy settings set to `no` and the record generated still had `proxy orange cloud`. I tried toggling the settings and nothing happens.

**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
- Create Rancher HA 2.4.5
- create Global DNS Provider Cloudflare with proxy setting set to `no`
- make DNS record on project

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.4.5
- Installation option (single install/HA): HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): VMware
- Machine type (cloud/VM/metal) and specifications (CPU/memory): 3 VM (12 CPU/32 GB)
- Kubernetes version (use `kubectl version`): 
```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.6", GitCommit:"d32e40e20d167e103faf894261614c5b45c44198", GitTreeState:"clean", BuildDate:"2020-05-20T13:16:24Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-15T16:51:04Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```
- Docker version (use `docker version`):
```
Client:
 Version:      1.10.3
 API version:  1.24
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 21:49:11 2016
 OS/Arch:      linux/amd64
```

**Comment by JoelESvensson** [comment]
This does not also work for me. Also, external-dns seems to create a new record every minute. Might be fixed in upstream external-dns version 0.7.2 https://github.com/kubernetes-sigs/external-dns/issues/1540
