### ISSUE TITLE
New Monitoring Prometheus PVC doesn't work with OpenEBS

### ISSUE THREAD

**Issue by damlub** [rancher/rancher#19410]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
Rancher 2.2.1 on premise HA setup with OpenEBS as Persistent Storage provider
When enabling monitoring, it is never becoming available.

Kubernetes version ist 1.12.5 and Docker 17.03 on Ubuntu 16.04. VM Sizing is 8GB Ram, 4 cores, 120GB disk

**Result:**
The error of the pod prometheus-cluster-monitoring-0 is 
pod has unbound immediate PersistentVolumeClaims (repeated 3 times)

Digging deeper the PVC is exceeding the PVC name restriction of 63 chars. It is called `prometheus-cluster-monitoring-db-prometheus-cluster-monitoring-0` 65 chars

`failed to provision volume with StorageClass "openebs-jiva-default": Internal Server Error: failed to create volume 'pvc-a333df8a-56e0-11e9-ac14-02000a463c08': response: Service "pvc-a333df8a-56e0-11e9-ac14-02000a463c08-ctrl-svc" is invalid: metadata.labels: Invalid value: "prometheus-project-monitoring-db-prometheus-project-monitoring-0": must be no more than 63 characters`

This is something that seems valid as seen on 
https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/#syntax-and-character-set

--

**Other details that may be helpful:**
I have tried an installtion in the cloud of DigitalOcean with their persistent storage provider, and it works perfectly. It ignores the limit of 63 chars.

Here, the Kubernetes is 1.13.5 with Docker 18.09, 4GB RAM, 2 CPU cores

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
v2.2.1

- Installation option (single install/HA):
HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Custom, on premise
- Machine type (cloud/VM/metal) and specifications (CPU/memory): VM, KVM, 4CPU, 8GB RAM
- Kubernetes version (use `kubectl version`): 

1.12.5

- Docker version (use `docker version`):

17.03.3

**Comment by loganhz** [comment]
@damlub Thanks for your reporting.

In Rancher, `prometheus-project-monitoring-db-prometheus-project-monitoring-0` is a metadata.name instead of metadata.label.

I think the label is added by OpenEBS?

![image](https://user-images.githubusercontent.com/21168270/55615933-463aab00-57c3-11e9-9d7c-d929209f5585.png)

**Comment by damlub** [comment]
Is there any way to change the name of the monitoring catalog "cluster-monitoring", e.g. to "cluster-mon", that would already solve the problem for my case.

**Comment by tinobrandt** [comment]
With the StorageClass glusterfs and rbd (ceph) this is the problem itself -> "prometheus-project-monitoring-db-prometheus-project-monitoring-0": must be no more than 63 characters
How can I change the name of the monitoring catalog? I don't want to succeed?

**Comment by loganhz** [comment]
Link to https://github.com/rancher/system-charts/pull/35

**Comment by mschickervxob** [comment]
I upgraded from 2.2.2 to 2.2.3 stable today and activated persistent storage on obenebs for prometheus. Still the same issue. Next I disabled and reenabled monitoring. Same issue. Disabled and reenabled with answer prometheus.persistent.useReleaseName = true. Same issue. What do I need to do?

**Comment by loganhz** [comment]
it will be fixed in 2.2.4

**Comment by mschickervxob** [comment]
Why? When it was fixed in 2.2.3-rc7 : https://github.com/rancher/rancher/issues/19610

Version: v2.2.3-rc7

I can confirm that when monitoring is enabled it will now automatically set this answer:
prometheus.persistent.useReleaseName = true
You will see it added after you enable monitoring for cluster or project level monitoring.

This essentially shortens the name of the prometheus-project-monitoring-db-prometheus-project-monitoring-0 which is the issue that was observed here #19410
I confirmed that this indeed resulted in the shortening of that name and thus this should resolve the issue with OpenEBS.
The name is now about as short as prometheus-project-monitoring and all names stay under the 63 char limit OpenEBS has. This should resolve the issue.

**Comment by davidnuzik** [comment]
We had to cut a release for v2.2.3 to fix an important monitoring issue. As such we have some issues that mention fixed in v2.2.3-rc* and while they are in that release candidate they are not in the actual v2.2.3 release.

v2.2.4 will contain this fix. Sorry for the confusion. I added a comment to that backport issue.

**Comment by davidnuzik** [comment]
Version: Master (v2.3) (5/20/19)

I can confirm that when monitoring is enabled it will now automatically set this answer:
`prometheus.persistent.useReleaseName` = `true`
You will see it added after you enable monitoring for cluster _or_ project level monitoring.

This essentially shortens the name of the `prometheus-project-monitoring-db-prometheus-project-monitoring-0` 
I confirmed that this indeed resulted in the shortening of that name and thus this should resolve the issue with OpenEBS. 
The name is now about as short as `prometheus-project-monitoring` and all  names stay under the 63 char limit OpenEBS has. This should resolve the issue.

**Comment by mschickervxob** [comment]
Upgraded to 2.2.4 and monitoring 0.0.3, set prometheus.persistent.useReleaseName as answer to true, disabled and reenabled monitoring - still the same issue:

failed to provision volume with StorageClass "openebs-jiva-default": Internal Server Error: failed to create volume 'pvc-c550af08-8819-11e9-9380-960000255958': response: Service "pvc-c550af08-8819-11e9-9380-960000255958-ctrl-svc" is invalid: metadata.labels: Invalid value: "prometheus-cluster-monitoring-db-prometheus-cluster-monitoring-0": must be no more than 63 characters

**Comment by mschickervxob** [comment]
Searched through the charts repo an did not find any reference to useReleaseName.

**Comment by guangbochen** [comment]
the correct answer value is `prometheus.persistence.useReleaseName` https://github.com/guangbochen/system-charts/commit/2730b9c7ec9817584c383f1e371b0ced3cde71a8

**Comment by thxCode** [comment]
@mschickervxob , you could use [`prometheus.persistence.name`](https://github.com/rancher/system-charts/blob/f503fe7488eea8f687766d3cc0a253ae3297d93b/charts/rancher-monitoring/v0.0.3/values.yaml#L324) to replace the persistence volume name.

**Comment by mschickervxob** [comment]
Thanks @thxCode. That did it :-)

**Comment by Goobaii** [comment]
I just installed Rancher v2.2.7. I followed started the Prometheus monitoring and double-checked if prometheus.persistent.useReleaseName was set to true and it is. I'm still getting the following error. 

failed to provision volume with StorageClass "openebs-cstor-disk": Internal Server Error: failed to create volume 'pvc-cd35bce7-bbad-11e9-b663-94c6911b3bfa': response: Deployment.apps "pvc-cd35bce7-bbad-11e9-b663-94c6911b3bfa-target" is invalid: [metadata.labels: Invalid value: "prometheus-project-monitoring-db-prometheus-project-monitoring-0": must be no more than 63 characters, spec.template.labels: Invalid value: "prometheus-project-monitoring-db-prometheus-project-monitoring-0": must be no more than 63 characters]

**Comment by thxCode** [comment]
@Goobaii , please follow https://github.com/rancher/rancher/issues/19410#issuecomment-499365060 and try again.

**Comment by Goobaii** [comment]
@thxCode Can you explain how to do that? I have seen the "Edit Yaml" part where "prometheus.persistent.useReleaseName = true" is listed, but I have not seen "prometheus.persistence.name" in the yaml file.

**Comment by Goobaii** [comment]
@thxCode I'd like to clarify that for [prometheus.persistence.name](https://github.com/rancher/system-charts/blob/f503fe7488eea8f687766d3cc0a253ae3297d93b/charts/rancher-monitoring/v0.0.3/values.yaml#L324), I did not actually have the `prometheus.persistence.name` field in my yaml file. I manually added it in as `name: ""`. After applying the new settings, my Rancher UI crashed and I deleted all of the Rancher Monitoring/Prometheus/Grafana objects.

Could you clarify where and what I should set `prometheus.persistence.name` to?

**Comment by Goobaii** [comment]
For others that may have this problem, at least on Rancher v2.2.7, after enabling Persistent Storage for Prometheus, click on `Show advanced options` at the bottom of the `Cluster/Project Monitoring Configuration` page , and set `prometheus.persistence.name` to any name and `prometheus.persistent.useReleaseName` to `true`. 

![image](https://user-images.githubusercontent.com/36184018/63624172-6f13df00-c5b0-11e9-9b1a-59b2645c41d3.png)

**Comment by phamhi** [comment]
I also have the same issue with GlusterFS.. The workaround suggested by Goobaii worked for me

**Comment by tardich** [comment]
Still have this same issue with Rancher 2.3.3 and OpenEBS 1.5

**Comment by aijanai** [comment]
The trick of renaming the volume works

**Comment by jonathon2nd** [comment]
Nothing from above worked for me, with Rancher 2.5.9

For anyone else, when installing Rancher monitoring edit yaml and add name manually. Be sure not to make it too long otherwise the full name will still be too much.

```
...
        storageSpec:
          volumeClaimTemplate:
            metadata:
              name: prometheus
            spec:
...
```
PVC name = `prometheus-prometheus-rancher-monitoring-prometheus-0`

Not on Rancher, but I am floored that manually setting the PV is not supported.
https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/values.yaml
https://github.com/prometheus-operator/prometheus-operator/blob/master/Documentation/user-guides/storage.md
