### ISSUE TITLE
etcd alerts during backups

### ISSUE THREAD

**Issue by mattmattox** [rancher/rancher#19474]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
- Create 3 node cluster using RKE 0.2.1 using k8s 1.13.5
- Deploy Rancher v2.2.1
- Configure etcd alert in Rancher UI using default
- Wait for scheduled etcd backup

**Result:**
The system component etcd is not running

Alert Name: Etcd is unavailable 
Severity: critical 
Cluster Name: ############# (ID: local) 
Logs: HTTP probe failed with statuscode: 503

**Other details that may be helpful:**
The issue looks to be that the Rancher etcd backups just take a bit longer than it takes for the alert to fire:

https://github.com/rancher/rancher/issues/14630

I got one at 0231 and another at 0831. On Rancher 2.1, I was able to edit the etcd alert and have it send the alert after 10 minutes instead of 3. I don't see a way to do that in 2.2.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.2.1
- Installation option (single install/HA): HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Imported
- Machine type (cloud/VM/metal) and specifications (CPU/memory): VMware 2 core / 8GB
- Kubernetes version (use `kubectl version`): 1.13.5

**Comment by gstorme** [comment]
You can still edit the tresholds using the API.
Select view in api -> edit -> change the intervals -> show request -> send request.

**Comment by deniseschannon** [comment]
@aiwantaozi did we lose some functionality in etcd alerts with the change from alerts to alert groups in 2.1 to 2.2?

**Comment by aiwantaozi** [comment]
In 2.2.1 UI not support advance option for alert rule level, but you can edit it in API. after 2.2.2 UI support advance option for alert rule level; the latest version also supports inherited advance option from alert group level.

**Comment by aiwantaozi** [comment]
UI added the advance option for alert rule. For the etcd component alert is base on ```kubectl get componentstatus```, kubernetes enhance etcd health check after kubernetes 1.14.0, before kubenetes uses this member list command to check health, now it used health command to check health. It should be better. 
https://github.com/kubernetes/kubernetes/blob/v1.14.0/staging/src/k8s.io/apiserver/pkg/storage/storagebackend/factory/etcd3.go

**Comment by deniseschannon** [comment]
@bmdepesa Can you re-test it? From the comments, it seems that this should be fixed with k8s 1.14. 

Can you test this with a k8s 1.13 cluster and k8s 1.14 cluster to see if there is an actual difference?

**Comment by janeczku** [comment]
Issue with false positive etcd alerts is occurring with k8s 1.14 (Rancher 2.2.5). @aiwantaozi @bmdepesa 
```
Alert Name: Etcd is unavailable
Severity: critical
Cluster Name: ############# (ID: local)
Logs: HTTP probe failed with statuscode: 503
```

**Comment by dramich** [comment]
Running rancher v2.3.0-rc1 
Cluster: DO hosted 1 node k8s 1.14.6
Still seeing the error come through in alerts. 

```
{"receiver":"c-9pq5m:etcd-alert","status":"firing","alerts":[{"status":"firing","labels":{"alert_name":"Etcd is unavailable","alert_type":"systemService","cluster_name":"k8s114 (ID: c-9pq5m)","component_name":"etcd","group_id":"c-9pq5m:etcd-alert","logs":"HTTP probe failed with statuscode: 503","rule_id":"c-9pq5m:etcd-alert_etcd-system-service","severity":"critical"},"annotations":{},"startsAt":"2019-09-06T22:42:01.195003044Z","endsAt":"0001-01-01T00:00:00Z","generatorURL":""}],"groupLabels":{"component_name":"etcd","rule_id":"c-9pq5m:etcd-alert_etcd-system-service"},"commonLabels":{"alert_name":"Etcd is unavailable","alert_type":"systemService","cluster_name":"k8s114 (ID: c-9pq5m)","component_name":"etcd","group_id":"c-9pq5m:etcd-alert","logs":"HTTP probe failed with statuscode: 503","rule_id":"c-9pq5m:etcd-alert_etcd-system-service","severity":"critical"},"commonAnnotations":{},"externalURL":"http://alertmanager-cluster-alerting-0:9093","version":"4","groupKey":"{}/{group_id=\"c-9pq5m:etcd-alert\"}/{rule_id=\"c-9pq5m:etcd-alert_etcd-system-service\"}:{component_name=\"etcd\", rule_id=\"c-9pq5m:etcd-alert_etcd-system-service\"}"}
```

The cluster was up for approx 50 min before I saw the error so it's not instant. Tried to trigger by doing a snapshot but that did not seem to help. 

Also seeing on a k8s v1.13.10 cluster which is expected. 

A third cluster running k8s v1.15.3 has not had the error.

**Comment by dramich** [comment]
Rancher: v2.3.0-rc6
Three clusters each with a different k8s version: 1.13.11, 1.14.7 and 1.15.4
Running 20 nginx pods on each cluster and occasionally kicking off a snapshot.
Clusters were running for hours and did not see the alert come through.
