### ISSUE TITLE
Add ability to specify "upgrade from" in the catalog to specify which apps can be upgrade from (like in 1.6)

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#20523]
Rancher server version - v2.2.4-rc15

Steps to reproduce the problem:
Create a custom cluster.
Deploy "Wordpress" app version 2.1.10.
Once app is deployed successfully , upgrade to "2.1.11" version.

App is stuck in "Installing" state :
<img width="609" alt="Screen Shot 2019-05-28 at 5 41 11 PM" src="https://user-images.githubusercontent.com/4266958/58521065-e1bb1d00-816f-11e9-823b-29b1478d6b7f.png">

<img width="1184" alt="Screen Shot 2019-05-28 at 5 24 43 PM" src="https://user-images.githubusercontent.com/4266958/58521069-e7186780-816f-11e9-8d1a-18a560cd08c6.png">

**Comment by mrajashree** [comment]
It’s because of the label for chart in spec.template.metadata.labels https://github.com/helm/helm/issues/2494#issuecomment-311691146

**Comment by soumyalj** [comment]
Observed the same issue on an upgrade from v2.1.9 to v2.1.10-rc5. 
1. Create AWS and DO RKE clusters in rancher v2.1.9 . 
2. Deploy mysql catalog of version v0.3.7, docker-registry catalog of version v1.4.3 and wordpress catalog of version v2.1.10 in the cluster.
3. Upgrade rancher server to v2.1.10-rc5
4. After rancher upgrade, upgrade mysql catalog to version v0.3.8. Upgrade docker-registry catalog to version to v1.6.1 . Both catalogs get upgraded successfully
5. Upgrade wordpress catalog to v2.1.11. It is stuck in installing state with the below error
```
Failed to install app wordpress. Error: UPGRADE FAILED: Deployment.apps "wordpress-wordpress" is invalid: spec.template.metadata.labels: Invalid value: map[string]string{"app":"wordpress-wordpress", "chart":"wordpress-2.1.11", "release":"wordpress"}: `selector` does not match template `labels`

```

**Comment by guangbochen** [comment]
Will be addressed in https://github.com/rancher/charts/pull/173, but for now, we may only test upgrade from `v1.0.5` to  `v2.1.10`.

https://github.com/helm/helm/issues/2494#issuecomment-340939417
> deployment spec selectors are no longer mutable as of apps/v1beta2 and this is noted upstream in kubernetes/kubernetes#50719. Short of helm delete --purge myrelease and running helm install again on your chart, there is no way to mutate the selector labels.

**Comment by guangbochen** [comment]
because the `spec.template.metadata.labels` fields are immutable, so we need to select `delete and recreate` option to force upgrade and it will works as expected. 
![image](https://user-images.githubusercontent.com/4569037/58614255-79447b00-82ea-11e9-8e37-e180911b13cd.png)
**Verification Steps:**
1. Deploy the WordPress app with version 2.1.10
2. select the deployed app and view the Secret of `wordpress-mariadb`, copy the auto-generated `mariadb-password` and `mariadb-root-password` to somewhere you can revisit it later.
3. upgrade the wordpress app to version 2.1.11 and copy paste the `mariadb-password` and `mariadb-root-password` to the answers respectively.
4. select the `Delete and recreate resources if needed during the upgrade` checkbox and click upgrade.
5. the app should get upgraded with success.

**Comment by guangbochen** [comment]
addressed in https://github.com/rancher/charts/pull/174, upgrade from template version `2.1.10` or `2.1.11` to the current version `2.1.12` requires to select `Delete and recreate resources if needed during the upgrade` option,  additionally, the immutable field label `chart` is removed from `v2.1.12`.

**Comment by loganhz** [comment]
We cannot change the released version. So 2.1.10 and 2.1.11 still have problem.

1. Upgrade "Wordpress" from "2.1.10" to  "2.1.11", you need to select `force upgrade`
2. Upgrade "Wordpress" from "2.1.10"/"2.1.11" to "2.1.12", you need to select `force upgrade`
3. Upgrade "Wordpress" from "1.0.5" to  "2.1.12", it works without selecting `force upgrade`
v1.0.5
4. Upgrade "Wordpress" from "2.1.12" to  other ongoing version, it works without selecting `force upgrade`

**Comment by sangeethah** [comment]
@loganhz  This is still failing:

Upgrade "Wordpress" from "1.0.5" to "2.1.12", it works without selecting force upgrade
v1.0.5
<img width="1219" alt="Screen Shot 2019-06-03 at 9 00 54 PM" src="https://user-images.githubusercontent.com/4266958/58850286-b5594200-8642-11e9-9c53-4f8e42f6893b.png">

**Comment by guangbochen** [comment]
you will need to use `force-upgrade` for "Wordpress" from "1.0.5" to "2.1.12", the description above should be updated, thanks.

**Comment by sangeethah** [comment]
@guangbochen  The only to upgrade to  new version - "2.1.12"  that is introduced from any exisying version is to use "force-upgrade" . Is this acceptable ?

**Comment by loganhz** [comment]
Sorry. 1.0.5 also have the issue. So yes, you have to always select force upgrade.
In the future, if we release 2.1.13, and then you can upgrade to 2.1.13 from 2.1.12 without using `force-upgrade`

**Comment by sangeethah** [comment]
@alena1108 @guangbochen If we are introducing a new version - "2.1.12" , is it not possible for us to make it upgradable from all existing versions or at least few of them ?  Right now we seem to be in a worse situation from before when we were atleast able to upgrade from `1.0.5` to latest version ( `2.1.11`) without any problems.

**Comment by guangbochen** [comment]
we need to support upgrade from `v2.1.10, v2.1.11` to `v2.1.12` with those immutable fields `spec.selector.matchLabels` and `spec.template.metadata.labels` changes, (https://github.com/helm/helm/issues/2494#issuecomment-340939417), this is noted restriction in the upstream https://github.com/kubernetes/kubernetes/pull/50719 with our current default deployment version `apps/v1beta2`, and this change will also require `v1.0.5` to do a force-upgrade to be compatible with the above upgrade.  @sangeethah @alena1108 .

**Comment by guangbochen** [comment]
for example, this also noted in the helm/stable charts, https://github.com/helm/charts/pull/7686/files#diff-b290a06961a11374d72f584e5925762cR53 , and definitely, it is better for us to add the notes in our app's README file.

**Comment by jiaqiluo** [comment]
met the same error on Rancher: master 6/13 with the default global library https://git.rancher.io/charts branch `master`

**Comment by deniseschannon** [comment]
With rancher min and rancher max version introduced into 2.3, we should hide the older templates in 2.3 that don't work for upgrading to the latest wordpress.

**Comment by guangbochen** [comment]
hide older templates will require us to modify the `questions.yml` file of the existing chart, the CI lint in `rancher/charts` repo will fail due to making changes without bump chart version, but we can still process the changes.

also, hide older templates will only prevent new users from using the older versions, but they can still do the upgrade if they have installed previously, a better solution is if we can get UI to filter out min and max app version support https://github.com/rancher/rancher/issues/22266.

**Comment by deniseschannon** [comment]
@loganhz @guangbochen With master that has the min/max support for the catalog, we should update wordpress to hide these older templates.

**Comment by loganhz** [comment]
The root cause is the Wordpress version. Our min and max is for Rancher version.
