### ISSUE TITLE
WebSocket issue on some requests with firefox

### ISSUE THREAD

**Issue by sebmoule** [rancher/rancher#2109]
Hello,

I have install latest rancher version today and i'm facing some issues with some features with Ranger UI

example for this request, I get systematically a 400 Bad Request
curl 'http://cloud.allamand.com/v1/exec/?token=eyJhbGcI1NiJ9.eyJleHAiOjE0NDMwMTEyODIsInN1YiI6ImNhdHRsZSIsImlzcyI6Imh0dHA6XC9cL2NhdHRsZS5pbyIsImhvc3RVdWlkIjoiM2Y0MGUwMDItMzQ2ZS00NTEwLWE4NWEtMzk2ZDRiZGQzNGY5IiwiZXhlYyI6eyJBdHRhY2hTdGRpbiI6dHJ1ZSwiQXR0YWNoU3Rkb3V0Ijp0cnVlLCJUdHkiOnRydWUsIkNtZCI6WyJcL2Jpblwvc2giLCItYyIsIlRFUk09eHRlcm0tMjU2Y29sb3I7IGV4cG9ydCBURVJNOyBbIC14IFwvYmluXC9iYXNoIF0gJiYgZXhlYyBcL2JpblwvYmFzaCB8fCBleGVjIFwvYmluXC9zaCJdLCJDb250YWluZXIiOiJlNjAyNzIwNDczZTAyOTQxNjRkZGEyZTFhMjcwMDhiMjIzOGU3MTAyMTk2M2JlMGQzOWUyMzY5NjIyNjg3YjlkIn0sImlhdCI6MTQ0MzAxMDk4Miwia2lkIjoiZGVmYXVsdCJ9.gxlKEqyaXmIbg-46BlslczPeGtRtCothNRaSW4zaVFrH6X9hJF4fJgfccG_l_lPD2Ex70n7Y5Y-FNqelh6xkCuyPGEnicW3r7IgHq0nCRvCWvw-ve50XFHR1aujMB7Vh0JPUvWwfFxrfi3hEUhiKnLpcHY6SoLZAyZaMT463rGrahz9eOFOj15MD3ca1CTKaXeWnHaFKB0OgKXEoZhRRAUjifToYAE-r4t56ZLJIpGvVNTWY3a5-ZdXqoG0C3iNPhAy4T1g6UkJIWv17RUlV73k8ZmFczKRdT1Pekv6NiTdEhby3hC8zmF7M7LMDBEr5XFAOKU2hUI6P0bA' -H 'Host: myrancher' -H 'User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:35.0) Gecko/20100101 Firefox/35.0' -H 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8' -H 'Accept-Language: fr,fr-fr;q=0.8,en-us;q=0.5,en;q=0.3' -H 'Accept-Encoding: gzip, deflate' -H 'Sec-WebSocket-Version: 13' -H 'Origin: http://myrancher' -H 'Sec-WebSocket-Key: 730cXFgqy95yys+qeP1g==' -H 'Cookie: CSRF=32E81ACA5B7B84CC131B9FA69F74DB; token=jdNbTL7ALWpacJTk1yzJC7S4oKXa9XJjQVJYf' -H 'Connection: keep-alive, Upgrade' -H 'Pragma: no-cache' -H 'Cache-Control: no-cache' -H 'Upgrade: websocket'

if i get logs from rancher-server I got dcdsf
**time="2015-09-23T12:23:02Z" level=error msg="Error during upgrade: [websocket: could not find connection header with token 'upgrade']" **
**2015/09/23 12:23:02 http: multiple response.WriteHeader calls**

I'm using Firefox 35.01 and rancher
docker images | grep rancher
rancher/server                        latest              080f59283bc3        18 hours ago        654.7 MB
rancher/agent-instance                v0.4.1              82dc81bb1dcf        2 weeks ago         541.8 MB
rancher/agent

**Comment by deniseschannon** [comment]
Could you give some more details on your setup? Was it a fresh install or upgrade from a previous version? Do you have a single rancher server and how many hosts?

**Comment by cjellick** [comment]
Hm. I've not seen this before. I also installed your version of Firefox and couldn't repro. Do have any proxies or load balancers between your browser and rancher?

**Comment by sebmoule** [comment]
Hi all,

Yes i've got my enterprise proxy to go through internet. I think that is the source of the problem.

I workaround this by putting a reverse proxy listening in https on front of my rancher so that i could tunnel in https the websocket access.
 

Sébastien

**Comment by cjellick** [comment]
@deniseschannon Seems like this problem is resolved and was a configuration issue. Think we can close?

**Comment by deniseschannon** [comment]
@sebmoule If you still have issues, please re-open and let us know.

**Comment by iamsteadman** [comment]
Yeah, this is still broken. Nothing to do with browser specifics, as the same issue happens on Chrome. "400 Bad Request" response, so unable to see any logs from containers.
