### ISSUE TITLE
Imported AKS clusters display controller/scheduler error

### ISSUE THREAD

**Issue by mikhail-arundo** [rancher/rancher#21537]
question/feature request:

Should I even be importing AKS clusters into Rancher or do I go to create cluster and fill in existing AKS cluster info?

When I import an existing AKS cluster, the controller/scheduler error issue comes up in the ui due the underlying kubernetes issue I wont get in to.

This does not happen when I create an AKS cluster via Rancher since that driver disables those settings/warnings.

Screenshot Imported AKS cluster:
https://screencast.com/t/p9cRYpAh

Rancher 2.2.4

Preferred solution for me would be to be able to import AKS clusters with the AKS driver if that is not already possible via create screen. 

Less optimal but reasonable would be to give imported driver ability to disable the ui alert based on whether it is in Azure.

Many thanks, loving the ranch.

**Comment by davidnuzik** [comment]
This is fixed here: https://github.com/rancher/rancher/issues/20066
v2.2.5 has the change

**Comment by mikhail-arundo** [comment]
thanks @davidnuzik for looking into it. I upgraded to 2.2.5 and still seeing the issue on my previously (on 2.2.4) imported cluster.

https://screencast.com/t/RBSO1lCP8ZUa

Should I post to the other issue?

**Comment by davidnuzik** [comment]
We can keep this issue @mikhail-arundo I reopened it; I was expecting fix to resolve this issue with imports but it doesn't seem to have covered that unfortunately.

**Comment by iboware** [comment]
Rancher 2.4.1  Kubernetes Version: v1.16.7 AKS still having the same problem.


![image](https://user-images.githubusercontent.com/180098/78518781-b6f31980-77c1-11ea-93d4-d2d6fa802adc.png)

**Comment by deniseschannon** [comment]
CLosing in favor of https://github.com/rancher/rancher/issues/11496#issuecomment-727641496
