### ISSUE TITLE
Changes to role inheritance do not affect existing grants

### ISSUE THREAD

**Issue by axeal** [rancher/rancher#23658]
**What kind of request is this (question/bug/enhancement/feature request):**

Bug

**Steps to reproduce (least amount of steps as possible):**

1. Provision a simple single node custom cluster from Rancher
2. Add a user `foo` to Rancher and grant this user the Project Member role on the Default Project.
3. Edit a Resource Grant on the Project Member role and observe the change is propagated to the ClusterRole in the downstream cluster immediately.
3. Edit the Project Member role to inherit from kubernetes admin or kubernetes view, or remove the role inheritance entirely from this role and observe that there is no change in the rolebindings on the default namespace for the `foo` user who continues to be granted the edit ClusterRole.
4. Remove and re-add Project Member role from user `foo` on Default Project and then observe the altered role inheritence takes effect.

**Environment information**
- Re-created in Rancher v2.2.8 and v2.3.1

**Comment by dramich** [comment]
This should be fixed by the changes in https://github.com/rancher/rancher/pull/23641

**Comment by axeal** [comment]
@dramich I just tested in v2.3.2 and still see this issue:

1. Provision a simple single node custom cluster from Rancher
2. Clone the Project Member role to 'test' role (since I couldn't edit the Project Member role in v2.3.2)
3. Add a user foo to Rancher and grant this user the 'test' role on the Default Project.
4. Edit a Resource Grant on the 'test' role and observe the change is propagated to the ClusterRole in the downstream cluster immediately.
5. Edit the 'test' role to inherit from kubernetes admin or kubernetes view, or remove the role inheritance entirely from this role and observe that there is no change in the rolebindings on the default namespace for the foo user who continues to be granted the edit ClusterRole.
6. Remove and re-add 'test' role from user foo on Default Project and then observe the altered role inheritance takes effect.

**Comment by bmdepesa** [comment]
rancher/rancher:v2.3.3-rc4

Reproduced this in `v2.3.3-rc4` using the exact steps above:
```
1. Provision a simple single node custom cluster from Rancher
2. Clone the Project Member role to 'test' role (since I couldn't edit the Project Member role in v2.3.2)
3. Add a user foo to Rancher and grant this user the 'test' role on the Default Project.
4. Edit a Resource Grant on the 'test' role and observe the change is propagated to the ClusterRole in the downstream cluster immediately.
5. Edit the 'test' role to inherit from kubernetes admin or kubernetes view, or remove the role inheritance entirely from this role and observe that there is no change in the rolebindings on the default namespace for the foo user who continues to be granted the edit ClusterRole.
6. Remove and re-add 'test' role from user foo on Default Project and then observe the altered role inheritance takes effect.
```

**Comment by deniseschannon** [comment]
@bmdepesa this is available in v2.3.4-rc4, but the master commit hasn't been merged which is why it's not marked to-test

**Comment by bmdepesa** [comment]
rancher/rancher:v2.3-head d73dff8df

Clusterrolebindings are synced correctly, but rolebindings are not being synced: 

* Create a cluster
* Clone the Project Member role
* Create a new user and give them the cloned role
* Update the resource grants for the role and see them reflected immediatedly
* Update the role to remove the `edit` inherited role
* Clusterrolebindings in the cluster are updated, but rolebindings are not:
```
# before editing
> kubectl get clusterrolebindings -o json | jq -r '.items[] | select(.subjects // [] | .[] | [.name] == ["u-vc8gf"]) | .metadata.name'
clusterrolebinding-ttgrv
clusterrolebinding-znvtk

> kubectl get rolebindings -o json | jq -r '.items[] | select(.subjects // [] | .[] | [.name] == ["u-vc8gf"]) | .metadata.name'
clusterrolebinding-g6sm5
clusterrolebinding-r9s77

# after editing 
> kubectl get clusterrolebindings -o json | jq -r '.items[] | select(.subjects // [] | .[] | [.name] == ["u-vc8gf"]) | .metadata.name'

> kubectl get rolebindings -o json | jq -r '.items[] | select(.subjects // [] | .[] | [.name] == ["u-vc8gf"]) | .metadata.name'
clusterrolebinding-g6sm5
clusterrolebinding-r9s77
```
* Remove the user from the project, and re-add them with the same role
```
> kubectl get rolebindings -o json | jq -r '.items[] | select(.subjects // [] | .[] | [.name] == ["u-vc8gf"]) | .metadata.name'
clusterrolebinding-26pbc
> kubectl get clusterrolebindings -o json | jq -r '.items[] | select(.subjects // [] | .[] | [.name] == ["u-vc8gf"]) | .metadata.name'
clusterrolebinding-5sm27
clusterrolebinding-8tcsv
clusterrolebinding-d6jpn
```
* The clusterrolebindings that were previously removed are also added back when adding a member to the project

**Comment by mrajashree** [comment]
After the `Update the role to remove the "edit" inherited role`, expected behavior is that clusterrolebindings should remain unchanged. And one of the 2 rolebindings should get removed

The following clusterrolebindings exist initially before removing "edit" role:
* `roleTemplate.Name-promoted`: Because project-member gives permissions for `storageClass`, `persistentVolumes` and `apiservices` resources
* `project.Name-namespaces-edit` and `create-ns`: Because project-member role has `create` permission on `namespace` resource

And the following rolebindings exist:
* One with the clusterRole of the roleTemplate.Name
* One with the Kubernetes default role of `edit`

On removing `edit` from inherited roles, only rolebinding with clusterrole `edit` should be removed.
If the `view` role is added under inherited roles instead, then a new rolebinding with clusterrole `view` should get created

**Comment by bmdepesa** [comment]
rancher/rancher:v2.3.4-rc6
rancher/rancher:master-head  8bd9f3be2

* After editing the inherited roles to remove `edit` the rolebindings are updated appropriately (1 is removed)
* After adding a new inherited role, the new rolebinding is created correctly
* Previous cases are still passing
