### ISSUE TITLE
user-data.iso files not removed from datastore upon deleting vSphere nodes

### ISSUE THREAD

**Issue by janeczku** [rancher/rancher#25073]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
1. Create a vSphere node template:
- Configure all required options under "Account" and  "Scheduling"
-  Under "Instance Options" select "Deploy from template - Datacenter"  and select a VM template from the dropdown. Select a VM network from the list. Leave all other options at their default.
2. Provision a cluster in Rancher using that node template
3. After provisioning is complete, delete the cluster in Rancher.

**Result:**

The VM is successfully deleted but the user-data.iso file persists in the directory for the VM within the datastore (see vCenter UI -> Storage) resulting in lots of orphaned files over time.

**Environment information**
- Rancher version: v2.3.4

SURE-6985

**Comment by rlewkowicz** [comment]
I'm having this issue. Can we verify that this was supposed to be resolved?

**Comment by FredNass** [comment]
Hi guys,

I believe this one should be fixed by unmounting the iso image after the successfull deployment of the node. After the umount, the .iso file should also be removed from the VM directory so that should the VM be move to another datastore, the directory would be remove correctly and not be left behind.

This would also fix another issue with the node VM not allowed to move to another ESXi because of the local .iso file still being connected and mounted during the node life.

Can someone check that a node doesn't need the cloud-init .iso file anymore after it's been successfully deployed and and if so, code this logic above to fix both of these issues?

**Comment by kingnarmer** [comment]
I still see this issue with Rancher 2.8.2. Is there a way to tell machinsets configuration to unmount **user-data.iso** post successful creation of node(worker/etc/control) ?

**Comment by flostru** [comment]
Is this issue being worked on?

Moreover not only the iso is not cleaned up, also it remains being connected to the node vm until we manually eject it from the vm system by calling "eject /dev/sr1"

This can prevent all sort of things related to vmware cluster operations (maintenance modes on storage, DRS Operations etc.)

Also if you disconnect it by vmware api or gui without ejecting it it will cause the worker machine to hang for a minute causing kubernetes services to jump out of the window.

Please fix this, its a showstopper.

**Comment by jakefhyde** [comment]
Currently unable to reproduce this on v2.9-head, will likely be moving to QA soon if users are unable to reproduce this on v2.9.2 (when it releases).

**Comment by jakefhyde** [comment]
Moving to QA due to inability to reproduce, @snasovich @daviswill2 would this be okay to include in the next 2.9 release for testing?

**Comment by snasovich** [comment]
Per above looks like this was fixed indirectly and it's no longer reproducible in v2.9.1 (or later) - pending QA confirmation before the issue is closed.

**Comment by Josh-Diamond** [comment]
Verified on Rancher `v2.9-023781e52103c45a9bbdf3cb47d60b9336321daa-head`:

No longer reproducible; user-data.iso files cleaned up upon cluster deletion; as expected

**Comment by lindhe** [comment]
I'm on v2.10.1 and just tried deploying a new node, yet it had the ISO mounted still after successful deployment.

Is this just available for new clusters, or do I have to change some other setting to apply it? Or did 2.10.1 nor receive the fix? 🤔

**Comment by dadez73** [comment]
same here on v2.10.0. Fix ?

**Comment by cklagenberg** [comment]
Same on 	v2.11.2 with a newly created cluster.

**Comment by snasovich** [comment]
@lindhe @dadez73 @cklagenberg , this issue is specifically about cleaning up `user-data.iso` / vSphere folder it's contained in _after_ the node (or, by extension, the cluster) is deleted. Currently, by design the user-data iso is meant to be connected for the lifetime of the vm, and will be cleaned up when the node is removed.

**Comment by lindhe** [comment]
Oh, that's quite problematic. But thanks a lot for clarifying!

With an ISO mounted, vmotion does not work. That makes it much harder for our IT to migrate and manage VMs while avoiding downtime (at least that's my understanding). 😕

**Comment by przemytn** [comment]
I can confirm that the cleanup issue is still present (or has regressed) in version 3.11.

Even after a successful downstream cluster/node deletion, the user-data.iso files are completely orphaned and left behind on the vSphere datastore. Accumulating these orphaned files directly violates our strict storage capacity tolerances and creates unnecessary overhead in automated environments.
