### ISSUE TITLE
Failed to connect to peer wss://10.42.2.5/v3/connect [local ID=10.42.1.4]: websocket: bad handshake 

### ISSUE THREAD

**Issue by alexshenyuefei** [rancher/rancher#26082]
![image](https://user-images.githubusercontent.com/16495430/76848704-1a52f100-687f-11ea-97e9-4dcdf4414701.png)

![image](https://user-images.githubusercontent.com/16495430/76848794-3fdffa80-687f-11ea-812b-2493406d8eeb.png)

![image](https://user-images.githubusercontent.com/16495430/76848856-5a19d880-687f-11ea-9f63-123bb45a66c0.png)

2020/03/17 10:34:24 [INFO] Rancher arguments {ACMEDomains:[] AddLocal:auto Embedded:false KubeConfig: HTTPListenPort:80 HTTPSListenPort:443 K8sMode:auto Debug:false NoCACerts:false ListenConfig:<nil> AuditLogPath:/var/log/auditlog/rancher-api-audit.log AuditLogMaxage:10 AuditLogMaxsize:100 AuditLogMaxbackup:10 AuditLevel:0 Features:}
2020/03/17 10:34:24 [INFO] Listening on /tmp/log.sock
2020/03/17 10:34:24 [INFO] Running in clustered mode with ID 10.42.1.4, monitoring endpoint cattle-system/rancher
2020/03/17 10:34:25 [INFO] Starting API controllers
2020/03/17 10:34:25 [INFO] Listening on :443
2020/03/17 10:34:25 [INFO] Listening on :80
2020/03/17 10:34:25 [INFO] Adding peer wss://10.42.0.4/v3/connect, 10.42.0.4
2020/03/17 10:34:25 [INFO] Adding peer wss://10.42.2.5/v3/connect, 10.42.2.5
2020/03/17 10:34:25 [INFO] Starting cluster controllers for local
2020/03/17 10:34:25 [ERROR] Failed to connect to peer wss://10.42.2.5/v3/connect [local ID=10.42.1.4]: websocket: bad handshake
2020/03/17 10:34:25 [ERROR] Failed to connect to peer wss://10.42.0.4/v3/connect [local ID=10.42.1.4]: websocket: bad handshake
2020/03/17 10:34:25 [INFO] Starting cluster agent for local [owner=false]
2020/03/17 10:34:30 [ERROR] Failed to connect to peer wss://10.42.2.5/v3/connect [local ID=10.42.1.4]: websocket: bad handshake
2020/03/17 10:34:30 [ERROR] Failed to connect to peer wss://10.42.0.4/v3/connect [local ID=10.42.1.4]: websocket: bad handshake
2020/03/17 10:34:35 [ERROR] Failed to connect to peer wss://10.42.2.5/v3/connect [local ID=10.42.1.4]: websocket: bad handshake
2020/03/17 10:34:35 [ERROR] Failed to connect to peer wss://10.42.0.4/v3/connect [local ID=10.42.1.4]: websocket: bad handshake
2020/03/17 10:34:40 [ERROR] Failed to connect to peer wss://10.42.0.4/v3/connect [local ID=10.42.1.4]: websocket: bad handshake
2020/03/17 10:34:40 [ERROR] Failed to connect to peer wss://10.42.2.5/v3/connect [local ID=10.42.1.4]: websocket: bad handshake
2020/03/17 10:34:45 [ERROR] Failed to connect to peer wss://10.42.0.4/v3/connect [local ID=10.42.1.4]: websocket: bad handshake
2020/03/17 10:34:45 [ERROR] Failed to connect to peer wss://10.42.2.5/v3/connect [local ID=10.42.1.4]: websocket: bad handshake
2020/03/17 10:34:50 [ERROR] Failed to connect to peer wss://10.42.0.4/v3/connect [local ID=10.42.1.4]: websocket: bad handshake
2020/03/17 10:34:50 [ERROR] Failed to connect to peer wss://10.42.2.5/v3/connect [local ID=10.42.1.4]: websocket: bad handshake
2020/03/17 10:34:55 [ERROR] Failed to connect to peer wss://10.42.0.4/v3/connect [local ID=10.42.1.4]: websocket: bad handshake
2020/03/17 10:34:55 [ERROR] Failed to connect to peer wss://10.42.2.5/v3/connect [local ID=10.42.1.4]: websocket: bad handshake
2020/03/17 10:34:58 [INFO] Handling backend connection request [10.42.0.4]
2020/03/17 10:34:58 [INFO] Handling backend connection request [10.42.2.5]
2020/03/17 10:41:10 [ERROR] Failed to serve peer connection 10.42.0.4: websocket: close 1006 (abnormal closure): unexpected EOF
2020/03/17 10:41:10 [INFO] error in remotedialer server [400]: websocket: close 1006 (abnormal closure): unexpected EOF
2020/03/17 10:41:10 [INFO] Removing peer 10.42.0.4
2020/03/17 10:41:12 [INFO] Starting catalog controller
2020/03/17 10:41:12 [INFO] Starting project-level catalog controller
2020/03/17 10:41:12 [INFO] Starting cluster-level catalog controller
2020/03/17 10:41:12 [INFO] Starting management controllers
2020/03/17 10:41:12 [INFO] Redeploy Rancher Agents is needed for local: forceDeploy=false, agent/auth image changed=true, private repo changed=false
2020/03/17 10:41:12 [INFO] update kontainerdriver azurekubernetesservice
2020/03/17 10:41:12 [INFO] update kontainerdriver amazonelasticcontainerservice
2020/03/17 10:41:12 [INFO] update kontainerdriver baiducloudcontainerengine
2020/03/17 10:41:12 [INFO] update kontainerdriver aliyunkubernetescontainerservice
2020/03/17 10:41:12 [INFO] update kontainerdriver tencentkubernetesengine
2020/03/17 10:41:12 [INFO] update kontainerdriver huaweicontainercloudengine
2020/03/17 10:41:12 [INFO] update kontainerdriver rancherkubernetesengine
2020/03/17 10:41:12 [INFO] update kontainerdriver googlekubernetesengine
2020/03/17 10:41:12 [ERROR] ClusterController local [cluster-deploy] failed with : waiting for server-url setting to be set
2020/03/17 10:41:12 [INFO] Reconciling GlobalRoles
2020/03/17 10:41:12 [INFO] Reconciling RoleTemplates
2020/03/17 10:41:12 [INFO] adding kontainer driver rancherKubernetesEngine
2020/03/17 10:41:12 [INFO] adding kontainer driver googleKubernetesEngine
2020/03/17 10:41:12 [INFO] adding kontainer driver azureKubernetesService
2020/03/17 10:41:12 [INFO] adding kontainer driver amazonElasticContainerService
2020/03/17 10:41:12 [INFO] adding kontainer driver baiducloudcontainerengine
2020/03/17 10:41:12 [INFO] adding kontainer driver aliyunkubernetescontainerservice
2020/03/17 10:41:12 [INFO] adding kontainer driver tencentkubernetesengine
2020/03/17 10:41:12 [INFO] adding kontainer driver huaweicontainercloudengine
2020/03/17 10:41:12 [INFO] Rancher startup complete
2020/03/17 10:41:12 [INFO] Redeploy Rancher Agents is needed for local: forceDeploy=false, agent/auth image changed=true, private repo changed=false
2020/03/17 10:41:12 [ERROR] ClusterController local [cluster-deploy] failed with : waiting for server-url setting to be set
2020/03/17 10:41:15 [INFO] driverMetadata: empty setting k8s-version, using stored defaults
2020/03/17 10:41:17 [INFO] kontainerdriver azurekubernetesservice listening on address 127.0.0.1:35115
2020/03/17 10:41:17 [INFO] kontainerdriver amazonelasticcontainerservice listening on address 127.0.0.1:35752
2020/03/17 10:41:17 [INFO] kontainerdriver googlekubernetesengine listening on address 127.0.0.1:42197
2020/03/17 10:41:17 [INFO] kontainerdriver azurekubernetesservice stopped
2020/03/17 10:41:17 [INFO] dynamic schema for kontainerdriver azurekubernetesservice updating
2020/03/17 10:41:17 [INFO] kontainerdriver amazonelasticcontainerservice stopped
2020/03/17 10:41:17 [INFO] dynamic schema for kontainerdriver amazonelasticcontainerservice updating
2020/03/17 10:41:17 [INFO] kontainerdriver googlekubernetesengine stopped
2020/03/17 10:41:17 [INFO] dynamic schema for kontainerdriver googlekubernetesengine updating
2020/03/17 10:41:25 [INFO] driverMetadata: refresh data
2020/03/17 10:41:26 [INFO] driverMetadata initialized successfully
2020/03/17 10:41:36 [INFO] Adding peer wss://10.42.0.5/v3/connect, 10.42.0.5
2020/03/17 10:41:38 [INFO] Handling backend connection request [10.42.0.5]
2020/03/17 10:42:16 [INFO] Redeploy Rancher Agents is needed for local: forceDeploy=false, agent/auth image changed=true, private repo changed=false
2020/03/17 10:42:16 [ERROR] ClusterController local [cluster-deploy] failed with : waiting for server-url setting to be set
2020/03/17 10:44:24 [INFO] Redeploy Rancher Agents is needed for local: forceDeploy=false, agent/auth image changed=true, private repo changed=false
2020/03/17 10:44:24 [ERROR] ClusterController local [cluster-deploy] failed with : waiting for server-url setting to be set

**Comment by ajjo-tech** [comment]
I get this as well, would be very intrested as to why i get and what ive missed.

**Comment by jk2K** [comment]
same problem here

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`):

```
- Cluster type: hosted
- Machine type: VM，4c/8g x 3, node list
- Kubernetes version:
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.2", GitCommit:"59603c6e503c87169aea6106f57b9f242f64df89", GitTreeState:"clean", BuildDate:"2020-01-18T23:30:10Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.2", GitCommit:"59603c6e503c87169aea6106f57b9f242f64df89", GitTreeState:"clean", BuildDate:"2020-01-18T23:22:30Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker version (use `docker version`):

```
Client: Docker Engine - Community
 Version:           19.03.5
 API version:       1.40
 Go version:        go1.12.12
 Git commit:        633a0ea838
 Built:             Wed Nov 13 07:22:05 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.5
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.12
  Git commit:       633a0ea838
  Built:            Wed Nov 13 07:28:45 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Comment by zaggash** [comment]
@jk2K @alexshenyuefei @ajjo-tech 

Can you try to remove the `rancher-token-*` secret listed with:
```
kubectl -n cattle-system get secret -o json | jq -r '.items[].metadata | select(.annotations."kubernetes.io/service-account.name" == "rancher") | .name'
```

something along this line:
```
kubectl -n cattle-system delete secret `kubectl -n cattle-system get secret -o json | jq -r '.items[].metadata | select(.annotations."kubernetes.io/service-account.name" == "rancher") | .name'` 
```

 Then remove the rancher pods:
```
kubectl -n cattle-system delete pods -l app=rancher
```

Wait for the pods to be rescheduled and check the logs again.

**Comment by jk2K** [comment]
after performing above operations, I got the errors
```bash
$ kubectl -n cattle-system apply -R -f ./rancher
clusterrolebinding.rbac.authorization.k8s.io/rancher unchanged
deployment.apps/rancher configured
ingress.extensions/rancher unchanged
service/rancher unchanged
serviceaccount/rancher unchanged
Error from server (InternalError): error when creating "rancher/templates/issuer-rancher.yaml": Internal error occurred: failed calling webhook "webhook.cert-manager.io": Post https://cert-manager-webhook.cert-manager.svc:443/mutate?timeout=30s: context deadline exceeded
```

related to https://github.com/jetstack/cert-manager/issues/2319

**Comment by zaggash** [comment]
The previous actions uncovered this new issue.
Looks like the cert manager webhook is stoped somehow.
You can take a look at the cert manager containers logs.
Or the kubectl events from the cert manager namespace.

**Comment by jk2K** [comment]
I didn't find anything wrong

```bash
$ kubectl -n cert-manager get pods
NAME                                       READY   STATUS    RESTARTS   AGE
cert-manager-6956784674-26fs8              1/1     Running   5          47d
cert-manager-cainjector-5454d77765-xt2jh   1/1     Running   93         47d
cert-manager-webhook-6569cd9f9b-vd6tx      1/1     Running   2          47d
```

I checked these 3 pods, `kubectl -n cert-manager logs` or `kubectl -n cert-manager describe pod`

**Comment by zaggash** [comment]
This one looks suspicious
cert-manager-cainjector-5454d77765-xt2jh   1/1     Running   93         47d

with `93` restart

**Comment by f1yers** [comment]
I did not upgrade via Rancher, did it with kops.  I've even logged into Rancher, deleted my cluster (it was not showing correct nodes after the upgrade and had connection issues), then deleted the cattle-system namespace, went back to Rancher re-created an imported cluster and re-deployed the cattle-system with the new yaml.  We get the same handshake error no matter what we've tired.

**Comment by r9labs** [comment]
This looks to affect new rke deployments of 2.4.5 without the cert-manager as well. Although I get a slightly different reason: i/o timeout. I have noticed that rancher-agent isn't deployed at all as another data point.

**Comment by caiconkhicon** [comment]
Hi all, is there any update on this issue? I have the exactly same issue. IMO, it is a serious problem.

**Comment by dkeightley** [comment]
@caiconkhicon have you [tested the overlay](https://rancher.com/docs/rancher/v2.x/en/troubleshooting/networking/#check-if-overlay-network-is-functioning-correctly) on the Rancher management cluster?

This can relate to a performance or networking issue, is the cluster performing OK? any issues in the kube-apiserver or etcd logs? If you can, upgrading to the current stable v2.4 release ([v2.4.8](https://github.com/rancher/rancher/releases/tag/v2.4.8) at the time of writing) would be worthwhile.

**Comment by caiconkhicon** [comment]
@dkeightley : Thanks for asking. I didn't test like you said but I know that the communication between Nodes is fine. 
In my case, I don't know the root cause but the symptom is: when a new Rancher Pod is created, its IP should be added to the Annotations of a Secret named `serving-cert`. Somehow it not added. I tried deleting the Pod and let K8S recreate it. After some times, it works (the leader Rancher Pod generated a log line saying that it had updated the Secret).

**Comment by cstackpole** [comment]
Greetings,
Upgrading from 2.4.5 to 2.4.8 and I ran into a LOT of the same issues in this thread. Like some above me, I don't have cert-manager as I provided my own. When I ran the overlay test as per @dkeightley it failed. BTW, that was useful information but it wasn't as useful as it could be. It told me that every host failed talking to every host, but didn't tell me what ip/port it was testing that failed. Every host could talk to every host on multiple IP's, yet it was VERY clear that the containers weren't talking to each other. No idea why. But I was also getting a lot of errors reaching out to DNS inside the container when it worked just fine on the host level.

So I started checking every version of everything I could find.
Helm? Already latest version.
kubectl? Already latest version.
docker? Already latest version.
ect ect ect
But then I noticed I had kernel updates ready for me (Scientific Linux 7.9 has just released). Why not?
Updated kernels and rebooted.

Now everything works.

I do NOT think that it was the kernel update that did it, nor any thing else in the OS updates. However, I do think that the reboot of all three hosts forced docker to reload all the docker images and that did it. I think there is something that didn't get refreshed that should have been in the docker images and it is causing network communication issues. Before I attempted the update, everything was working as it should.

Just for reference, the directions I followed for updating are here:
https://rancher.com/docs/rancher/v2.x/en/installation/upgrades-rollbacks/upgrades/ha/

And the command I used was this one:
`helm upgrade rancher rancher-stable/rancher --namespace cattle-system --reuse-values --version=2.4.8` 

So I hate to suggest it, but...try a reboot? And/or a complete restart of all the docker services?

**Comment by ss75710541** [comment]
k8s 1.21.0

I have the same problem

Rancher was normal after set replicas 1

**Comment by EdanBrooke** [comment]
I am now seeing this also:

Failed to connect to peer wss://10.42.64.10/v3/connect [local ID=10.42.192.8]: dial tcp 10.42.64.10:443: connect: no route to host

In my case I am seeing lots of DNS failures and 502 errors too, so have stumbled upon this during my search.

**Comment by EdanBrooke** [comment]
> I am now seeing this also:
> 
> Failed to connect to peer wss://10.42.64.10/v3/connect [local ID=10.42.192.8]: dial tcp 10.42.64.10:443: connect: no route to host
> 
> In my case I am seeing lots of DNS failures and 502 errors too, so have stumbled upon this during my search.

So in my case this was due to the Weave overlay getting stuck. One node in particular was throwing up a few errors after I ran the "overlay test" from Rancher's troubleshooting guide: https://rancher.com/docs/rancher/v2.x/en/troubleshooting/networking/

I killed the Weave pod on that node and when it came back up all my issues were resolved. Simple fix, but took an age to track down.

**Comment by andrewmunro** [comment]
I have this problem too after a fresh install of k3s and rancher using helm. The cluster appears to be functioning fine, but the replicas aren't able to connect to each other...

**Comment by yvespp** [comment]
For me this error seems to be related to the Kubernetes 1.21 update.
I tested it with two fresh clusters with the exact same settings (vm/kernel, kubeadm, canal, rancher config, containerd, nginx etc.) but with different Kubernetes versions: one with 1.21.2 and one with 1.20.5. With 1.20.5 the Rancher Pods can talk to each other but with 1.21.2 I get this error and imported clusters can't be accessed:
```
[ERROR] Failed to connect to peer wss://172.28.3.7/v3/connect [local ID=172.28.4.8]: websocket: bad handshake
 ```
If I scale rancher down to one instance everything works.

**Comment by joshuakraitberg** [comment]
Dropping K3S down to `v1.20.8+k3s1` fixed this issue for me.  My understanding is that Rancher is not supported on `^v1.21+k3s1` yet.

**Comment by ryanwkan** [comment]
@joshuakraitberg do you have source for this?

**Comment by joshuakraitberg** [comment]
@ryanwkan https://rancher.com/support-maintenance-terms/all-supported-versions/rancher-v2.5.8/

**Comment by spatialy** [comment]
I can confirm this … downgrade solve the problem

best

yulian

**Comment by followsound** [comment]
Can also confirm an downgrade fixed this:

`v1.20.8+k3s1` - works
`v1.21.2+k3s1` - does not work

**Comment by swordfly** [comment]
> k8s 1.21.0
> 
> I have the same problem
> 
> Rancher was normal after set replicas 1

I also fixed the issue by reduce the replicas to 1. What's the root cause here? Why reduce replicas=1 fix the issue?

**Comment by ryanwkan** [comment]
@swordfly setting the replica to 1 does not fix the issue per se, it alleviates the issue, as it does not need to communicate with any other rancher replicas when it's 1. The error comes from rancher trying to communicate with other rancher replicas through the websocket protocol, wss://

**Comment by swordfly** [comment]
@ryansann yes, it alleviates the issue. Many thanks for your comment, waiting for the fix.

**Comment by all4innov** [comment]
From documentation, rancher is not tested and supported in all k8s distributions + versions. 
For example, on top of EKS version `1.18` is the highest supported one for rancher 2.5.9: 

https://rancher.com/support-maintenance-terms/all-supported-versions/rancher-v2.5.9/

![image](https://user-images.githubusercontent.com/520080/128369566-ce33d789-4e06-419e-8c95-df213dd16699.png)

**Comment by aquam8** [comment]
I question if the documentation is up to date or if it just hasn’t been
tested on >1.18

I was running it on EKS 1.19 fine before. In EKS1.21 I have had to reduce
replica to 1 but other than that it seems okay.

**Comment by jgallucci32** [comment]
Is there an easier method to downgrading K3s other than a complete reinstall specifying `INSTALL_K3S_VERSION=v1.20.8+k3s1` when doing the K3s install? Seems very specific because I lose the ability to get the latest release of 1.20.x when doing this method.

Overall I was kind of surprised to find that 1.21 made it's way into the `stable` channel considering Rancher 2.6 has not yet been released. This is not the first time K3s has updated ahead of Rancher Server and caused issues. Would be nice if K3s stable channels would keep with the stable Rancher server channels.

**Comment by DerFels** [comment]
Is there any update on this? 
We downgraded to k8s 1.20.11 and still had to scale down the rancher replicas to 1 in order to get everything operational again.

**Comment by ArsalanSaleem94** [comment]
> 

This has solved my problem, thanks a lot.

Running HA k3s cluster and installing Rancher on it.

**Comment by brianbturner82** [comment]
We encountered this after upgrading RKE to 1.21.7 to match our Rancher 2.6.3 version. I eventually had to revert to an etcd snapshot of 1.21.5, which is the version we were previously on. However, after a short amount of time everything broke again. How can I fix this?

**Comment by brianbturner82** [comment]
```
kubectl -n cattle-system delete secret ``kubectl -n cattle-system get secret -o json | jq -r '.items[].metadata | select(.annotations."kubernetes.io/service-account.name" == "rancher") | .name' `

kubectl -n cattle-system delete pods -l app=rancher

```
The above fixed it for me as well. 

Here are some of the symptoms i observed prior to finding this page:

1. Clusters going in and out of active/unavailable states
2. Clusters in unavailable states with a message that reads 'Cluster agent unavailable' even when all dowsntream agents are running.
3. Failures to connect to downstream clusters via kubectl with the following message: 

`an error on the server ("unable to create impersonator account: error setting up impersonation for user u-uhsicwycs5: failed to get secret for service account: cattle-impersonation-system/cattle-impersonation-u-uhsicwycs5, error: timed out waiting for the condition") has prevented the request from succeeding
`

4. The following messages repeating in the logs:

```
[ERROR] error syncing 'kubeconfig-u-xnki2n2d5gj7vlx': handler cat-token-controller: clusterAuthToken for token [kubeconfig-u-xnki2n2d5gj7vlx] has not been created yet, requeuing

[ERROR] failed to start cluster controllers c-tjtdh: context canceled

[ERROR] Failed to connect to peer wss://10.42.0.4/v3/connect [local ID=10.42.1.4]: websocket: bad handshake
```

**Comment by NullIsNot0** [comment]
My 2 cents to this:
After running these commands
```
kubectl -n cattle-system delete secret ``kubectl -n cattle-system get secret -o json | jq -r '.items[].metadata | select(.annotations."kubernetes.io/service-account.name" == "rancher") | .name' `

kubectl -n cattle-system delete pods -l app=rancher
```
downstream clusters displayed _Active_ states again, but websockets did not work (red error pop up: "`Unable to establish a WebSocket connection to the server. If your server is behind a proxy or SSL-termination device, Browser can not connect to WebSocket. If you run the server behind a proxy, please make sure the proxy supports WebSockets. Streaming stats, logs, shell/console, and auto-updating of the state of resources may not work until this is resolved.`") - status updates, console, logs did not work.
I had to restart Rancher cluster nodes for everything to working fine again.

**Comment by brianbturner82** [comment]
Just wanted to update this bug with my experience and a couple of questions. 

We originally tried using the workaround of deleting the secret and restarting Rancher, which seemed to work some of the time. We also tried rebooting the Rancher nodes, but that didn't see to consistently help either. Rancher would just occasionally go into this state and not recover until performing a rollout restart, and it would require multiple restarts. 

We had been trying to avoid the workaround of scaling down to one Rancher pod because, quite frankly, it's a terrible solution for an enterprise environment. HA is a core functionality, in my opinion. Nonetheless, we finally scaled down to one Rancher pod and things have been good since then. No more 'failed to connect to peer' messages between Rancher pods as there is only one pod now and it doesn't have to sync with anything.  The Rancher pod still crashes occasionally due to CPU contention, even though the underlying node is at 4 times what the scaling docs suggest for an environment our size, but when it does crash it just comes right back up now instead of going into a death spiral while trying to communicate with itself. So having one pod crash every now and then and waiting for it to come back up is actually less disruptive than Rancher crashing in HA.

For what it's worth, ours is a relatively large environment with about 300 clusters / 1500 nodes, so this may be something that manifests at scale. That said, is there anything on the road map about when we might get a software fix for this? I know it's mentioned as being fixed in 2.6.2, but we're at 2.6.3, so is this possibly some kind of regression? We started encountering this as soon as we upgraded to 2.6.3. Never had the issue in 2.4.5 or 2.5.8. Running enterprise workload without HA is not a viable long term solution though, so i'm curious about a fix. I haven't seen anything about it in 2.6.4 release notes.

**Comment by weisdd** [comment]
@brianbturner82 Can't say anything for sure since I stopped using Rancher after changing companies, but my **guess** at that time (we were using `v2.5.x`) was that it might be part of the same issue as https://github.com/rancher/rancher/issues/30959. So, it's likely to be fixed starting from [v2.6.3-patch1](https://github.com/rancher/rancher/releases/tag/v2.6.3-patch1) under `The API Server has been updated to fix slow consumers causing deadlocks. See https://github.com/rancher/rancher/pull/34906.` release note. I'd give it a try :)

**Comment by Sphinxgaia** [comment]
a temporary solution in Rancher v2.5.12 against an AKS cluster in v1.21 (we don't use all Rancher's capabilities) but websocket: bad handhake disappear. 

create a service-account-token and mount it into Rancher pod with a deployment patch. This prevent mutation of Kubernetes API mounting a projected volume with native rancher service account (JWT new format)

```bash
# Create secret service-account-token associated with native Rancher service account
cat <<EOF | kubectl apply -f -
apiVersion: v1
kind: Secret
metadata:
  name: rancher-fixed-token
  namespace: cattle-system
    annotations:
      kubernetes.io/service-account.name: rancher
type: kubernetes.io/service-account-token
EOF

cat <<EOF | kubectl apply -f - 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rancher
  namespace: cattle-system
spec:
  template:
    spec:
      containers:
      - name: rancher
        volumesMounts:
        - mountPath: /var/run/secrets/tokens
          name: svctoken
      volumes:
      - name: svctoken
        secret:
          secretName: rancher-fixed-token
EOF
```
