### ISSUE TITLE
Need to  build a testcontainer that can deploy successfully in PSP enabled setup.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#26789]
Currently the test container  used in automation runs for validating clusters is built from "nginx" image.

`nginx` container does not deploy successfully on a cluster with "Pod Security Policy" set to "restricted".
Pod gets deployed and then gets into a crash loop with following error messages in the logs:

```2020/04/23 20:11:05 [emerg] 1#1: chown("/var/cache/nginx/client_temp", 101) failed (1: Operation not permitted)
nginx: [emerg] chown("/var/cache/nginx/client_temp", 101) failed (1: Operation not permitted)```


Need to find an alternate way to build a testc ontainer that can be used for automation runs.

**Comment by FFock** [comment]
Due to this bug, **Longhorn UI 1.0.0** cannot be deployed to a cluster with Pod Security Policy "restricted" enabled on Rancher 2.4.3, too.

**Comment by khushboo-rancher** [comment]
@FFock You can refer to https://github.com/longhorn/longhorn/pull/1281 and try workaround to deploy longhorn to a cluster with Pod Security Policy "restricted" enabled

**Comment by FFock** [comment]
I have tried longhorn/longhorn#1281 without success. Steps I had done:

1. Created a "longhorn-system" project in a cluster with default PSP "restricted"
2. Defined security policy for the project to "psp-longhorn-system" as described as "least privileged PSP" in https://github.com/longhorn/longhorn/issues/603 
3. Launched Longhorn 1.0.0 in that project/namespace.
4. All pods deployed successfully except "longhorn-driver-deployer" hangs in "PodInitilization" and "longhorn-manager" is not running (intentionally?) on any node.

I tried to add the "missing" serviceAccount values as mentioned in https://github.com/longhorn/longhorn/issues/603 but I have no clue were to do that and how. All I tried so far, had no effect.

**Comment by khushboo-rancher** [comment]
@FFock You just need to deploy PSP as mentioned https://github.com/longhorn/longhorn/pull/1281#issuecomment-622924015 before launching longhorn app.

Try below steps:
1. Create a cluster with PSP enabled with 'restricted'.
2. kubectl apply yaml from https://github.com/longhorn/longhorn/pull/1281#issuecomment-622924015
3. Check the PodSecurityPolicy, it should be as below.
```
> kubectl get PodSecurityPolicy
NAME                      PRIV    CAPS   SELINUX    RUNASUSER   FSGROUP     SUPGROUP    READONLYROOTFS   VOLUMES
default-psp               true    *      RunAsAny   RunAsAny    RunAsAny    RunAsAny    false            *
longhorn-default-psp      false          RunAsAny   RunAsAny    RunAsAny    RunAsAny    false            configMap,emptyDir,projected,secret,downwardAPI
longhorn-privileged-psp   true    *      RunAsAny   RunAsAny    RunAsAny    RunAsAny    false            *
restricted-psp            false          RunAsAny   RunAsAny    MustRunAs   MustRunAs   false            configMap,emptyDir,projected,secret,downwardAPI,persistentVolumeClaim
```
4. Launch Longhorn app 1.0.0.  It should work.

Let us know if this works for you.

**Comment by FFock** [comment]
Had not luck yet. It seems that I got a bit further, but now the longhorn-engine pods are failing with:
cannot create regular file '/data/longhorn': Permission denied
Please note that I am using RHEL 7.8 with SELinux enabled. 

The following issue seems to be related to the bug I am facing:
https://github.com/longhorn/longhorn/issues/1273
But is there a workaround? If not which Longhorn version will include that fix?

**Comment by khushboo-rancher** [comment]
Thanks @FFock for letting us know. Are you using k3s or k8s?
As you mentioned we had an issue with k3s https://github.com/longhorn/longhorn/issues/1273 which is solved now and will be out with longhorn version - v1.0.1

**Comment by FFock** [comment]
Issue longhorn/longhorn#1273 does not solve all needed issues when SELinux is enabled. I had to run
```
ausearch -c 'csi-resizer' --raw | audit2allow -M my-csiresizer
semodule -i my-csiresizer.pp
ausearch -c 'csi-provisioner' --raw | audit2allow -M my-csiprovisioner
semodule -i my-csiprovisioner.pp
ausearch -c 'csi-attacher' --raw | audit2allow -M my-csiattacher
semodule -i my-csiattacher.pp
```
on all nodes too, to get it working.
