### ISSUE TITLE
2.4.3 upgrade monitoring to 0.1.0 fails

### ISSUE THREAD

**Issue by eroji** [rancher/rancher#26969]
Just upgraded Rancher to 2.4.3 from 2.3.6. The clusters I have were previously running on 1.7.4 and I have upgraded them to 1.7.5. It indicated there is a monitoring upgrade to 0.1.0. I was previously running 0.7.0 without any issues. However, when proceeded with the upgrade, the `prometheus-cluster-monitoring` statefulset never comes up on and is constantly created then removed. It's not quite clear what the issue is. All the sidecars in the pod comes up healthy except `prometheus-agent`. I'm running CentOS 7 VMs and Docker 19.3.1/19.3.8.

I am using persistent storage. Of the clusters I have that I tried performing the upgrade, one is using Rook/Ceph and one is on AWS using EBS. Both exhibit the same exact problem. However, if I turn off persistent storage it comes online fine.

**Comment by teknologista** [comment]
Same issue here:

Logs from the pod:
`level=info ts=2020-05-07T17:32:26.461Z caller=main.go:329 msg="Starting Prometheus" version="(version=2.11.1, branch=HEAD, revision=e5b22494857deca4b806f74f6e3a6ee30c251763)"
level=info ts=2020-05-07T17:32:26.461Z caller=main.go:330 build_context="(go=go1.12.7, user=root@d94406f2bb6f, date=20190710-13:51:17)"
level=info ts=2020-05-07T17:32:26.461Z caller=main.go:331 host_details="(Linux 4.15.0-76-generic #86-Ubuntu SMP Fri Jan 17 17:24:28 UTC 2020 x86_64 prometheus-cluster-monitoring-0 (none))"
level=info ts=2020-05-07T17:32:26.461Z caller=main.go:332 fd_limits="(soft=1048576, hard=1048576)"
level=info ts=2020-05-07T17:32:26.461Z caller=main.go:333 vm_limits="(soft=unlimited, hard=unlimited)"
level=info ts=2020-05-07T17:32:26.463Z caller=main.go:652 msg="Starting TSDB ..."
level=info ts=2020-05-07T17:32:26.463Z caller=web.go:448 component=web msg="Start listening for connections" address=127.0.0.1:9090
level=info ts=2020-05-07T17:32:26.488Z caller=main.go:667 fs_type=EXT4_SUPER_MAGIC
level=info ts=2020-05-07T17:32:26.488Z caller=main.go:668 msg="TSDB started"
level=info ts=2020-05-07T17:32:26.488Z caller=main.go:738 msg="Loading configuration file" filename=/etc/prometheus/config_out/prometheus.env.yaml
level=info ts=2020-05-07T17:32:26.505Z caller=kubernetes.go:192 component="discovery manager scrape" discovery=k8s msg="Using pod service account via in-cluster config"
level=info ts=2020-05-07T17:32:26.507Z caller=kubernetes.go:192 component="discovery manager scrape" discovery=k8s msg="Using pod service account via in-cluster config"
level=info ts=2020-05-07T17:32:26.508Z caller=kubernetes.go:192 component="discovery manager scrape" discovery=k8s msg="Using pod service account via in-cluster config"
level=info ts=2020-05-07T17:32:26.511Z caller=kubernetes.go:192 component="discovery manager scrape" discovery=k8s msg="Using pod service account via in-cluster config"
level=info ts=2020-05-07T17:32:26.514Z caller=kubernetes.go:192 component="discovery manager scrape" discovery=k8s msg="Using pod service account via in-cluster config"
level=info ts=2020-05-07T17:32:26.516Z caller=kubernetes.go:192 component="discovery manager scrape" discovery=k8s msg="Using pod service account via in-cluster config"
level=info ts=2020-05-07T17:32:26.522Z caller=main.go:766 msg="Completed loading of configuration file" filename=/etc/prometheus/config_out/prometheus.env.yaml
level=info ts=2020-05-07T17:32:26.522Z caller=main.go:621 msg="Server is ready to receive web requests."
level=warn ts=2020-05-07T17:32:29.261Z caller=main.go:496 msg="Received SIGTERM, exiting gracefully..."
level=info ts=2020-05-07T17:32:29.262Z caller=main.go:521 msg="Stopping scrape discovery manager..."
level=info ts=2020-05-07T17:32:29.262Z caller=main.go:535 msg="Stopping notify discovery manager..."
level=info ts=2020-05-07T17:32:29.262Z caller=main.go:557 msg="Stopping scrape manager..."
level=info ts=2020-05-07T17:32:29.262Z caller=manager.go:776 component="rule manager" msg="Stopping rule manager..."
level=info ts=2020-05-07T17:32:29.262Z caller=manager.go:782 component="rule manager" msg="Rule manager stopped"
level=info ts=2020-05-07T17:32:29.262Z caller=main.go:517 msg="Scrape discovery manager stopped"
level=info ts=2020-05-07T17:32:29.262Z caller=main.go:551 msg="Scrape manager stopped"
level=info ts=2020-05-07T17:32:29.262Z caller=main.go:531 msg="Notify discovery manager stopped"
level=info ts=2020-05-07T17:32:29.274Z caller=notifier.go:602 component=notifier msg="Stopping notification manager..."
level=info ts=2020-05-07T17:32:29.274Z caller=main.go:722 msg="Notifier manager stopped"
level=info ts=2020-05-07T17:32:29.274Z caller=main.go:734 msg="See you next time!"`

and

`level=error ts=2020-05-07T17:07:53.291Z caller=pod.go:85 component="discovery manager scrape" discovery=k8s role=pod msg="pod informer unable to sync cache"
level=error ts=2020-05-07T17:07:53.291Z caller=endpoints.go:131 component="discovery manager scrape" discovery=k8s role=endpoint msg="endpoints informer unable to sync cache"
level=error ts=2020-05-07T17:07:53.291Z caller=endpoints.go:131 component="discovery manager scrape" discovery=k8s role=endpoint msg="endpoints informer unable to sync cache"
level=error ts=2020-05-07T17:07:53.291Z caller=pod.go:85 component="discovery manager scrape" discovery=k8s role=pod msg="pod informer unable to sync cache"
level=error ts=2020-05-07T17:07:53.292Z caller=pod.go:85 component="discovery manager scrape" discovery=k8s role=pod msg="pod informer unable to sync cache"
level=error ts=2020-05-07T17:07:53.292Z caller=pod.go:85 component="discovery manager scrape" discovery=k8s role=pod msg="pod informer unable to sync cache"
level=info ts=2020-05-07T17:07:53.301Z caller=main.go:766 msg="Completed loading of configuration file" filename=/etc/prometheus/config_out/prometheus.env.yam`

**Comment by jiaqiluo** [comment]
hi @teknologista can you provide more details about your setup and the steps you did?  Did you upgrade only the monitoring? Or did you upgrade Rancher & the cluster as well?

**Comment by teknologista** [comment]
@jiaqiluo I was on Rancher 2.3 series.
All was running prefectly on an rke launched custom cluster running 2.3.6

1) I upgraded the cluster to 2.4.3
2) I upgraded kubernetes from 1.17.4 to 1.17.5 using rke
3) all was fine

Then I decided to upgrade the monitoring to 0.1.0 and from there it went all crazy...
the operator ini as well as the cluster monitoring workloads keep on restarting every 3 secs.
Istio is working for the ingress gateway but kiali and jaeger are not...

Thank god the istio gateway is still working...

I also tried to cleanup everything related to monitoring down to the volumes and namespace and relaunch monitoring and istio from scratch. Same issue.

**Comment by crazycreak** [comment]
same here, we disabled the monitoring and enabled it again ... monitoring doesn't start with persistent storage

**Comment by teknologista** [comment]
@jiaqiluo any way to downgrade or install the previous monitoring charts ?

**Comment by teknologista** [comment]
> same here, we disabled the monitoring and enabled it again ... monitoring doesn't start with persistent storage

I just tested with persistent storage and it doesn't make any difference. same issue

**Comment by jiaqiluo** [comment]
Check 1:
- run Rancher v2.3.7, single install 
- add a cluster with cloud provider (Amazon)
- add a storage class
- enable cluster monitoring (0.1.0) with persistent storage enabled 
- Results: the cluster monitoring works

Check 2:
- run Rancher v2.4.3, single install 
- add a cluster with cloud provider (Amazon)
- add a storage class
- enable cluster monitoring (0.1.0) with persistent storage enabled 
- Results: the cluster monitoring does NOT work, see the following error on the pod `prometheus-cluster-monitoring-0`
```
level=info ts=2020-05-07T17:52:30.869Z caller=main.go:329 msg="Starting Prometheus" version="(version=2.11.1, branch=HEAD, revision=e5b22494857deca4b806f74f6e3a6ee30c251763)"
level=info ts=2020-05-07T17:52:30.869Z caller=main.go:330 build_context="(go=go1.12.7, user=root@d94406f2bb6f, date=20190710-13:51:17)"
level=info ts=2020-05-07T17:52:30.869Z caller=main.go:331 host_details="(Linux 4.15.0-1051-aws #53-Ubuntu SMP Wed Sep 18 13:35:53 UTC 2019 x86_64 prometheus-cluster-monitoring-0 (none))"
level=info ts=2020-05-07T17:52:30.869Z caller=main.go:332 fd_limits="(soft=1048576, hard=1048576)"
level=info ts=2020-05-07T17:52:30.869Z caller=main.go:333 vm_limits="(soft=unlimited, hard=unlimited)"
level=info ts=2020-05-07T17:52:30.870Z caller=main.go:652 msg="Starting TSDB ..."
level=info ts=2020-05-07T17:52:30.871Z caller=web.go:448 component=web msg="Start listening for connections" address=127.0.0.1:9090
level=info ts=2020-05-07T17:52:30.889Z caller=main.go:667 fs_type=EXT4_SUPER_MAGIC
level=info ts=2020-05-07T17:52:30.889Z caller=main.go:668 msg="TSDB started"
level=info ts=2020-05-07T17:52:30.889Z caller=main.go:738 msg="Loading configuration file" filename=/etc/prometheus/config_out/prometheus.env.yaml
level=info ts=2020-05-07T17:52:30.889Z caller=main.go:521 msg="Stopping scrape discovery manager..."
level=info ts=2020-05-07T17:52:30.889Z caller=main.go:535 msg="Stopping notify discovery manager..."
level=info ts=2020-05-07T17:52:30.889Z caller=main.go:557 msg="Stopping scrape manager..."
level=info ts=2020-05-07T17:52:30.890Z caller=main.go:531 msg="Notify discovery manager stopped"
level=info ts=2020-05-07T17:52:30.890Z caller=main.go:517 msg="Scrape discovery manager stopped"
level=info ts=2020-05-07T17:52:30.890Z caller=manager.go:776 component="rule manager" msg="Stopping rule manager..."
level=info ts=2020-05-07T17:52:30.890Z caller=manager.go:782 component="rule manager" msg="Rule manager stopped"
level=info ts=2020-05-07T17:52:30.890Z caller=main.go:551 msg="Scrape manager stopped"
level=info ts=2020-05-07T17:52:30.915Z caller=notifier.go:602 component=notifier msg="Stopping notification manager..."
level=info ts=2020-05-07T17:52:30.915Z caller=main.go:722 msg="Notifier manager stopped"
level=error ts=2020-05-07T17:52:30.915Z caller=main.go:731 err="error loading config from \"/etc/prometheus/config_out/prometheus.env.yaml\": couldn't load configuration (--config.file=\"/etc/prometheus/config_out/prometheus.env.yaml\"): open /etc/prometheus/config_out/prometheus.env.yaml: no such file or directory"
```

Check 3:
- run Rancher v2.3.6, single install 
- add a cluster with cloud provider (Amazon)
- add a storage class
- enable cluster monitoring (0.0.7) with persistent storage enabled 
- Results: the cluster monitoring works
- upgrade to v2.4.3
- upgrade monitoring to 0.1.0
- Results: fail to upgrade the workload `prometheus-cluster-monitoring`

**Comment by jiaqiluo** [comment]
The cluster monitoring eventually works after a long wait and uncountable re-creation of the workload `prometheus-cluster-monitoring`, especially:
- for case 2, it takes about 1 hour for `prometheus-cluster-monitoring` to be healthy
- for case 3, it takes about 2 hours for `prometheus-cluster-monitoring` to be healthy

**Comment by loganhz** [comment]
This is bad. 
It's really easy to reproduce in Rancher `v2.4.3` with k8s `v1.17.5` and monitoring `v0.1.0`.
Just enable cluster monitoring with PV enabled.

Also tried Rancher monitoring `0.0.7`, same problem.

Here is the change between v0.0.7 and v0.1.0 https://github.com/rancher/system-charts/pull/204/commits/32907f0b63f6c30f1574247696525d7c77d3c864

It looks like it's related to Prometheus Operator version and Kubernetes version.

I guess it is related to https://github.com/coreos/prometheus-operator/pull/2987/files which has been fixed in `v0.36.0` 

# Workaround

## Option 1:

Enable cluster monitoring without PV enabled

## Option 2:

- Disable cluster monitoring first.
- Edit `system-library` to use `https://github.com/loganhz/system-charts` with branch `fix`.
- Enable monitoring again.

![image](https://user-images.githubusercontent.com/21168270/81359927-0e600e80-910d-11ea-821f-15be4cc15ac6.png)
 
Related fix commit https://github.com/loganhz/system-charts/commit/a41ce9f9e65778efc5cb05669486173449b1ee6c

## Option 3:

- Click `View Edit YAML` of `prometheus-operator-monitoring-operator`
- Delete line `- --crd-apigroup=monitoring.coreos.com`
- Update image to `quay.io/coreos/prometheus-operator:v0.38.1`
- Click `Save`

![image](https://user-images.githubusercontent.com/21168270/81360284-06ed3500-910e-11ea-932a-19274cb54eb5.png)

# Solution

At least, we need to upgrade Prometheus Operator version. 

Maybe we can bump component versions for Rancher monitoring such as prometheus, operator, exporter, configmap-reload and so on.

You can find the whole image list via https://github.com/rancher/system-charts/blob/release-v2.4/charts/rancher-monitoring/v0.1.0/values.yaml

We need to verify monitoring and alerting in many cases such as different K8s version,  PV enabled nor not, upgrading monitoring from old monitoring version.

**Comment by loganhz** [comment]
Upgrade Prometheus Operator can fix this issue. But it means we need to do a lot of regression tests for monitoring and alerting.

Maybe we should revert https://github.com/rancher/rancher/commit/ac7471754e6301262dfc2a696195d5bd099cbf8f or a better fix for it.

It will update the Prometheus CRD with a new `storage.volumeClaimTemplate.metadata.creationTimestamp` value when Rancher controller force deploy monitoring app. The field will be ignored by Prometheus Operator 0.38. But in  Prometheus Operator 0.32, Prometheus Operator will redeploy Prometheus StatefulSet.  

Rancher controller should not force deploy cluster monitoring app when:

- Prometheus Operator hasn't created the first Prometheus StatefulSet yet.
- Prometheus StatefulSet is not removed by users by mistake. It is removed by Prometheus Operator intentionally.(Not sure if it is doable)

**Comment by teknologista** [comment]
@loganhz That is great news! Thanks for the quick response.

**Comment by barankaynak** [comment]
Disabling PV helped.

**Comment by StrongMonkey** [comment]
@loganhz Thanks for the detailed response. I think it is a good time to bump our chart version since it is lagging behind upstream.

**Comment by StrongMonkey** [comment]
https://github.com/rancher/system-charts/pull/226. This PR should bump our monitoring chart with upstream prometheus-operator and fix the issue above. It only bumps image version and CRD.

@jiaqiluo you can use my branch for testing the issue. https://github.com/StrongMonkey/system-charts.git(monitoring-v0.1.1). As @loganhz instructed, you should test all the functionality(upgrade, fresh-install) and make sure there is no regression.

**Comment by dr4Ke** [comment]
I can confirm that I was able to upgrade monitoring to 0.1.1, on a fresh cluster installed with monitoring 0.1.0 enabled, using @StrongMonkey branch.

**Comment by StrongMonkey** [comment]
@jiaqiluo This issue is ready to test. You can use my branch for now to do the testing, once the new chart has been validated we will merge into master.

**Comment by jiaqiluo** [comment]
The bug fix is validated.

Steps:
- run Rancher v2.3.6, single install
- add a cluster with the cloud provider (Amazon) (v1.17.4)
- add a storage class
- enable cluster monitoring (0.0.7) with persistent storage enabled
- Results: the cluster monitoring works
- upgrade to v2.4.3
- edit the system chart to point to https://github.com/StrongMonkey/system-charts/tree/monitoring-v0.1.1
- upgrade monitoring to 0.1.1

Result:
- The monitoring upgrade succeeds and is functional

Also validate that both cluster monitoring and project monitoring (v0.1.1) work on k8s 1.17.5 cluster on a fresh-installed v2.4.3 setup

**Comment by jiaqiluo** [comment]
This issue is close since the bug is fixed by the new monitoring chart version 0.1.1 here: https://github.com/StrongMonkey/system-charts/tree/monitoring-v0.1.1 

New issues will be made if needed for the new monitoring chart.

**Comment by saikaushik-itsmyworld** [comment]
> same here, we disabled the monitoring and enabled it again ... monitoring doesn't start with persistent storage

I ran into same Issue, I'm using Kubernetes version 1.18.2 and latest rancher stable version 2.4.3.
When I enabled the monitoring with persistent storage, prometheus-cluster-monitoring-0 keeps on failing

**Comment by saikaushik-itsmyworld** [comment]
> This issue is close since the bug is fixed by the new monitoring chart version 0.1.1 here: https://github.com/StrongMonkey/system-charts/tree/monitoring-v0.1.1
> 
> New issues will be made if needed for the new monitoring chart.

@jiaqiluo @StrongMonkey Looks like this isn't completely fixed. I got the monitoring enabled in `Rancher2.4.3` with your fix! But Grafana dashboard isn't still working. When I try to open the Grafana dashboard from RancherUI I'm getting `502's Bad Gateway` errors. Here is the screenshot
![image](https://user-images.githubusercontent.com/29764002/82000595-deda6600-9626-11ea-9841-194cf9c7b994.png)

**Comment by jiaqiluo** [comment]
Hi @saikaushik-itsmyworld  
I cannot reproduce your issue. I tried running Rancher v2.4.3 and enabling the cluster monitoring v0.1.1 with/without persistent storage.

Can you provide more info about your setup? like the k8s version of your cluster, where are nodes from?

in your case, do you see the node metrics on the node detail page in Rancher UI?

**Comment by saikaushik-itsmyworld** [comment]
@jiaqiluo I'm using latest k8 version v1.18.2 rancher2.4.3 and monitoring v0.1.1. 
I have deployed the multi-master cluster with v1.17.4 and then upgraded it to latest version. These nodes are running Centos7 and running on vsphere6.7.
Yes I see the node metrics in the rancher UI fine! but its the grafana dashboard that's failing.
![image](https://user-images.githubusercontent.com/29764002/82091011-a5583800-96c4-11ea-8a84-84e7abc3bcef.png)

**Comment by jiaqiluo** [comment]
reopen this issue to wait for the PR is merged into rancher/system-charts

**Comment by StrongMonkey** [comment]
@saikaushik-itsmyworld can you share the log of your grafana pod? Also is any of your monitoring pods crashing?

**Comment by jiaqiluo** [comment]
@saikaushik-itsmyworld  k8s 1.18 is not officially supported on rancher v2.4.3

@StrongMonkey I got the issue reproduced in this way:
- run Rancher master-head
- add a k8s 1.18.2 cluster with cloud provider enabled (AWS)
- enable monitoring 0.1.1 with persistence storage  

<img width="1819" alt="Screen Shot 2020-05-15 at 2 23 37 PM" src="https://user-images.githubusercontent.com/6218999/82097424-b9e20380-96b7-11ea-92eb-e57911e01a0b.png">

**Comment by saikaushik-itsmyworld** [comment]
@StrongMonkey All the Pods in the cattle-prometheus namespace working fine, none of them crashes.
![image](https://user-images.githubusercontent.com/29764002/82106036-9a190280-96ec-11ea-9292-26b74bfc22e7.png)

But my grafana-cluster-monitoring and prometheus-operator-monitoring-operator pods are being overwhelmed with these errors 
```
t=2020-05-15T00:37:17+0000 lvl=info msg="Initializing LoginService" logger=server
t=2020-05-15T00:37:17+0000 lvl=info msg="Initializing SearchService" logger=server
t=2020-05-15T00:37:17+0000 lvl=info msg="Initializing TracingService" logger=server
t=2020-05-15T00:37:17+0000 lvl=info msg="Initializing UsageStatsService" logger=server
t=2020-05-15T00:37:17+0000 lvl=info msg="Initializing CleanUpService" logger=server
t=2020-05-15T00:37:17+0000 lvl=info msg="Initializing NotificationService" logger=server
t=2020-05-15T00:37:17+0000 lvl=info msg="Initializing provisioningServiceImpl" logger=server
t=2020-05-15T00:37:17+0000 lvl=info msg="inserting datasource from configuration " logger=provisioning.datasources name=RANCHER_MONITORING
t=2020-05-15T00:37:17+0000 lvl=info msg="Backend rendering via phantomJS" logger=rendering renderer=phantomJS
t=2020-05-15T00:37:17+0000 lvl=warn msg="phantomJS is deprecated and will be removed in a future release. You should consider migrating from phantomJS to grafana-image-renderer plugin. Read more at https://grafana.com/docs/grafana/latest/administration/image_rendering/" logger=rendering renderer=phantomJS
t=2020-05-15T00:37:17+0000 lvl=warn msg="[Deprecated] the dashboard provisioning config is outdated. please upgrade" logger=provisioning.dashboard filename=/etc/grafana/provisioning/dashboards/all.yaml
t=2020-05-15T00:37:17+0000 lvl=info msg="Initializing Stream Manager"
t=2020-05-15T00:37:17+0000 lvl=info msg="HTTP Server Listen" logger=http.server address=[::]:3000 protocol=http subUrl= socket=
t=2020-05-15T00:38:49+0000 lvl=info msg=Requesting logger=data-proxy-log url="http://prometheus-operated:9090/api/v1/series?match[]=node_load1&start=1589502830&end=1589503130"
t=2020-05-15T00:39:19+0000 lvl=eror msg="Data proxy error" logger=data-proxy-log userId=0 orgId=1 uname= path=/api/datasources/proxy/1/api/v1/series remote_addr="10.3.2.142, 10.10.10.45" referer="https://rancher.example.com/k8s/clusters/c-7x7qs/api/v1/namespaces/cattle-prometheus/services/http:access-grafana:80/proxy/d/FnxG5TYiz/nodes?orgId=1" error="http: proxy error: dial tcp: i/o timeout"
t=2020-05-15T00:39:19+0000 lvl=info msg="Request Completed" logger=context userId=0 orgId=1 uname= method=GET path=/api/datasources/proxy/1/api/v1/series status=502 remote_addr="10.3.2.142, 10.10.10.45" time_ms=30006 size=0 referer="https://rancher.example.com/k8s/clusters/c-7x7qs/api/v1/namespaces/cattle-prometheus/services/http:access-grafana:80/proxy/d/FnxG5TYiz/nodes?orgId=1"
t=2020-05-15T00:39:25+0000 lvl=info msg=Requesting logger=data-proxy-log url="http://prometheus-operated:9090/api/v1/query_range?query=(1%20-%20(avg(irate(node_cpu_seconds_total%7Bmode%3D%22idle%22%2C%20instance%3D~%22%5E172.31.11.173%3A9796%22%7D%5B5m%5D))%20by%20(instance)))%20*%20100&start=1589502855&end=1589503155&step=15"
t=2020-05-15T00:39:25+0000 lvl=info msg=Requesting logger=data-proxy-log url="http://prometheus-operated:9090/api/v1/query_range?query=((node_memory_SwapTotal_bytes%7Binstance%3D~%22%5E172.31.11.173%3A9796%22%7D%20-%20node_memory_SwapFree_bytes%7Binstance%3D~%22%5E172.31.11.173%3A9796%22%7D)%20%2F%20(node_memory_SwapTotal_bytes%7Binstance%3D~%22%5E172.31.11.173%3A9796%22%7D%20))%20*%20100&start=1589502855&end=1589503155&step=15"
t=2020-05-15T00:39:25+0000 lvl=info msg=Requesting logger=data-proxy-log url="http://prometheus-operated:9090/api/v1/query_range?query=(sum(node_filesystem_size_bytes%7Bdevice!~%22rootfs%7CHarddiskVolume.%2B%22%2Cinstance%3D~%22%5E172.31.11.173%3A9796%22%7D)%20%20%20%20%20-%20sum(node_filesystem_free_bytes%7Bdevice!~%22rootfs%7CHarddiskVolume.%2B%22%2Cinstance%3D~%22%5E172.31.11.173%3A9796%22%7D))%20%2F%20sum(node_filesystem_size_bytes%7Bdevice!~%22rootfs%7CHarddiskVolume.%2B%22%2Cinstance%3D~%22%5E172.31.11.173%3A9796%22%7D)%20*%20100&start=1589502855&end=1589503155&step=15"
t=2020-05-15T00:39:25+0000 lvl=info msg=Requesting logger=data-proxy-log url="http://prometheus-operated:9090/api/v1/query_range?query=avg(node_load1%7Binstance%3D~%22172.31.11.173%3A9796%22%7D)%20%2F%20count(node_cpu_seconds_total%7Bmode%3D%22system%22%2Cinstance%3D~%22%5E172.31.11.173%3A9796%22%7D)%20*%20100&start=1589502855&end=1589503155&step=15"
t=2020-05-15T00:39:25+0000 lvl=info msg=Requesting logger=data-proxy-log url="http://prometheus-operated:9090/api/v1/query_range?query=100%20-%20((node_memory_MemAvailable_bytes%7Binstance%3D~%22%5E172.31.11.173%3A9796%22%7D%20*%20100)%20%2F%20node_memory_MemTotal_bytes%7Binstance%3D~%22%5E172.31.11.173%3A9796%22%7D)&start=1589502855&end=1589503155&step=15"
t=2020-05-15T00:39:25+0000 lvl=info msg=Requesting logger=data-proxy-log url="http://prometheus-operated:9090/api/v1/query_range?query=avg(node_load1%7Binstance%3D~%22172.31.11.173%3A9796%22%7D)%20%2F%20sum(wmi_cs_logical_processors%7Binstance%3D~%22172.31.11.173%3A9796%22%7D)%20*%20100&start=1589502855&end=1589503155&step=15"
t=2020-05-15T00:39:55+0000 lvl=eror msg="Data proxy error" logger=data-proxy-log userId=0 orgId=1 uname= path=/api/datasources/proxy/1/api/v1/query_range remote_addr="10.3.2.142, 10.10.10.49" referer="https://rancher.example.com/k8s/clusters/c-7x7qs/api/v1/namespaces/cattle-prometheus/services/http:access-grafana:80/proxy/d/FnxG5TYiz/nodes?orgId=1" error="http: proxy error: dial tcp: i/o timeout"
t=2020-05-15T00:39:55+0000 lvl=info msg="Request Completed" logger=context userId=0 orgId=1 uname= method=GET path=/api/datasources/proxy/1/api/v1/query_range status=502 remote_addr="10.3.2.142, 10.10.10.49" time_ms=30023 size=0 referer="https://rancher.example.com/k8s/clusters/c-7x7qs/api/v1/namespaces/cattle-prometheus/services/http:access-grafana:80/proxy/d/FnxG5TYiz/nodes?orgId=1"
t=2020-05-15T00:39:55+0000 lvl=eror msg="Data proxy error" logger=data-proxy-log userId=0 orgId=1 uname= path=/api/datasources/proxy/1/api/v1/query_range remote_addr="10.3.2.142, 10.10.10.45" referer="https://rancher.example.com/k8s/clusters/c-7x7qs/api/v1/namespaces/cattle-prometheus/services/http:access-grafana:80/proxy/d/FnxG5TYiz/nodes?orgId=1" error="http: proxy error: dial tcp: i/o timeout"
t=2020-05-15T00:39:55+0000 lvl=info msg="Request Completed" logger=context userId=0 orgId=1 uname= method=GET path=/api/datasources/proxy/1/api/v1/query_range status=502 remote_addr="10.3.2.142, 10.10.10.45" time_ms=30024 size=0 referer="https://rancher.example.com/k8s/clusters/c-7x7qs/api/v1/namespaces/cattle-prometheus/services/http:access-grafana:80/proxy/d/FnxG5TYiz/nodes?orgId=1"
t=2020-05-15T00:39:55+0000 lvl=eror msg="Data proxy error" logger=data-proxy-log userId=0 orgId=1 uname= path=/api/datasources/proxy/1/api/v1/query_range remote_addr="10.3.2.142, 10.10.10.45" referer="https://rancher.example.com/k8s/clusters/c-7x7qs/api/v1/namespaces/cattle-prometheus/services/http:access-grafana:80/proxy/d/FnxG5TYiz/nodes?orgId=1" error="http: proxy error: dial tcp: lookup prometheus-operated on 169.254.25.10:53: server misbehaving"
t=2020-05-15T00:39:55+0000 lvl=info msg="Request Completed" logger=context userId=0 orgId=1 uname= method=GET path=/api/datasources/proxy/1/api/v1/query_range status=502 remote_addr="10.3.2.142, 10.10.10.45" time_ms=29989 size=0 referer="https://rancher.example.com/k8s/clusters/c-7x7qs/api/v1/namespaces/cattle-prometheus/services/http:access-grafana:80/proxy/d/FnxG5TYiz/nodes?orgId=1"
t=2020-05-15T00:39:55+0000 lvl=eror msg="Data proxy error" logger=data-proxy-log userId=0 orgId=1 uname= path=/api/datasources/proxy/1/api/v1/query_range remote_addr="10.3.2.142, 10.10.10.46" referer="https://rancher.example.com/k8s/clusters/c-7x7qs/api/v1/namespaces/cattle-prometheus/services/http:access-grafana:80/proxy/d/FnxG5TYiz/nodes?orgId=1" error="http: proxy error: dial tcp: lookup prometheus-operated on 169.254.25.10:53: server misbehaving"
t=2020-05-15T00:39:55+0000 lvl=info msg="Request Completed" logger=context userId=0 orgId=1 uname= method=GET path=/api/datasources/proxy/1/api/v1/query_range status=502 remote_addr="10.3.2.142, 10.10.10.46" time_ms=30019 size=0 referer="https://rancher.example.com/k8s/clusters/c-7x7qs/api/v1/namespaces/cattle-prometheus/services/http:access-grafana:80/proxy/d/FnxG5TYiz/nodes?orgId=1"
t=2020-05-15T00:39:55+0000 lvl=eror msg="Data proxy error" logger=data-proxy-log userId=0 orgId=1 uname= path=/api/datasources/proxy/1/api/v1/query_range remote_addr="10.3.2.142, 10.10.10.46" referer="https://rancher.example.com/k8s/clusters/c-7x7qs/api/v1/namespaces/cattle-prometheus/services/http:access-grafana:80/proxy/d/FnxG5TYiz/nodes?orgId=1" error="http: proxy error: dial tcp: lookup prometheus-operated on 169.254.25.10:53: server misbehaving"
t=2020-05-15T00:39:55+0000 lvl=info msg="Request Completed" logger=context userId=0 orgId=1 uname= method=GET path=/api/datasources/proxy/1/api/v1/query_range status=502 remote_addr="10.3.2.142, 10.10.10.46" time_ms=30024 size=0 referer="https://rancher.example.com/k8s/clusters/c-7x7qs/api/v1/namespaces/cattle-prometheus/services/http:access-grafana:80/proxy/d/FnxG5TYiz/nodes?orgId=1"
t=2020-05-15T00:39:55+0000 lvl=eror msg="Data proxy error" logger=data-proxy-log userId=0 orgId=1 uname= path=/api/datasources/proxy/1/api/v1/query_range remote_addr="10.3.2.142, 10.10.10.48" referer="https://rancher.example.com/k8s/clusters/c-7x7qs/api/v1/namespaces/cattle-prometheus/services/http:access-grafana:80/proxy/d/FnxG5TYiz/nodes?orgId=1" error="http: proxy error: dial tcp: lookup prometheus-operated on 169.254.25.10:53: server misbehaving"
t=2020-05-15T00:39:55+0000 lvl=info msg="Request Completed" logger=context userId=0 orgId=1 uname= method=GET path=/api/datasources/proxy/1/api/v1/query_range status=502 remote_addr="10.3.2.142, 10.10.10.48" time_ms=29995 size=0 referer="https://rancher.example.com/k8s/clusters/c-7x7qs/api/v1/namespaces/cattle-prometheus/services/http:access-grafana:80/proxy/d/FnxG5TYiz/nodes?orgId=1"
```

```
E0516 00:47:48.846057       1 reflector.go:123] github.com/coreos/prometheus-operator/pkg/thanos/operator.go:317: Failed to list *v1.ThanosRuler: thanosrulers.monitoring.coreos.com is forbidden: User "system:serviceaccount:cattle-prometheus:prometheus-operator-monitoring-operator" cannot list resource "thanosrulers" in API group "monitoring.coreos.com" at the cluster scope
E0516 00:47:49.848723       1 reflector.go:123] github.com/coreos/prometheus-operator/pkg/thanos/operator.go:317: Failed to list *v1.ThanosRuler: thanosrulers.monitoring.coreos.com is forbidden: User "system:serviceaccount:cattle-prometheus:prometheus-operator-monitoring-operator" cannot list resource "thanosrulers" in API group "monitoring.coreos.com" at the cluster scope
E0516 00:47:50.850941       1 reflector.go:123] github.com/coreos/prometheus-operator/pkg/thanos/operator.go:317: Failed to list *v1.ThanosRuler: thanosrulers.monitoring.coreos.com is forbidden: User "system:serviceaccount:cattle-prometheus:prometheus-operator-monitoring-operator" cannot list resource "thanosrulers" in API group "monitoring.coreos.com" at the cluster scope
E0516 00:47:51.852663       1 reflector.go:123] github.com/coreos/prometheus-operator/pkg/thanos/operator.go:317: Failed to list *v1.ThanosRuler: thanosrulers.monitoring.coreos.com is forbidden: User "system:serviceaccount:cattle-prometheus:prometheus-operator-monitoring-operator" cannot list resource "thanosrulers" in API group "monitoring.coreos.com" at the cluster scope
E0516 00:47:52.854267       1 reflector.go:123] github.com/coreos/prometheus-operator/pkg/thanos/operator.go:317: Failed to list *v1.ThanosRuler: thanosrulers.monitoring.coreos.com is forbidden: User "system:serviceaccount:cattle-prometheus:prometheus-operator-monitoring-operator" cannot list resource "thanosrulers" in API group "monitoring.coreos.com" at the cluster scope
E0516 00:47:53.856547       1 reflector.go:123] github.com/coreos/prometheus-operator/pkg/thanos/operator.go:317: Failed to list *v1.ThanosRuler: thanosrulers.monitoring.coreos.com is forbidden: User "system:serviceaccount:cattle-prometheus:prometheus-operator-monitoring-operator" cannot list resource "thanosrulers" in API group "monitoring.coreos.com" at the cluster scope
E0516 00:47:54.859273       1 reflector.go:123] github.com/coreos/prometheus-operator/pkg/thanos/operator.go:317: Failed to list *v1.ThanosRuler: thanosrulers.monitoring.coreos.com is forbidden: User "system:serviceaccount:cattle-prometheus:prometheus-operator-monitoring-operator" cannot list resource "thanosrulers" in API group "monitoring.coreos.com" at the cluster scope
E0516 00:47:55.861195       1 reflector.go:123] github.com/coreos/prometheus-operator/pkg/thanos/operator.go:317: Failed to list *v1.ThanosRuler: thanosrulers.monitoring.coreos.com is forbidden: User "system:serviceaccount:cattle-prometheus:prometheus-operator-monitoring-operator" cannot list resource "thanosrulers" in API group "monitoring.coreos.com" at the cluster scope
E0516 00:47:56.862845       1 reflector.go:123] github.com/coreos/prometheus-operator/pkg/thanos/operator.go:317: Failed to list *v1.ThanosRuler: thanosrulers.monitoring.coreos.com is forbidden: User "system:serviceaccount:cattle-prometheus:prometheus-operator-monitoring-operator" cannot list resource "thanosrulers" in API group "monitoring.coreos.com" at the cluster scope
E0516 00:47:57.864513       1 reflector.go:123] github.com/coreos/prometheus-operator/pkg/thanos/operator.go:317: Failed to list *v1.ThanosRuler: thanosrulers.monitoring.coreos.com is forbidden: User "system:serviceaccount:cattle-prometheus:prometheus-operator-monitoring-operator" cannot list resource "thanosrulers" in API group "monitoring.coreos.com" at the cluster scope
E0516 00:47:58.866617       1 reflector.go:123] github.com/coreos/prometheus-operator/pkg/thanos/operator.go:317: Failed to list *v1.ThanosRuler: thanosrulers.monitoring.coreos.com is forbidden: User "system:serviceaccount:cattle-prometheus:prometheus-operator-monitoring-operator" cannot list resource "thanosrulers" in API group "monitoring.coreos.com" at the cluster scope
E0516 00:47:59.868745       1 reflector.go:123] github.com/coreos/prometheus-operator/pkg/thanos/operator.go:317: Failed to list *v1.ThanosRuler: thanosrulers.monitoring.coreos.com is forbidden: User "system:serviceaccount:cattle-prometheus:prometheus-operator-monitoring-operator" cannot list resource "thanosrulers" in API group "monitoring.coreos.com" at the cluster scope
E0516 00:48:00.870673       1 reflector.go:123] github.com/coreos/prometheus-operator/pkg/thanos/operator.go:317: Failed to list *v1.ThanosRuler: thanosrulers.monitoring.coreos.com is forbidden: User "system:serviceaccount:cattle-prometheus:prometheus-operator-monitoring-operator" cannot list resource "thanosrulers" in API group "monitoring.coreos.com" at the cluster scope
E0516 00:48:01.872331       1 reflector.go:123] github.com/coreos/prometheus-operator/pkg/thanos/operator.go:317: Failed to list *v1.ThanosRuler: thanosrulers.monitoring.coreos.com is forbidden: User "system:serviceaccount:cattle-prometheus:prometheus-operator-monitoring-operator" cannot list resource "thanosrulers" in API group "monitoring.coreos.com" at the cluster scope
E0516 00:48:02.874240       1 reflector.go:123] github.com/coreos/prometheus-operator/pkg/thanos/operator.go:317: Failed to list *v1.ThanosRuler: thanosrulers.monitoring.coreos.com is forbidden: User "system:serviceaccount:cattle-prometheus:prometheus-operator-monitoring-operator" cannot list resource "thanosrulers" in API group "monitoring.coreos.com" at the cluster scope
E0516 00:48:03.876095       1 reflector.go:123] github.com/coreos/prometheus-operator/pkg/thanos/operator.go:317: Failed to list *v1.ThanosRuler: thanosrulers.monitoring.coreos.com is forbidden: User "system:serviceaccount:cattle-prometheus:prometheus-operator-monitoring-operator" cannot list resource "thanosrulers" in API group "monitoring.coreos.com" at the cluster scope
E0516 00:48:04.878153       1 reflector.go:123] github.com/coreos/prometheus-operator/pkg/thanos/operator.go:317: Failed to list *v1.ThanosRuler: thanosrulers.monitoring.coreos.com is forbidden: User "system:serviceaccount:cattle-prometheus:prometheus-operator-monitoring-operator" cannot list resource "thanosrulers" in API group "monitoring.coreos.com" at the cluster scope
E0516 00:48:05.879882       1 reflector.go:123] github.com/coreos/prometheus-operator/pkg/thanos/operator.go:317: Failed to list *v1.ThanosRuler: thanosrulers.monitoring.coreos.com is forbidden: User "system:serviceaccount:cattle-prometheus:prometheus-operator-monitoring-operator" cannot list resource "thanosrulers" in API group "monitoring.coreos.com" at the cluster scope
E0516 00:48:06.881479       1 reflector.go:123] github.com/coreos/prometheus-operator/pkg/thanos/operator.go:317: Failed to list *v1.ThanosRuler: thanosrulers.monitoring.coreos.com is forbidden: User "system:serviceaccount:cattle-prometheus:prometheus-operator-monitoring-operator" cannot list resource "thanosrulers" in API group "monitoring.coreos.com" at the cluster scope
E0516 00:48:07.883238       1 reflector.go:123] github.com/coreos/prometheus-operator/pkg/thanos/operator.go:317: Failed to list *v1.ThanosRuler: thanosrulers.monitoring.coreos.com is forbidden: User "system:serviceaccount:cattle-prometheus:prometheus-operator-monitoring-operator" cannot list resource "thanosrulers" in API group "monitoring.coreos.com" at the cluster scope
E0516 00:48:08.884901       1 reflector.go:123] github.com/coreos/prometheus-operator/pkg/thanos/operator.go:317: Failed to list *v1.ThanosRuler: thanosrulers.monitoring.coreos.com is forbidden: User "system:serviceaccount:cattle-prometheus:prometheus-operator-monitoring-operator" cannot list resource "thanosrulers" in API group "monitoring.coreos.com" at the cluster scope
E0516 00:48:09.886436       1 reflector.go:123] github.com/coreos/prometheus-operator/pkg/thanos/operator.go:317: Failed to list *v1.ThanosRuler: thanosrulers.monitoring.coreos.com is forbidden: User "system:serviceaccount:cattle-prometheus:prometheus-operator-monitoring-operator" cannot list resource "thanosrulers" in API group "monitoring.coreos.com" at the cluster scope
E0516 00:48:10.888306       1 reflector.go:123] github.com/coreos/prometheus-operator/pkg/thanos/operator.go:317: Failed to list *v1.ThanosRuler: thanosrulers.monitoring.coreos.com is forbidden: User "system:serviceaccount:cattle-prometheus:prometheus-operator-monitoring-operator" cannot list resource "thanosrulers" in API group "monitoring.coreos.com" at the cluster scope
E0516 00:48:11.892551       1 reflector.go:123] github.com/coreos/prometheus-operator/pkg/thanos/operator.go:317: Failed to list *v1.ThanosRuler: thanosrulers.monitoring.coreos.com is forbidden: User "system:serviceaccount:cattle-prometheus:prometheus-operator-monitoring-operator" cannot list resource "thanosrulers" in API group "monitoring.coreos.com" at the cluster scope
```

**Comment by StrongMonkey** [comment]
Oh I see, did you enable thanos @saikaushik-itsmyworld? Looks like there is a RBAC issue in the chart. I will investigate further. Thanks for reporting it!

**Comment by StrongMonkey** [comment]
@saikaushik-itsmyworld actually nevermind, we are missing the correct rbac rules for thanos and that's why you are seeing these logs. I have a pr to fix this https://github.com/rancher/system-charts/pull/229. Also looks like your cluster has a DNS issue.

**Comment by saikaushik-itsmyworld** [comment]
@StrongMonkey Thanks for the quick turn around on this.  when the PR gets merged, I'll redeploy the rancher monitoring component and will test it.
I'll look into the DNS issue, atleast I don't have any resolution errors with other services that I'm running on this cluster. I'll verify once again. Thank you!

**Comment by StrongMonkey** [comment]
@jiaqiluo Chart is officially merged into dev-v2.4. This should be ready to test on v2.4-head.

**Comment by jiaqiluo** [comment]
The fix for the specific bug in this issue is validated. 
Also, the Thanos-related logs are not seen anymore.  

The new chart `v0.1.1` is validated on rancher `v2.4-head` and `master-head` on different kinds of clusters and different scenarios during validating other monitoring related issues, and it works well as expected. 

All new issues will be logged as separate issues.

**Comment by Leen15** [comment]
@jiaqiluo I'm on rancher 2.4.4 but I cannot see the monitoring version 0.1.1.
Is there a way to force it?

**Comment by PhilipSchmid** [comment]
@Leen15 I've got the same problem.. Anyone knows a fix for this? Thanks.

**Comment by vitobotta** [comment]
Hi @StrongMonkey , how can I get 0.1.1? Only 0.1.0 is listed for me on 2.4.3. Thanks!

**Comment by vitobotta** [comment]
I am trying the dev-v2.4 branch but there is no sight of 0.1.1

**Comment by jiaqiluo** [comment]
Hi @vitobotta 

the new monitoring chart `0.1.1` is available for `rancher:v2.4.5`

**Comment by vitobotta** [comment]
Thanks @jiaqiluo I am trying to enable monitoring without a pv as workaround since I don't really need persistence I think. But I am hitting another issue now with monitoring because my cloud provider controller manager unsets the internal IPs of the nodes causing various issues with metrics etc...

**Comment by vitobotta** [comment]
Hi @StrongMonkey @jiaqiluo I am on 2.4.5 now and have enabled the monitoring in a new cluster. I have the ThanosRuler rbac issue. Hasn't the fixed chart been merged into 2.4.5? Thanks
