### ISSUE TITLE
[2.4.3] Failed to add Registry Credentials

### ISSUE THREAD

**Issue by kingsd041** [rancher/rancher#26981]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
1. Click Resources > Secrets > Registry Credentials.
2. Click Add Registry.
3. Scope select` Available to all namespaces in this project`
4. Configure the correct DockerHub or Custom Registry,  SAVE

**Result:**
Unable to save, always showing `saving`
![image](https://user-images.githubusercontent.com/19684717/81364341-022d7e80-9118-11ea-9660-d3d9444bef72.png)

**Other details that may be helpful:**
1. 2.4.2 will not reproduce the problem
2. Scope is set to `Available to a single namespace` will not reproduce

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 
v2.4.3
- Installation option (single install/HA):
single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Custom
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
- Kubernetes version (use `kubectl version`):

```
(paste the output here)
```

- Docker version (use `docker version`): 19.03.8
 
```
(paste the output here)
```

**Comment by huijitec** [comment]
I found a image pulling problem in Rancher 2.4.3, and it should cause image pull failed in workload pods initializing.

For example, the private registry is `docker.test.com` and the pod's image is `docker.test.com/project/app:v1`.

When creating pod containers, Rancher pulls image from `https://docker.test.com/v2/project/app:v1`, the image url is broken by add `/v2/` and pod get stacks on pulling fails.

Maybe this url error is the reason for ui stacking.

**Comment by ArgonV** [comment]
I see the same thing on my end, with a newly provisioned RancherOS cluster on vSphere running K8s v1.17.5 and Rancher Server v2.4.3. Mentioned this in the Rancher Slack channels as well.

My output in Firefox dev console is this:

```
TypeError: this.namespace is nullcomponent.js:79
    willSave component.js:79
    save new-or-edit.js:54
    _join backburner.js:1048
    join backburner.js:759
    Ember 4
    save component.js:55
    Ember 5
    _run backburner.js:1066
    _join backburner.js:1042
    join backburner.js:759
    Ember 3
    jQuery 2
```

**Comment by WeetA34** [comment]
Hi,
right now, the only way i found to create the registry credential is using the api:
`/v3/project/<clusterid>:<projectid>/dockerCredentials/`

**Comment by stefanlasiewski** [comment]
Does anyone have a workaround for this, other than the API strategy mentioned above? Can I restart anything to get this working again?

**Comment by theAkito** [comment]
@stefanlasiewski 

Try turning off anything that tries to access the credentials. Like, e.g., before you deploy anything, add the credentials. This worked for me 1 time. Don't know if this workaround works.

**Comment by Axelcouty** [comment]
As a workaround i created the creds with kubectl as described in kubernetes
documentation (
https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/#create-a-secret-by-providing-credentials-on-the-command-line
)

They'll show up in the Rancher Interface.

Hope that helps !

**Comment by sangeethah** [comment]
@stefanlasiewski https://github.com/rancher/rancher/issues/27117#issuecomment-629664499

**Comment by soumyalj** [comment]
Reproduced the issue in v2.4.3
1. Create a registry selecting "Available to all namespaces" and save
UI is stuck in Saving state and does not complete. 
![Screen Shot 2020-05-20 at 11 53 10 AM](https://user-images.githubusercontent.com/18536626/82485578-8379ff00-9a90-11ea-96e2-e725e4a2acf9.png)

Validated with master-head(8e20687a4)
1. Create a registry selecting "Available to all namespaces" and save. 
Registry gets created as expected. 

Creating registry in a single namespace also works.

**Comment by stefanlasiewski** [comment]
@theAkito We are actually getting this error before deploying the workloads that would depend on it.

We need our users to be able to deploy some important workloads, but they are not familiar with the kubectl CLI and therefore using the native kubectl workaround does not work. In those cases we need a working GUI.

Does anyone have a workaround to get the GUI portion working again before Rancher 2.4.4?

**Comment by theAkito** [comment]
My reproducible workaround:
1. Add Registry
2. "Available to a single namespace"
3. "Available to all namespaces in this project"
4. Add credentials
5. Save

For me it works, if I select "Available to a single namespace" in the very beginning, then switching back to "Available to all namespaces in this project" and proceeding as usual.

**Comment by Napsty** [comment]
@soumyalj you mentioned it is fixed in master 15 days ago. 
Which actual release will contain the fix? I see a milestone of 2.4.5 in this issue. Can this be confirmed by someone from Rancher Labs?

**Comment by fredleger** [comment]
@Napsty i can confirm it's still present on 2.4.4 if that helps

**Comment by ArgonV** [comment]
Hello, I just recently upgraded from Rancher v2.4.3 to v2.4.4 and it is working now. I can create a secret, and tell it to apply for all namespaces. I did perform an update on my cluster after upgrading Rancher, you may need to reconcile yours as well.


-Jason


________________________________

**Comment by stefanlasiewski** [comment]
> Which actual release will contain the fix? I see a milestone of 2.4.5 in this issue. Can this be confirmed by someone from Rancher Labs?

That may be the best official confirmation we can get at the moment. The Rancher devs are pretty busy.

The Github history doesn't show when the milestone was bumped from 2.4.4 to 2.4.5, which would have been helpful to know for our planning-- this caused a few headaches for us.

**Comment by Napsty** [comment]
The release notes of 2.4.5 mention this issue as fixed.
