### ISSUE TITLE
calico-node keeps restarting in K8s cluster with canal networking.

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#27300]
Steps to reproduce the problem:
Build from master - master-3049-head
Deploy a cluster with with canal networking any of the following K8s version : 
1.16.10-rancher2-1 
1.15.12-rancher2-2 
1.18.3-rancher2-1
1.17.6-rancher2-1

`rancher/calico-node:v3.13.4`  fails to start with following errors:

```
2020-05-28 06:13:22.858 [INFO][9] startup.go 309: Early log level set to info
2020-05-28 06:13:22.858 [INFO][9] startup.go 325: Using NODENAME environment for node name
2020-05-28 06:13:22.858 [INFO][9] startup.go 337: Determined node name: ip-172-31-12-10
2020-05-28 06:13:22.860 [INFO][9] startup.go 369: Checking datastore connection
2020-05-28 06:13:22.872 [INFO][9] startup.go 393: Datastore connection verified
2020-05-28 06:13:22.872 [INFO][9] startup.go 104: Datastore is ready
2020-05-28 06:13:22.876 [INFO][9] customresource.go 101: Error getting resource Key=GlobalFelixConfig(name=CalicoVersion) Name="calicoversion" Resource="GlobalFelixConfigs" error=the server could not find the requested resource (get GlobalFelixConfigs.crd.projectcalico.org calicoversion)
2020-05-28 06:13:22.881 [ERROR][9] startup.go 146: failed to query kubeadm's config map error=configmaps "kubeadm-config" is forbidden: User "system:serviceaccount:kube-system:canal" cannot get resource "configmaps" in API group "" in the namespace "kube-system"
2020-05-28 06:13:22.881 [WARNING][9] startup.go 1214: Terminating
Calico node failed to start
```

<img width="1266" alt="Screen Shot 2020-05-27 at 11 22 00 PM" src="https://user-images.githubusercontent.com/4266958/83106235-f840d080-a070-11ea-87cb-855cb196d65d.png">

**Comment by sangeethah** [comment]
This issue is still reproducible when testing with latest build from master - master-3063-head.

**Comment by rancher-max** [comment]
#### Validated in master-3065-head

- This isssue is now fixed and pods are not crashing. 
- Uses the correct calico versions of v3.13.4

**Comment by richyta** [comment]
Still seeing this issue with 2.4.4 when upgrading from 2.4.3. Below is what I am seeing when a new pod spins up for canal. 


2020-06-19 00:53:50.985 [INFO][9] startup.go 309: Early log level set to info
2020-06-19 00:53:50.985 [INFO][9] startup.go 325: Using NODENAME environment for node name
2020-06-19 00:53:50.985 [INFO][9] startup.go 337: Determined node name: master01
2020-06-19 00:53:50.987 [INFO][9] startup.go 369: Checking datastore connection
2020-06-19 00:53:51.028 [INFO][9] startup.go 393: Datastore connection verified
2020-06-19 00:53:51.028 [INFO][9] startup.go 104: Datastore is ready
2020-06-19 00:53:51.065 [ERROR][9] startup.go 146: failed to query kubeadm's config map error=configmaps "kubeadm-config" is forbidden: User "system:serviceaccount:kube-system:canal" cannot get resource "configmaps" in API group "" in the namespace "kube-system"
2020-06-19 00:53:51.066 [WARNING][9] startup.go 1214: Terminating
Calico node failed to start
