### ISSUE TITLE
 Template system-library-rancher-monitoring allowed rancher version not match current server 

### ISSUE THREAD

**Issue by harshsharma22** [rancher/rancher#27678]
* Template system-library-rancher-monitoring allowed rancher version not match current server *
unable to start  monitioring

---
| Useful | Info |
Versions|Rancher `v2.4.2` UI: `v2.4.14` 

gz#10896

**Comment by huangxinping** [comment]
Rancher v2.4.4

**Comment by harshsharma22** [comment]
@huangxinping  workaround regarding the same problem . 
use rancher api to enable monitoring .

**Comment by huangxinping** [comment]
@harshsharma22 thanks, I will try it directly.

**Comment by krishofmans** [comment]
We're having the same issue, a couple of clusters turned red, no specific action from our side, one of the clusters had monitoring enabled but it no longer seems to work now?

What's the root cause? Can we get it to green without enabling monitoring through the api?

**Comment by jiaqiluo** [comment]
Hi @harshsharma22  @huangxinping @kinarashah 

I cannot reproduce the bug in a fresh-installed v2.4.4 setup. We saw the same issue last week but it was fixed immediately: https://github.com/rancher/rancher/issues/27672#issuecomment-646888083

Could you try to refresh the `system-library` catalog manually to see if it will solve your problem? 
 

<img width="1409" alt="Screen Shot 2020-06-22 at 10 18 24 AM" src="https://user-images.githubusercontent.com/6218999/85316596-d836de00-b471-11ea-91e4-12841e918024.png">

**Comment by GertVil** [comment]
Refreshing the system-library manually did not resolve the issue. Cluster overview is still full of
> Template system-library-rancher-monitoring allowed rancher version not match current server

**Comment by kinarashah** [comment]
@GertVil Could you confirm if this version (v0.1.0) of monitoring template is available for the setup? This can be done by checking under `Rancher_Server_IP/v3/templates`. 

Restarting rancher server might also help if this doesn't get fixed even after a refresh.

**Comment by huangxinping** [comment]
@jiaqiluo No, refreshing it manually didn't resolve the issue.

**Environment information:**
Rancher version (rancher/rancher/rancher/server image tag or shown bottom left in the UI): v2.4.4
Installation option (single install/HA): HA

**Cluster information:**
Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Custom
Machine type (cloud/VM/metal) and specifications (CPU/memory): Metal
Kubernetes version (use kubectl version): v1.13.5
Docker version (use docker version): 17.3.2

**Other details:**
Upgrade rancher from v2.3.x to v2.4.4.
All of our clusters suddenly started showing this error on the Global view yesterday.

**Comment by kinarashah** [comment]
> @GertVil Could you confirm if this version (v0.1.0) of monitoring template is available for the setup? This can be done by checking under `Rancher_Server_IP/v3/templates`.
> Restarting rancher server might also help if this doesn't get fixed even after a refresh.
> 
> If the required version is available, then could you try editing this cluster?

@huangxinping please try ^

**Comment by AcidAngel21** [comment]
I have the same issue with Rancher 2.4.4.
@kinarashah monitoring template version v0.1.0 is available.
`"versionLinks": {
"0.1.0": "…/v3/templateVersions/cattle-global-data:system-library-rancher-cis-benchmark-0.1.0"
}`

**Comment by harshsharma22** [comment]
> Hi @harshsharma22 @huangxinping @kinarashah
> 
> I cannot reproduce the bug in a fresh-installed v2.4.4 setup. We saw the same issue last week but it was fixed immediately: [#27672 (comment)](https://github.com/rancher/rancher/issues/27672#issuecomment-646888083)
> 
> Could you try to refresh the `system-library` catalog manually to see if it will solve your problem?
> 
> <img alt="Screen Shot 2020-06-22 at 10 18 24 AM" width="1409" src="https://user-images.githubusercontent.com/6218999/85316596-d836de00-b471-11ea-91e4-12841e918024.png">

refreshing didn't work .

**Comment by GertVil** [comment]
@kinarashah After refresh, restart, refresh and period of waiting  This is the template in /v3/templates. So the versionLinks field is still empty.
```
{
"baseType": "template",
"catalogId": "system-library",
"clusterCatalogId": null,
"clusterId": null,
"created": "2019-04-17T10:01:44Z",
"createdTS": 1555495304000,
"creatorId": null,
"defaultTemplateVersionId": null,
"defaultVersion": "0.1.1",
"description": "Provides monitoring for Kubernetes which maintaining by Rancher 2.",
"folderName": "rancher-monitoring",
"id": "cattle-global-data:system-library-rancher-monitoring",
"labels": {
"catalog.cattle.io/name": "system-library"
},
"links": {
"catalog": "…/v3/catalogs/cattle",
"icon": "https://coreos.com/sites/default/files/inline-images/Overview-prometheus_0.png",
"remove": "…/v3/templates/cattle-global-data:system-library-rancher-monitoring",
"self": "…/v3/templates/cattle-global-data:system-library-rancher-monitoring",
"update": "…/v3/templates/cattle-global-data:system-library-rancher-monitoring"
},
"name": "rancher-monitoring",
"projectCatalogId": null,
"projectId": null,
"projectURL": "https://github.com/coreos/prometheus-operator",
"state": "active",
"status": {
"type": "/v3/schemas/templateStatus"
},
"transitioning": "no",
"transitioningMessage": "",
"type": "template",
"uuid": "cdf83103-60f7-11e9-932a-0242ac110002",
"versionLinks": { }
}
```

**Comment by kinarashah** [comment]
> I have the same issue with Rancher 2.4.4.
> @kinarashah monitoring template version v0.1.0 is available.
> `"versionLinks": { "0.1.0": "…/v3/templateVersions/cattle-global-data:system-library-rancher-cis-benchmark-0.1.0" }`

@AcidAngel21 This seems like the 0.10 for cis-benchmark, not monitoring. Could you look for monitoring please?

**Comment by kinarashah** [comment]
> @kinarashah After refresh, restart, refresh and period of waiting This is the template in /v3/templates. So the versionLinks field is still empty.
> 
> ```
> {
> "baseType": "template",
> "catalogId": "system-library",
> "clusterCatalogId": null,
> "clusterId": null,
> "created": "2019-04-17T10:01:44Z",
> "createdTS": 1555495304000,
> "creatorId": null,
> "defaultTemplateVersionId": null,
> "defaultVersion": "0.1.1",
> "description": "Provides monitoring for Kubernetes which maintaining by Rancher 2.",
> "folderName": "rancher-monitoring",
> "id": "cattle-global-data:system-library-rancher-monitoring",
> "labels": {
> "catalog.cattle.io/name": "system-library"
> },
> "links": {
> "catalog": "…/v3/catalogs/cattle",
> "icon": "https://coreos.com/sites/default/files/inline-images/Overview-prometheus_0.png",
> "remove": "…/v3/templates/cattle-global-data:system-library-rancher-monitoring",
> "self": "…/v3/templates/cattle-global-data:system-library-rancher-monitoring",
> "update": "…/v3/templates/cattle-global-data:system-library-rancher-monitoring"
> },
> "name": "rancher-monitoring",
> "projectCatalogId": null,
> "projectId": null,
> "projectURL": "https://github.com/coreos/prometheus-operator",
> "state": "active",
> "status": {
> "type": "/v3/schemas/templateStatus"
> },
> "transitioning": "no",
> "transitioningMessage": "",
> "type": "template",
> "uuid": "cdf83103-60f7-11e9-932a-0242ac110002",
> "versionLinks": { }
> }
> ```

@GertVil what version of rancher server? original issue mentions 2.4.2, same for you?

**Comment by krishofmans** [comment]
No, @GertVil is on 2.4.4.

We might attempt en update to 2.4.5 as the helm repo refresh seems completely stuck for now ...

**Comment by GertVil** [comment]
> > @kinarashah After refresh, restart, refresh and period of waiting This is the template in /v3/templates. So the versionLinks field is still empty.
> > ```
> > {
> > "baseType": "template",
> > "catalogId": "system-library",
> > "clusterCatalogId": null,
> > "clusterId": null,
> > "created": "2019-04-17T10:01:44Z",
> > "createdTS": 1555495304000,
> > "creatorId": null,
> > "defaultTemplateVersionId": null,
> > "defaultVersion": "0.1.1",
> > "description": "Provides monitoring for Kubernetes which maintaining by Rancher 2.",
> > "folderName": "rancher-monitoring",
> > "id": "cattle-global-data:system-library-rancher-monitoring",
> > "labels": {
> > "catalog.cattle.io/name": "system-library"
> > },
> > "links": {
> > "catalog": "…/v3/catalogs/cattle",
> > "icon": "https://coreos.com/sites/default/files/inline-images/Overview-prometheus_0.png",
> > "remove": "…/v3/templates/cattle-global-data:system-library-rancher-monitoring",
> > "self": "…/v3/templates/cattle-global-data:system-library-rancher-monitoring",
> > "update": "…/v3/templates/cattle-global-data:system-library-rancher-monitoring"
> > },
> > "name": "rancher-monitoring",
> > "projectCatalogId": null,
> > "projectId": null,
> > "projectURL": "https://github.com/coreos/prometheus-operator",
> > "state": "active",
> > "status": {
> > "type": "/v3/schemas/templateStatus"
> > },
> > "transitioning": "no",
> > "transitioningMessage": "",
> > "type": "template",
> > "uuid": "cdf83103-60f7-11e9-932a-0242ac110002",
> > "versionLinks": { }
> > }
> > ```
> 
> @GertVil could you try deleting this template and see if versions show up? Also, what version of rancher server? original issue mentions 2.4.2, same for you?

As @krishofmans already stated these are our versions on a single install of rancher with custom clusters running Kubernetes 1.15.11 and 1.15.12:

Rancher | v2.4.4
User Interface | v2.4.22
Helm | v2.16.5-rancher1
Machine | v0.15.0-rancher36

**Comment by jiaqiluo** [comment]
Currently, the monitoring chart `0.1.1` is available in `rancher:v2.4.5`, 
and we are planning to backport the chart to all v2.4.x release: https://github.com/rancher/rancher/issues/27703

**Comment by kinarashah** [comment]
Was able to resolve this issue on @GertVil's setup using following steps, 

1) First check `Rancher_Server_IP/v3/templates` and check `versionLinks` for `rancher-monitoring` 
2) If the correct version (v0.1.0) is 
a) present for rancher 2.4.0-2.4.4, edit the cluster to see if it recovers. Please post the error msg if the cluster doesn't become active. 
b) is not present under `versionLinks` proceed to step 3. 

3) Delete the `rancher-monitoring` entry under `Rancher_Server_IP/v3/templates`. Go to `v3/templates/cattle-global-data:system-library-rancher-monitoring` and delete. 
3) Go to Tools -> Catalogs, edit `system-library` catalog and change the branch to `dev-v2.4`. Edit `system-library` catalog and change the branch back to `release-v2.4`. This allows to force refresh and load the deleted template. 
4)  Go to step 1 to check for versionLinks and then step 2a.

**Comment by 631068264** [comment]
same problem in rancher2.6.5



Template system-library-rancher-monitoring incompatible with rancher version or cluster's [local] kubernetes version


/v3/templates/cattle-global-data:system-library-rancher-monitoring

```
{
"baseType": "template",
"catalogId": ["system-library"](https://10.19.64.205:3443/v3/catalogs/system-library),
"clusterCatalogId": null,
"clusterId": null,
"created": "2022-05-31T09:00:08Z",
"createdTS": 1653987608000,
"creatorId": null,
"defaultTemplateVersionId": null,
"defaultVersion": "0.3.2",
"description": "Provides monitoring for Kubernetes which is maintained by Rancher 2.",
"folderName": "rancher-monitoring",
"id": ["cattle-global-data:system-library-rancher-monitoring"](https://10.19.64.205:3443/v3/templates/cattle-global-data:system-library-rancher-monitoring),
"labels": {
"catalog.cattle.io/name": "system-library",
"cattle.io/creator": "norman"
},
"links": {
"catalog": ["…/v3/catalogs/cattle"](https://10.19.64.205:3443/v3/catalogs/cattle),
"icon": ["https://coreos.com/sites/default/files/inline-images/Overview-prometheus_0.png"](https://coreos.com/sites/default/files/inline-images/Overview-prometheus_0.png),
"remove": ["…/v3/templates/cattle-global-data:system-library-rancher-monitoring"](https://10.19.64.205:3443/v3/templates/cattle-global-data:system-library-rancher-monitoring),
"self": ["…/v3/templates/cattle-global-data:system-library-rancher-monitoring"](https://10.19.64.205:3443/v3/templates/cattle-global-data:system-library-rancher-monitoring),
"update": ["…/v3/templates/cattle-global-data:system-library-rancher-monitoring"](https://10.19.64.205:3443/v3/templates/cattle-global-data:system-library-rancher-monitoring)
},
"name": "rancher-monitoring",
"projectCatalogId": null,
"projectId": null,
"projectURL": ["https://github.com/coreos/prometheus-operator"](https://github.com/coreos/prometheus-operator),
"state": "active",
"status": {
"type": "/v3/schemas/templateStatus"
},
"transitioning": "no",
"transitioningMessage": "",
"type": ["template"](https://10.19.64.205:3443/v3/schemas/template),
"uuid": "67d6db5d-2e52-43f9-8261-8d4a48835777",
"versionLinks": {
"0.1.5": ["…/v3/templateVersions/cattle-global-data:system-library-rancher-monitoring-0.1.5"](https://10.19.64.205:3443/v3/templateVersions/cattle-global-data:system-library-rancher-monitoring-0.1.5),
"0.3.2": ["…/v3/templateVersions/cattle-global-data:system-library-rancher-monitoring-0.3.2"](https://10.19.64.205:3443/v3/templateVersions/cattle-global-data:system-library-rancher-monitoring-0.3.2)
}
}
```

> Was able to resolve this issue on @GertVil's setup using following steps,
> 
> 1. First check `Rancher_Server_IP/v3/templates` and check `versionLinks` for `rancher-monitoring`
> 2. If the correct version (v0.1.0) is
>    a) present for rancher 2.4.0-2.4.4, edit the cluster to see if it recovers. Please post the error msg if the cluster doesn't become active.
>    b) is not present under `versionLinks` proceed to step 3.
> 3. Delete the `rancher-monitoring` entry under `Rancher_Server_IP/v3/templates`. Go to `v3/templates/cattle-global-data:system-library-rancher-monitoring` and delete.
> 4. Go to Tools -> Catalogs, edit `system-library` catalog and change the branch to `dev-v2.4`. Edit `system-library` catalog and change the branch back to `release-v2.4`. This allows to force refresh and load the deleted template.
> 5. Go to step 1 to check for versionLinks and then step 2a.

I  delete   v3/templates/cattle-global-data:system-library-rancher-monitoring  and  `system-library` catalog is not allow to edit 
```
{
"baseType": "error",
"code": "InvalidBodyContent",
"message": "not allowed to edit system-library catalog",
"status": 422,
"type": "error"
}
```
