### ISSUE TITLE
system-charts release-v2.4 branch breaks cluster monitoring

### ISSUE THREAD

**Issue by daanemanz** [rancher/rancher#27672]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
Have Rancher v2.4.3 installed
Try to install cluster monitoring
No installable candidates

-or-

Have Rancher v2.4.3 installed with cluster-monitoring v0.1.0
System-library catalog is tracking release-v2.4 branch
Cluster monitoring stops working

**Result:**
No installable candidates for cluster-monitoring
Clusters show message "Template system-library-rancher-monitoring allowed rancher version not match current server"

**Other details that may be helpful:**
2 days ago this commit was merged into the release-v2.4 branch:
https://github.com/rancher/system-charts/commit/d623a935af05fec5b6b868afc2ecce996bb5ebd8

This disallows cluster-monitoring v0.1.0 for anything > v2.3.7
Cluster-monitoring v0.1.1 has _minimum_ version v2.4.5-rc0

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.4.3
- Installation option (single install/HA): HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Custom
- Machine type (cloud/VM/metal) and specifications (CPU/memory): Metal
- Kubernetes version (use `kubectl version`): v1.17.4

- Docker version (use `docker version`):
19

**Comment by armsnyder** [comment]
I think I've run into this same issue. All of our clusters suddenly started showing this error on the Global view today.

```
Template system-library-rancher-monitoring allowed rancher version not match current server
```

We are running Rancher v2.4.3 and cluster-monitoring v0.1.0, which shows as "up to date".

**Comment by daanemanz** [comment]
See https://github.com/rancher/system-charts/pull/259

**Comment by nikkelma** [comment]
Looks like this was a disconnect between a review and a commit: https://github.com/rancher/system-charts/pull/247#discussion_r441522494 - trying to get it resolved ASAP.

**Comment by daanemanz** [comment]
@nikkelma do you have an ETA for the fix? We're currently flying blind on pretty much all our clusters.

**Comment by jiaqiluo** [comment]
@daanemanz Our engineer is working on this now. A fix will be provided very soon.

**Comment by daanemanz** [comment]
@jiaqiluo Thanks for the update. I see that the fix has been merged into the `dev-v2.4` branch - will it also be merged into `release-v2.4`?

**Comment by armsnyder** [comment]
It looks like a fix was merged. https://github.com/rancher/system-charts/pull/260 Is there any explicit action we can do now in order to fix the warning in Rancher?

**Comment by nikkelma** [comment]
@daanemanz The process will need to be followed for a formal release, I expect it to happen ASAP because of the noise this has caused.

**Comment by nikkelma** [comment]
@armsnyder It will resolve itself on next catalog refresh when the change is fully merged - either automatically in the background or by performing a manual refresh of the `system-library` catalog.

**Comment by daanemanz** [comment]
@nikkelma all looks resolved now; thank you for the quick action :+1:

**Comment by sowmyav27** [comment]
Verified on 2.4.4 - system-charts branch `release-v2.4`

Monitoring version `0.1.0` is now available. 
User is able to enable on a cluster

**Comment by kz12123** [comment]
Have refreshed the system library, template is still showing empty/blank under monitoring.

**Comment by junkiebev** [comment]
the fact that `admin`/`admin` works on logoff/login is the the thing which made me leap on this like a cat with a tail on fire - I feared some sort of Bad Thing had occurred...

**Comment by catherineluse** [comment]
I've documented the default username and password here https://github.com/rancher/docs/commit/961e0f77aeb34cfe7cdb991ff9c4925663cfad1e

**Comment by junkiebev** [comment]
> I've documented the default username and password here [rancher/docs@961e0f7](https://github.com/rancher/docs/commit/961e0f77aeb34cfe7cdb991ff9c4925663cfad1e)

I meant `grafana` has admin/admin. If you click `Log Out`, you will be presented with a login page where `admin/admin` works.

**Comment by nikkelma** [comment]
Ah, we'd need to add that this is Not a Concern because Grafana dashboards are served via Rancher proxy - only users currently authenticated into the Rancher server have access to these proxied services. Thanks for the feedback!

**Comment by catherineluse** [comment]
Thanks for the clarification. I've reverted https://github.com/rancher/docs/commit/961e0f77aeb34cfe7cdb991ff9c4925663cfad1e and will add the correct note.

**Comment by catherineluse** [comment]
I've documented the default username and password for Grafana here https://github.com/rancher/docs/commit/876c74b3ea475ab090c791a664af6311c497f1fe
