### ISSUE TITLE
Installing Apps (charts) from Dashboard in Rancher docker installation stuck  In-Progress status

### ISSUE THREAD

**Issue by izaac** [rancher/rancher#28502]
**What kind of request is this:**
Bug

**Steps to reproduce:**

- Use Rancher single install (8a14c935a)
- Deploy an RKE cluster (DO, Linode..)
- Navigate to Dashboard -> Apps -> Charts
- Deploy `rancher-gatekeeper` or any other chart.

**Result:**

`Operation generation is 1, but latest observed generation is 0`
No other Logs shown in Dashboard Recent Operations.

![Screen Shot 2020-08-21 at 6 52 43 AM](https://user-images.githubusercontent.com/27659/90898249-34878280-e37b-11ea-9906-3b4ecdf3d851.png)

**This works on HA setups.**

**Environment information**
- Rancher version: `master-version (08/21/2020)` _8a14c935a_
- Installation option: single with Rancher generated certs.

**Comment by cbron** [comment]
This is known issue, fixed by: https://github.com/rancher/rancher/issues/28279

**Comment by izaac** [comment]
Closing in favor of: #28587

**Comment by MSandro** [comment]
same issue still in Rancher v2.6.2
![image](https://user-images.githubusercontent.com/10937159/140276221-221e5485-f16c-4dd6-8c68-d92796077098.png)

**Comment by mogoman** [comment]
@MSandro agree, I see the issue on 2.6.2 too. However I solved it by removing the repository and re-adding it. Perhaps try that as a workaround?

**Comment by cbron** [comment]
@MSandro the original issue dealt with helm charts being stuck in installation, your screenshot is referring to the repository object. Your error is a different one, related to multiple changes of the resource happening at same time.
