### ISSUE TITLE
[rancher-dns] Rancher DNS fails to resolve queries when reply from upstream server is truncated

### ISSUE THREAD

**Issue by janeczku** [rancher/rancher#2931]
### Steps to reproduce
1. Get a shell to a running container that is using the managed network (image needs to have `dig` utility installed)
2. `$ dig txt large.festplatte.eu.org @8.8.8.8`
3. `$ dig txt large.festplatte.eu.org @169.254.169.250`

### Expected result
Rancher DNS returns a reply containing the TXT record for large.festplatte.eu.org

### Actual result
Rancher DNS returns a reply without any records

```SHELL
/ # dig txt large.festplatte.eu.org @8.8.8.8

; <<>> DiG 9.10.2-P4 <<>> txt large.festplatte.eu.org @8.8.8.8
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 2689
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;large.festplatte.eu.org.	IN	TXT

;; ANSWER SECTION:
large.festplatte.eu.org. 119	IN	TXT	"MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDVcIwUlyUpCM8OoPzE/d318UL4x9gnE821iGf43oedUyDrX83YB13IfpiqgH524tVUMIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDVcIwUlyUpCM8OoPzE/d318UL4x9gnE821iGf43oedUyDrX83YB13IfpiqgH524tVUMIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDVcIwUlyU" "pCM8OoPzE/d318UL4x9gnE821iGf43oedUyDrX83YB13IfpiqgH524tVUMIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDVcIwUlyUpCM8OoPzE/d318UL4x9gnE821iGf43oedUyDrX83YB13IfpiqgH524tVUQEBAQUAA4GNADCBiQKBgQDVcIwUlyUpCM8OoPzE/d318UL4x9gnE821iGf43oedUyDrX83YB13IfpiqgH524tVU"

;; Query time: 146 msec
;; SERVER: 8.8.8.8#53(8.8.8.8)
;; WHEN: Sat Dec 05 19:51:33 UTC 2015
;; MSG SIZE  rcvd: 569
```

```SHELL
/ # dig txt large.festplatte.eu.org @169.254.169.250

;; Truncated, retrying in TCP mode.

; <<>> DiG 9.10.2-P4 <<>> txt large.festplatte.eu.org
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 742
;; flags: qr tc rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;large.festplatte.eu.org.	IN	TXT

;; Query time: 12 msec
;; SERVER: 169.254.169.250#53(169.254.169.250)
;; WHEN: Sat Dec 05 19:51:44 UTC 2015
;; MSG SIZE  rcvd: 41
```

**Comment by janeczku** [comment]
Rancher-DNS is compiled against a legacy commit of `github.com/miekg/dns` whose `client.Exchange()` method returns nil for truncated replies. See https://github.com/rancher/rancher-dns/blob/master/Godeps/Godeps.json and https://github.com/miekg/dns/blob/3e549e2f6fd420cdffa528144b925305401bf55c/client.go#L199

Accordingly the condition
https://github.com/rancher/rancher-dns/blob/master/resolve.go#L25
```Go
		if resp != nil && resp.Truncated {
			log.Debug("Response truncated, retrying with TCP")
```
will never be true and truncated queries won't fallback to TCP.

**Comment by bhchew** [comment]
No sure if it related..

Was sending a notification to slack via the container managed by rancher v0.47.0 and gotten the below error from the app.

Delivery: Post https://hooks.slack.com/services/XXXXXXXXXXXXXX: dial tcp: lookup hooks.slack.com on 169.254.169.250:53: no such host

But starting up the container manually, the post was successful...

**Comment by janeczku** [comment]
@bhchew looks more like you hit this issue: https://github.com/rancher/rancher/issues/2928
What nameservers do you have in /etc/resolv.conf on your Docker host?

**Comment by bhchew** [comment]
@janeczku Its having one internal and another external self hosted nameservers. Apologies as I can't disclose the IPs as part of company policies.

Tried changing 1st nameserver to 8.8.8.8 and restarted network agent and container. Now within container can't even resolve to google etc. Pardon me for my limited knowledge on networking. Might be some network settings in my company's DC....

**Comment by deniseschannon** [comment]
This should be fixed with what was fixed for https://github.com/rancher/rancher/issues/2928

**Comment by janeczku** [comment]
@deniseschannon This is not yet fixed. Basically https://github.com/rancher/rancher-dns/blob/master/Godeps/Godeps.json just needs to be updated to pin to the current head of https://github.com/miekg/dns/.
/cc @vincent99

**Comment by vincent99** [comment]
Is there a reason why you didn't put that in the PR if it was required @janeczku?

**Comment by janeczku** [comment]
Basically i wasn't sure if maybe miekg/DNS was intentionally pinned to that older commit for some reason and I didn't want to break anything :smile:

**Comment by janeczku** [comment]
Besides my PR clearly stated which issues it fixes and this here wasn't one of them.

**Comment by vincent99** [comment]
This should have been fixed a while ago, and the example record works.  @janeczku please reopen if you still have an issue.
