### ISSUE TITLE
ETCD high traffic, RAM + timeouts after migration to 2.5.2 

### ISSUE THREAD

**Issue by timmy59100** [rancher/rancher#30168]
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
Migrated Rancher docker install from 2.4.6 2.5.2.

**Result:**
ETCD generates a lot more traffic, needs more RAM and generates timeouts.

**Other details that may be helpful:**
This is an issue on both clusters on this manager.

In etcd log:

`etcdserver: read-only range request.... took too long (130.571166ms) to execute`

![image](https://user-images.githubusercontent.com/7300669/99820528-3109c000-2b51-11eb-841e-00016cf8b1ad.png)

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.5.2
- Installation option (single install/HA): single

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Custom
- Machine type (cloud/VM/metal) and specifications (CPU/memory): cloud, 3x etcd/controlplane nodes: 4 cores 8GB RAM, 5x  worker nodes 4cores 16GB RAM
- Kubernetes version (use `kubectl version`): 1.18.3

```
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-20T12:43:34Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker version (use `docker version`):

```
Client: Docker Engine - Community
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.12.17
 Git commit:        afacb8b
 Built:             Wed Mar 11 01:27:04 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.8
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.17
  Git commit:       afacb8b
  Built:            Wed Mar 11 01:25:42 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

gz#14921

**Comment by maggieliu** [comment]
@timmy59100 Do you have Project network isolation enabled?

**Comment by timmy59100** [comment]
@maggieliu no, project isolation is not enabled.

**Comment by adampl** [comment]
What is your Linux kernel version?

**Comment by timmy59100** [comment]
@adampl  kernel version: 3.10.0-1127.el7.x86_64
monitoring is enabled. 2.4 version

**Comment by adampl** [comment]
Then maybe your containers are being throttled? The new monitoring app has a CPU throttling chart and alerts that made me aware of this fact (but in general it's still buggy so I've returned to the old monitoring).

See this article: https://medium.com/omio-engineering/cpu-limits-and-aggressive-throttling-in-kubernetes-c5b20bd8a718

Also check: https://github.com/kubernetes/kubernetes/issues/67577

**Comment by timmy59100** [comment]
@adamcarlile a few containers have throttling values above 0. 
But I don't think that has anything to do with ETCD as it's not running on the cluster itself.

**Comment by adampl** [comment]
Sure, that was just my guess. Also the fact that it happened after upgrade indicates another cause.

Have you tried downgrading back to 2.4.6?

PS: you've mentioned some other Adam, not me ;)

**Comment by timmy59100** [comment]
After downgrade to 2.4.6 all metrics are normal again...

![image](https://user-images.githubusercontent.com/7300669/99962890-39e8d480-2d91-11eb-9a95-9981d3ada4cb.png)

**Comment by jzandbergen** [comment]
We are currently experiencing the exact same problem after upgrading rancher from 2.4.8 to 2.5.3.
It happens on both our rancher instances and both on k8s 1.18 as 1.19 clusters.

**Comment by mogoman** [comment]
Similar problem with 2.5.5 running in Docker. etcd using 10GB of RAM. We are also experiencing multiple crashes of the entire stack when browsing the UI - almost hourly at this point. I'm almost at the point of re-installing, but worried about data loss (rolled out helm charts for example). Also see quite a few error messages related to syncing, not sure if this is causing the etcd RAM use:

```
2021/01/15 10:49:58 [ERROR] error syncing 'website-test': handler resourceQuotaSyncController: projects.management.cattle.io "c-j2q7b/p-6fbxc" not found, handler resourceQuotaUsedLimitController: projects.management.cattle.io "c-j2q7b/p-6fbxc" not found, requeuing
```

(cluster c-j2q7b doesn't exist). I could try hard-deleting this cluster - is there a way to do this?

**Comment by fredleger** [comment]
Same here. Migrated one customer with a kops imported cluster from 2.4.6 to 2.5.5 and had to upgrade masters nodes flavors because high raise of memory consumption and hence load.

**Comment by fredleger** [comment]
@timmy59100 did you rollback using an etcd snapshot. For us trying to revert rancher version through helm 3 without restoring etcd snapshot does not change significaly the RAM used.

**Comment by mgruener** [comment]
After downgrading to an unaffected Rancher version or after upgrading to a version that fixes the problem, it helps to [defragment](https://rancher.com/docs/rancher/v2.x/en/troubleshooting/kubernetes-components/etcd/#defrag-all-etcd-members) (reduces db size) and restart (reduces the memory footprint back to normal) the etcd member.

At least for us that restored the etcd behavior to the way it was before encountering this issue.

**Comment by intonet** [comment]
Same here after upgrade from 2.4.11 to 2.5.5. Master node with less than 8GB RAM has OOM many times.  Increasing  ram to 12GB fix OOM problems. Also traffic on master node's VLAN grow up 
<img width="1226" alt="Screenshot 2021-02-12 at 12 06 36" src="https://user-images.githubusercontent.com/35962194/107760885-c4a2f500-6d2a-11eb-9445-41716f6978a5.png">

**Comment by mshade** [comment]
Also seeing this, going from 2.4.13 to 2.5.5. Lots more network traffic, cpu, and memory usage post-upgrade.

**Comment by mshade** [comment]
> the RAM suddenly dropped at the timeframe where we cleaned old helm2 releases with plugin helm-2to3 through helm 2to3 cleanup.

@fredleger  Thank you for this lead! We had a couple of lingering helm2 releases still present. We migrated rancher's release to helm3 prior to the 2.5 upgrade, but didn't bother with two other charts at the time (fluent-bit and datadog). Since converting and deleting the other old helm v2 releases, CPU, network, and disk I/O dropped quickly. Memory usage hasn't yet fallen, but I imagine it will if we reboot our nodes.

**Comment by dramich** [comment]
This issue has been fixed and is availed in v2.5.6-rc5

@mshade you would want to follow this to fix your memory consumption:

> After downgrading to an unaffected Rancher version or after upgrading to a version that fixes the problem, it helps to [defragment](https://rancher.com/docs/rancher/v2.x/en/troubleshooting/kubernetes-components/etcd/#defrag-all-etcd-members) (reduces db size) and restart (reduces the memory footprint back to normal) the etcd members. Just to be extra sure I also compacted the keyspace but I am not sure if this helps.
> 
> At least for us that restored the etcd behavior to the way it was before encountering this issue.

**Comment by izaac** [comment]
Reproduced the issue in `v2.5.5` with a Downstream RKE EC2 cluster monitored with CloudWatch.
A test k8s yaml was provided by Dev. 

Two scenarios tested on 2.5.5
- Downstream cluster upgraded from 2.4.13 
- 2.5.5 provisioned cluster

Both clusters shown the following stats during monitoring after a couple hours of applying the test yaml.

Higher memory usage spike can be observed on the etcd node.
Higher CPU utilization on the Control Plane.
Network Traffic increase on both Control Plane and etcd.


![Screen Shot 2021-02-24 at 7 18 35 AM](https://user-images.githubusercontent.com/27659/109015859-cd70c080-7672-11eb-93dc-0e3391cc6079.png)
![Screen Shot 2021-02-24 at 7 17 42 AM](https://user-images.githubusercontent.com/27659/109015890-d366a180-7672-11eb-826c-4940a01dbb6b.png)

**Comment by izaac** [comment]
Rancher version: `v2.5-head (02/24/2021)` _87006de_

Normal network activity is observed in this 2.5-head build and Memory/CPU usage isn't noticeably spiking as observed previously in 2.5.5.

![Screen Shot 2021-02-24 at 2 29 42 PM](https://user-images.githubusercontent.com/27659/109068528-3aa14780-76ad-11eb-8339-41029625d113.png)

**Comment by izaac** [comment]
Rancher version `master-head (02/25/2021)` _465bb3b_
Rancher version `v2.5-head (02/25/2021)` _87006de_


### Upgrade from 2.5.5 with the issue reproduced to 2.5-head build with fix

Network traffic chart goes back to 2.5.5 without the issue.
Memory usage of etcd stays high but it recover to normal levels after etcd defrag and node restart. (Second graphic)

![Screen Shot 2021-02-25 at 7 31 15 AM](https://user-images.githubusercontent.com/27659/109168671-4b4cce80-773c-11eb-8c39-519826c6f6f2.png)

![Screen Shot 2021-02-25 at 11 05 10 AM](https://user-images.githubusercontent.com/27659/109196768-5bbf7200-7759-11eb-9462-e270fec416eb.png)



### `master-head` with the test yaml

Metrics stayed on normal levels.

![Screen Shot 2021-02-25 at 7 39 18 AM](https://user-images.githubusercontent.com/27659/109168993-9961d200-773c-11eb-98ff-348d9eae3e2f.png)

**Comment by izaac** [comment]
After upgrade the etcd nodes will be still utilizing high memory but as commented here I did:

- `etcdctl defrag`
- `docker etcd restart` 

On each etcd node and the memory consumption was back to normal levels.

I checked this by validating this scenario 

- Install `v2.5.5`  with reproduced high network traffic and high memory consumption in it
- Upgrade to `v2.5-head (02/25/2021)`  _f9b93ea_
- Wait some time and observed the memory wasn't restored to normal levels.
- Proceed to troubleshoot each etcd container.

Example of a node before and after the container restart (etcd is above 50% before restart):

```
sudo docker stats --no-stream
CONTAINER ID        NAME                                                                                     CPU %               MEM USAGE / LIMIT     MEM %               NET I/O             BLOCK I/O           PIDS
792c486b2589        k8s_agent_cattle-node-agent-9dgd8_cattle-system_06fffe21-0ed0-4553-abc2-15d6d4b9ce13_0   0.00%               27.91MiB / 3.786GiB   0.72%               0B / 0B             18.8MB / 0B         8
453cffe64365        k8s_POD_cattle-node-agent-9dgd8_cattle-system_06fffe21-0ed0-4553-abc2-15d6d4b9ce13_0     0.00%               540KiB / 3.786GiB     0.01%               0B / 0B             631kB / 0B          1
98a0d53b9cda        etcd                                                                                     3.05%               1.904GiB / 3.786GiB   50.28%              0B / 0B             251MB / 27.6GB      12
272b3bdc6ef5        k8s_kube-flannel_canal-k8j5c_kube-system_78828e47-76b0-4c75-8e20-f3f37c442b03_0          0.00%               10.81MiB / 3.786GiB   0.28%               0B / 0B             63.9MB / 0B         9
5b112b7d985d        k8s_calico-node_canal-k8j5c_kube-system_78828e47-76b0-4c75-8e20-f3f37c442b03_0           2.71%               32.88MiB / 3.786GiB   0.85%               0B / 0B             154MB / 36.9kB      31
94f003677046        k8s_POD_canal-k8j5c_kube-system_78828e47-76b0-4c75-8e20-f3f37c442b03_0                   0.00%               452KiB / 3.786GiB     0.01%               0B / 0B             0B / 0B             1
ae3cc7a1bd94        kube-proxy                                                                               0.03%               14.18MiB / 3.786GiB   0.37%               0B / 0B             92.2MB / 12.3kB     6
f1025ffdb838        kubelet                                                                                  1.37%               49.99MiB / 3.786GiB   1.29%               0B / 0B             375MB / 77.8kB      15
25c5db61cdd3        nginx-proxy                                                                              0.02%               3.691MiB / 3.786GiB   0.10%               0B / 0B             274kB / 0B          4
ubuntu@izstats5-etcd-1:~$ sudo docker restart etcd
etcd
ubuntu@izstats5-etcd-1:~$ sudo docker stats --no-stream
CONTAINER ID        NAME                                                                                     CPU %               MEM USAGE / LIMIT     MEM %               NET I/O             BLOCK I/O           PIDS
792c486b2589        k8s_agent_cattle-node-agent-9dgd8_cattle-system_06fffe21-0ed0-4553-abc2-15d6d4b9ce13_0   0.00%               27.91MiB / 3.786GiB   0.72%               0B / 0B             18.8MB / 0B         8
453cffe64365        k8s_POD_cattle-node-agent-9dgd8_cattle-system_06fffe21-0ed0-4553-abc2-15d6d4b9ce13_0     0.00%               540KiB / 3.786GiB     0.01%               0B / 0B             631kB / 0B          1
98a0d53b9cda        etcd                                                                                     1.69%               79.45MiB / 3.786GiB   2.05%               0B / 0B             4.99MB / 492kB      22
272b3bdc6ef5        k8s_kube-flannel_canal-k8j5c_kube-system_78828e47-76b0-4c75-8e20-f3f37c442b03_0          0.64%               10.79MiB / 3.786GiB   0.28%               0B / 0B             63.9MB / 0B         9
5b112b7d985d        k8s_calico-node_canal-k8j5c_kube-system_78828e47-76b0-4c75-8e20-f3f37c442b03_0           1.10%               32.85MiB / 3.786GiB   0.85%               0B / 0B             154MB / 36.9kB      31
94f003677046        k8s_POD_canal-k8j5c_kube-system_78828e47-76b0-4c75-8e20-f3f37c442b03_0                   0.00%               452KiB / 3.786GiB     0.01%               0B / 0B             0B / 0B             1
ae3cc7a1bd94        kube-proxy                                                                               0.01%               14.18MiB / 3.786GiB   0.37%               0B / 0B             92.2MB / 12.3kB     6
f1025ffdb838        kubelet                                                                                  4.28%               50.16MiB / 3.786GiB   1.29%               0B / 0B             375MB / 77.8kB      15
25c5db61cdd3        nginx-proxy                                                                              0.00%               3.699MiB / 3.786GiB   0.10%               0B / 0B             274kB / 0B          4
```

Sample monitoring graph:

![Screen Shot 2021-02-26 at 7 37 31 AM](https://user-images.githubusercontent.com/27659/109314766-00e45400-7807-11eb-9609-cf839a69ebbf.png)

**Comment by adampl** [comment]
Wouldn't it be a good idea to automate this, so that Rancher does this defragmentation after upgrade?

**Comment by dramich** [comment]
@adampl That isn't really an option for multiple reasons:
1. Rancher is not in charge of etcd, the provisioner is. 
2. We don't know how to talk to etcd and in a lot of cases can't. A good example is a hosted cluster in AKS or GKE. 
3. That would be unexpected behavior of doing a rancher upgrade. We don't cause changes to etcd unless it's explicit i.e. you as a user change the k8s version of your cluster which would (possibly) update the version of etcd.

**Comment by adampl** [comment]
> 3\. We don't cause changes to etcd unless it's explicit i.e. you as a user change the k8s version of your cluster which would (possibly) update the version of etcd.

So this error concerns only the `etcd` component of the local cluster, the user's clusters or all clusters?
And cluster upgrade to newer k8s version should resolve this issue as well, right?
Or defragmentation would still be required?

**Comment by onnet-goey** [comment]
Is there any proper fix for this issue? 
We are still facing this even with rancher 2.5.8. 
It happen on one node after another, endless cycle.

**Comment by dramich** [comment]
@onnet-goey The original issue was fixed and this issue was closed. If you are experiencing issue please open a new issue with as much detail as possible
