### ISSUE TITLE
git-remote-http defunct processes from cluster-register_cattle-cluster-agent

### ISSUE THREAD

**Issue by dnoland1** [rancher/rancher#30172]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
1. Set up a downstream RKE cluster with controlplane/worker/etcd roles
2. May need to let environment run for a few hours or days (or longer)
3. Run `ps -aef| grep git-remote-http | grep defunct`

**Result:**
```
root@ip-10-0-10-10:~# ps -aef| grep git-remote-http | grep defunct
root      691961 1938477  0 Nov14 ?        00:00:00 [git-remote-http] <defunct>
root      693565 1938477  0 Nov14 ?        00:00:00 [git-remote-http] <defunct>
root      701971 1938477  0 Nov14 ?        00:00:00 [git-remote-http] <defunct>
root      713516 1938477  0 Nov14 ?        00:00:00 [git-remote-http] <defunct>
root      718538 1938477  0 Nov14 ?        00:00:00 [git-remote-http] <defunct>
root      726678 1938477  0 Nov14 ?        00:00:00 [git-remote-http] <defunct>
root      728547 1938477  0 Nov14 ?        00:00:00 [git-remote-http] <defunct>
root      741905 1938477  0 Nov14 ?        00:00:00 [git-remote-http] <defunct>
root      748518 1938477  0 Nov14 ?        00:00:00 [git-remote-http] <defunct>
root      753543 1938477  0 Nov14 ?        00:00:00 [git-remote-http] <defunct>
root      761990 1938477  0 Nov14 ?        00:00:00 [git-remote-http] <defunct>
root      763578 1938477  0 Nov14 ?        00:00:00 [git-remote-http] <defunct>
root      771680 1938477  0 Nov14 ?        00:00:00 [git-remote-http] <defunct>
root      773302 1938477  0 Nov14 ?        00:00:00 [git-remote-http] <defunct>
root      776697 1938477  0 Nov14 ?        00:00:00 [git-remote-http] <defunct>
root      778313 1938477  0 Nov14 ?        00:00:00 [git-remote-http] <defunct>
root      781703 1938477  0 Nov14 ?        00:00:00 [git-remote-http] <defunct>
root      783296 1938477  0 Nov14 ?        00:00:00 [git-remote-http] <defunct>
root      786716 1938477  0 Nov14 ?        00:00:00 [git-remote-http] <defunct>
root      788309 1938477  0 Nov14 ?        00:00:00 [git-remote-http] <defunct>
root      791693 1938477  0 Nov14 ?        00:00:00 [git-remote-http] <defunct>
root      793317 1938477  0 Nov14 ?        00:00:00 [git-remote-http] <defunct>
root      796715 1938477  0 Nov14 ?        00:00:00 [git-remote-http] <defunct>
root      798323 1938477  0 Nov14 ?        00:00:00 [git-remote-http] <defunct>
root      803329 1938477  0 Nov14 ?        00:00:00 [git-remote-http] <defunct>
root      806739 1938477  0 Nov14 ?        00:00:00 [git-remote-http] <defunct>
root      808318 1938477  0 Nov14 ?        00:00:00 [git-remote-http] <defunct>
root      811774 1938477  0 Nov14 ?        00:00:00 [git-remote-http] <defunct>
root      813381 1938477  0 Nov14 ?        00:00:00 [git-remote-http] <defunct>
root      816810 1938477  0 Nov14 ?        00:00:00 [git-remote-http] <defunct>
root      818416 1938477  0 Nov14 ?        00:00:00 [git-remote-http] <defunct>
root      821823 1938477  0 Nov14 ?        00:00:00 [git-remote-http] <defunct>
root      823412 1938477  0 Nov14 ?        00:00:00 [git-remote-http] <defunct>
root      826827 1938477  0 Nov14 ?        00:00:00 [git-remote-http] <defunct>
root      828462 1938477  0 Nov14 ?        00:00:00 [git-remote-http] <defunct>
root      831853 1938477  0 Nov14 ?        00:00:00 [git-remote-http] <defunct>
root      833453 1938477  0 Nov14 ?        00:00:00 [git-remote-http] <defunct>
root      836843 1938477  0 Nov14 ?        00:00:00 [git-remote-http] <defunct>
root      841848 1938477  0 Nov14 ?        00:00:00 [git-remote-http] <defunct>
root      843445 1938477  0 Nov14 ?        00:00:00 [git-remote-http] <defunct>
root      846840 1938477  0 Nov14 ?        00:00:00 [git-remote-http] <defunct>
root      848460 1938477  0 Nov14 ?        00:00:00 [git-remote-http] <defunct>
root      851870 1938477  0 Nov14 ?        00:00:00 [git-remote-http] <defunct>
root      853489 1938477  0 Nov14 ?        00:00:00 [git-remote-http] <defunct>
root      856889 1938477  0 Nov14 ?        00:00:00 [git-remote-http] <defunct>
root      858516 1938477  0 Nov14 ?        00:00:00 [git-remote-http] <defunct>
root      861918 1938477  0 Nov14 ?        00:00:00 [git-remote-http] <defunct>
root      863487 1938477  0 Nov14 ?        00:00:00 [git-remote-http] <defunct>
root      868464 1938477  0 Nov14 ?        00:00:00 [git-remote-http] <defunct>
root      871850 1938477  0 Nov14 ?        00:00:00 [git-remote-http] <defunct>
root      873468 1938477  0 Nov14 ?        00:00:00 [git-remote-http] <defunct>
root      876856 1938477  0 Nov14 ?        00:00:00 [git-remote-http] <defunct>
root      878464 1938477  0 Nov14 ?        00:00:00 [git-remote-http] <defunct>
root      881852 1938477  0 Nov14 ?        00:00:00 [git-remote-http] <defunct>
root      883454 1938477  0 Nov14 ?        00:00:00 [git-remote-http] <defunct>
root      886899 1938477  0 Nov14 ?        00:00:00 [git-remote-http] <defunct>
root      888499 1938477  0 Nov14 ?        00:00:00 [git-remote-http] <defunct>
root      891887 1938477  0 Nov14 ?        00:00:00 [git-remote-http] <defunct>
root      893512 1938477  0 Nov14 ?        00:00:00 [git-remote-http] <defunct>
root      896904 1938477  0 Nov14 ?        00:00:00 [git-remote-http] <defunct>
root      898522 1938477  0 Nov14 ?        00:00:00 [git-remote-http] <defunct>
root      901929 1938477  0 Nov14 ?        00:00:00 [git-remote-http] <defunct>
root      903529 1938477  0 Nov14 ?        00:00:00 [git-remote-http] <defunct>
root      906939 1938477  0 Nov14 ?        00:00:00 [git-remote-http] <defunct>
root      911918 1938477  0 Nov14 ?        00:00:00 [git-remote-http] <defunct>
root      913517 1938477  0 Nov14 ?        00:00:00 [git-remote-http] <defunct>
root      916906 1938477  0 Nov14 ?        00:00:00 [git-remote-http] <defunct>
root      918523 1938477  0 Nov14 ?        00:00:00 [git-remote-http] <defunct>
root      921911 1938477  0 Nov14 ?        00:00:00 [git-remote-http] <defunct>
root      923521 1938477  0 Nov14 ?        00:00:00 [git-remote-http] <defunct>
root      926916 1938477  0 Nov14 ?        00:00:00 [git-remote-http] <defunct>
root      928517 1938477  0 Nov14 ?        00:00:00 [git-remote-http] <defunct>
root      931954 1938477  0 Nov14 ?        00:00:00 [git-remote-http] <defunct>
root      933534 1938477  0 Nov14 ?        00:00:00 [git-remote-http] <defunct>
root      936926 1938477  0 Nov14 ?        00:00:00 [git-remote-http] <defunct>
root      938508 1938477  0 Nov14 ?        00:00:00 [git-remote-http] <defunct>
root      941916 1938477  0 Nov14 ?        00:00:00 [git-remote-http] <defunct>
root      943524 1938477  0 Nov14 ?        00:00:00 [git-remote-http] <defunct>
root      946962 1938477  0 Nov14 ?        00:00:00 [git-remote-http] <defunct>
root      948577 1938477  0 Nov14 ?        00:00:00 [git-remote-http] <defunct>
root      952012 1938477  0 Nov14 ?        00:00:00 [git-remote-http] <defunct>
root      953619 1938477  0 Nov14 ?        00:00:00 [git-remote-http] <defunct>
root      957011 1938477  0 Nov14 ?        00:00:00 [git-remote-http] <defunct>
root      958599 1938477  0 Nov14 ?        00:00:00 [git-remote-http] <defunct>
root      962008 1938477  0 Nov14 ?        00:00:00 [git-remote-http] <defunct>
root      963620 1938477  0 Nov14 ?        00:00:00 [git-remote-http] <defunct>
root      967017 1938477  0 Nov14 ?        00:00:00 [git-remote-http] <defunct>
root      968633 1938477  0 Nov14 ?        00:00:00 [git-remote-http] <defunct>
root      972058 1938477  0 Nov14 ?        00:00:00 [git-remote-http] <defunct>
root      973662 1938477  0 Nov14 ?        00:00:00 [git-remote-http] <defunct>
root      977044 1938477  0 Nov14 ?        00:00:00 [git-remote-http] <defunct>
root      978652 1938477  0 Nov14 ?        00:00:00 [git-remote-http] <defunct>
root      982017 1938477  0 Nov14 ?        00:00:00 [git-remote-http] <defunct>
root      983625 1938477  0 Nov14 ?        00:00:00 [git-remote-http] <defunct>
root      987038 1938477  0 Nov14 ?        00:00:00 [git-remote-http] <defunct>
root      988639 1938477  0 Nov14 ?        00:00:00 [git-remote-http] <defunct>
root      992029 1938477  0 Nov14 ?        00:00:00 [git-remote-http] <defunct>
root      993636 1938477  0 Nov14 ?        00:00:00 [git-remote-http] <defunct>
root      997049 1938477  0 Nov14 ?        00:00:00 [git-remote-http] <defunct>
root      998635 1938477  0 Nov14 ?        00:00:00 [git-remote-http] <defunct>
root     1002027 1938477  0 Nov14 ?        00:00:00 [git-remote-http] <defunct>
root     1003623 1938477  0 Nov14 ?        00:00:00 [git-remote-http] <defunct>
root     1007068 1938477  0 Nov14 ?        00:00:00 [git-remote-http] <defunct>
root     1008661 1938477  0 Nov14 ?        00:00:00 [git-remote-http] <defunct>
root     1013683 1938477  0 Nov14 ?        00:00:00 [git-remote-http] <defunct>
root     1047331 1938477  0 Nov14 ?        00:00:00 [git-remote-http] <defunct>
root     1063943 1938477  0 Nov14 ?        00:00:00 [git-remote-http] <defunct>
root     1072376 1938477  0 Nov14 ?        00:00:00 [git-remote-http] <defunct>
root     1114015 1938477  0 Nov14 ?        00:00:00 [git-remote-http] <defunct>
root     1164008 1938477  0 Nov14 ?        00:00:00 [git-remote-http] <defunct>
root     1192443 1938477  0 Nov14 ?        00:00:00 [git-remote-http] <defunct>
root     1207442 1938477  0 Nov14 ?        00:00:00 [git-remote-http] <defunct>
root     1212456 1938477  0 Nov14 ?        00:00:00 [git-remote-http] <defunct>
root     1939739 1938477  0 Oct22 ?        00:00:00 [git-remote-http] <defunct>
root     1940142 1938477  0 Oct22 ?        00:00:00 [git-remote-http] <defunct>
root     1940285 1938477  0 Oct22 ?        00:00:00 [git-remote-http] <defunct>
root     1940319 1938477  0 Oct22 ?        00:00:00 [git-remote-http] <defunct>
root     1940684 1938477  0 Oct22 ?        00:00:00 [git-remote-http] <defunct>
root     1940750 1938477  0 Oct22 ?        00:00:00 [git-remote-http] <defunct>
root     1940763 1938477  0 Oct22 ?        00:00:00 [git-remote-http] <defunct>
root     1940793 1938477  0 Oct22 ?        00:00:00 [git-remote-http] <defunct>
root     1940822 1938477  0 Oct22 ?        00:00:00 [git-remote-http] <defunct>
root     1940828 1938477  0 Oct22 ?        00:00:00 [git-remote-http] <defunct>
root     1940914 1938477  0 Oct22 ?        00:00:00 [git-remote-http] <defunct>
root     1941101 1938477  0 Oct22 ?        00:00:00 [git-remote-http] <defunct>
root     1941272 1938477  0 Oct22 ?        00:00:00 [git-remote-http] <defunct>
root     1941642 1938477  0 Oct22 ?        00:00:00 [git-remote-http] <defunct>
root     2019753 1938477  0 Nov15 ?        00:00:00 [git-remote-http] <defunct>
root     2023155 1938477  0 Nov15 ?        00:00:00 [git-remote-http] <defunct>
root     2024758 1938477  0 Nov15 ?        00:00:00 [git-remote-http] <defunct>
root     2029990 1938477  0 Nov15 ?        00:00:00 [git-remote-http] <defunct>
root     2033161 1938477  0 Nov15 ?        00:00:00 [git-remote-http] <defunct>
root     2034739 1938477  0 Nov15 ?        00:00:00 [git-remote-http] <defunct>
root     2039756 1938477  0 Nov15 ?        00:00:00 [git-remote-http] <defunct>
root     2043166 1938477  0 Nov15 ?        00:00:00 [git-remote-http] <defunct>
root     2044772 1938477  0 Nov15 ?        00:00:00 [git-remote-http] <defunct>
root     2048280 1938477  0 Nov15 ?        00:00:00 [git-remote-http] <defunct>
root     2049884 1938477  0 Nov15 ?        00:00:00 [git-remote-http] <defunct>
root     2053285 1938477  0 Nov15 ?        00:00:00 [git-remote-http] <defunct>
root     2054868 1938477  0 Nov15 ?        00:00:00 [git-remote-http] <defunct>
root     2058284 1938477  0 Nov15 ?        00:00:00 [git-remote-http] <defunct>
root     2059877 1938477  0 Nov15 ?        00:00:00 [git-remote-http] <defunct>
root     2063267 1938477  0 Nov15 ?        00:00:00 [git-remote-http] <defunct>
root     2064879 1938477  0 Nov15 ?        00:00:00 [git-remote-http] <defunct>
root     2068271 1938477  0 Nov15 ?        00:00:00 [git-remote-http] <defunct>
root     2069877 1938477  0 Nov15 ?        00:00:00 [git-remote-http] <defunct>
root     2073259 1938477  0 Nov15 ?        00:00:00 [git-remote-http] <defunct>
root     2074850 1938477  0 Nov15 ?        00:00:00 [git-remote-http] <defunct>
root     2078256 1938477  0 Nov15 ?        00:00:00 [git-remote-http] <defunct>
root     2079849 1938477  0 Nov15 ?        00:00:00 [git-remote-http] <defunct>
root     2083236 1938477  0 Nov15 ?        00:00:00 [git-remote-http] <defunct>
root     2084824 1938477  0 Nov15 ?        00:00:00 [git-remote-http] <defunct>
root     2088252 1938477  0 Nov15 ?        00:00:00 [git-remote-http] <defunct>
```

**Other details that may be helpful:**
This PID matches this container:
```
# docker inspect 079 | grep -i "pid\|Name"
            "Pid": 1938477,
        "HostnamePath": "/var/lib/docker/containers/2b3fab56a2bd8d4b3be4a26d0eec54ab8f589e8cd4ab7fce7e031ea7a3fa09f2/hostname",
        "Name": "/k8s_cluster-register_cattle-cluster-agent-5c97dd84f-h9ctr_cattle-system_c1b8ec65-40c3-4195-aa11-63d7e341c38d_0",
                "Name": "no",
            "PidMode": "",
            "PidsLimit": null,
            "Name": "overlay2"
            "Hostname": "cattle-cluster-agent-5c97dd84f-h9ctr",
            "Domainname": "",
                "io.kubernetes.container.name": "cluster-register",
                "io.kubernetes.pod.name": "cattle-cluster-agent-5c97dd84f-h9ctr",
                "io.kubernetes.pod.namespace": "cattle-system",
```
Looks like there was a similar problem in v2.0 with another rancher workload - https://github.com/rancher/rancher/issues/13858
**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
v2.5.2
- Installation option (single install/HA):
HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):
Custom
- Machine type (cloud/VM/metal) and specifications (CPU/memory):
t3a.medium on AWS EC2 - 2vCPU, 8GB RAM
- Kubernetes version (use `kubectl version`):

```
> kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T11:56:40Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.2", GitCommit:"f5743093fd1c663cb0cbc89748f730662345d44d", GitTreeState:"clean", BuildDate:"2020-09-16T13:32:58Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
```

- Docker version (use `docker version`):

```
root@ip-10-0-10-10:~# docker version
Client:
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.13.8
 Git commit:        afacb8b7f0
 Built:             Wed Oct 14 19:43:43 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          19.03.8
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.8
  Git commit:       afacb8b7f0
  Built:            Wed Oct 14 16:41:21 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.3.3-0ubuntu2
  GitCommit:
 runc:
  Version:          spec: 1.0.1-dev
  GitCommit:
 docker-init:
  Version:          0.18.0
  GitCommit:
```
gz#13535

gz#16312

**Comment by skbki** [comment]
I am too experiencing this issue on selfhosted centos 8 with docker 19.03.12

**Comment by uluzox** [comment]
I am also experiencing this issue on self-hosted air-gapped installation on ubuntu with two master and one worker node.

```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3+k3s2", GitCommit:"f8a4547bec36b4d1597c19c86b5063756d4c150e", GitTreeState:"clean", BuildDate:"2020-10-30T19:30:45Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3+k3s2", GitCommit:"f8a4547bec36b4d1597c19c86b5063756d4c150e", GitTreeState:"clean", BuildDate:"2020-10-30T19:30:45Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
```

```
Client: Docker Engine - Community
 Version:           19.03.12
 API version:       1.40
 Go version:        go1.13.10
 Git commit:        48a66213fe
 Built:             Mon Jun 22 15:45:44 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.12
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.10
  Git commit:       48a66213fe
  Built:            Mon Jun 22 15:44:15 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```
```
NAME="Ubuntu"
VERSION="20.04.1 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.1 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```

**Comment by zhaoge77** [comment]
I am also experiencing this issue on centos 7.x with docker 19.03.12、19.03.13

**Comment by gizmotronic** [comment]
I've had a k3s cluster working for the better part of this year without any issue, until recently. The defunct processes show up within minutes after the cluster starts. These started after installing the nfs-client-provisioner chart from the archived Helm stable repository.

**Comment by superseb** [comment]
This can be solved the same way as we solved it in Rancher previously, see https://github.com/rancher/rancher/issues/13858. This needs to be applied and tested if we see any side effects when using this.

**Comment by uluzox** [comment]
> This can be solved the same way as we solved it in Rancher previously, see #13858. This needs to be applied and tested if we see any side effects when using this.

I am on 

```
Rancher | v2.5.1
User Interface | v2.5.0
Helm | v2.16.8-rancher1
Machine | v0.15.0-rancher45
```

and still I have the issue. The ticket mentioned said this would be fixed in v2.0.7

**Comment by gizmotronic** [comment]
Temporary workaround: on the k3s server, scale the cattle-cluster-agent deployment down and then back up.

```shell
sudo k3s kubectl scale deployment -n cattle-system cattle-cluster-agent --replicas=0
sudo k3s kubectl scale deployment -n cattle-system cattle-cluster-agent --replicas=1
```

**Comment by StoneCut** [comment]
I can also confirm this issue. For me it also affects custom (Rancher-launched) RKE clusters, not just imported ones. I'm running VMware Ubuntu 18.04 nodes on-premise.

- First Environment: Rancher 2.5.1 (Clusters: RKE-launched 1.19.4) || affected, uses proxy for internet access
- Second Environment: Rancher 2.5.1 (Clusters: RKE-launched and imported RKE 1.19.3 & 1.19.4) || affected, uses proxy for internet access
- Third Environment: Rancher 2.43 (Clusters: RKE-launched and imported RKE 1.17.5) || Seemingly unaffected, does not use proxy for internet access

The issue doesn't seem to affect any nodes that are part of the Rancher HA cluster in any environment, only other RKE clusters.

**Comment by zhaoge77** [comment]
I think it is fixed in 2.5.4, when I upgrade to 2.5.4,  the problem disappeared

**Comment by gizmotronic** [comment]
This is still a problem with my Rancher 2.5.5 HA environment, which is managing the following clusters:

- The Rancher HA cluster itself, RKE-launched v1.19.4; unaffected
- A Rancher-launched v1.18.4 cluster; there are only a handful of defunct git-remote-http processes
- An imported k3s v1.20.2+k3s1 cluster; a pair of new defunct processes every 5 minutes

**Comment by gizmotronic** [comment]
My problem turns out to be another case of wildcard DNS causing lookups to fail because of the default `options ndots:5` DNS configuration; see rancher/k3s#1954. Having said that, my workaround in that issue is [probably evil](https://github.com/kubernetes/kubernetes/issues/33554#issuecomment-266251056).

By [turning on query logging](https://rancher.com/docs/rancher/v2.x/en/troubleshooting/dns/#enable-query-logging) I was able to find that something was attempting to resolve `git.rancher.io`, which caused a lookup for `git.rancher.io.mydomain.tld`, and in turn resolved to the external address of my cluster's ingress controller. This of course returns a 404. I imagine that the error status isn't being handled gracefully.

I've removed the wildcard DNS record. It simply doesn't provide enough value, especially when compared to chasing my tail each time it causes a strange problem like this. I haven't seen a single defunct git-remote-http since making this change.

**Comment by shubb30** [comment]
I think @StoneCut is correct about it being proxy related.  We upgraded our dev Rancher HA to 2.5.6. and we are seeing 2 new zombie procs every 5 minutes on the host that is running the cattle cluster agent in each of our clusters managed by that Rancher.

I took a packet capture (for our proxy server, as well as the IPs that `git.rancher.io` resolve to) on the host running the agent.
At the same time, I was tailing the logs for the coredns workload.  Every time I see the coredns spit out a bunch of DNS queries related to `git.rancher.io`, I see the K8s node trying to communicate directly to the AWS IP, and not to our proxy server.

**Comment by shubb30** [comment]
To test the theory about the proxy, we manually modified the `cattle-cluster-agent` workload in our clusters and added in the `HTTPS_PROXY`, `HTTP_PROXY` and `NO_PROXY` values that it should be using.  After the pod restarts, we have not seen any zombie procs on any of our clusters.

**Comment by StoneCut** [comment]
@shubb30 Can you let me know your settings for NO_PROXY (sans your personal domain)? I'm having a few issues.

**Comment by shubb30** [comment]
@StoneCut 

`127.0.0.0/8,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16,.<our-domain>.com,cluster.local`

**Comment by StoneCut** [comment]
@shubb30 Thank you very much. I always though it wasn't possible to add networks to NO_PROXY.

**Comment by Volkimd** [comment]
Proxy isn't really an Option in my Air gapped environment. Any suggestions for this case? 

No Idea from where is the cause. Cluster-Agent is clear. Which process is trying to bring up this connection to git.rancher.io?

**Comment by StrongMonkey** [comment]
Availabl to test on both master and 2.5-head.

**Comment by StrongMonkey** [comment]
@kravciak To reproduce this issue, you can try to:
1. Go to downstream cluster and add a helm chart repo in app & marketplace
2. Edit the helm repo URL so that it can't be reached or failed to reach.
3. Go to the node where cattle-cluster-agent is deployed, run `ps -ef | grep defunct`

**Comment by kravciak** [comment]
I was able to reproduce the issue on v2.5.5.

**Comment by kravciak** [comment]
This works fine on 2.5-head (41f173a), I tried on k3s and rke clusters and they are without defunct processes.

**Comment by sowmyav27** [comment]
@kravciak Please log a forwardport for this issue to validate it on master-head
