### ISSUE TITLE
[Catalog v2] can not change the url or branch of the builtin catalog `Rancher`

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/rancher#30594]
**What kind of request is this (question/bug/enhancement/feature request):**
question / bug 
I am not sure if this is the expected behavior or built-in charts.

**Steps to reproduce (least amount of steps as possible):**
- run rancher:`v2.5-head`/`v2.5.3`  single-install
- go to the `cluster explorer` page of the local cluster 
- edit the builtin catalog `Rancher` to the same repo url and branch as the `partner` one, as the following screenshot shows 
![image](https://user-images.githubusercontent.com/6218999/102930959-b0452900-445a-11eb-83f7-2b6ea6bc4ec4.png)

**Result:**
Go to the `charts` page, we still see the original charts under the `Rancher` catalog even refreshing the catalog manually 
<img width="1860" alt="Screen Shot 2020-12-22 at 1 40 00 PM" src="https://user-images.githubusercontent.com/6218999/102931226-382b3300-445b-11eb-84f4-ccda3a84d3e4.png">

**Expected**:
I expected to see the same set of charts under both catalogs.

**Comment by jiaqiluo** [comment]
The same behavior happens on the downstream cluster on v2.5.3 single-install setup.

**Comment by StrongMonkey** [comment]
@jiaqiluo I think there are some caches in browser. If you switch to incognite mode I think both will show the same.

**Comment by StrongMonkey** [comment]
Also we should not change the url for rancher charts. This will break the existing system charts.

**Comment by slickwarren** [comment]
can confirm the charts don't refresh even after emptying the cache/opening in incognito mode
* rancher 2.5-head (2ae4cf1)
<img width="1792" alt="Screen Shot 2021-02-01 at 7 08 38 AM" src="https://user-images.githubusercontent.com/16691014/106476902-689fbd00-645c-11eb-8727-fa18af467672.png">

**Comment by StrongMonkey** [comment]
@slickwarren I just tried 2.5-head and it is working for me... Do you have a setup that I can look at?

**Comment by StrongMonkey** [comment]
@slickwarren Available to test on the latest 2.5-head.

**Comment by StrongMonkey** [comment]
@slickwarren Make sure you tested the airgap. This touches the airgap code so we want to make sure it doesn't break airgap install(airgap install should have the right access to catalog still)

**Comment by slickwarren** [comment]
thank you for bringing that to attention. It seems that this is fixed for non-airgapped rancher, but on airgapped installations, the repo will not update to the new URL
* using version 2.5.6-rc4
airgapped server: 
<img width="1528" alt="Screen Shot 2021-02-04 at 9 22 37 AM" src="https://user-images.githubusercontent.com/16691014/106930664-a9047280-66ca-11eb-90aa-79f5343e5133.png">

**Comment by StrongMonkey** [comment]
@slickwarren I don't think we support changing URL in air-gapped setup. It will not try to download from internet. Just make sure airgap setup still have the access to catalog(we made a copy into image). You can verify the chart in apps page.

**Comment by slickwarren** [comment]
<img width="1528" alt="Screen Shot 2021-02-04 at 11 00 10 AM" src="https://user-images.githubusercontent.com/16691014/106941789-2e425400-66d8-11eb-86b7-c1c762a0a06e.png">
verified on v2.5.6-rc4
* changed https://git.rancher.io/charts -> https://git.rancher.io/partner-charts (main branch)
