### ISSUE TITLE
RKE network config is not correctly applied when creating custom cluster

### ISSUE THREAD

**Issue by janeczku** [rancher/rancher#31236]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
1. In the UI click on "Add Cluster"
2. Click on "Existing Nodes" and then click on "Edit as Yaml"
3. Enter the following config in the `rancher_kubernetes_engine_config` block to enable the Cisco ACI network plugin ([available in Rancher API since 2.5.5](https://github.com/rancher/rancher/blob/v2.5.5/pkg/client/generated/management/v3/zz_generated_network_config.go#L19)):
```
  network:
    plugin: "aci"
    aci_network_provider:
      system_id: "rancher"
      apic_hosts:
      - "172.28.184.110"
      token: "2f8cc816-21e6-49d3-b18e-00d1bf38f37d"
      apic_user_name: "rancher"
      apic_user_key: "ABC"
      apic_user_crt: "ABC"
      encap_type: "vxlan"
      mcast_range_start: "225.10.1.1"
      mcast_range_end: "225.10.255.255"
      aep: "sauto-aep"
      vrf_name: "sauto_l3out-1_vrf"
      vrf_tenant: "common"
      l3out: "sauto_l3out-1"
      node_subnet: "10.100.1.1/24"
      l3out_external_networks:
      -  "sauto_l3out-1_epg"
      extern_dynamic: "10.3.0.1/24"
      extern_static: "10.4.0.1/24"
      node_svc_subnet: "10.5.0.1/24"
      kube_api_vlan: "213"
      service_vlan: "214"
      infra_vlan: "4081"
      service_monitor_interval: "5" 
```

4. Click on "Next" to create the cluster object in Rancher
5. Click the context menu for the cluster to edit it
6. Inspect the network configuration in the YAML editor. Note how the entire `aci_network_provider` YAML block is missing.
<img width="294" alt="Screenshot 2021-02-10 at 12 34 09" src="https://user-images.githubusercontent.com/3813921/107506417-56312c00-6b9e-11eb-9d56-8de2933cc257.png">

7. Enter the same network configuration again as in step 3 and click on "Save"
8. Inspect again the network configuration in the cluster YAML editor. Note how the `aci_network_provider` YAML block is now present but some of its subkeys are still missing, e.g. `l3out`.
<img width="439" alt="Screenshot 2021-02-10 at 12 47 39" src="https://user-images.githubusercontent.com/3813921/107506511-7365fa80-6b9e-11eb-9358-123a6c21deec.png">

**Expected Result:**
The RKE `rancher_kubernetes_engine_config` provided in the YAML editor is correctly applied to the cluster configuration.

**Actual Result:**

The configuration is applied inconsistently and incomplete.

**Other details that may be helpful:**

Possibly related to erroneous unmarshalling of the nested RKE config JSON object

**Environment information**
- Rancher version: v2.5.5

**Comment by kinarashah** [comment]
Fixed in `v2.5-head`, created cluster and passed the following in Edit as yaml option. They only difference was I got back the l3out field as `l3_out` after cluster was created. Works with Edit as well.

```
  network:
    aci_network_provider:
      aep: sauto-aep
      apic_hosts:
        - 172.28.184.110
      apic_refresh_time: '1200'
      apic_user_crt: ABC
      apic_user_key: ABC
      apic_user_name: rancher
      encap_type: vxlan
      extern_dynamic: 10.3.0.1/24
      extern_static: 10.4.0.1/24
      infra_vlan: '4081'
      l3_out: sauto_l3out-1
      mcast_range_end: 225.10.255.255
      mcast_range_start: 225.10.1.1
      node_subnet: 10.100.1.1/24
      node_svc_subnet: 10.5.0.1/24
      service_monitor_interval: '5'
      service_vlan: '214'
      system_id: rancher
      token: 2f8cc816-21e6-49d3-b18e-00d1bf38f37d
      vrf_name: sauto_l3out-1_vrf
      vrf_tenant: common
 ```

**Comment by deniseschannon** [comment]
@janeczku this looks like rancher-operator was missing fields which is updated in v2.5.6 already. 

Can you validate with a v2.5-head and verify it's working for you? 

This is an issue only on create but not updates.

**Comment by janeczku** [comment]
@deniseschannon Issue is reproduced on `v2.5-dba332111aacdba283baabdc6501d5c42079a3e4-head`:

While the `aci_network_provider` option map is now saved during initial cluster create it is still missing multiple nested keys available in the input, specifically:

- `l3out`
- `l3out_external_networks`
- `kube_api_vlan`

These keys (aside from l3out) are actually missing in @kinarashah output as well. So the issue was already reproduced there.

Cluster YAML input:

<img width="466" alt="Screenshot 2021-02-12 at 13 31 42" src="https://user-images.githubusercontent.com/3813921/107769339-2584fa00-6d38-11eb-9ba2-1a570c72d61d.png">


Resulting API object:

<img width="426" alt="Screenshot 2021-02-12 at 13 34 54" src="https://user-images.githubusercontent.com/3813921/107769395-35044300-6d38-11eb-8d20-115575bd1648.png">

**Comment by kinarashah** [comment]
@janeczku `l3out` is present in the yaml I posted as `l3_out`, let me double check on the other 2 fields again.

**Comment by kinarashah** [comment]
While `apicHosts` show up in API, adding `kube_api_vlan` is breaking UI, waiting on this to be fixed before testing out more https://github.com/rancher/rancher/issues/31258#issuecomment-778327303

**Comment by janeczku** [comment]
Fix for RKE here: https://github.com/rancher/rke/pull/2461

**Comment by thedadams** [comment]
The issue persists in `v2.5-b4be2b22879d85f268dff655206b8e515d803142-head`: following the steps above, the fields `l3out`, `l3out_external_networks`, and `kube_api_vlan` are missing.

<img width="508" alt="Screen Shot 2021-02-22 at 7 06 05 AM" src="https://user-images.githubusercontent.com/3682717/108722753-ba2deb80-74e0-11eb-9a04-caaeab6f6c6e.png">

**Comment by thedadams** [comment]
The problem is actually in `rancher-operator` (anytime I see fields disappearing like this, I always look at rancher-operator first). I need to verify a couple things before the fix can be applied to `rancher-operator`.

**Comment by thedadams** [comment]
In order to fix this, a new branch is needed in `rancher-operator` at the last RC tag. Once that is done
1. Update rke import in `go.mod` in rancher-operator and merge PR.
2. Tag new RC in rancher-operator.
3. Submit PR to `rancher/charts` with new RC.

Once the charts PR is merged, verify the fix.

**Comment by thedadams** [comment]
Fix has been verified on `v2.5-87006de30625c046523a329b03ea2580db35fb57-head`:

Follow the steps above to create a cluster with existing nodes. Wait a few minutes and edit cluster YAML. All fields are listed.

<img width="459" alt="Screen Shot 2021-02-23 at 8 18 54 PM" src="https://user-images.githubusercontent.com/3682717/108942664-a1beed80-7614-11eb-8444-2e4ec51704a0.png">

**Comment by janeczku** [comment]
Thanks for helping to get this fix landed everyone 🎉
