### ISSUE TITLE
Issue with Space in Catalog Name

### ISSUE THREAD

**Issue by zaubererty** [rancher/rancher#3124]
When creating a catalog entry (Admin > Settings > Catalog) with a space in the name like "XYZ Lib" the catalog items show up but without image and failing on view.

Current solution, use a catalog name without space like "XYZLib"

**Comment by deniseschannon** [comment]
Do you have a GitHub repo that I could look at your directory structure/templates? Have you looked at the docs on how the repo should be set up? http://docs.rancher.com/rancher/configuration/settings/#creating-private-catalogs

The name shouldn't be an issue as we have many spaces in our catalog names in the one that is shipped with Rancher. The name that shows up in Rancher should be in the `config.yml`. 

https://github.com/rancher/rancher-catalog

**Comment by vincent99** [comment]
The library and template name in `links` values should be urlencoded, and the API needs to handle decoding and matching them on subsequent requests.

**Comment by vincent99** [comment]
@deniseschannon it's the catalog name having a space in it that's the problem, not the individual templates in that catalog.

**Comment by zaubererty** [comment]
@deniseschannon Vincent is right, its the catalog name

**Comment by demarant** [comment]
I had same issue and can confirm that you cannot add a custom catalog name with a space, since the name is not url-encoded the links to images in the catalog are broken.

**Comment by prachidamle** [comment]
@vincent99 @deniseschannon @demarant @zaubererty this is fixed in PR rancher/rancher-catalog-service#42

**Comment by tfiduccia** [comment]
Version - master 3/8
Not fixed - this is still broken.

Note to myself to reproduce - this is in reference to the "catalog name" on the setting page.

**Comment by prachidamle** [comment]
Changes are needed on cattle to pass in the catalogUrl argument enclosed in quotes, so that catalog service can parse the names containing spaces. PR #1449 submitted to fix the cattle part.

**Comment by sangeethah** [comment]
Tested with latest build from master.
I am still able to reproduce this issue.

**Comment by prachidamle** [comment]
This has already been fixed from rancher-catalog-service side. But cattle needs some fix, somewhere the proxy is somehow messing up the request containing a url encoded space - as per @ibuildthecloud 

@ibuildthecloud let me know if you have any ideas around the proxy I can check

**Comment by soumyalj** [comment]
Tested with v1.1.0-dev4. Was able add a catalog with space in the catalog name. The catalog items show up correctly with the image and was able to launch them successfully.
