### ISSUE TITLE
vSphere node driver - VM deployed from content library is not setting network as per node template

### ISSUE THREAD

**Issue by ansilh** [rancher/rancher#31408]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
- Create a vsphere node template with creation method as content library 
<img width="1315" alt="node_template_network" src="https://user-images.githubusercontent.com/11064902/108620192-768ba100-7450-11eb-85eb-a4ce3380ef70.png">
- Create a cluster using the new template 

**Result:**
- VM gets created with no network 
<img width="1076" alt="vm_no_network" src="https://user-images.githubusercontent.com/11064902/108620212-9de26e00-7450-11eb-9456-3521f0f5e96e.png">

**Other details that may be helpful:**

Rancher trace log shows that the network parameters are passed to `rancher-machine` via flag `-vmwarevsphere-network`

```
[TRACE] buildCommand args: [rancher-machine --debug create -d vmwarevsphere --engine-install-url https://releases.rancher.com/install-docker/19.03.sh --vmwarevsphere-cfgparam disk.enableUUID=TRUE --vmwarevsphere-datastore /NUCDC/datastore/DS01 --vmwarevsphere-network /NUCDC/network/DPortGroup 1 --vmwarevsphere-datacenter /NUCDC --vmwarevsphere-disk-size 20000 --vmwarevsphere-ssh-password tcuser --vmwarevsphere-folder /NUCDC/vm/test folder/k8s vms --vmwarevsphere-memory-size 2048 --vmwarevsphere-pool /NUCDC/host/esxi01.ansil.io/Resources --vmwarevsphere-creation-type library --vmwarevsphere-password Vmware@123 --vmwarevsphere-ssh-user-group staff --vmwarevsphere-vcenter-port 443 --vmwarevsphere-content-library test content library --vmwarevsphere-ssh-port 22 --vmwarevsphere-ssh-user docker --vmwarevsphere-username administrator@ansil.io --vmwarevsphere-vcenter 192.168.110.40 --vmwarevsphere-clone-from ubuntu-18-cloud-template --vmwarevsphere-cpu-count 2 --vmwarevsphere-cloud-config /RDEVSVNQER/cloud-config all-in-one-node1]
```
- Rancher trace log 
[rancher_node_driver_debug.log](https://github.com/rancher/rancher/files/6017426/rancher_node_driver_debug.log)

- If there is a network adapter present in the VM template and that is mapped to an existing network, then VM comes up with that network instead of the one passed via node template.

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.4.11
- Installation option (single install/HA): HA

gz#15111

**Comment by depasseg** [comment]
I'm having the same problem and noticed that if I go back and edit the node template that the network settings are empty in the template itself (as an aside the same thing happens to the Folder location and the Data Store settings not getting saved).

**Comment by ansilh** [comment]
@depasseg , The issue you are facing is not the same.
Values not getting populated while editing node template is addressed via https://github.com/rancher/rancher/issues/30690 and the milestone for that fix is v2.5.6.

**Comment by slickwarren** [comment]
this is still an issue on master-351f7ca04973c1f023653f171c0f621f31bf2ca2-head: 
* deploy rancher on vsphere
* deploy vsphere downstream cluster using content library with custom network settings
**Network still uses default value on vsphere instead of user chosen value**

<img width="895" alt="Screen Shot 2021-05-13 at 1 07 30 PM" src="https://user-images.githubusercontent.com/16691014/118181195-4ec32e00-b3ec-11eb-99d1-c9e5be4f6910.png">
<img width="391" alt="Screen Shot 2021-05-13 at 1 07 01 PM" src="https://user-images.githubusercontent.com/16691014/118181352-8336ea00-b3ec-11eb-9beb-76f00a7f035c.png">

**Comment by ansilh** [comment]
Looks like the flag `vmwarevsphere-network` in `rancher-machine` is not setting even though we pass the values properly. 
https://github.com/rancher/machine/blob/v0.15.0-rancher57/drivers/vmwarevsphere/flags.go#L202

So we ending up with the default network. 
https://github.com/rancher/machine/blob/v0.15.0-rancher57/drivers/vmwarevsphere/vsphere.go#L263

Need to check the recent changes that went into the flag code path.

**Comment by ansilh** [comment]
The driver reports the below messages and this points to the update I made above. 

```
2021/05/14 00:00:49 [INFO] [node-controller-rancher-machine] (all-in-one-test1) Type assertion did not go smoothly to string slice for key vmwarevsphere-network
2021/05/14 00:00:49 [INFO] [node-controller-rancher-machine] (all-in-one-test1) Type assertion did not go smoothly to string slice for key vmwarevsphere-tag
2021/05/14 00:00:49 [INFO] [node-controller-rancher-machine] (all-in-one-test1) Type assertion did not go smoothly to string slice for key vmwarevsphere-custom-attribute
2021/05/14 00:00:49 [INFO] [node-controller-rancher-machine] (all-in-one-test1) Type assertion did not go smoothly to string slice for key vmwarevsphere-cfgparam
2021/05/14 00:00:49 [INFO] [node-controller-rancher-machine] (all-in-one-test1) Type assertion did not go smoothly to string slice for key vmwarevsphere-vapp-property
```

But while testing with `rancher/machine`  tag `v0.15.0-rancher56` I didn't see this message and network mapping works fine.

**Comment by ansilh** [comment]
Hi @superseb , Need your help on this. I can't find the reason for this issue since the PR I pushed works fine with `v0.15.0-rancher56`

**Comment by superseb** [comment]
Your changes went into `v0.15.0-rancher57`, I'm not following what you are saying. It works with a version without your changes and now it doesn't? While it was filed as not working currently?

**Comment by ansilh** [comment]
I pulled branch `v0.15.0-rancher56` and replaced the file which was modified in that PR and compiled the binary.
Then used that binary to create a machine and it worked fine.

When I pulled `v0.15.0-rancher57` and compiled it and while using it I get the message `Type assertion did not go smoothly to string slice for key` while creating the machine. I don't know what is causing this message to appear which is not happening when I manually test PR directly on `v0.15.0-rancher56`

**Comment by superseb** [comment]
Isn't using tag `v0.15.0-rancher56` + your PR the same as using `v0.15.0-rancher57` as your PR was merged in between? What Rancher version/branch/commit are you testing this with?

**Comment by ansilh** [comment]
Oops, looks like the way I compiled the binary is the problem. When I use`-a` along with the build, this issue is happening on `v0.15.0-rancher56` too.  I wasn't using `-a` when I tested the PR locally. 

```
CGO_ENABLED=0 GOARCH=amd64 go build -a -tags netgo -installsuffix netgo -ldflags "-X main.VERSION=$VERSION -extldflags '-static -s'" -o ./bin/rancher-machine-Linux-x86_64 ./cmd/rancher-machine;
```

**Comment by ansilh** [comment]
Build from `tags/v0.15.0-rancher56` have issues. 
I think the blast radius of this issue is more here since the flags with the type "string slice" from the command line are NOT propagating to the driver at all.

Build from `tags/v0.15.0-rancher55` works fine
So this issue is introduced in `tags/v0.15.0-rancher56`. 
Since I was using an old tag while creating this PR , my test worked fine at that time.

**Comment by superseb** [comment]
Its probably the urfave/cli bump done when pod driver was introduced, have to look at what exactly changed and how to remediate.

**Comment by superseb** [comment]
@ansilh Can you test using https://github.com/rancher/machine/pull/124?

**Comment by ansilh** [comment]
Thanks, @superseb . Yes, It worked after appying  [124.patch](https://patch-diff.githubusercontent.com/raw/rancher/machine/pull/124.patch).

**Comment by slickwarren** [comment]
master-head (5d2b7ac), node template settings for network now are correctly setting the VM network
new related issue filed here: https://github.com/rancher/rancher/issues/32761

<img width="123" alt="Screen Shot 2021-05-17 at 9 36 34 AM" src="https://user-images.githubusercontent.com/16691014/118529778-bb923d00-b6f8-11eb-902d-245dde49ab8f.png">
<img width="140" alt="Screen Shot 2021-05-17 at 10 16 33 AM" src="https://user-images.githubusercontent.com/16691014/118529977-fa27f780-b6f8-11eb-8356-911cae446af5.png">
