### ISSUE TITLE
Missing Images in rancher-images.txt on 2.5.8-rc10 when using image list for use with rancher HA AG setup

### ISSUE THREAD

**Issue by slickwarren** [rancher/rancher#32350]
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
* deploy private registry using the [v2.5.8-rc9 rancher-images.txt](https://github.com/rancher/rancher/releases/download/v2.5.8-rc9/rancher-images.txt)
* deploy an airgap setup using the latest RKE, with the latest rancher version (v2.5.8-rc9)

**Result:**
the following images are missing for HA airgap setup when using [RKE 1.2.8-rc3](https://github.com/rancher/rke/releases/tag/v1.2.8-rc3) + v2.5.8-rc9 (these are the images that each pod is failing on. I am not sure if the image list or if the pod image has the `true` correct image): 
* rancher/rancher-operator:v0.1.4-rc3
* rancher/rancher-webhook:v0.1.0-rc2
* rancher/fleet:v0.3.5-rc6
* rancher/gitjob:v0.1.15
* rancher/nginx-ingress-controller:nginx-0.43.0-rancher1

also, this image appears to be in the wrong format (missing forward slash)
.qa.rancher.spacerancher/shell:v0.1.6

**Other details that may be helpful:**
this was following [instructions here](https://rancher.com/docs/rancher/v2.x/en/installation/other-installation-methods/air-gap/install-rancher/) for deploying an HA setup with an airgapped cluster. RKE deployment was successful but fails when installing rancher
<img width="809" alt="Screen Shot 2021-04-26 at 11 54 36 AM" src="https://user-images.githubusercontent.com/16691014/116135647-36ca7b00-a686-11eb-8486-331ffaa95d0d.png">

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.5.8-rc9
- Installation option (single install/HA): HA airgap

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): HA, ec2 instances
- Machine type (cloud/VM/metal) and specifications (CPU/memory): t3a.xlarge
- Kubernetes version (use `kubectl version`): 1.20

- Docker version (use `docker version`):20.10

**Comment by cbron** [comment]
This should be fixed with recent RC.

**Comment by slickwarren** [comment]
the following images are still missing on v2.5.8-rc10 for an HA airgap install using :
* /rancher/nginx-ingress-controller:nginx-0.43.0-rancher1

note: I think we should be using one of the later versions, so not sure why rancher is looking for `rancher1` instead of 2 or 3
and  this image is still in the wrong format (missing forward slash) -- can file separate ticket if necessary
.qa.rancher.spacerancher/shell:v0.1.6

**Comment by sowmyav27** [comment]
[This](https://github.com/rancher/rancher/issues/32350#issuecomment-827880440) happens as the latest `nginx-ingress-controller` is not available in `v1.2.8-rc3`

**Comment by slickwarren** [comment]
on v2.5.8-rc12 and rke v1.2.8-rc4, I was able to deploy an airgapped HA cluster without any images missing in the registry (besides https://github.com/rancher/rancher/issues/32436, filed separately)
