### ISSUE TITLE
Operation cannot be fulfilled on gitrepos.fleet.cattle.io 

### ISSUE THREAD

**Issue by giuseppeCozzolino** [rancher/rancher#32909]
**What kind of request is this (question/bug/enhancement/feature request):** Bug

**Steps to reproduce (least amount of steps as possible):**
- Create a cluster
- Access to Explorer and then Continuous Delivery
- Configure a git Repo with watch to a branch or a revision and save
- edit the git Repo configuration editing the branche name or the revision 

**Result:**

Operation cannot be fulfilled on gitrepos.fleet.cattle.io "project-name": the object has been modified; please apply your changes to the latest version and try again

**Other details that may be helpful:**

<img width="1791" alt="Schermata 2021-05-27 alle 13 48 33" src="https://user-images.githubusercontent.com/77336342/119821330-b8fec700-bef2-11eb-9251-55c510c51b0b.png">

**Comment by dwainmsims** [comment]
I just ran into this same issue.  The problem seems be intermittent and browser specific.  

I am using Rancher 2.5.8 and browser Firefox 89.0.2 on OpenSUSE Tumbleweed.  When I tried this same operation on Vivaldi 4.0.2312.38, the issue was not there.

**Comment by firefhtr** [comment]
I a running into the same issue, I am running on MacOS Big Sur, Firefox 89.0.2 and Chrome 91.0.4472.114.  Safari is un-useable for Rancher (just get a blank screen).  I also got the error on Vivaldi 4.0.2312.38 on MacOS.

**Comment by gaktive** [comment]
This should be resolved by https://github.com/rancher/dashboard/issues/1324

**Comment by erSitzt** [comment]
Still getting an error if i'm too slow
Adding the `pollingInterval` in this case... which works if im fast enough...
After adding the higher pollingInterval i can edit the repo without problems...

So it seems this is not resolved by https://github.com/rancher/dashboard/issues/1324

Rancher 2.6.3-patch1

<img width="537" alt="image" src="https://user-images.githubusercontent.com/1625376/155713820-11345f0d-cc1b-439b-a0b3-3d36cd628759.png">
