### ISSUE TITLE
Unable to provision custom Windows 2004/20H2/2019 RKE cluster with k8s v1.21.1-rancher2-1 - Win nodes stuck in Registering state

### ISSUE THREAD

**Issue by thehejik** [rancher/rancher#32910]
**What kind of request is this (question/bug/enhancement/feature request):** bug 
* This issue is related to new kubernetes `v1.21.1-rancher1-1` only - **it does work with `v1.20.6-rancher1-1` correctly**

**Steps to reproduce (least amount of steps as possible):**
* Deploy `rancher/rancher:master-head 26d6cde` on ec2 singlenode as custom RKE
* In Ember UI define a custom Windows RKE cluster on "Existing node" and choose k8s `v1.21.1-rancher1-1` version, select `Flannel` as Network Provider and Enable `Windows Support`
* Copy and execute the Linux reg. commands on existing aws t3a.medium VMs with Ubuntu 18.04 `ami-0d5d9d301c853a04a` - 1x worker, 1x controlplane and 1x etcd
* Copy and execute the Windows reg. commands on existing aws t3.xlarge VMs with Windows 2004 `ami-006a0cc7076eedf9e` - 3x windows worker node with `vxlan`

**Result:**
* All 3 windows worker nodes are stuck in `Registering` state and message `Waiting to register with Kubernetes` is visible after ~1 hour after running the reg. command (reload doesn't help):
![windows_nodes_stuck](https://user-images.githubusercontent.com/12828077/119817658-894dc000-beee-11eb-8608-c4fdcab01be2.png)

**Other details that may be helpful:**
<details>
<summary>Logs from rancher-agent container on win worker</summary>

```
C:\Users\Administrator>docker logs 635bb -f
WARN: Default docker named pipe is not found
WARN: Please bind mount in the docker named pipe to //./pipe/docker_engine if docker errors occur
WARN: example: docker run -v //./pipe/custom_docker_named_pipe://./pipe/docker_engine ...
INFO: https://rancher.mydomain is accessible
time="2021-05-27T10:31:24Z" level=info msg="Listening on /tmp/log.sock"
time="2021-05-27T10:31:24Z" level=info msg="Rancher agent version 26d6cde is starting"
time="2021-05-27T10:31:24Z" level=info msg="Option worker=true"
time="2021-05-27T10:31:24Z" level=info msg="Option requestedHostname=ip-ac1f03de"
time="2021-05-27T10:31:24Z" level=info msg="Option dockerInfo={DXNQ:RIEV:5TIN:MM2H:BYK7:CBEP:UGYF:W52T:DW6S:BIDA:BO5Y:S3V5 2 1 0 1 4 windowsfilter [[Windows ]] [] {[local] [ics internal l2bridge l2tunnel nat null overlay private transparent] [] [awslogs etwlogs fluentd gcplogs gelf json-file local logentries splunk syslog]} false false false false false false false false false true true true false -1 false 35 2021-05-27T10:31:24.0892718Z json-file   0 10.0 19041 (19041.1.amd64fre.vb_release.191206-1406) Windows Server Datacenter Version 2004 (OS Build 19041.928) 10.0.19041 windows x86_64 https://index.docker.io/v1/ 0xc000494070 4 16982306816 [] C:\\ProgramData\\docker    IP-AC1F03DE [] false 20.10.4   map[]  {  inactive false  [] 0 0 <nil> []} false process  { } { } { } []  [] []}"
time="2021-05-27T10:31:24Z" level=info msg="Option customConfig=map[address:3.143.247.224 internalAddress:172.31.3.222 label:map[rke.cattle.io/windows-build:19041 rke.cattle.io/windows-kernel-version:19041.1.amd64fre.vb_release.191206-1406 rke.cattle.io/windows-major-version:10 rke.cattle.io/windows-minor-version:0 rke.cattle.io/windows-release-id:2004 rke.cattle.io/windows-version:10.0.19041.928] roles:[worker] taints:[]]"
time="2021-05-27T10:31:24Z" level=info msg="Option etcd=false"
time="2021-05-27T10:31:24Z" level=info msg="Option controlPlane=false"
time="2021-05-27T10:31:24Z" level=info msg="Connecting to wss://rancher.mydomain/v3/connect/register with token gdp9d6t9hc9k9dtjh7jqgqh6gcvdb4zwmgz692v8cvlptxm5g58ldm"
time="2021-05-27T10:31:24Z" level=info msg="Connecting to proxy" url="wss://rancher.mydomain/v3/connect/register"
time="2021-05-27T10:31:25Z" level=error msg="Failed to connect to proxy. Response status: 400 - 400 Bad Request. Response body: Operation cannot be fulfilled on nodes.management.cattle.io \"m-66792281f6cc\": the object has been modified; please apply your changes to the latest version and try again" error="websocket: bad handshake"
time="2021-05-27T10:31:25Z" level=error msg="Remotedialer proxy error" error="websocket: bad handshake"
time="2021-05-27T10:31:35Z" level=info msg="Connecting to wss://rancher.mydomain/v3/connect/register with token gdp9d6t9hc9k9dtREDACTED"
time="2021-05-27T10:31:35Z" level=info msg="Connecting to proxy" url="wss://rancher.mydomain/v3/connect/register"
time="2021-05-27T10:31:35Z" level=info msg="Waiting for node to register. Either cluster is not ready for registering, cluster is currently provisioning, or etcd, controlplane and worker node have to be registered"
time="2021-05-27T10:31:38Z" level=info msg="Waiting for node to register. Either cluster is not ready for registering, cluster is currently provisioning, or etcd, controlplane and worker node have to be registered"
time="2021-05-27T10:31:40Z" level=info msg="Waiting for node to register. Either cluster is not ready for registering, cluster is currently provisioning, or etcd, controlplane and worker node have to be registered"
time="2021-05-27T10:31:42Z" level=info msg="Waiting for node to register. Either cluster is not ready for registering, cluster is currently provisioning, or etcd, controlplane and worker node have to be registered"
time="2021-05-27T10:31:44Z" level=info msg="Waiting for node to register. Either cluster is not ready for registering, cluster is currently provisioning, or etcd, controlplane and worker node have to be registered"
time="2021-05-27T10:31:47Z" level=info msg="Waiting for node to register. Either cluster is not ready for registering, cluster is currently provisioning, or etcd, controlplane and worker node have to be registered"
time="2021-05-27T10:31:49Z" level=info msg="Waiting for node to register. Either cluster is not ready for registering, cluster is currently provisioning, or etcd, controlplane and worker node have to be registered"
time="2021-05-27T10:31:51Z" level=info msg="Waiting for node to register. Either cluster is not ready for registering, cluster is currently provisioning, or etcd, controlplane and worker node have to be registered"
time="2021-05-27T10:31:53Z" level=info msg="Waiting for node to register. Either cluster is not ready for registering, cluster is currently provisioning, or etcd, controlplane and worker node have to be registered"
time="2021-05-27T10:31:55Z" level=info msg="Waiting for node to register. Either cluster is not ready for registering, cluster is currently provisioning, or etcd, controlplane and worker node have to be registered"
time="2021-05-27T10:31:58Z" level=info msg="Waiting for node to register. Either cluster is not ready for registering, cluster is currently provisioning, or etcd, controlplane and worker node have to be registered"
time="2021-05-27T10:32:00Z" level=info msg="Waiting for node to register. Either cluster is not ready for registering, cluster is currently provisioning, or etcd, controlplane and worker node have to be registered"
time="2021-05-27T10:32:02Z" level=info msg="Waiting for node to register. Either cluster is not ready for registering, cluster is currently provisioning, or etcd, controlplane and worker node have to be registered"
time="2021-05-27T10:32:04Z" level=info msg="Waiting for node to register. Either cluster is not ready for registering, cluster is currently provisioning, or etcd, controlplane and worker node have to be registered"
time="2021-05-27T10:32:06Z" level=info msg="Waiting for node to register. Either cluster is not ready for registering, cluster is currently provisioning, or etcd, controlplane and worker node have to be registered"
time="2021-05-27T10:32:08Z" level=info msg="Waiting for node to register. Either cluster is not ready for registering, cluster is currently provisioning, or etcd, controlplane and worker node have to be registered"
time="2021-05-27T10:32:10Z" level=info msg="Waiting for node to register. Either cluster is not ready for registering, cluster is currently provisioning, or etcd, controlplane and worker node have to be registered"
time="2021-05-27T10:32:13Z" level=info msg="Waiting for node to register. Either cluster is not ready for registering, cluster is currently provisioning, or etcd, controlplane and worker node have to be registered"
time="2021-05-27T10:32:15Z" level=info msg="Waiting for node to register. Either cluster is not ready for registering, cluster is currently provisioning, or etcd, controlplane and worker node have to be registered"
time="2021-05-27T10:32:17Z" level=info msg="Waiting for node to register. Either cluster is not ready for registering, cluster is currently provisioning, or etcd, controlplane and worker node have to be registered"
time="2021-05-27T10:32:19Z" level=info msg="Waiting for node to register. Either cluster is not ready for registering, cluster is currently provisioning, or etcd, controlplane and worker node have to be registered"
time="2021-05-27T10:32:21Z" level=info msg="Waiting for node to register. Either cluster is not ready for registering, cluster is currently provisioning, or etcd, controlplane and worker node have to be registered"
time="2021-05-27T10:32:23Z" level=info msg="Waiting for node to register. Either cluster is not ready for registering, cluster is currently provisioning, or etcd, controlplane and worker node have to be registered"
time="2021-05-27T10:32:26Z" level=info msg="Waiting for node to register. Either cluster is not ready for registering, cluster is currently provisioning, or etcd, controlplane and worker node have to be registered"
time="2021-05-27T10:32:28Z" level=info msg="Waiting for node to register. Either cluster is not ready for registering, cluster is currently provisioning, or etcd, controlplane and worker node have to be registered"
time="2021-05-27T10:32:30Z" level=info msg="Waiting for node to register. Either cluster is not ready for registering, cluster is currently provisioning, or etcd, controlplane and worker node have to be registered"
time="2021-05-27T10:32:32Z" level=info msg="Waiting for node to register. Either cluster is not ready for registering, cluster is currently provisioning, or etcd, controlplane and worker node have to be registered"
time="2021-05-27T10:32:34Z" level=info msg="Waiting for node to register. Either cluster is not ready for registering, cluster is currently provisioning, or etcd, controlplane and worker node have to be registered"
time="2021-05-27T10:32:36Z" level=info msg="Waiting for node to register. Either cluster is not ready for registering, cluster is currently provisioning, or etcd, controlplane and worker node have to be registered"
time="2021-05-27T10:32:39Z" level=info msg="Waiting for node to register. Either cluster is not ready for registering, cluster is currently provisioning, or etcd, controlplane and worker node have to be registered"
time="2021-05-27T10:32:41Z" level=info msg="Waiting for node to register. Either cluster is not ready for registering, cluster is currently provisioning, or etcd, controlplane and worker node have to be registered"
time="2021-05-27T10:32:43Z" level=info msg="Waiting for node to register. Either cluster is not ready for registering, cluster is currently provisioning, or etcd, controlplane and worker node have to be registered"
time="2021-05-27T10:32:45Z" level=info msg="Waiting for node to register. Either cluster is not ready for registering, cluster is currently provisioning, or etcd, controlplane and worker node have to be registered"
time="2021-05-27T10:32:47Z" level=info msg="Waiting for node to register. Either cluster is not ready for registering, cluster is currently provisioning, or etcd, controlplane and worker node have to be registered"
time="2021-05-27T10:32:50Z" level=info msg="Waiting for node to register. Either cluster is not ready for registering, cluster is currently provisioning, or etcd, controlplane and worker node have to be registered"
time="2021-05-27T10:32:52Z" level=info msg="Waiting for node to register. Either cluster is not ready for registering, cluster is currently provisioning, or etcd, controlplane and worker node have to be registered"
time="2021-05-27T10:32:54Z" level=info msg="Waiting for node to register. Either cluster is not ready for registering, cluster is currently provisioning, or etcd, controlplane and worker node have to be registered"
time="2021-05-27T10:32:56Z" level=info msg="Waiting for node to register. Either cluster is not ready for registering, cluster is currently provisioning, or etcd, controlplane and worker node have to be registered"
time="2021-05-27T10:32:58Z" level=info msg="Waiting for node to register. Either cluster is not ready for registering, cluster is currently provisioning, or etcd, controlplane and worker node have to be registered"
time="2021-05-27T10:33:00Z" level=info msg="Waiting for node to register. Either cluster is not ready for registering, cluster is currently provisioning, or etcd, controlplane and worker node have to be registered"
time="2021-05-27T10:33:03Z" level=info msg="Waiting for node to register. Either cluster is not ready for registering, cluster is currently provisioning, or etcd, controlplane and worker node have to be registered"
time="2021-05-27T10:33:05Z" level=info msg="Waiting for node to register. Either cluster is not ready for registering, cluster is currently provisioning, or etcd, controlplane and worker node have to be registered"
time="2021-05-27T10:33:07Z" level=info msg="Waiting for node to register. Either cluster is not ready for registering, cluster is currently provisioning, or etcd, controlplane and worker node have to be registered"
time="2021-05-27T10:33:09Z" level=info msg="Waiting for node to register. Either cluster is not ready for registering, cluster is currently provisioning, or etcd, controlplane and worker node have to be registered"
time="2021-05-27T10:33:11Z" level=info msg="Waiting for node to register. Either cluster is not ready for registering, cluster is currently provisioning, or etcd, controlplane and worker node have to be registered"
time="2021-05-27T10:33:13Z" level=info msg="Waiting for node to register. Either cluster is not ready for registering, cluster is currently provisioning, or etcd, controlplane and worker node have to be registered"
time="2021-05-27T10:33:16Z" level=info msg="Waiting for node to register. Either cluster is not ready for registering, cluster is currently provisioning, or etcd, controlplane and worker node have to be registered"
time="2021-05-27T10:33:18Z" level=info msg="Waiting for node to register. Either cluster is not ready for registering, cluster is currently provisioning, or etcd, controlplane and worker node have to be registered"
time="2021-05-27T10:33:20Z" level=info msg="Waiting for node to register. Either cluster is not ready for registering, cluster is currently provisioning, or etcd, controlplane and worker node have to be registered"
time="2021-05-27T10:33:22Z" level=info msg="Waiting for node to register. Either cluster is not ready for registering, cluster is currently provisioning, or etcd, controlplane and worker node have to be registered"
time="2021-05-27T10:33:24Z" level=info msg="Waiting for node to register. Either cluster is not ready for registering, cluster is currently provisioning, or etcd, controlplane and worker node have to be registered"
time="2021-05-27T10:33:26Z" level=info msg="Waiting for node to register. Either cluster is not ready for registering, cluster is currently provisioning, or etcd, controlplane and worker node have to be registered"
time="2021-05-27T10:33:29Z" level=info msg="Waiting for node to register. Either cluster is not ready for registering, cluster is currently provisioning, or etcd, controlplane and worker node have to be registered"
time="2021-05-27T10:33:31Z" level=info msg="Waiting for node to register. Either cluster is not ready for registering, cluster is currently provisioning, or etcd, controlplane and worker node have to be registered"
time="2021-05-27T10:33:33Z" level=info msg="Waiting for node to register. Either cluster is not ready for registering, cluster is currently provisioning, or etcd, controlplane and worker node have to be registered"
time="2021-05-27T10:33:35Z" level=info msg="Waiting for node to register. Either cluster is not ready for registering, cluster is currently provisioning, or etcd, controlplane and worker node have to be registered"
time="2021-05-27T10:33:37Z" level=info msg="Waiting for node to register. Either cluster is not ready for registering, cluster is currently provisioning, or etcd, controlplane and worker node have to be registered"
time="2021-05-27T10:33:39Z" level=info msg="Starting plan monitor, checking every 15 seconds"
```
Note that curent time on node is ~10:50.
</details>

<details>
<summary>Logs from rancher-agent container on win worker after its restart</summary>

```
WARN: Default docker named pipe is not found
WARN: Please bind mount in the docker named pipe to //./pipe/docker_engine if docker errors occur
WARN: example: docker run -v //./pipe/custom_docker_named_pipe://./pipe/docker_engine ...
INFO: https://rancher.mydomain is accessible
time="2021-05-27T11:37:31Z" level=info msg="Listening on /tmp/log.sock"
time="2021-05-27T11:37:31Z" level=info msg="Rancher agent version 26d6cde is starting"
time="2021-05-27T11:37:31Z" level=info msg="Option etcd=false"
time="2021-05-27T11:37:31Z" level=info msg="Option controlPlane=false"
time="2021-05-27T11:37:31Z" level=info msg="Option worker=true"
time="2021-05-27T11:37:31Z" level=info msg="Option requestedHostname=ip-ac1f03de"
time="2021-05-27T11:37:31Z" level=info msg="Option dockerInfo={DXNQ:RIEV:5TIN:MM2H:BYK7:CBEP:UGYF:W52T:DW6S:BIDA:BO5Y:S3V5 2 1 0 1 4 windowsfilter [[Windows ]] [] {[local] [ics internal l2bridge l2tunnel nat null overlay private transparent] [] [awslogs etwlogs fluentd gcplogs gelf json-file local logentries splunk syslog]} false false false false false false false false false true true true false -1 false 37 2021-05-27T11:37:31.1141655Z json-file   0 10.0 19041 (19041.1.amd64fre.vb_release.191206-1406) Windows Server Datacenter Version 2004 (OS Build 19041.928) 10.0.19041 windows x86_64 https://index.docker.io/v1/ 0xc00041a000 4 16982306816 [] C:\\ProgramData\\docker    IP-AC1F03DE [] false 20.10.4   map[]  {  inactive false  [] 0 0 <nil> []} false process  { } { } { } []  [] []}"
time="2021-05-27T11:37:31Z" level=info msg="Option customConfig=map[address:3.143.247.224 internalAddress:172.31.3.222 label:map[rke.cattle.io/windows-build:19041 rke.cattle.io/windows-kernel-version:19041.1.amd64fre.vb_release.191206-1406 rke.cattle.io/windows-major-version:10 rke.cattle.io/windows-minor-version:0 rke.cattle.io/windows-release-id:2004 rke.cattle.io/windows-version:10.0.19041.928] roles:[worker] taints:[]]"
time="2021-05-27T11:37:31Z" level=info msg="Connecting to wss://rancher.mydomain/v3/connect with token gdp9d6t9hcREDACTED"
time="2021-05-27T11:37:31Z" level=info msg="Connecting to proxy" url="wss://rancher.mydomain/v3/connect"
time="2021-05-27T11:37:32Z" level=info msg="Starting plan monitor, checking every 15 seconds"
```

</details>

* logs from rancher container with DEBUG level set - look for `c-8g2tw` cluster [container.log](https://github.com/rancher/rancher/files/6553740/container.log)

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): `rancher/rancher:master-head 26d6cde`
- Installation option (single install/HA): any

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Custom Windows RKE
- Machine type (cloud/VM/metal) and specifications (CPU/memory): t3a.medium, t3.xlarge
- Kubernetes version (use `kubectl version`): v1.21.1-rancher1-1

**Edit 21/06/04:** this problem has been recognized today on Windows 2019 as well - the summary applies also for recent versions of `rancher/rancher:master-head 772ef96` and RKE1 k8s `v1.21.1-rancher2-1`

**Comment by laoshancun** [comment]
Maybe same issue
windows 2004 on custom windows rke.
It seems that `rancher/rke-tools` is wrong version.

## TL;DL;

## kubelet logs
```text
INFO: Waiting for servcie-sidekick to prepare the entrypoint.ps1 ...
FATA: Timeout, could not found c:\opt\rke-tools\entrypoint.ps1
INFO: Waiting for servcie-sidekick to prepare the entrypoint.ps1 ...
FATA: Timeout, could not found c:\opt\rke-tools\entrypoint.ps1
```
## start service-sidekick
```
[192.168.10.161]: PS C:\Users\Administrator\Documents> docker start service-sidekick
docker : Error response from daemon: hcsshim::CreateComputeSystem 8f6d7cd0b6ddf1c1d95b9c5f4dc8e147a357ac13fcd8cb1c5d17b
037cfcb8446: The container operating system does not match the host operating system.
    + CategoryInfo          : NotSpecified: (Error response ...erating system.:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError

(extra info: {"SystemType":"Container","Name":"8f6d7cd0b6ddf1c1d95b9c5f4dc8e147a357ac13fcd8cb1c5d17b037cfcb8446","Owner
":"docker","VolumePath":"\\\\?\\Volume{96154feb-e1c7-4684-a2e1-8a781fe6ecea}","IgnoreFlushesDuringBoot":true,"LayerFold
erPath":"C:\\ProgramData\\Docker\\windowsfilter\\8f6d7cd0b6ddf1c1d95b9c5f4dc8e147a357ac13fcd8cb1c5d17b037cfcb8446","Lay
ers":[{"ID":"526c805d-b3b8-5031-acfb-e67cd50ea290","Path":"C:\\ProgramData\\Docker\\windowsfilter\\c75804befb37c64ccf5f
88f0b908de83d51b6de1351260dbbbe10cc3a72274f2"},{"ID":"d3f6d7cf-239e-51c0-9cd0-7d1cbafe0ea9","Path":"C:\\ProgramData\\Do
cker\\windowsfilter\\563ed8822b4849e8b17a831d977175f5eb630614285c29305d287d646fc97b3c"},{"ID":"308e020d-0e23-5a44-9424-
bb4f4acae4c3","Path":"C:\\ProgramData\\Docker\\windowsfilter\\c10724eafd6ce363042e62163677b9b81b2d9f880e7c9e08019459a46
1777077"},{"ID":"3f82ead6-44be-53cc-adc9-00f5d05ca6fb","Path":"C:\\ProgramData\\Docker\\windowsfilter\\23539e3815bf77c1
92c8ffc920e38525131f496f38b870deedc145edec5434a7"},{"ID":"94de1067-1149-5b75-b0be-3dbb1bb924a1","Path":"C:\\ProgramData
\\Docker\\windowsfilter\\bf3503af5d6e39176ed6f33fa52ca2cab4bc84e34d3023823ad5d222007db4e5"},{"ID":"213736e9-487e-5241-9
8e9-badaee8ad5d6","Path":"C:\\ProgramData\\Docker\\windowsfilter\\3a7952d21fc14ac7b8497248b5c2498f975bc0b8e295d25b797bc
d82d9557f9f"},{"ID":"f2fe9e5c-8672-5f34-b748-915e730bda6e","Path":"C:\\ProgramData\\Docker\\windowsfilter\\500d3901851c
854b063fda16b8a52b8a6974ae1c4b756caffee6b64c0a511668"},{"ID":"eb928d72-2612-5d27-b2e6-993838511815","Path":"C:\\Program
Data\\Docker\\windowsfilter\\ab97a0b886ab387194035bbbec964e22c9f0581c64742d0ecb000511943570b8"},{"ID":"88cb3733-99dc-5f
28-95aa-6759e960244a","Path":"C:\\ProgramData\\Docker\\windowsfilter\\ffd5e9de6e0dbd8d8f48dedb281158b7d5b3f12f617a10c6e
dba307d7c422aa3"},{"ID":"28cd962d-112a-5e3b-a036-594db65f2f4e","Path":"C:\\ProgramData\\Docker\\windowsfilter\\ccf3cae0
cf849f38432710c719ff8a49c5ad63b8607b6ef877f4b01c9376c1d9"},{"ID":"a611bf88-1bf1-59b1-9317-8774e2822ccc","Path":"C:\\Pro
gramData\\Docker\\windowsfilter\\5ad28c27586f88f8569fd20e27596f8184608a753d6045ce5b12abda1c3e9a07"},{"ID":"48d72746-971
a-5342-9f46-bc9726878c0b","Path":"C:\\ProgramData\\Docker\\windowsfilter\\89c685ce497e5fe68ae8e2000d468dc5904d4b43016e1
f911320157bb1afbf8f"},{"ID":"1f1b2593-cfb1-5d59-b62e-6d17b09a9da3","Path":"C:\\ProgramData\\Docker\\windowsfilter\\5156
6cfab05af68df5b4c34bff7b9f03748b762f01c4fcc2732a84f834bb145e"},{"ID":"dee56eec-3884-515c-a8a9-3e78cf34cce5","Path":"C:\
\ProgramData\\Docker\\windowsfilter\\be2d505586aed41f07c08a2f23bf8590b2a6f7fcb5b1c39ec4b1a3c5dbff447a"},{"ID":"6ded6a7e
-6e33-523e-9ab2-66ae43778711","Path":"C:\\ProgramData\\Docker\\windowsfilter\\412300a7d7d9191520a03a017c05573cac9414c40
82cd43adfd2830209634821"},{"ID":"7f53db5f-c0af-553b-a2e3-9f48982658da","Path":"C:\\ProgramData\\Docker\\windowsfilter\\
802516c7b3deabac470141246cdc2a1d12cdef4834fd0b8bd6bf520c2717354a"},{"ID":"aed4a242-d107-550a-b7d0-ce771a7331cf","Path":
"C:\\ProgramData\\Docker\\windowsfilter\\bf4583dc27c0135e078bdda9bb14756402b1073e37cec5ab6d0ba5ea8072b1c7"},{"ID":"bf3e
8812-4793-5841-a994-2b414b3dfe5d","Path":"C:\\ProgramData\\Docker\\windowsfilter\\74468b21799614236c85280f62e0c0499ce4b
8dae05e1d92e741879838c7484e"},{"ID":"c37e8187-6ffd-5486-9c89-d9c824ab23e0","Path":"C:\\ProgramData\\Docker\\windowsfilt
er\\ed62fe395d845d84ab4285b3ee4d44a780ea7a872cd84c26824b5423c886c260"},{"ID":"c5a81cfa-fa3b-595d-9946-41a43ebd63b6","Pa
th":"C:\\ProgramData\\Docker\\windowsfilter\\44278ca1a2764f4d244d110eeccfc78e92c4767e954d6484b292c3a42ee0acd7"},{"ID":"
2c7a9991-fc3c-5400-8c42-3455480808b4","Path":"C:\\ProgramData\\Docker\\windowsfilter\\83fbb302be866278e10f1585a21ba686d
fa7140c33429f37cbe9c37be7e30ce0"},{"ID":"7ebec584-df06-5b52-9d0e-a052265f001f","Path":"C:\\ProgramData\\Docker\\windows
filter\\04d0fcea98e2eaa9dbcdc5624152d14e74e9bd609483a00553e028130384a34a"},{"ID":"00500ec4-5ca6-5a12-b41e-fbac879cb2b6"
,"Path":"C:\\ProgramData\\Docker\\windowsfilter\\08cebf802a65bef7d1759f42051675111f1aca663fd2a28be460228bfd676b2d"},{"I
D":"7b88a22f-d1a6-5807-aa8f-201becf28910","Path":"C:\\ProgramData\\Docker\\windowsfilter\\15b25cb77dfa67a9e32c07c825cd7
05d0e69291680917ca5d5d3fadb9d3eb236"},{"ID":"ee7204b7-f289-5d15-a80a-cc86fa77bccb","Path":"C:\\ProgramData\\Docker\\win
dowsfilter\\2ec0720224b31454eaeb1274d0e511665f78b0a6d9dde0a102a4e8a36b191000"},{"ID":"170cdb47-4e5c-573b-a6ea-f6499a9cd
05f","Path":"C:\\ProgramData\\Docker\\windowsfilter\\4525f78ade19244348d2724a62e1e3cff572d3228616b420f3ed837c6dd9cb30"}
,{"ID":"3de72c0d-a4af-5e30-95f1-ea3f032d32a3","Path":"C:\\ProgramData\\Docker\\windowsfilter\\f5405688779083fc582841b02
26ea68b9a9b581d39f76fcb9a78cbb9ddb2f0c3"},{"ID":"0b65cfdc-7c1a-562e-a385-9800a6fc11ee","Path":"C:\\ProgramData\\Docker\
\windowsfilter\\9185c39e46b08aa6c63f40611ec05e618b2e43e5a32e2799e5d626285fdd0389"}],"HostName":"8f6d7cd0b6dd","MappedDi
rectories":[{"HostPath":"C:\\ProgramData\\Docker\\volumes\\5014230731e16f6cdb1f470dba73d17bccb9b73882287a9fd85abf1ce19d
4b7c\\_data","ContainerPath":"c:\\run","ReadOnly":false,"BandwidthMaximum":0,"IOPSMaximum":0,"CreateInUtilityVM":false}
,{"HostPath":"c:\\etc","ContainerPath":"c:\\host\\etc","ReadOnly":false,"BandwidthMaximum":0,"IOPSMaximum":0,"CreateInU
tilityVM":false},{"HostPath":"c:\\run","ContainerPath":"c:\\host\\run","ReadOnly":false,"BandwidthMaximum":0,"IOPSMaxim
um":0,"CreateInUtilityVM":false},{"HostPath":"C:\\ProgramData\\Docker\\volumes\\cc0f14aae108381e8a8509194b8cd9e37c57415
27843a3bd4437efc485d61f81\\_data","ContainerPath":"c:\\opt\\rke-tools","ReadOnly":false,"BandwidthMaximum":0,"IOPSMaxim
um":0,"CreateInUtilityVM":false},{"HostPath":"c:\\opt","ContainerPath":"c:\\host\\opt","ReadOnly":false,"BandwidthMaxim
um":0,"IOPSMaximum":0,"CreateInUtilityVM":false},{"HostPath":"c:\\etc\\kube-flannel","ContainerPath":"c:\\host\\etc\\ku
be-flannel","ReadOnly":false,"BandwidthMaximum":0,"IOPSMaximum":0,"CreateInUtilityVM":false},{"HostPath":"c:\\etc\\cni\
\net.d","ContainerPath":"c:\\host\\etc\\cni\\net.d","ReadOnly":false,"BandwidthMaximum":0,"IOPSMaximum":0,"CreateInUtil
ityVM":false}],"MappedPipes":[{"HostPath":"\\\\.\\pipe\\rancher_wins","ContainerPipeName":"rancher_wins"}],"HvPartition
":false,"EndpointList":["d6a48f60-deea-455b-89f4-9c7da9a95c48"],"AllowUnqualifiedDNSQuery":true})
Error: failed to start containers: service-sidekick
```
## service-sidekick
- Image: `rancher/rke-tools:v0.1.69`
- OsVersion: `10.0.17763.1637`

**Comment by sowmyav27** [comment]
@laoshancun Can you please let us know what version of rancher the cluster is on? Could you also give us more details on the setup?

**Comment by sirredbeard** [comment]
Is cluster provisioning working on master?

**Comment by laoshancun** [comment]
@sowmyav27 OK.

**Comment by thehejik** [comment]
Same result with Windows 20H2 `ami-005281e398ece7d23`

**Comment by thehejik** [comment]
Windows 2019 `ami-0d6f7eaedf946c299` worker nodes do not appear in the list of nodes at all. But the problem is different - `rancher-agent` container Exited on following Error:
```
C:\Users\Administrator>docker ps -a
CONTAINER ID        IMAGE                                                                        COMMAND                  CREATED             STATUS                      PORTS               NAMES
7c7125b3fb20        rancher/rancher-agent:master-62aef7654f34a105b65ebf326167674d7809c730-head   "pwsh -NoLogo -NonIn…"   18 minutes ago      Exited (0) 18 minutes ago                       crazy_rhodes

C:\Users\Administrator>docker logs 7c7125
Get-Command: C:\etc\rancher\bootstrap.ps1:279
Line |
 279 |  Copy-Item $($(Get-Command powershell).Source) $($CATTLE_PREFIX_PATH)e …
     |                ~~~~~~~~~~~~~~~~~~~~~~
     | The term 'powershell' is not recognized as a name of a cmdlet,
     | function, script file, or executable program. Check the
     | spelling of the name, or if a path was included, verify that
     | the path is correct and try again.
```

@sowmyav27 please let me know in case you'd like to have an extra card for it.

**Comment by thehejik** [comment]
I've opened extra issue for the Windows 2019/1809 problem https://github.com/rancher/rancher/issues/32937

**Comment by luthermonson** [comment]
@laoshancun you have a different issue. youre running `rancher/rke-tools:v0.1.69` which does not support 2004 and it's complaining that the image pulled down is not a 2004 image. you can do 1809/1903/1909 with that version of k8s youre deploying. rke-tools:v0.1.70 and beyond supported 2004 and 20H2.

**Comment by luthermonson** [comment]
@thehejik so is this a dupe of #32937 ? the solution in the PR for that issue fixes 2004 as well as it would have affected anything not 20H2. I believe this is now a dupe issue and you can close.

**Comment by thehejik** [comment]
@luthermonson no, it is not a DUP - it was another issue which has been resolved and closed (it was about missing powershell bin in 2004/1809 container).

Now the problem is that all windows versions I tried today (2004/2019) on latest `rancher/rancher:master-head 772ef96` are stuck in this `Registering` state forever (waiting for more than hour) with RKE1 k8s `v1.21.1-rancher2-1` on the win cluster. With previous RKE1 k8s `v1.20.7-rancher1-1` all the Win 2004 nodes are `Active` after a while.

So basically after fixing the poweshell bin issue #32927 is this problem present on all windows version on latest k8s `v1.21.1-rancher2-1`.

This is recent docker log from rancher-agent container on windows 2019, it looks ~ the same as for win 2004 in summary:
```
INFO: https://rancher is accessible
time="2021-06-04T13:31:20Z" level=info msg="Listening on /tmp/log.sock"
time="2021-06-04T13:31:20Z" level=info msg="Rancher agent version 772ef96e6 is starting"
time="2021-06-04T13:31:20Z" level=info msg="Option customConfig=map[address:4.3.2.1 internalAddress:172.31.3.194 label:map[rke.cattle.io/windows-build:17763 rke.cattle.io/windows-kernel-version:17763.1.amd64fre.rs5_release.180
914-1434 rke.cattle.io/windows-major-version:10 rke.cattle.io/windows-minor-version:0 rke.cattle.io/windows-release-id:1809 rke.cattle.io/windows-version:10.0.17763.1637] roles:[worker] taints:[]]"
time="2021-06-04T13:31:20Z" level=info msg="Option etcd=false"
time="2021-06-04T13:31:20Z" level=info msg="Option controlPlane=false"
time="2021-06-04T13:31:20Z" level=info msg="Option worker=true"
time="2021-06-04T13:31:20Z" level=info msg="Option requestedHostname=ip-ac1f03c2"
time="2021-06-04T13:31:20Z" level=info msg="Option dockerInfo={2WJ3:3ZQC:Y53M:YH2T:6S3G:XS5B:K6DQ:JRGL:YXIK:7LOA:U4W5:BTRK 2 1 0 1 4 windowsfilter [[Windows ]] [] {[local] [ics internal l2bridge l2tunnel nat null overlay private tr
ansparent] [] [awslogs etwlogs fluentd gcplogs gelf json-file local logentries splunk syslog]} false false false false false false false false false true true true false -1 false 33 2021-06-04T13:31:20.8237598Z json-file   0 10.0 1
7763 (17763.1.amd64fre.rs5_release.180914-1434) Windows Server 2019 Datacenter Version 1809 (OS Build 17763.1637)  windows x86_64 https://index.docker.io/v1/ 0xc00032a070 4 16982306816 [] C:\\ProgramData\\docker    IP-AC1F03C2 [] f
alse 19.03.13   map[]  {  inactive false  [] 0 0 <nil> []} false process  { } { } { } []  [] []}"
time="2021-06-04T13:31:21Z" level=info msg="Connecting to wss://rancher/v3/connect with token REDACTED"
time="2021-06-04T13:31:21Z" level=info msg="Connecting to proxy" url="wss://rancher/v3/connect"
time="2021-06-04T13:31:22Z" level=info msg="Starting plan monitor, checking every 15 seconds"
```

**Comment by luthermonson** [comment]
the agents are booting and talking back to rancher server url and stuck waiting for plans and the plan never comes. i do not believe this is an exclusive windows problem and more a no v3.Node plan that needs to be investigated. possible reasons are no nodeconfig or no docker info returned. will need to turn on debug and look for rkeworkerupgrader logs and see what is erroring out and it's possible the windows nodes are being asked for something they're not providing.

**Comment by sirredbeard** [comment]
Please re-test on Windows and Linux. Thank you.

**Comment by thehejik** [comment]
> Please re-test on Windows and Linux. Thank you.

Still doesn't work on `rancher/rancher:master-head cd623b5`. Windows-20H2 nodes are stuck in `Registering` state forever, Linux nodes are ok.

**Comment by luthermonson** [comment]
@thehejik this should be working in the latest dev-v2.6 kdm which should get pulled down when you boot master head. please test again

**Comment by thehejik** [comment]
@luthermonson still the same problem, win node is waiting for registering Kubernetes forever with latest `rancher/rancher:master-head 94bca99` which should, according to the timestamps from drone, contain the provided kdm changes.

```
administrator@IP-AC1F07F0 C:\Users\Administrator>docker logs a47
INFO: https://rancher.redacted.org is accessible
time="2021-07-30T10:13:47Z" level=info msg="Listening on /tmp/log.sock"
time="2021-07-30T10:13:47Z" level=info msg="Rancher agent version 94bca99 is starting"
time="2021-07-30T10:13:47Z" level=info msg="Option requestedHostname=ip-ac1f07f0"
time="2021-07-30T10:13:47Z" level=info msg="Option dockerInfo={UQ77:UG5A:T5JV:ABOC:K7G6:TCDK:RNQU:BQQM:KWAE:6TE2:FOPD:HWRW 2 1 0 1 1 windowsfilter [[Windows ]] [] {[local] [ics internal l2bridge l2tunnel nat null overlay private tr
ansparent] [] [awslogs etwlogs fluentd gcplogs gelf json-file local logentries splunk syslog]} false false false false false false false false false true true true false -1 false 33 2021-07-30T10:13:47.3952836Z json-file   0 10.0 1
9042 (19041.1.amd64fre.vb_release.191206-1406) Windows Server Datacenter Version 2009 (OS Build 19042.746)  windows x86_64 https://index.docker.io/v1/ 0xc0018f24d0 4 16982241280 [] C:\\ProgramData\\docker    IP-AC1F07F0 [] false 19
.03.14   map[]  {  inactive false  [] 0 0 <nil> []} false process  { } { } { } []  [] []}"
time="2021-07-30T10:13:47Z" level=info msg="Option customConfig=map[address:1.2.3.4 internalAddress:172.31.7.240 label:map[rke.cattle.io/windows-build:19042 rke.cattle.io/windows-kernel-version:19041.1.amd64fre.vb_release.19120
6-1406 rke.cattle.io/windows-major-version:10 rke.cattle.io/windows-minor-version:0 rke.cattle.io/windows-release-id:2009 rke.cattle.io/windows-version:10.0.19042.746] roles:[worker] taints:[]]"
time="2021-07-30T10:13:47Z" level=info msg="Option etcd=false"
time="2021-07-30T10:13:47Z" level=info msg="Option controlPlane=false"
time="2021-07-30T10:13:47Z" level=info msg="Option worker=true"
time="2021-07-30T10:13:47Z" level=info msg="Connecting to wss://rancher.redacted.org/v3/connect/register with token starting with redacted45xk7g88vwbvbnbr882"
time="2021-07-30T10:13:47Z" level=info msg="Connecting to proxy" url="wss://rancher.redacted.org/v3/connect/register"
time="2021-07-30T10:13:48Z" level=info msg="Starting plan monitor, checking every 15 seconds"
```

Reopening.

**Comment by thehejik** [comment]
Seeing `Registering` also for `Windows_Server-2019-English-Full-ContainersLatest-2021.07.14` node on k8s `v1.21.1-rancher3-1`. Linux/ubuntu nodes are all `Active`.

**Comment by sirredbeard** [comment]
"32910 is confirmed as a KDM issue, it's being resolved right now" per @rosskirkpat

**Comment by sowmyav27** [comment]
On latest 2.6-head commit id: `1e814fe`

- Able to deploy a 2019 Windows cluster on 1.21.3-rancher1-1
