### ISSUE TITLE
Charts page shows no useful chart data and Chart Repositories are stuck "In Progress"

### ISSUE THREAD

**Issue by catastrophe-brandon** [rancher/rancher#33711]
*Steps to Reproduce*

1. Install Rancher via Docker from master-head (`cfbd0d3`)
2. Create an RKE1 or RKE2 cluster in EC2
3. Await completion of the cluster creation process
4. Navigate to the cluster
5. Click on Apps & Marketplace > Charts, the message `There are no charts available, have you added any repos?` appears.
6. Click on Apps & Marketplace > Chart Repositories, there will be two repositories. Both appear to be stuck "In Progress"

*Expected Results*
The rancher and partner charts populate the Charts page from the repositories.

*Symptoms*
When I was using the UI, I noticed an error in the dev console that may or may not be relevant. [Gist](https://gist.github.com/catastrophe-brandon/ce2e33c1097850d8f31e108a0767598a)

In the docker logs there are numerous ERROR messages like this:
```
2021/07/20 23:05:50 [ERROR] Error during subscribe websocket: close sent
2021/07/20 23:05:50 [ERROR] Error during subscribe websocket: close sent
```

However, it is unclear whether or not these messages are related to the issue.

Also noteworthy are the messages that appear on the Chart Repositories page, such as `ClusterRepo generation is 5, but latest observed generation is 0`

![Screen Shot 2021-07-20 at 6 08 24 PM](https://user-images.githubusercontent.com/20647751/126406653-1fdd8ecc-f1dd-48e6-abeb-8ace64ed6aca.png)

**Comment by anupama2501** [comment]
The issue is seen for rke2 clusters as well 
<img width="400" alt="Screen Shot 2021-07-21 at 8 04 22 PM" src="https://user-images.githubusercontent.com/38144301/126584590-93124037-9829-4a62-8134-e0b020e61576.png">

**Comment by catastrophe-brandon** [comment]
This is fixed in master-head `9e0d1b2`

**Comment by garrmark** [comment]
I'm still seeing an issue in 2.6.2, any other troubleshooting tips?
![image](https://user-images.githubusercontent.com/2669864/144117474-7e90ad4c-b98a-4792-af8f-4714527e11d3.png)

**Comment by aellert** [comment]
Same here after upgrade to 2.7.9

**Comment by YaronL16** [comment]
Same after upgrading to v2.8.5
