### ISSUE TITLE
[2.6] Unable to remove cluster

### ISSUE THREAD

**Issue by abhi1693** [rancher/rancher#34650]
**Rancher Server Setup**
- Rancher version: 2.6.0
- Installation option (Docker install/Helm Chart): Helm chart
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): RKE1
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version: v1.20.0
- Cluster Type (Local/Downstream): Downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): vSphere

**Describe the bug**

I delete a downstream cluster and the node was removed from vsphere but now it's stuck in removal on the UI

**To Reproduce**
 
I'm not sure how to reproduce this as I have not tried it again.

**Result**
```
2021/09/05 05:26:50 [INFO] Stopping cluster agent for c-8lh48
2021/09/05 05:26:50 [ERROR] error syncing 'c-5dbcl': handler restrictedAdminsRBACCluster: Index with name by-cluster does not exist, requeuing
```

**Expected Result**

The cluster should be removed from the UI

**Screenshots**

![image](https://user-images.githubusercontent.com/5083532/132116386-37e4693e-9cce-415b-bdf2-dbdd6d2c07a5.png)

**Additional context**
<!--Add any other context about the problem here.—>

**Comment by anupama2501** [comment]
@abhi1693 if the UI is refreshed was the deleted cluster removed from the UI?

**Comment by abhi1693** [comment]
@anupama2501  It took about 24 hours for it to get removed from it. I tried relogin but that didn't help.

Since then I have had this issue twice with the exact same log

**Comment by abhi1693** [comment]
@anupama2501 I was mistaken the home page still shows the cluster is scheduled for deletion. However, it's not visible in the sidebar

**Comment by abhi1693** [comment]
@anupama2501 I have another cluster that is stuck now. I have tried to remove the ns for the cluster, but rancher keeps recreating it again and so every cluster that we are deleting is now stuck at deletion.

**Comment by abhi1693** [comment]
Now, the UI would not let me delete the cluster because delete is not supported

![image](https://user-images.githubusercontent.com/5083532/134985548-50385bcf-f35a-4217-800b-9aede873499b.png)

**Comment by ppommarel** [comment]
Got the same behaviour on my side, unremovable cluster.
In my case, I aborted while provisioning, but also got the message mentioned by @abhi1683

**Comment by abhi1693** [comment]
I tried to recreate the issue and now my `local` cluster is also getting deleted.

Here are the logs 
[rancher-b9b5f6cb-w69hb_rancher.log](https://github.com/rancher/rancher/files/7243338/rancher-b9b5f6cb-w69hb_rancher.log)

**Comment by anupama2501** [comment]
@abhi1693 would you be able to provide the steps that were tried when you see this issue, I will try to reproduce the same in my test setup?

**Comment by abhi1693** [comment]
@anupama2501 I have no idea how the local cluster started getting deleted. I deleted my test cluster and that on its own triggered it. Because I don't see any way to do this from the UI.

Unable to delete downstream cluster is always reproducible with vsphere setups. Once your cluster is active, then delete it from the UI from the homepage.

**Comment by anupama2501** [comment]
Have a couple of clarification questions:

1. Cluster that you were trying to delete created as a standard user or an admin?
2. vsphere cluster that was created, was it an infrastructure provider/custom cluster?
3. Was the cloud provider enabled?
4. Was the rancher server upgraded from v2.5.x or v2.4.x versions to v2.6.0 or a fresh install of v2.6.0?

**Comment by fm4991** [comment]
I have a similar problem... we have a cluster in deleting state it isnt there when i do a `k get cluster -n fleet-default` on the rmc but still appears on the startpage of rmc (2.6.0)

**Comment by abhi1693** [comment]
@anupama2501 

1. Cluster that you were trying to delete, was it created as a standard user or an admin?
```
I created using administrator
```

2. vsphere cluster that was created, was it an infrastructure provider/custom cluster?
```
I'm not sure about what exactly you are asking here. It's an on-prem setup. We are running vCenter v6.5 and v6.7 in our datacenters.
```

3. Was the cloud provider enabled?
```
No
```

4. Was the rancher server upgraded from v2.5.x or v2.4.x versions to v2.6.0 or a fresh install of v2.6.0?
```
I upgraded from v2.5.9 using the terraform provider as that is how we manage the cluster.
```

**Comment by anupama2501** [comment]
@abhi1693 thanks for all the info. 

I created a downstream vsphere cluster as an admin with 3 etcd, 3 worker and 2 cp nodes on rancher v2.6.0
When I delete the cluster, I see the cluster is deleted from home page, cluster management and explore cluster page. I myself was not able to repro this issue but we already have similar issues logged:
https://github.com/rancher/dashboard/issues/3423
https://github.com/rancher/dashboard/issues/4053

This is not seen on the latest v2.6-head version which will be released as v2.6.2. 
I tried creating the same on the latest v2.6-head and haven't seen the issue for a vsphere downstream cluster.

**Comment by brooksphilip** [comment]
I am also having this same issue. I provisioned a RKE2 cluster and deleted the VM without removing it from rancher and I am not able to remove the cluster now. 
![image](https://user-images.githubusercontent.com/56730922/139717627-ce225c70-e4a9-4442-b604-c699f4c39349.png)

**Comment by bgulla** [comment]
Here's how to manually delete a cluster. Thanks Brad.  

```
kubectl get clusters.management.cattle.io  # find the cluster you want to delete 
export CLUSTERID="c-xxxxxxxxx" # 
kubectl patch clusters.management.cattle.io $CLUSTERID -p '{"metadata":{"finalizers":[]}}' --type=merge
kubectl delete clusters.management.cattle.io $CLUSTERID
```

**Comment by brandond** [comment]
Or if you like just copy-pasting things:

```bash
kubectl get clusters.management.cattle.io  # find the cluster you want to delete, use for $CLUSTERID below
kubectl patch clusters.management.cattle.io $CLUSTERID -p '{"metadata":{"finalizers":[]}}' --type=merge
kubectl delete clusters.management.cattle.io $CLUSTERID
```

**Comment by bmartin13** [comment]
Awesome.  I can confirm this worked for me.  Thanks!

**Comment by brandond** [comment]
Awesome, glad to hear it!

**Comment by DanielKotik** [comment]
> I am also having the same issue with 2.6.2. Previously deleted cluster still shows under Advanced -> Mgmt Clusters
Same here. https://github.com/rancher/rancher/issues/34650#issuecomment-956555419 fixed it for me.

**Comment by aslafy-z** [comment]
We're also hitting this issue with 2.6.2 which prevents us to migrate to Rancher 2.6.x.

**Comment by danielbjornadal** [comment]
> Here's how to manually delete a cluster. Thanks Brad.
> 
> ```
> kubectl get clusters.management.cattle.io  # find the cluster you want to delete 
> export CLUSTERID="c-xxxxxxxxx" # 
> kubectl patch clusters.management.cattle.io $CLUSTERID -p '{"metadata":{"finalizers":[]}}' --type=merge
> kubectl delete clusters.management.cattle.io $CLUSTERID
> ```

After running `kubectl patch clusters.management.cattle.io $CLUSTERID -p '{"metadata":{"finalizers":[]}}' --type=merge`, the cluster no longer shows under `kubectl get clusters.management.cattle.io`, and the `kubectl delete clusters.management.cattle.io $CLUSTERID` cant find it.

Cluster still shows under Cluster Management in the UI. Name is replaced with the cluster ID.

![image](https://user-images.githubusercontent.com/7441428/144826328-a7002a73-be7d-412b-a627-8d79719391c0.png)

**Comment by jackelynoliveira** [comment]
> > Here's how to manually delete a cluster. Thanks Brad.
> > ```
> > kubectl get clusters.management.cattle.io  # find the cluster you want to delete 
> > export CLUSTERID="c-xxxxxxxxx" # 
> > kubectl patch clusters.management.cattle.io $CLUSTERID -p '{"metadata":{"finalizers":[]}}' --type=merge
> > kubectl delete clusters.management.cattle.io $CLUSTERID
> > ```
> 
> After running `kubectl patch clusters.management.cattle.io $CLUSTERID -p '{"metadata":{"finalizers":[]}}' --type=merge`, the cluster no longer shows under `kubectl get clusters.management.cattle.io`, and the `kubectl delete clusters.management.cattle.io $CLUSTERID` cant find it.
> 
> Cluster still shows under Cluster Management in the UI. Name is replaced with the cluster ID.
> 
> ![image](https://user-images.githubusercontent.com/7441428/144826328-a7002a73-be7d-412b-a627-8d79719391c0.png)

Had the same problem. I was able to fix it by running these commands:

```
kubectl -n fleet-default get clusters.provisioning.cattle.io
kubectl -n fleet-default patch clusters.provisioning.cattle.io <cluster_name> -p '{"metadata":{"finalizers":[]}}' --type=merge
kubectl -n fleet-default delete clusters.provisioning.cattle.io <cluster_name>
```

**Comment by brandond** [comment]
The steps above were assuming that you'd already tried deleting it, and it was stuck waiting on the finalizers. Deleting it at some point (either before or after removing the finalizers) is definitely a requirement.

**Comment by laurie-kepford** [comment]
i am having a similar problem. My old cluster was called vetpro-prod2 and had an id of c-c16h4

i first tried  these commands:
```
kubectl get clusters.management.cattle.io  # find the cluster you want to delete 
export CLUSTERID="c-xxxxxxxxx" # 
kubectl patch clusters.management.cattle.io $CLUSTERID -p '{"metadata":{"finalizers":[]}}' --type=merge
kubectl delete clusters.management.cattle.io $CLUSTERID
```
However export CLUSTERID command returned no value.

So I tried these commands:
```
kubectl -n fleet-default get clusters.provisioning.cattle.io # find the name of the cluster you want to delete
kubectl -n fleet-default patch clusters.provisioning.cattle.io <cluster_name> -p '{"metadata":{"finalizers":[]}}' --type=merge
kubectl -n fleet-default delete clusters.provisioning.cattle.io <cluster_name>
```
That worked and the cluster does not show up in the Cluster manager anymore. (the old cluster was called vetpro-prod2) 
![2022-02-14 at 6 40 AM](https://user-images.githubusercontent.com/86793511/153884818-2bc75ba1-809d-437c-8fde-538506c4d5ee.png)

HOWEVER it does still show up in the explorer:

![2022-02-14 at 6 41 AM](https://user-images.githubusercontent.com/86793511/153885171-d657d668-9908-439a-90d6-d8e424258a34.png)

In the docker logs I am seeing many of these errors:

`2022/02/14 14:31:28 [ERROR] error syncing 'c-cl6h4/machine-99r5x': handler node-controller: Delete "https://D77ECA3AB450391D7A294C8F90AD0996.yl4.us-west-2.eks.amazonaws.com/api/v1/nodes/ip-10-50-98-31.us-west-2.compute.internal?timeout=45s": dial tcp: lookup D77xxxxxxxxxxxx.us-west-2.eks.amazonaws.com on 10.50.0.2:53: no such host, requeuing`
`2022/02/14 14:43:38 [ERROR] Failed to handling tunnel request from 10.50.47.153:42338: response 400: cluster not found`

I am running 2.6.1 in a single docker container on ubuntu.  My clusters are all EKS.

**Comment by aslafy-z** [comment]
@laurie-kepford FYI, this issue was addressed in 2.6.2.

**Comment by laurie-kepford** [comment]
I did finally get it to delete.  I ran `kubectl delete namespace c-cl6h4`

**Comment by KeithTt** [comment]
Same problem in 2.6.3, I even delete the namespace local, but it still exists, I think it is a BUG!

/BUG

**Comment by thedadams** [comment]
There seems to be several issues being discussed in this thread. I will do my best to address them all.
1. The original description had a log message describing that the `by-cluster` index didn't exist. That is not related to deleting. The code that produces that error is not run if a cluster is deleting.
2. The name of the finalizer that is on the provisioning cluster object would be helpful to know. My guess, based on the comments here is that the finalizer was the `mgmt-cluster-remove` finalizer.
3. If the above is correct and the `mgmt-cluster-remove` finalizer was the one that was leftover, then that would explain why the cluster disappears from the Cluster Management page in the UI but not the Explore Cluster page.
4. The error from [this comment](https://github.com/rancher/rancher/issues/34650#issuecomment-1039170793) indicates that the cluster no longer exists and Rancher is stuck trying to cleanup it up. There are certain protection built in (like if Rancher can contact the cluster, but the node no longer exists but this error is outside that scope).
5. There are mentions of not being able to delete a cluster with errors `Method DELETE is not supported`. That can happen if the role bindings are cleaned up before the cluster is completely deleted or left hanging around. That issue is being fixed: https://github.com/rancher/rancher/issues/35899
6. Finally, there are mentions of namespaces being left around or not cleaned up. That issue is also being fixed: https://github.com/rancher/rancher/issues/31546

**Comment by dnoland1** [comment]
@thedadams For 2 above, I remove the`controller.cattle.io/cluster-agent-controller-cleanup` finalizer on clusters.management.catttle.io, then the cluster is completely removed.

**Comment by thedadams** [comment]
@dnoland1 That issue is being fixed: https://github.com/rancher/rancher/issues/35700

**Comment by janeczku** [comment]
@thedadams Steps to reproduce this issue:

1. Provision an RKE2 cluster using the vSphere integration
2. Go to the vCenter and delete the VMs that Rancher provisioned for this cluster
3. Delete the cluster in Rancher from the Cluster Management page

**Comment by janeczku** [comment]
Related issue: https://github.com/rancher/rancher/issues/35853

**Comment by kinarashah** [comment]
https://github.com/rancher/rancher/issues/35853 will be tracked separately, can close this if the original issue is fixed. cc @Auston-Ivison-Suse

**Comment by Auston-Ivison-Suse** [comment]
**Validation Setup**

- Rancher version: v2.6-head(599a9e8) (Setup via vsphere)
- Local cluster k8s version: v1.22.7+k3s1
- Downstream: vSphere, RKE1, k8s version: v1.22.7-rancher1-2

**Validation Steps**

1. setup rancher within vsphere then login. 
2. Provision downstream clusters using the vsphere node driver
3. Wait for them to come up and then delete the clusters

**Results**
The cluster is removed successfully and no longer hangs like in the original description. 

**Further tests: **
- Clusters out of a vsphere environment also remove
- RKE2 clusters also removed
- Ec2, DO, all removed as well.

**Comment by shfy70** [comment]
The issue is still persistent in Rancher 2.6.5, I mean as a former scientist, always wonder why the QC is so poor for so many IT products, so anti-user, the new 2.6.* GUI is horrendous compare to 2.5.*

**Comment by boldynnetwork** [comment]
I am on 2.7.9 Rancher - in my case the cluster is deleted and all the nodes are deleted in vsphere. But one worker node is stuck in deleting - by which the cluster cannot be deleted. 
all the resources on vsphere are completely deleted. And Rancher UI is showing 
cluster removing state "Resource scheduled for deletion"   and 
one node is  in deleting state and tries to create - which it cant because there is no clsuter
"Creating server [fleet-default/boldyn-dev-ingress-d309c68e-mrv44] of kind (VmwarevsphereMachine) for machine boldyn-dev-ingress-59c9cf79b6xzqj5j-jsp7s in infrastructure provider
--
 

<br class="Apple-interchange-newline">

Tried everything - and i cannot do kubectl commands to delete by finalizers - because there are no resources

**Comment by gmiller01** [comment]
This issu is old, but exists yet.
The solution:
https://www.suse.com/support/kb/doc/?id=000021228
