### ISSUE TITLE
Add Option and text not aligned properly in Add Volume

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#3600]
Version - master 2/11

Steps:
1.  Create and start Gluster FS
2.  Create and start Convoy Gluster FS
3.  Go to Storage Pools page and click on Add Volume

Results:  Driver Options text and +Add Options are not aligned
![image](https://cloud.githubusercontent.com/assets/11514927/12993124/a00f9f14-d0d5-11e5-8d6e-4fedb8e49b5a.png)

Expected:  Should be aligned together.

**Comment by lvuch** [comment]
resolved in https://github.com/rancher/ui/pull/470

**Comment by tfiduccia** [comment]
Version - master 2/17
Not fixed - this is still not aligned, looks exactly the same as before.

**Comment by lvuch** [comment]
resolved in https://github.com/rancher/ui/pull/481

**Comment by tfiduccia** [comment]
Version - master UI version 0.91.0
Verified fixed
