### ISSUE TITLE
Shared Label Causes Pods to Show Under Another Deployment in the Cluster Explorer UI 

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/rancher#36810]
**Rancher Server Setup**
- Rancher version: 2.6-head 3df76e4
- Installation option (Docker install/Helm Chart): docker install 
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc):
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version: v1.21.10+rke2r1
- Cluster Type (Local/Downstream):
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider):  Infrastructure Provider, Digital Ocean

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
  - If custom, define the set of permissions: Admin

   
**Describe the bug**

The label `upgrade.cattle.io/controller: system-upgrade-controller` is shared by the pods of the deployment `system-upgrade-controller` and the job `apply-system-agent-upgrader-on-xxx`, and is used as the selector in the deployment.  As the result, the pod for the job shows under the deployment. 

**To Reproduce**

- create an RKE2 cluster 

**Result**
The pods for the job show under the deployment. 

**Expected Result**

The pods for the job should not show under the deployment. 

**Screenshots**

![screencapture-165-232-129-73-dashboard-c-c-m-5nx6t9w6-explorer-apps-deployment-cattle-system-system-upgrade-controller-2022-03-08-17_25_36](https://user-images.githubusercontent.com/6218999/157350103-46a9427f-0c35-499c-bf6d-9f7c032c5f3f.png)

**Additional context**

This issue does not see in the old UI
<img width="1425" alt="image" src="https://user-images.githubusercontent.com/6218999/157350522-ce02ea8d-2227-4416-a8c6-50a1954a6c57.png">

**Comment by paynejacob** [comment]
This issue is in the system upgrade controller.  The job selectors need to be more specific to prevent collisions like this.

**Comment by HarrisonWAffel** [comment]
I could not reproduce this issue on 2.6 head (851ff2f401b2c932869407cb75751806bae72776).

Screenshots:

Deployment list is empty 
![Screen Shot 2022-04-11 at 12 37 57 PM](https://user-images.githubusercontent.com/25062254/162791220-84cf65d1-22f0-4936-a188-455e8045ce66.png)

System Upgrade Controller pod is running 
![Screen Shot 2022-04-11 at 12 37 48 PM](https://user-images.githubusercontent.com/25062254/162791961-082836eb-f106-4ae2-a8ab-b4bbd5d707fc.png)


However, the cluster dashboard does show 9 deployments (even though the list is empty when clicked on)
![Screen Shot 2022-04-11 at 12 41 17 PM](https://user-images.githubusercontent.com/25062254/162791990-05a16a39-3c06-4968-83b7-682a9901578e.png)

**Comment by markusewalker** [comment]
Reproduced this on v2.6-head https://github.com/rancher/rancher/commit/6c12bee2d0bee16a2854df5471aaa0cdee5b9bf1.

Repro Steps:

1. Created RKE2 cluster, `v1.21.10+rke2r1` (1 server, 1 agent, but only server node should be sufficient).
2. Imported into Rancher.
3. Navigated to Cluster Management > click imported cluster's ellipses > edit config.
4. Update `Kubernetes Version` to  `v1.22.8+rke2r1`.
5. Navigated to Rancher Menu > clicked imported cluster > Workload > Deployments > system-upgrade-controller. Noted the following:
6. 
![image](https://user-images.githubusercontent.com/52591819/163888579-1be10df8-2554-4982-9eb9-988353d63caf.png)

Interestingly, after some time passed and I happened to refresh the page, it went away and I see the following:

![image](https://user-images.githubusercontent.com/52591819/163888650-6a2d7cb1-5d01-4479-9a53-0e2e9cbf740c.png)

Testing this workflow once more but will do a hard refresh to ensure this is not a caching issue. I will comment back once I finish...

**Comment by markusewalker** [comment]
Verified this is not a caching issues. After 17 minutes, both of my jobs disappeared and I now only see the following:

![image](https://user-images.githubusercontent.com/52591819/163891152-ad6b3a84-4974-4158-a277-bcce96375657.png)

**Comment by markusewalker** [comment]
Further testing this, I see that provisioning a downstream cluster via Rancher UI more accurately captures the original reported bug. Details below:

Reproduced this on v2.6-head https://github.com/rancher/rancher/commit/6c12bee2d0bee16a2854df5471aaa0cdee5b9bf1.

Repro Steps:

1. Provisioned downstream RKE2 cluster via Rancher UI, `v1.21.11+rke2r1`.
2. Navigated to Rancher menu > provisioned cluster > Workload > Deployments > `system-upgrade-controller`. Noted the following:

![image](https://user-images.githubusercontent.com/52591819/164046627-f474d9bd-a553-4167-856c-e0584d52b8e5.png)

However, just like the above-mentioned [comment](https://github.com/rancher/rancher/issues/36810#issuecomment-1101825618), after around 17 minutes, the SUC jobs disappear:

![image](https://user-images.githubusercontent.com/52591819/164046801-779d3c11-fb89-4520-96a9-209e6e3f4def.png)

Verified that this exact same behavior occurs on `v1.22.8+rke2r1` as well.

**Comment by snasovich** [comment]
Moving to 2.6.6 based on the current timeline.

**Comment by HarrisonWAffel** [comment]
@markusewalker Yes, I think system-charts might need a bump, this is why the task was not yet moved to `to-test`. I will look into this today.

**Comment by HarrisonWAffel** [comment]
### Root cause
  The system-upgrade-controller deployment shared a label with the job created by the system-upgrade-controller. This resulted in both items being show in the `Deployment` section of the UI. 
### What was fixed, or what changes have occurred
  The system-upgrade-controller deployment has had an extra label added to it to create a narrower scope and ensure that jobs do not appear in the `Deployments` section of the UI.
### Areas or cases that should be tested
  After creating a downstream cluster, go to the `Workloads` section and find the system-upgrade-controller deployment. Ensure that only the system-upgrade-controller is present in the UI. 
### What areas could experience regressions?
system-upgrade-controllers appearance in the UI

**Comment by markusewalker** [comment]
Still reproducing this on `v2.6-head` https://github.com/rancher/rancher/commit/e93864b3364e18e81dfd5c12366206f2d495cf52.

**ENVIRONMENT**
- Rancher HA
- Rancher version: `v2.6-head` https://github.com/rancher/rancher/commit/e93864b3364e18e81dfd5c12366206f2d495cf52
- Cluster version:`v1.23.6+rke2r2`
- Browser: Chrome

**REPRODUCED STEPS**
1. Setup Rancher and navigate to the UI in a browser.
2. Create standard user and login to Rancher as that user.
3. Created a downstream EC2 node driver cluster, version `v1.23.6+rke2r2`.
4. After successful cluster provisioning, navigate to Cluster Explorer > created cluster > Workloads > Deployments.
5. Make sure you filter to `All Namespaces` and click deployment `system-upgrade-controller`. You'll see the following:
![image](https://user-images.githubusercontent.com/52591819/170555978-b8908f75-9ecb-408e-9893-c5c28d98a710.png)
6. After waiting ~16 minutes, then the jobs will go away and you only see the pod as expected.

**Comment by HarrisonWAffel** [comment]
Unfortunately the changes made to resolve this issue prevent the proper downgrading of a rancher server, as mentioned in https://github.com/rancher/rancher/issues/38501. I'm re-opening this issue and reassigning the milestone to `2.7.0`

**Comment by HarrisonWAffel** [comment]
Unfortunately I cannot determine an alternate solution to this issue. While changing the deployment for the system-upgrade-controller to add a new label does resolve the issue, it unfortunately breaks backup-restore operations. I don't believe there is a way for the UI team to address this, the explore page simply displays what the cluster providers and does not have additional logic for filtering out specific elements / jobs. Because this is not an issue surfaced by a customer, and because it does not have any functional effects on the cluster, I am going to close this ticket out. We can reopen it if we absolutely need to introduce the change into the SUC.
