### ISSUE TITLE
kubernetes 1.22 conflicts with system-library-rancher-monitoring, cluster is in error state

### ISSUE THREAD

**Issue by materemias** [rancher/rancher#37039]
**Rancher Server Setup**
- Rancher version: v2.6.3-patch2
- Installation option (Docker install/Helm Chart): Docker

**Information about the Cluster**
- Kubernetes version: v1.22.6-gke.300
- Cluster Type (Local/Downstream): Hosted, gke

**User Information**
- What is the role of the user logged in? Admin

   
**Describe the bug**
my 1.22.6-gke.300 cluster is in error state since upgrading from v2.5 to rancher v2.6, stating
`Template system-library-rancher-monitoring incompatible with rancher version or cluster's [c-ab123] kubernetes version`
legacy monitoring is disabled on all projects and the cluster, alerts, alert groups and notifiers are all deleted, `cattle-prometheus` namespace is deleted. `system-library` chart is on branch `release-v2.6`

Rancher logs show
`[ERROR] error syncing 'system-library': handler system-image-upgrade-catalog-controller: upgrade cluster c-ab123 system service alerting failed: template system-library-rancher-monitoring incompatible with rancher version or cluster's [c-ab123] kubernetes version, requeuing`

**Comment by materemias** [comment]
things are unchanged on v2.6.4

**Comment by tarakanof** [comment]
Have exactly the same problem with upgrading docker version of rancher from 2.5.12 to 2.6.4
`2022/04/07 07:06:01 [ERROR] error syncing 'system-library': handler system-image-upgrade-catalog-controller: upgrade cluster local system service alerting failed: template system-library-rancher-monitoring incompatible with rancher version or cluster's [local] kubernetes version, requeuing
W0407 07:06:53.762722      56 transport.go:288] Unable to cancel request for *client.addQuery
2022/04/07 07:08:02 [ERROR] error syncing 'system-library': handler system-image-upgrade-catalog-controller: upgrade cluster local system service alerting failed: template system-library-rancher-monitoring incompatible with rancher version or cluster's [local] kubernetes version, requeuing`

**Comment by immanuelfodor** [comment]
Same here

**Comment by jaccoh** [comment]
same here

**Comment by vzaicevs** [comment]
Same here

**Comment by alex-s-team** [comment]
same same, rancher version 2.6.4 (upgrade from 2.6.2)

**Comment by abalhamoud** [comment]
has anyone been able to fix this issue? 
I am on version 2.6.4

**Comment by vj6** [comment]
`2.6.4` facing the same issue.

**Comment by Hitesh-Agrawal** [comment]
Any update on this , we are facing the same issue.

**Comment by guiguetmarcelo** [comment]
Same here (2.6.4)

**Comment by mshivanna** [comment]
2.6.4 we also go hit by this 🐛

**Comment by onpaws** [comment]
Sorry to add to the noise, wanted to ask if you guys are on the Docker image also? Or the Helm chart?.
I'm getting it on the Docker image, also v2.6.4.

```
2022/04/20 12:34:57 [INFO] Creating clusterRoleBinding User u-mo773yttt4 Role cluster-owner
2022/04/20 12:35:05 [ERROR] error syncing 'system-library': handler system-image-upgrade-catalog-controller: upgrade cluster local system service alerting failed: template system-library-rancher-monitoring incompatible with rancher version or cluster's [local] kubernetes version, requeuing
```

Not sure how urgent/serious it truly is, does anyone have insight?

**Comment by txj-xyz** [comment]
Same issue arising after going from 2.6.2 to 2.6.4

**Comment by mshivanna** [comment]
@onpaws  we are using single instance docker image

**Comment by txj-xyz** [comment]
The default catalogs are causing the issue, when you refresh manually the catalog in Rancher, the error pops up, this ONLY happens when you upgrade to 2.6.4

**Comment by mshivanna** [comment]
@txj-xyz you may be right but the error persists on restart too

**Comment by jaccoh** [comment]
We are also at 2.6.4 fyi

**Comment by karlrenaut** [comment]
I'm on 2.6.4 and I'm getting the same issue.

**Comment by danielfrancora** [comment]
Same issue here. Followed the documentation (https://rancher.com/docs/rancher/v2.5/en/installation/other-installation-methods/single-node-docker/single-node-upgrades/) to upgrade from 2.5.8 to 2.6.4 with owned CA certificate.

`2022/04/25 13:54:25 [ERROR] error syncing 'local/p-vw8js': handler system-image-upgrade-controller: upgrade cluster local system service alerting failed: template system-library-rancher-monitoring incompatible with rancher version or cluster's [local] kubernetes version, requeuing
2022/04/25 13:54:27 [INFO] Handling backend connection request [c-hwkfv:m-03bd5c964572]
2022/04/25 13:54:27 [INFO] error in remotedialer server [400]: websocket: close 1006 (abnormal closure): unexpected EOF
2022/04/25 13:54:37 [INFO] Handling backend connection request [c-hwkfv:m-03bd5c964572]
2022/04/25 13:54:37 [INFO] error in remotedialer server [400]: websocket: close 1006 (abnormal closure): unexpected EOF`

**Comment by txj-xyz** [comment]
I am now getting thousands of these errors every second, can someone please inform me if I missed a step during the upgrade process or if this is a true bug?

Should I roll back our production system?

**Comment by txj-xyz** [comment]
![image](https://user-images.githubusercontent.com/7461476/165793307-d9cec8f3-76aa-4404-bbf3-3fa2dcce8525.png)

**Comment by jaccoh** [comment]
That's a different issue. This isn't the correct place to get support honestly either.

**Comment by txj-xyz** [comment]
I was directed here for this specifically from the slack.

I will go elsewhere.

**Comment by groucho64738** [comment]
same here. issue is exactly as described, rancher 2.6.4 + k8s 1.22, helm installation

**Comment by phoenix-bjoern** [comment]
Can be still reproduced in rancher 2.6.5.

**Comment by strowi** [comment]
Same with an imported cluster in Rancher 2.6.5. Since downgrading the cluster is not an option right now - how can i get the cluster out of the error state?

`Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.6+k3s1", GitCommit:"418c3fa858b69b12b9cefbcff0526f666a6236b9", GitTreeState:"clean", BuildDate:"2022-04-28T22:16:18Z", GoVersion:"go1.17.5", Compiler:"gc", Platform:"linux/amd64"}`

**Comment by M4rku5D** [comment]
Hi we also faced this problem right yesterday on Rancher 2.6.5 after upgrade to k8s-Version 1.22.9 but we updated from 1.20.15 to 1.22.9. Downgrading is also not an option now. Monitoring seems to be usable right now.

maybe you ve an advice for us how to fix this error message
thx

**Comment by acidicX** [comment]
same here after upgrading RKE to `1.3.11` and kubernetes to the new default `v1.23.6-rancher1-1`, rancher (both `2.6.4` and `2.6.5`) keeps crashing. I had to use RKE etcd snapshot restore to get out of the error state.

**Comment by theelog** [comment]
> Hi we also faced this problem right yesterday on Rancher 2.6.5 after upgrade to k8s-Version 1.22.9 but we updated from 1.20.15 to 1.22.9. Downgrading is also not an option now. Monitoring seems to be usable right now.
> 
> maybe you ve an advice for us how to fix this error message thx

We experience the same issues even on 1.20.15.

**Comment by christianrolle** [comment]
Are there any news on this?

**Comment by jloisel** [comment]
Same here.

**Comment by txj-xyz** [comment]
Still having the same issue

**Comment by truztee** [comment]
we have bumped into this issue, and cannot go through the loading scene. Any ways to mitigate this issue?

**Comment by alex-s-team** [comment]
since this topic does not seem to gain any traction, is there anything, a workaround maybe, a manual update, that can be done to mitigate this?

**Comment by jordanburke** [comment]
My clusters are still functional with this problem, but I'd like to resolve this error somehow. Any progress on this? Thanks.

**Comment by jaccoh** [comment]
This is because somehow (in your template or manually) you still have v1 monitoring enabled in your cluster. Set                           "enable_cluster_alerting: false" and "enable_cluster_monitoring: false" in your RKE template. Also check this marvelous script: https://github.com/bashofmann/rancher-monitoring-v1-to-v2#check-why-monitoring-v1-is-not-disabled

**Comment by materemias** [comment]
I for one definitely cleaned up monitoring v1 before, running the script mentioned in the previous comment also produced this output:
`The Monitoring V1 operator does not appear to exist in cluster c-12345. Migration to Monitoring V2 should be possible.`

**Comment by alex-s-team** [comment]
the script tells me

`The Monitoring V1 operator does not appear to exist in cluster *******. Migration to Monitoring V2 should be possible.`

enable_cluster_alerting: false
and
enable_cluster_monitoring: false

both are set.

the error still exists

**Comment by h0jeZvgoxFepBQ2C** [comment]
Same problem here.

**Comment by h0jeZvgoxFepBQ2C** [comment]
I tried to upgrade to 2.6.6 from 2.6.2.

**Comment by h0jeZvgoxFepBQ2C** [comment]
Did anyone find a solution on how to fix this? the mentioned script doesn't work for us?

**Comment by angusfz** [comment]
Same issue here
Rancher: `v2.6.6`
Kubernetes:  `v1.23.6`
```
[Error] template system-library-rancher-monitoring incompatible with rancher version or cluster's [c-glr99] kubernetes version
```

**Comment by chri4774** [comment]
We had the same problem and found a workaround until someone at rancher will foix this:

In the local cluster where rancher is running: 
1. Make a backup of catalogtemplates/system-library-rancher-monitoring ressource
`kubectl get catalogtemplates system-library-rancher-monitoring -n cattle-global-data -o yaml > system-library-rancher-monitoring.yaml`
2. Edit the catalogtemplates/system-library-rancher-monitoring ressource
`kubectl edit catalogtemplates system-library-rancher-monitoring -n cattle-global-data`

In the first list item under "spec.versions" edit the "kubeVersion: < 1.22.0-0" to something that matches your kubernetes version. We have set "kubeVersion: '>=1.21.0-0'"

Before
```
apiVersion: management.cattle.io/v3
kind: CatalogTemplate
metadata:
  creationTimestamp: "2021-08-05T07:15:46Z"
  generation: 4
  labels:
    catalog.cattle.io/name: system-library
  name: system-library-rancher-monitoring
  namespace: cattle-global-data
  resourceVersion: "183697747"
  uid: b68405eb-3973-4baa-b887-6f973ad3dc61
spec:
  catalogId: system-library
  defaultVersion: 0.3.2
  description: Provides monitoring for Kubernetes which is maintained by Rancher 2.
  displayName: rancher-monitoring
  folderName: rancher-monitoring
  icon: https://coreos.com/sites/default/files/inline-images/Overview-prometheus_0.png
  projectURL: https://github.com/coreos/prometheus-operator
  versions:
  - digest: 08fbaee28d5a0efb79db02d9372629e2
    externalId: catalog://?catalog=system-library&template=rancher-monitoring&version=0.3.2
    kubeVersion: < 1.22.0-0
    rancherMinVersion: 2.6.1-alpha1
    version: 0.3.2
    versionDir: charts/rancher-monitoring/v0.3.2
    versionName: rancher-monitoring
...
```

After
```
apiVersion: management.cattle.io/v3
kind: CatalogTemplate
metadata:
  creationTimestamp: "2021-08-05T07:15:46Z"
  generation: 4
  labels:
    catalog.cattle.io/name: system-library
  name: system-library-rancher-monitoring
  namespace: cattle-global-data
  resourceVersion: "183697747"
  uid: b68405eb-3973-4baa-b887-6f973ad3dc61
spec:
  catalogId: system-library
  defaultVersion: 0.3.2
  description: Provides monitoring for Kubernetes which is maintained by Rancher 2.
  displayName: rancher-monitoring
  folderName: rancher-monitoring
  icon: https://coreos.com/sites/default/files/inline-images/Overview-prometheus_0.png
  projectURL: https://github.com/coreos/prometheus-operator
  versions:
  - digest: 08fbaee28d5a0efb79db02d9372629e2
    externalId: catalog://?catalog=system-library&template=rancher-monitoring&version=0.3.2
    kubeVersion: '>=1.21.0-0'
    rancherMinVersion: 2.6.1-alpha1
    version: 0.3.2
    versionDir: charts/rancher-monitoring/v0.3.2
    versionName: rancher-monitoring
...
```

After editing this ressource the error messages have stopped immediately.

**Comment by txj-xyz** [comment]
What a legend, thank you so much!! @chri4774

**Comment by h0jeZvgoxFepBQ2C** [comment]
Thank you so much, this fixed it for me! @chri4774

**Comment by materemias** [comment]
thanks @chri4774 for the tip, indeed logs are gone with this tweak, but I still have this error state on my 1.22 cluster, could you get this gone as well?
![image](https://user-images.githubusercontent.com/529994/177935184-2e03139a-f06a-4e26-9820-c9d000500f2b.png)

**Comment by chri4774** [comment]
Hi @materemias 
I'm sorry, we didn't have this error message. The cluster state in rancher was always ok for us. 
Maybe try to restart the cattle-cluster agent pods (namespace cattle-system) in your downstream cluster. We had some strange errors with Rancher in the past and restarting those pods seemed to help in some of those situations. But that's just a speculation.

**Comment by tomhouweling1987** [comment]
@chri4774 have the same issue. Restarted the cluster agent pods but still got the error state.
<img width="840" alt="Screenshot 2022-07-08 at 11 07 25" src="https://user-images.githubusercontent.com/45419572/177958665-ac5e1283-3f32-44f4-b224-7485644a8a89.png">

**Comment by materemias** [comment]
thanks for the fast reply @chri4774 , unfortunately it did not change anything.

**Comment by chri4774** [comment]
@tomhouweling1987 
I'm sorry then I'm afraid I can't help you.  We never had an error like this in the Rancher UI, only in the logfiles.

**Comment by carlomontanari** [comment]
I was able to get rid of the error in the dashboard by editing the cluster resource (kubectl edit clusters.management.cattle.io c-*****) and simply removing the error entry from .status.conditions

**Comment by alex-s-team** [comment]
@materemias i tried your solution, now i have a different error:

`Unknown error: Operation cannot be fulfilled on preferences.management.cattle.io "cluster": the object has been modified; please apply your changes to the latest version and try again`

which seems about right, as i have modified the object. how can i tell rancher to apply his preferences to the latest version of the object?

as i see this the management cluster is not operational in this state.

**Comment by courcelm** [comment]
Affected by the same issue on Rancher 2.6.7 migrating from 1.21 to 1.22.

**Comment by user173193** [comment]
I'm having the same issue. I'm using Rancher 2.6.7 and I've upgraded my Kubernetes to v1.23.8.

**Comment by matthewalanpenning** [comment]
I was able to fix my same issue by disabling the legacy feature and restarting rancher. The option is located in Global settings -> Feature flags. After disabling it, the errors continue to populate the logs until Rancher is restarted.

**Comment by MKlimuszka** [comment]
Monitoring v1 and Logging v1 is not supported on any K8s version above 1.21. Closing this ticket.

**Comment by materemias** [comment]
Dear @MKlimuszka please consider reopening the case since the original issue reporting clearly claims that `legacy monitoring is disabled on all projects on the cluster, alerts, alert groups and notifiers are all deleted` so the issue is not that Monitoring and logging v1 is not supported any more above 1.21, but that although they are all turned off an error is still logged on dashboard
![image](https://user-images.githubusercontent.com/529994/195302854-0b4de741-0b35-4d43-bd17-b903b751615c.png)

**Comment by materemias** [comment]
![image](https://user-images.githubusercontent.com/529994/195322198-c1fee582-28e4-4ff1-9848-f3cd6fb2730b.png)
I have found this in the Cluster resource's conditions array, my bet is that during migration this error message was generated and not cleaned up since. is there a way to get rid of this condition? I cannot edit that yaml, `kubectl get clusters.management.cattle.io` only returns `local`

**Comment by gizmotronic** [comment]
This should not have been closed. One of the problems is that a message is being logged over and over about something that we don't care about, precisely because it isn't supported. It's still happening on my Rancher 2.6.9 instance. This started its life on 2.3.x and never had monitoring V1 enabled. The other problem has a separate ticket as noted above.

**Comment by jonathon2nd** [comment]
Question.

If we have legacy disabled, and nothing is installed with legacy apps anymore on latest rancher, can we delete catalogs? That seems to be where this problem is rooted in. 
![image](https://user-images.githubusercontent.com/52681917/201712624-9ad57eb7-d9d9-4ea9-9c13-5d468159a551.png)
![image](https://user-images.githubusercontent.com/52681917/201712665-e3eeed5f-7d37-4972-9124-8db2282f9683.png)
![image](https://user-images.githubusercontent.com/52681917/201712714-471c0da2-874f-4a4e-bcd6-8b3e9d2b48a2.png)

It seems lke we have moved away from catalogs to cluster tools
![image](https://user-images.githubusercontent.com/52681917/201712927-49ac7540-643a-46bc-92a2-bf036915681b.png)
And repositories
![image](https://user-images.githubusercontent.com/52681917/201712984-8c0edfb1-f62f-453f-8a87-17c9622db971.png)

for the local Rancher cluster, is that right?

**Comment by jonathon2nd** [comment]
LMAO

```
2022/11/14 23:13:44 [ERROR] error syncing 'local/p-smfgt': handler system-image-upgrade-controller: upgrade cluster local system service alerting failed: template system-library-rancher-monitoring incompatible with rancher version or cluster's [local] kubernetes version, requeuing
--
Mon, Nov 14 2022 4:13:46 pm | 2022/11/14 23:13:46 [ERROR] error syncing 'local/p-k9jrr': handler system-image-upgrade-controller: upgrade cluster local system service alerting failed: template system-library-rancher-monitoring incompatible with rancher version or cluster's [local] kubernetes version, requeuing
Mon, Nov 14 2022 4:13:46 pm | 2022/11/14 23:13:46 [ERROR] error syncing 'local/p-7v444': handler system-image-upgrade-controller: upgrade cluster local system service alerting failed: template system-library-rancher-monitoring incompatible with rancher version or cluster's [local] kubernetes version, requeuing
Mon, Nov 14 2022 4:15:44 pm | 2022/11/14 23:15:44 [ERROR] error syncing 'local/p-smfgt': handler system-image-upgrade-controller: upgrade cluster local system service alerting failed: get template cattle-global-data:system-library-rancher-monitoring failed, catalogtemplates.management.cattle.io "cattle-global-data/system-library-rancher-monitoring" not found, requeuing
Mon, Nov 14 2022 4:15:46 pm | 2022/11/14 23:15:46 [ERROR] error syncing 'local/p-k9jrr': handler system-image-upgrade-controller: upgrade cluster local system service alerting failed: get template cattle-global-data:system-library-rancher-monitoring failed, catalogtemplates.management.cattle.io "cattle-global-data/system-library-rancher-monitoring" not found, requeuing
Mon, Nov 14 2022 4:15:46 pm | 2022/11/14 23:15:46 [ERROR] error syncing 'local/p-7v444': handler system-image-upgrade-controller: upgrade cluster local system service alerting failed: get template cattle-global-data:system-library-rancher-monitoring failed, catalogtemplates.management.cattle.io "cattle-global-data/system-library-rancher-monitoring" not found, requeuing
```

That's what you get for deleting old catalog: https://github.com/rancher/system-charts/tree/dev-v2.7/charts

**Comment by jonathon2nd** [comment]
So weird. Created a new project and it instantly got added to the spamming logs. Was hoping I could create a new project and migrate all namespaces, nope.

**Comment by kingyzf** [comment]
After Upgrade K8S from 1.19 to 1.23.12,and rancher from 2.6.5 to 2.7.0，Cluster is in Error State；Then I Modified clusters.management.cattle.io，Cluster State became active for seconds，then turn into error state again；I tried to turn off  Monitor v1，and installed Monitor V2, not helping;
The state of  Cluster.fleet.cattle.io of this cluster is Wait Applied

**Comment by aiyengar2** [comment]
Apologies to our users on the delay getting some resolution on this issue! We're working on it 😄 

Putting a brief summary on this ticket as I'm working on it since there are many comments and I want to make sure any additional scenarios that are not addressed by the below summary are commented (so that we can make sure they are also tested).

## Summary

On turning on legacy feature flag (as identified correctly in https://github.com/rancher/rancher/issues/37039#issuecomment-1264359510, thank you @matthewalanpenning), users are seeing the following logs:

```log
2022/12/14 21:53:54 [ERROR] error syncing '${SOMETHING}': handler ${HANDLER}: ${SOME_ERROR}: template system-library-rancher-monitoring incompatible with rancher version or cluster's [${CLUSTER}] kubernetes version, requeuing
```

## Steps to Reproduce:
- Create a Rancher local cluster at any version not supported by Monitoring V1 (i.e. 1.22+)
- Turn on the Legacy feature flag on the Rancher UI
- Look at Rancher logs

### Outcome:
At minimum, you will see the errors identified by the `${HANDLER}` being `system-image-upgrade-controller` or `system-image-upgrade-catalog-controller`.

## Resolution:
As analyzed accurately in https://github.com/rancher/rancher/issues/37039#issuecomment-1349051136 (thank you @raphaelzoellner), areas of the Rancher code that make a call to https://github.com/rancher/rancher/blob/v2.6.8/pkg/catalog/manager/manager.go#L318 need to be modified to ensure that they don't create spammy logs **unless expected to** (for example, if you try to enable Monitoring V1 / Alerting V1 in a 1.22+ cluster).

As suggested, the first fix seems to be around the code in the alerting service in the systemimage controller (`system-image-upgrade-controller` or `system-image-upgrade-catalog-controller`), which I will look into a fix for!

## Final Note

**If there are any other fixes that users have encountered around different handlers, please comment below so I can keep track of any more fixes that may be necessary to fix this issue (or reproduce it in a more complex environment)!**

**Comment by aiyengar2** [comment]
## Investigation

There seems to be six handlers that can trigger this type of error:
- `cluster-alert-rule-deployer` / `cluster-alert-group-deployer` / `project-alert-rule-deployer` / `project-alert-group-deployer`: this is triggered on trying to enable Monitoring V1 on a cluster that doesn't have a compatible version to deploy. **This error is valid; it should be triggered until the user stops trying to deploy the chart.**
  - All are triggered by the following code: https://github.com/rancher/rancher/blob/a2ef50b5d9519e19df9256685d3f661636da8504/pkg/controllers/managementuserlegacy/alert/deployer/deployer.go#L341-L344
- `system-image-upgrade-controller` / `system-image-upgrade-catalog-controller`: as indicated above, this is triggered on enabling the Legacy feature. **This error should not be emitted if the v.Upgrade fails.**
  - Both are triggered by the following code: https://github.com/rancher/rancher/blob/a2ef50b5d9519e19df9256685d3f661636da8504/pkg/controllers/managementuserlegacy/systemimage/systemimage.go#L72-L75
  - The Upgrade on each of the underlying System Services is what actually makes the call
    - Underlying system services in 2.7: https://github.com/rancher/rancher/blob/a2ef50b5d9519e19df9256685d3f661636da8504/pkg/controllers/managementuserlegacy/systemimage/systemimage.go#L115-L119
    - Underlying system services in 2.6: https://github.com/rancher/rancher/blob/3f0519d41fff0561e37661ea5767a929869f7461/pkg/controllers/managementuserlegacy/systemimage/systemimage.go#L117-L123
    - Of these services, **the alerting and logging services upgrade implementations are what make this issue appear**, although logging has not appeared on a user environment yet since the latest Logging V1 chart has no upper kubeVersion limit (see [this](https://github.com/rancher/system-charts/blob/d3720d22f2f49ee8603d5e4f94109585bbda3c47/charts/rancher-logging/0.4.0/Chart.yaml#L13)), unlike the Monitoring chart (see [this](https://github.com/rancher/system-charts/blob/d3720d22f2f49ee8603d5e4f94109585bbda3c47/charts/rancher-monitoring/v0.3.2/Chart.yaml#L12)) 
    - Alerting implementation: https://github.com/rancher/rancher/blob/3f0519d41fff0561e37661ea5767a929869f7461/pkg/controllers/managementuserlegacy/alert/deployer/upgradeimpl.go#L95-L98
    - Logging implementation: https://github.com/rancher/rancher/blob/3f0519d41fff0561e37661ea5767a929869f7461/pkg/controllers/managementuserlegacy/logging/deployer/upgradeimpl.go#L79-L82

**Comment by aiyengar2** [comment]
> We think we would need a way to remove the alerting service from the system service map to not run into the error.
Would only adding the alerting service to the system services when enableClusterAlerting is set to true for the corresponding cluster solve the problem?

@raphaelzoellner Rather than trying to remove the systemService, which may be more complicated, I think it might make sense to modify the returned error to instead return a typed error:

https://github.com/rancher/rancher/blob/3f0519d41fff0561e37661ea5767a929869f7461/pkg/catalog/manager/manager.go#L318

That way, we could just do a check in `v.Upgrade` to check if the error is of the underlying type, in which case we'd omit it from the `versionMap`.

**Comment by aiyengar2** [comment]
Original PR that has the context on why this behavior was introduced: https://github.com/rancher/rancher/pull/14883

Relevant comment on intention of this controller: https://github.com/rancher/rancher/pull/14883#issuecomment-417343237

**Comment by samjustus** [comment]
@ronhorton  can you please see if SURE-5427 is resolved by this issue? Kevin thinks it is a symptom.

**Comment by 631068264** [comment]
rancher 2.6.5  docker run

```
Template system-library-rancher-monitoring incompatible with rancher version or cluster's [local] kubernetes version
```

https://github.com/rancher/rancher/issues/27678#issuecomment-1173626803

**Comment by ronhorton** [comment]
@samjustus yes, the fix for this issue will eliminate the log messages indicated in SURE-5427

**Comment by lkjangir** [comment]
same issue in 2.7 also

**Comment by ronhorton** [comment]
No longer seeing this error message in `2.6-head commit ID bf54d7b`
tested with gke cluster k8s 1.22; enabled and disabled the legacy flag; installed apps (monitoring, logging); no occurrence of log message in rancher logs.

**Comment by qRainBirdp** [comment]
Still having the same issue on 2.6.10
2023/01/30 04:52:02 [ERROR] error syncing 'local/p-x88fv': handler system-image-upgrade-controller: upgrade cluster local system service alerting failed: template system-library-rancher-monitoring incompatible with rancher version or cluster's [local] kubernetes version, requeuing

**Comment by 631068264** [comment]
In my case

finally  I  edit the **clusters.management.cattle.io**  cr  del  err  in  **conditions**， because  even I uninstall system-monitor ,  the error still here.   

I read the code and  some params in `kubectl edit catalogtemplates system-library-rancher-monitoring -n cattle-global-data`  , it's impossible get error ,   so I have to edit the cr
```go
func (m *Manager) LatestAvailableTemplateVersion(template *v3.CatalogTemplate, clusterName string) (*v32.TemplateVersionSpec, error) {
	versions := template.DeepCopy().Spec.Versions
	if len(versions) == 0 {
		return nil, errors.New("empty catalog template version list")
	}

	sort.Slice(versions, func(i, j int) bool {
		val1, err := semver.ParseTolerant(versions[i].Version)
		if err != nil {
			return false
		}

		val2, err := semver.ParseTolerant(versions[j].Version)
		if err != nil {
			return false
		}

		return val2.LT(val1)
	})

	for _, templateVersion := range versions {
		catalogTemplateVersion := &v3.CatalogTemplateVersion{
			Spec: templateVersion,
		}

		if err := m.ValidateChartCompatibility(catalogTemplateVersion, clusterName, ""); err == nil {
			return &templateVersion, nil
		}
	}

	return nil, errors.Errorf("template %s incompatible with rancher version or cluster's [%s] kubernetes version", template.Name, clusterName)
}
```

**Comment by qRainBirdp** [comment]
Thank you for your replay.
We have decided to ignore this error for now If it won't make a bigger impact. We will continue to observe in the test environment for some time.

I can only hope that this issue will be completely fixed in the future.


雨鳥
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "rancher/rancher"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年1月30日(星期一) 下午5:04
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [rancher/rancher] kubernetes 1.22 conflicts with system-library-rancher-monitoring, cluster is in error state (Issue #37039)





 
In my case
 
finally  I  edit the clusters.management.cattle.io  cr  del  err  in  conditions， because  even I uninstall system-monitor ,  the error still here.
 
I read the code and  some params in kubectl edit catalogtemplates system-library-rancher-monitoring -n cattle-global-data  , it's impossible get error ,   so I have to edit the cr
 func (m *Manager) LatestAvailableTemplateVersion(template *v3.CatalogTemplate, clusterName string) (*v32.TemplateVersionSpec, error) { 	versions := template.DeepCopy().Spec.Versions 	if len(versions) == 0 { 		return nil, errors.New("empty catalog template version list") 	} 	sort.Slice(versions, func(i, j int) bool { 		val1, err := semver.ParseTolerant(versions[i].Version) 		if err != nil { 			return false 		} 		val2, err := semver.ParseTolerant(versions[j].Version) 		if err != nil { 			return false 		} 		return val2.LT(val1) 	}) 	for _, templateVersion := range versions { 		catalogTemplateVersion := &amp;v3.CatalogTemplateVersion{ 			Spec: templateVersion, 		} 		if err := m.ValidateChartCompatibility(catalogTemplateVersion, clusterName, ""); err == nil { 			return &amp;templateVersion, nil 		} 	} 	return nil, errors.Errorf("template %s incompatible with rancher version or cluster's [%s] kubernetes version", template.Name, clusterName) }

**Comment by lbudai74** [comment]
We have the same issue present in rancher 2.7.1.

**Comment by txj-xyz** [comment]
Still having the same issue as well with 781 nodes, on Rancher 2.7.1

**Comment by h0jeZvgoxFepBQ2C** [comment]
Same issue again now in 2.7.1.. come on... 🙄

**Comment by h0jeZvgoxFepBQ2C** [comment]
This solved it again for me: https://github.com/rancher/rancher/issues/37039#issuecomment-1176320933

**Comment by fengxx** [comment]
hit the same issue and since we don't need the legacy catalog feature, so I simply removed it, and no errors any more
```
kubectl get catalogs system-library -o yaml > system-library.yaml
kubectl delete -f system-library.yaml
kubectl rollout restart -n cattle-system deploy/rancher
```

**Comment by eroji** [comment]
How exactly do you clear the error in the UI after it has triggered? All the solutions I see so far only disables the error being logged. With the error triggered, the cluster is not actually selectable even though if you paste in the ID into the URL you can still access the Cluster Explorer. The cluster in question is not even using the legacy Prometheus monitoring. Running Rancher 2.7.1 and this cluster was upgraded to 1.24.10.

![image](https://user-images.githubusercontent.com/13228540/230763280-4345aa25-60aa-447e-b41f-7bbba17baaf6.png)

**Comment by vadim-morozow** [comment]
Thanks @eroji and @gmanera, that finally did the trick for me!

**Comment by Tejeev** [comment]
Are people still having issues with this?  I see a lot of comments that folks are having issues but it looks like the milestone is 2.6.11 and most folks are pre that.

**Comment by ronnie-webb** [comment]
Yes 2.7.3 still having issues with this

**Comment by eumel8** [comment]
[_] I have read all 83 comments above

The root cause of this error is the [declaration in the legacy rancher-monitoring chart](https://github.com/caas-team/system-charts/blob/dev-v2.7/charts/rancher-monitoring/v0.3.2/Chart.yaml#L12). This prevents installations on Kubernetes cluster greater then 1.22. If you don't need the V1 monitoring you should disable it in RKE1 cluster.yaml

```yaml
spec:
  enableClusterAlerting: false
  enableClusterMonitoring: false
```

Also the `system-library.catalogs.management.cattle.io` should be removed.

If you still need this stuff, you can serve your own Helm v2 catalog by fork and remove this defintion. Or you patch the catalogtemplate with `kubectl -n cattle-global-data edit catalogtemplates system-library-rancher-monitoring`

look for the defaultVersion, replace kubeVersion 1.22.0-0 with 1.26.0-0

```yaml
spec:
  catalogId: system-library
  defaultVersion: 0.3.3
  description: Provides monitoring for Kubernetes which is maintained by Rancher 2.
  displayName: rancher-monitoring
  folderName: rancher-monitoring
  icon: https://coreos.com/sites/default/files/inline-images/Overview-prometheus_0.png
  projectURL: https://github.com/coreos/prometheus-operator
  versions:
  - digest: c9c1e5c1e70f68823857df19fe423fd2
    externalId: catalog://?catalog=system-library&template=rancher-monitoring&version=0.3.3
    kubeVersion: < 1.26.0-0
...
```

cluster status should be green [x] 

after the next catalog refresh this resource might be overwritten

**Comment by ahazelwood** [comment]
I was just hit by this bug.  When I attempt the fixes documented in the issue, I was having a hard time locating the right resource to edit, until I realized I needed to perform the `kubectl edit clusters.management.cattle.io <cluster-id>` from the "local" cluster.  I hope this helps someone else who is just a newbie with rancher as well.
