### ISSUE TITLE
Link DNS doesn't appear to be working

### ISSUE THREAD

**Issue by atrauzzi** [rancher/rancher#3714]
### Rancher Version
```
v0.59.0
```

### Docker Version: 
```
Docker version 1.10.2, build c3959b1
```

### OS: 
```
Distributor ID:	Ubuntu
Description:	Ubuntu 15.10
Release:	15.10
Codename:	wily
```

### Steps to Reproduce 

_tldr; Create a container linked to another._

I have a container called `staging-webapp` which runs a php-fpm server listening on port 9000.

![image](https://cloud.githubusercontent.com/assets/115199/13374424/2d233dae-dd4a-11e5-943b-a53f7768aefe.png)

It seems to get up and running just fine.

I then have an nginx container configured to use the php-fpm container as an upstream server:

![image](https://cloud.githubusercontent.com/assets/115199/13374430/6219a084-dd4a-11e5-8be7-8426f4a7e19c.png)

Which I also configure in Rancher:

![image](https://cloud.githubusercontent.com/assets/115199/13374340/4c607ffe-dd47-11e5-8edd-b30eb9af4e07.png)

### Results

![image](https://cloud.githubusercontent.com/assets/115199/13374418/0b0b3294-dd4a-11e5-8b5a-3fd4ad9ff340.png)

My nginx container ends up failing because it can't resolve my php-fpm container by hostname:

```
27/02/2016 12:01:172016/02/27 18:01:17 [emerg] 1#1: host not found in upstream "webapp:9000" in /etc/nginx/nginx.conf:12
27/02/2016 12:01:17nginx: [emerg] host not found in upstream "webapp:9000" in /etc/nginx/nginx.conf:12
```

### Expected

My nginx container to be up and running and linked to my php-fpm container.

**Comment by atrauzzi** [comment]
Possibly related?

**Comment by atrauzzi** [comment]
Noticed that using the fix found here https://github.com/rancher/rancher/issues/2628#issuecomment-165304326 works, but unfortunately it goes against the portability of containers.  It requires me to bind-mount an alternate config (or worse: master an image specifically aware of Rancher).

It would be nice if DNS worked right away for nginx.

**Comment by haswalt** [comment]
We've found in investigation that the issue is not because the link doesn't resolve for DNS but is that it's slow to resolve. We have a small image we run that boots pretty faster, if we sleep for 30 seconds the links then resolve but before that we get no DNS resolution of linked containers.

I'm wondering now how the DNS is handled by Rancher in respect to caching and lookups? Is it possible we're having  cache issue with the DNS resolver not having the new information for the linked container when it's first requested? Or is it a race condition that the data isn't available for the link quite yet?


Our small image has a similar setup that it tries to resolve a backend connection that is linked. The link container exists and has been up for some time so it's unlikely that one container is booting before the other. We have the same issue with DNS regardless of our containers running on the same host or seperate hosts.

We're on Rancher 0.59.0.

**Comment by janeczku** [comment]
@atrauzzi Can you share the content of resolv.conf in the affected container?

**Comment by haswalt** [comment]
@janeczku I hit this again when running a small go binary inside scratch. Resolver showed up as 8.8.8.8 and 8.8.4.4 which is the docker default I believe?

**Comment by vincent99** [comment]
Containers can start executing your code before the resolv.conf is updated; that's essentially https://github.com/rancher/rancher/issues/3705, though it's not new at all.

The Rancher DNS server does not cache anything.

Using hostnames in an nginx config like this is never going to work correctly, but it has nothing to do with Rancher really.  Their default behavior is to resolve that name exactly one on startup and never again, unless you provide a resolver (as in https://github.com/rancher/rancher/issues/2628#issuecomment-165304326).  So even if it were to be available on startup and resolve correctly the first time, it would never update as target containers come and go and you'll end up sending traffic to bad/gone containers.  The only way to make nginx work is to add the resolver to the config.  Or (I think?) paying for their commercial version which has additional options.

**Comment by djmaze** [comment]
Not exactly sure our problem is related, but I'd like to mention it at least. We had problems with linked containers not coming up. Investigation showed that linked hosts could not be reached by their short names, but only via the FQDN `<servicename>.rancher.internal`.

Looking at the resolv.conf on the host, we saw that our provider supplies a `domain` value via DHCP. That setting made its way into the containers' resolv.conf, seemingly rendering Rancher's internal DNS unable to provide answers for the unqualified hostnames.

We added the following lines to our cloud config in order to solve the problem:

```
rancher:
  network:
    dns:
      override: true
      search:
        - rancher.internal
```

**Comment by janeczku** [comment]
@djmaze The missing search domain is probably this issue: https://github.com/rancher/rancher/issues/3737

**Comment by alena1108** [comment]
Should be fixed with rancher cross-stack discovery internal DNS fixes

**Comment by sangeethah** [comment]
With rancher-server version - V0.63.0 , all the required search paths are populated in container in resolv.conf

<img width="637" alt="screen shot 2016-03-14 at 12 32 07 pm" src="https://cloud.githubusercontent.com/assets/4266958/13757305/15624cfc-e9e1-11e5-90a5-bec32d21c3e1.png">

@atrauzzi , please retest with  rancher-server version - V0.63.0 which has this fix.

**Comment by atrauzzi** [comment]
Just upgraded to Rancher `v0.63.1` and I'm still experiencing this issue.  This task likely needs to be reopened.

**Comment by atrauzzi** [comment]
Also, worse still is the workaround I've been using up until now has suddenly stopped working as well:

![image](https://cloud.githubusercontent.com/assets/115199/13847571/d8da65ca-ec1b-11e5-82b8-f9d5b02ba3c6.png)
