### ISSUE TITLE
Clusters become unreachable via UI and kubectl after some times

### ISSUE THREAD

**Issue by Lebvanih** [rancher/rancher#37250]
**Rancher Server Setup**
- Rancher version: 2.6.4
- Installation option (Docker install/Helm Chart): Helm, RKE1, K8S 1.21.10

**Information about the Cluster**
- Kubernetes version: K8S 1.20.9
- Cluster Type (Local/Downstream): Downsteam, the remote cluster was provisioned using docker command. We are able to reproduce this on two different cluster.

**User Information**
- What is the role of the user logged in? Admin

**Describe the bug**
We noticed since the upgrade from 2.5.8 to 2.6.4 that our cluster would become unresponsive via the UI and via Kubectl. However, weirdly enough, if we log via the old ui (removing the /dashboard in the url and add login), we still can't see everything without issue... 

**To Reproduce**
The fastest way we found to reproduce is to spam a few times (10-15, not in parallel) the following command toward the cluster, the cluster is quite busy so we get a bunch of logs doing this:
``` kubectl logs -n ingress-nginx -f <nignx-ingress-pod>``` or ``` kubectl logs -n ingress-nginx <nignx-ingress-pod>```

**Result**
After a few attempts, it will hang, and any command via kubectl will hang (either all the time or once every 2 attempts at the start). The cluster is still displayed as connected and healthy in the UI. 

**Expected Result**
The command shouldn't hang making the interaction with the cluster impossible.
The situation never recover we are forced to kill all the rancher pod to restore the UI + kubectl.

**Additional context**
We are unsure if the kubectl logs is the reason or if it's just a quantity of data that is enough to block something in rancher.. We are wondering if we aren't in a similar case of this one where the routing that handle the forward to the cluster is blocked by a full buffer or something similar. But as the ticket is close, we aren't sure if it could be the same. https://github.com/rancher/rancher/issues/34819#issuecomment-1007600901 

We also see alot of message mentioned in this one: https://github.com/rancher/rancher/issues/36584 but we aren't sure if they are the cause of our outages.

Also note that restarting the agent on the downstream or forcing a full connection interrupt between the agents and the cluster to make them reconnect doesn't fix the issue either, only a full kill of the rancher pod fixes our issue at the moment

SURE-4484

**Comment by cambierr** [comment]
Exact same issue here....

**Comment by gray314** [comment]
the same issue.. =/
one of the three provisioned cluster become partly unavailable. not working Cluster Summary Page, external link to Longhorn UI , to Prometheus UI with proxy uRL

**Comment by netmanbworker** [comment]
I just found the issue you all created, and believe the issue I commented on/joined (https://github.com/rancher/rancher/issues/37174) is related. Do any of you notice that kubectl shell is no longer working once you've upgraded from Rancher v2.6.2 to v2.6.4? Can't use the kubectl tool from the menu bar, nor can you do "execute shell" to connect to any pods.

**Comment by klaus385** [comment]
Having the same issues as well with regards to going from 2.6.3 -> 2.6.4. But, can at least one of the downstream clusters use the kubectl from to UI.

**Comment by T-helper** [comment]
Faced with the exactly same problem few days ago, right after upgrading to 2.4.0. Non of my monitoring stack or rancher downstream cluster ui is resplonsible, as downstream cluster via kubectl. But if i do direct access to downstream cluster, or grafana ingress endpoin, everything works fine. seems like the problem related to proxy part

**Comment by rmweir** [comment]
Is anyone able to produce this from scratch starting with a new setup and a new downstream cluster? If not a new setup then at least a new cluster?

**Comment by AndreasDeCrinis** [comment]
We are also affected. Baremetal, Onprem on Ubuntu 20.04.
As mentioned above, a restart of the cluster agent does not help. Only a kill of the affected rancher pod solves the issue temporarily.

**Comment by beatsandpics** [comment]
We are also experimenting this.. but currently only on one of our down-stream clusters. 

@AndreasDeCrinis what do you mean with "affected rancher pod"? The rancher/rancher:v2.6.4 pod on the mgmt cluster?

**Comment by AndreasDeCrinis** [comment]
@beatsandpics exactly:
`kubectl rollout restart -n=cattle-system deployment rancher`

BTW it happened to us today. So ~4 days since the last restart. We set up monitoring and alerting using kube-prometheus probes to get alerted as soon as it pops up again.
this is the URL we continuously check: https://rancher.mycompany.com/k8s/clusters/<clusterid>/api?timeout=32s

**Comment by abaua** [comment]
we are facing the same problem, the described restart is also for us the only way how we could fix this temporarily.
We played a little bit around with some timeout values in the cluster where the rancher application is deployed and since we did that, we did not have this issue (around 8 days). Maybe you could also try this values and it helps you.
Here is, what we changed:

kubectl get cm -n ingress-nginx ingress-nginx-controller -o json
```
{
    "data": {
        "client-body-timeout": "120",
        "client-header-timeout": "120",
        "keep-alive": "360",
        "proxy-send-timeout": "120",
    }
}
```

If this helps in your case, please let me know

**Comment by AndreasDeCrinis** [comment]
@abaua unfortunately, increasing the timeouts did not solve it on our side. it occured again today

**Comment by justdan96** [comment]
We are seeing this issue as well, @AndreasDeCrinis did you set those annotations as well as the configmap @abaua pasted?

**Comment by T-helper** [comment]
@justdan96 @AndreasDeCrinis as i metnined above, try to do a new  backup of rancher state via rancher-backup operator, and then restore it right after that, its look dumb but it works, and  permanently fix that problem )

**Comment by justdan96** [comment]
@T-helper I'll see if we can give it a go and test that it resolves the issue.

**Comment by nickvth** [comment]
@rmweir why would we test this on new clusters? This problem is on many existing clusters. 

Unable to connect to the server: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
There are no log errors in rancher or downstream agents

Log nginx: upstream_status="-" upstream_response_time="32.000" request_uri="/k8s/clusters/[cluster]/apis?timeout=32s"

Rancher 2.6.5 and downstream clusters RKE 1.21.10 and 1.22.9

After restart rancher it's working for some time, till someone as mentioned above do:

To Reproduce
The fastest way we found to reproduce is to spam a few times (10-15, not in parallel) the following command toward the cluster, the cluster is quite busy so we get a bunch of logs doing this:
kubectl logs -n ingress-nginx -f <nignx-ingress-pod> or kubectl logs -n ingress-nginx <nignx-ingress-pod>

**Comment by cbron** [comment]
> why would we test this on new clusters? This problem is on many existing clusters with load.

@nickvth asking because we have not been able to reproduce this on the Rancher side, and it's very hard to debug without doing that. We've tried creating new downstream clusters and adding loads to them, then doing the `kubectl logs` steps, but still haven't seen this behavior. So there is some specific piece we are still missing.

**Comment by fplantinga-guida** [comment]
@cbron We can reproduce this by obtaining logs from any pod with a large amount of logs.

**Comment by justdan96** [comment]
> this is the URL we continuously check: https://rancher.mycompany.com/k8s/clusters/c-clusterid/api?timeout=32s

We just had this issue reoccur and this URL returned with "200 OK" so I'm not sure it can be consistently relied upon to test the error occurred.

**Comment by justdan96** [comment]
@fplantinga-guida Would you be able to say approximately how many log entries there are? I'm attempting to reproduce the issue on a pod with 20,000 logs but I am not able to so far.

**Comment by wd** [comment]
I think we have the same issue here. We have 3 rancher pods, one of the pods stuck at somewhere. 

I have tested with commands bellow. (pod-ip-1 is from working pods, pod-ip-2 is from stuck pod)
```
# this is working
curl -k -v -H 'Authorization: Bearer <TOKEN>' https://<pod-ip-1>/k8s/clusters/c-psxs4/apis

# this is not working
curl -k -v -H 'Authorization: Bearer <TOKEN>' https://<pod-ip-2>/k8s/clusters/c-psxs4/apis

# this is working
curl -k -v -H 'Authorization: Bearer <TOKEN>' https://<pod-ip-2>/k8s/clusters
```

**Comment by samjustus** [comment]
closed #37747 in favor of tracking via this issue.

**Comment by fplantinga-guida** [comment]
@justdan96 

We reproduce this by enabling debug log for our promtail pods. In the example below you see the api requests on the ingress controller. Steps:

1. kubectl get pod promtail-8zghf (works fine)
2. kubectl logs promtail-8zghf -f (works fine)
3. kubectl get pod promtail-8zghf (not responding, have to cancel the command)
 
```
2022-05-27 10:50:23 | (no unique labels) | upstream_status="-" request_uri="/k8s/clusters/<redacted>/api/v1/namespaces/<redacted>/pods/promtail-8zghf" request_time="95.180"
2022-05-27 10:48:39 | (no unique labels) | upstream_status="200" request_uri="/k8s/clusters/<redacted>/api/v1/namespaces/<redacted>/pods/promtail-8zghf/log" request_time="10.328"
2022-05-27 10:48:28 | (no unique labels) | upstream_status="200" request_uri="/k8s/clusters/<redacted>/api/v1/namespaces/<redacted>/pods/promtail-8zghf" request_time="0.093"
```
After this Rancher is only available via the authorized endpoint and Rancher UI. It can only be fixed by restarting the rancher deployment.

**Comment by jaimehrubiks** [comment]
I can reproduce on rancher 2.6.4, can't connect to imported clusters... (specially one of them which is in datacenter and much bigger than others)

Some facts (for this cluster, which is on kube 1.21 and built with kubeadm)

- Cluster works fine (and admin credentials work good)
- Rancher cluster main page doesn't load (c/c-rcjg6/explorer)
- But if you click anywhere else (nodes/namespaces/..., c/c-rcjg6/explorer/projectsnamespaces) it works
- And I can also click on "Kubectl shell" and **it works perfectly from the rancher web console**
- However, accessing the cluster with kube config credentials from the internet doesn't work
- It also doesn't work connecting with Curl (makes sense as i'm recreating the same queries that kubectl would do - i saw them with --v=9)
- Querying svc/rancher through kubectl port-forwarding also doesn't work.

**Comment by dwainmsims** [comment]
I am seeing this on an RKE cluster running in Azure, with the 2.6.4 Rancher node/ K3S also running in Azure.  This demo config in Azure had been working fine, I fired it up today to check it out and found my downstream RKE cluster stuck in this state, "Cluster Agent is not connected"

**Comment by justdan96** [comment]
It looks this is reproducible on 2.6.5 as well, correct?

**Comment by fplantinga-guida** [comment]
Correct, we upgraded from 2.6.2 to 2.6.5

**Comment by cbron** [comment]
Hello all, thanks for the information so far. We are trying to piece together the problem here. So far we have been unable to reproduce this on the Rancher side. Some questions to tie threads together:

* For those that see this on only some of your clusters, are there any common traits between those affected clusters ? This could be things like k8s distro, k8s version, imported vs provisioned, or cluster usage.
* Is anyone seeing this issue below k8s 1.21 ?
* Has anyone seen this issue before Rancher 2.6.4 ?
* Are people seeing high CPU usage on the downstream agent when this happens ?
* Does Rancher have high CPU or memory usage ?
* Does this only happen during high Rancher usage hours ? Meaning people updating things via Rancher or getting logs. 
Downstream workload activity shouldn't matter here.
* What do affected downstream clusters have in them. What amount of namespaces, workloads, rolebindings etc... This info we are looking for specifically to try and reproduce the bug.

**Comment by jaimehrubiks** [comment]
Last time I restarted the rancher server pods (2 days ago), it kept working fine and has not broke ever since. If it happens again I'll happily try to answer all those questions. As OP said, *maybe*, who knows, is triggered by a huge burst/spam of api calls on that cluster, so I'll try that next week.

**Comment by davidburge1** [comment]
> Hello all, thanks for the information so far. We are trying to piece together the problem here. So far we have been unable to reproduce this on the Rancher side. Some questions to tie threads together:
> 
> * For those that see this on only some of your clusters, are there any common traits between those affected clusters ? This could be things like k8s distro, k8s version, imported vs provisioned, or cluster usage.
> * Is anyone seeing this issue below k8s 1.21 ?

yes.  1.20.11

> * Has anyone seen this issue before Rancher 2.6.4 ?

No.  The issue surfaced after the upgrade to 2.6.4

> * Are people seeing high CPU usage on the downstream agent when this happens ?

No.

> * Does Rancher have high CPU or memory usage ?

No.

> * Does this only happen during high Rancher usage hours ? Meaning people updating things via Rancher or getting logs.

I think yes.  Usually find out because someone is using kubectl and starts having issues

>   Downstream workload activity shouldn't matter here.
> * What do affected downstream clusters have in them. What amount of namespaces, workloads, rolebindings etc... This info we are looking for specifically to try and reproduce the bug.

It doesn't seem to be associated with any particular cluster (we have about 40 clusters)

**Comment by EC-Sean** [comment]
I am running Rancher 2.6.5 on Kubernetes v1.22.9-eks-a64ea69, using nginx-ingress.

I have found a way to reliably reproduce the issue on my server. First I created a pod on one of my clusters that generates a large amount of logs:

```yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: snowcrash
  name: snowcrash
spec:
  replicas: 1
  selector:
    matchLabels:
      app: snowcrash
  serviceName: snowcrash
  template:
    metadata:
      labels:
        app: snowcrash
    spec:
      containers:
        - command:
            - sh
            - -c
            - while true ; do sleep 1 ; dd if=/dev/zero bs=8M count=32 | xxd -c 1048576 ; done
          image: alpine
          name: snowcrash
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "100m"
```

Next, using a kubeconfig that utilizes Rancher's auth proxy, I leave the following command running:

```bash
kubectl logs -f snowcrash-0
```

One instance of `kubectl logs` would eventually (5m?) make that cluster unreachable through the auth proxy. Running three of those in parallel would kill it in about 1-3 minutes. Restarting Rancher fixes everything. If I connect directly to the cluster instead of going through Rancher server's proxy everything works fine.

I tried `kubectl attach` through the proxy, and could run several instances of that in parallel experiencing any issues. There must be something different about `kubectl logs` that breaks things.

**Comment by jaimehrubiks** [comment]
I could replicate. It took a few minutes but then I broke the clusterk with 3 tabs using kubectl logs.

Once the cluster is broken, I tried to set rancher pods to loglevel --set trace. But I could not find any specific "error" or exception. There are of course messages I don't understand, but nothing explicit related to errors when I send a request.

**Comment by cbron** [comment]
It's much more than that when you include all the vendored repo's. Not an efficient angle to attack it from. However, we have started to be able to reproduce this in-house thanks to @EC-Sean 's comment. Still some sporadic behavior, but leaving multiple console's following a logs feed is reproducing it at least some of the time. Hope to have a better update soon. We have started to look into specific commits between 2.6.3 and 2.6.4 which we think may be causing it.

**Comment by Turb0Fly** [comment]
We are also affected by this since the upgrade to Rancher 2.6.5.  We were running 2.6.2.  We can reproduce the issue in the same way with getting logs from multiple consoles on a downstream cluster. 
Restarting the rancher pods on the Rancher cluster and then the cattle-cluster-agent pods on the downstream cluster fixes it.  For how long, no idea.
Case has been logged with SUSE support.

**Comment by justdan96** [comment]
I've done quite a bit of work replicating the issue across our clusters - can I ask what people have for their Docker logging driver maximum file size? For example we aren't able to replicate in environments with these logging options in `daemon.json`:
```
{
  "log-opts": {
    "max-size": "10m",
    "max-file": "10" 
  }
}
```

Larger values for the `max-size` seem to equate with being able to replicate the issue.

**Comment by Turb0Fly** [comment]
@justdan96 We have the same logging options for Docker in the `daemon.json` file. 
```
  "log-opts": {
     "max-size": "10m",
     "max-file": "10"
```
Yet we are affected.  I just checked in one of the clusters that had the issue and it has those values. ( in fact, all of our clusters use those values. )

**Comment by EC-Sean** [comment]
@justdan96 I do not have a `daemon.json` file. I'm running this version of docker:

```
 docker-ce | 5:20.10.8~3-0~ubuntu-bionic | https://download.docker.com/linux/ubuntu bionic/stable amd64 Packages
```

I believe the [defaults](https://docs.docker.com/config/containers/logging/local/#options) are `10m` and `3`.

**Comment by atsai1220** [comment]
The defaults depend on the logging driver. We use `json` and the default size is unlimited and file count is 1.

Unsure if this is the cause but we're configured for 100m for size and leave the rest for default.
https://docs.docker.com/config/containers/logging/json-file/

**Comment by nickvth** [comment]
Changing the logging driver settings is maybe a workaround but not a solution. Why is the max-size an issue after 2.6.4? This issue is only when you do kubectl logs over rancher api in combination with rancher cluster agent, when direct on k8s api (authorized endpoint) it’s always working and we have no issues.

**Comment by justdan96** [comment]
I just changed our logging options in an affected cluster to `10m` and `10` and are still seeing the same issue - so clearly something else is going on.

**Comment by jaimehrubiks** [comment]
The cluster were I see most of the issues is on datacenter, whereas Rancher is on AWS. Just another hint, in case latency/slowness could be a factor.

**Comment by phoenix-bjoern** [comment]
In our environment I recognized a Crashloop of the cattle-cluster-agent. You can verify it with `kubectl -n cattle-system get pods`. If you have a high number of restarts, check the logs of the pods: `kubectl -n cattle-system logs cattle-cluster-agent-7768b574c6-74jlw` (<- adjust the pod name from the previous output).

It helped to redeploy the cluster agent, but only for a few seconds: `kubectl rollout restart -n=cattle-system deployment cattle-cluster-agent`. 

This was our error trace you can retrieve with `kubectl -n cattle-system logs  cattle-cluster-agent-7768b574c6-74jlw` (<- adjust the pod name from the previous output):
```
E0614 04:55:52.712879      39 runtime.go:78] Observed a panic: runtime.boundsError{x:3, y:0, signed:true, code:0x2} (runtime error: slice bounds out of range [:3] with capacity 0)
goroutine 3461 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic({0x3cee580, 0xc033910228})
	/go/pkg/mod/k8s.io/apimachinery@v0.23.3/pkg/util/runtime/runtime.go:74 +0x7d
k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0xc01c5f2450})
	/go/pkg/mod/k8s.io/apimachinery@v0.23.3/pkg/util/runtime/runtime.go:48 +0x75
panic({0x3cee580, 0xc033910228})
	/usr/lib64/go/1.17/src/runtime/panic.go:1038 +0x215
github.com/rancher/rancher/pkg/catalogv2/helm.decodeHelm3({0x0, 0xc9d18d})
	/go/src/github.com/rancher/rancher/pkg/catalogv2/helm/helm3.go:124 +0x1b1
github.com/rancher/rancher/pkg/catalogv2/helm.fromHelm3Data({0x0, 0xc007d2be80}, 0x3fc4a54)
	/go/src/github.com/rancher/rancher/pkg/catalogv2/helm/helm3.go:23 +0x25
github.com/rancher/rancher/pkg/catalogv2/helm.ToRelease({0x47b3720, 0xc007d2be80}, 0x23)
	/go/src/github.com/rancher/rancher/pkg/catalogv2/helm/release.go:74 +0x3eb
github.com/rancher/rancher/pkg/controllers/dashboard/helm.(*appHandler).OnSecretChange(0xc00da90f50, {0xc00c33f810, 0x4f}, 0xc007d2be80)
	/go/src/github.com/rancher/rancher/pkg/controllers/dashboard/helm/apps.go:170 +0xa5
github.com/rancher/wrangler/pkg/generated/controllers/core/v1.FromSecretHandlerToHandler.func1({0xc00c33f810, 0x59f31e7551bea}, {0x47b3720, 0xc007d2be80})
	/go/pkg/mod/github.com/rancher/wrangler@v0.8.11-0.20220411195911-c2b951ab3480/pkg/generated/controllers/core/v1/secret.go:102 +0x44
github.com/rancher/lasso/pkg/controller.SharedControllerHandlerFunc.OnChange(0xc007d2be80, {0xc00c33f810, 0x400dc68}, {0x47b3720, 0xc007d2be80})
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20220412224715-5f3517291ad4/pkg/controller/sharedcontroller.go:29 +0x38
github.com/rancher/lasso/pkg/controller.(*SharedHandler).OnChange(0xc001115860, {0xc00c33f810, 0x4f}, {0x47b3720, 0xc007d2be80})
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20220412224715-5f3517291ad4/pkg/controller/sharedhandler.go:75 +0x23f
github.com/rancher/lasso/pkg/controller.(*controller).syncHandler(0xc001200f20, {0xc00c33f810, 0x4f})
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20220412224715-5f3517291ad4/pkg/controller/controller.go:220 +0x93
github.com/rancher/lasso/pkg/controller.(*controller).processSingleItem(0xc001200f20, {0x35b2e60, 0xc01c5f2450})
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20220412224715-5f3517291ad4/pkg/controller/controller.go:201 +0x10e
github.com/rancher/lasso/pkg/controller.(*controller).processNextWorkItem(0xc001200f20)
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20220412224715-5f3517291ad4/pkg/controller/controller.go:178 +0x46
github.com/rancher/lasso/pkg/controller.(*controller).runWorker(...)
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20220412224715-5f3517291ad4/pkg/controller/controller.go:167
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0x7f1cabfda990)
	/go/pkg/mod/k8s.io/apimachinery@v0.23.3/pkg/util/wait/wait.go:155 +0x67
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0x634c6e77772f4b64, {0x4781a40, 0xc00c46a7e0}, 0x1, 0xc0005fc3c0)
	/go/pkg/mod/k8s.io/apimachinery@v0.23.3/pkg/util/wait/wait.go:156 +0xb6
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0x394b5a6f75694f54, 0x3b9aca00, 0x0, 0x56, 0x3538473137534676)
	/go/pkg/mod/k8s.io/apimachinery@v0.23.3/pkg/util/wait/wait.go:133 +0x89
k8s.io/apimachinery/pkg/util/wait.Until(0x4450625a784f315a, 0x4c6a576f6a61336b, 0x436d506f2f4d5475)
	/go/pkg/mod/k8s.io/apimachinery@v0.23.3/pkg/util/wait/wait.go:90 +0x25
created by github.com/rancher/lasso/pkg/controller.(*controller).run
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20220412224715-5f3517291ad4/pkg/controller/controller.go:135 +0x2c6
panic: runtime error: slice bounds out of range [:3] with capacity 0 [recovered]
	panic: runtime error: slice bounds out of range [:3] with capacity 0
```

The cluster agent seemed to crash while reading a Helm secret. We worked on a Helm deployment before the UI was unaccessible. The Helm secret of this deployment seemed to be corrupt, so `helm list` returned an error. So we deleted the Helm secrets and the cluster agent stopped restarting (`kubectl -n cattle-system get pods`) which brought back the Rancher UI for us.

Although your situation might be very different, I hope the debug steps described helps to better understand what's going on and maybe brings back your UI as well. If you also have corrupt resources, restoring a recent etcd snapshot might help if it's okay for you to loose latest changes and to have a downtime while the restore is in progress.

**Comment by justdan96** [comment]
@jaimehrubiks We are in the same scenario, RKE in our data centres is seeing the issue but GKE and EKS are not.

**Comment by danielllek** [comment]
We're facing the same problem.

**Comment by justdan96** [comment]
It's good to see the issue will be resolved soon, is anyone in this thread able to test if the following PRs resolve their issue? https://github.com/rancher/rancher/pull/38096 https://github.com/rancher/remotedialer/pull/46

**Comment by danielllek** [comment]
I've built 2.6.5 with bumped version of remotedialer. 
If I'll be able to replicate issue on dev environment, I'll test this change.

**Comment by GentianRrafshi** [comment]
Hi,

we have fixed this Issue in a way, that so far no one has mentioned. We had a problem with our rancher setup. We determined that this command:
`kubectl get pods -A | awk '{ system ("kubectl logs --all-containers " $2 " -n " $1) }'`
pretty reliably crashed rancher with the error about remotedial mentioned above.

After some research, where we for example activated log rotate as mentioned, we found a flag in the api, that seems to have caused this.

We used the API extraArg `--service-account-api-audience` before upgrading to Rancher version 2.6.5. The key-value is deprecated and is now called `--api-audiences`. 

We missed that, and after some research realized, that rancher ignored `--service-account-api-audience` and set `--api-audiences`, but to unknown. So we removed the Flag `--service-account-api-audience` and added `--api-audiences=api` (which rancher itself set to `--api-audiences=unknown`) and after that, everything works fine. 

Maybe this causes the error and this is the fix? Could someone verify that?

**Comment by konih** [comment]
> We used the API extraArg `--service-account-api-audience` before upgrading to Rancher version 2.6.5. The key-value is deprecated and is now called `--api-audiences`.
> 
> Maybe this causes the error and this is the fix? Could someone verify that?

https://github.com/rancher/rancher/issues/37250

We tried setting the kube-apiserver flag for our RKE clusters. This resulted in the token authentication not working anymore.

**Comment by tonyfahrion** [comment]
@konih the value of `--api-audiences` needs to match the one from `--service-account-issuer` in our case (I am in the same team as @GentianRrafshi ).

This only makes sense if you have `--service-account-api-audience` set and are running a Kubernetes version affected by the deprecation I guess. 

It is the only change we did since we can't reproduce the rancher agent issues anymore so we are not sure if this is the real cause. Our Kubernetes clusters are running 1.22.9

I hope this helps :)

**Comment by git-ival** [comment]
Was **not** able to reproduce this issue using verified repro steps on the latest 2.5.15-rc1 or 2.6.6-rc2. This issue is resolved. 

Note that previous behavior has also been observed: if attempting to stream logs using multiple concurrent connections (running `kubectl logs -f` with multiple shell instances) then the following error might be encountered `error: stream error: stream ID 3; PROTOCOL_ERROR; received from peer`.

**Comment by danielllek** [comment]
I've also confirmed on 2.6.5 + just `remotedialer` patch.

**Comment by hemanth4984** [comment]
The issue is still there even after upgrading to v2.6.6

Getting below error:

**helm upgrade --install dev-calico-ipam . '--kubeconfig=****' '--namespace=dev-ipam'
Error: Kubernetes cluster unreachable: Get "https://rancher.xyz.net/k8s/clusters/c-123/version?timeout=32s": net/http: TLS handshake timeout**

My environment details:
RKE2 Version: v1.23.6+rke2r1
Rancher Version: v2.6.6
Downstream K8s version: v1.21.7

**Comment by Vaitheesh-SS** [comment]
> the same issue.. =/ one of the 3 provisioned cluster become partly unavailable. not working Cluster Summary Page, external link to Longhorn UI , to Prometheus UI with proxy uRL

Exactly facing the same issue Rancher v2.6.4! :-(

**Comment by Vaitheesh-SS** [comment]
> @beatsandpics exactly: `kubectl rollout restart -n=cattle-system deployment rancher`
> 
> BTW it happened to us today. So ~4 days since the last restart. We set up monitoring and alerting using kube-prometheus probes to get alerted as soon as it pops up again. this is the URL we continuously check: https://rancher.mycompany.com/k8s/clusters/c-clusterid/api?timeout=32s

Unable to open Downstream Cluster Summary Page, Pods summary page, external link to Longhorn UI , to Grafana monitoring page with proxy URL. We had setup another Downstream cluster which is was working fine while the other Downstream cluster breaking our heads!
This is fix worked perfectly for now in Rancher v2.6.4 - `kubectl rollout restart -n=cattle-system deployment rancher`

**Comment by chris93111** [comment]
same here 2.6.6

**Comment by eumel8** [comment]
runs stable since 25d in 2.6.6

**Comment by sphr2k** [comment]
Still seeing this issue w/ 2.6.6 and 2.6.7 a couple of times per day:

```
  |   | 2022/08/22 12:08:03 [INFO] error in remotedialer server [400]: websocket: close 1006 (abnormal closure): unexpected EOF
  |   | 2022/08/22 12:08:03 [INFO] error in remotedialer server [400]: websocket: close 1006 (abnormal closure): unexpected EOF
  |   | 2022/08/22 12:08:03 [INFO] error in remotedialer server [400]: websocket: close 1006 (abnormal closure): unexpected EOF
  |   | 2022/08/22 12:08:03 [INFO] error in remotedialer server [400]: websocket: close 1006 (abnormal closure): unexpected EOF
  |   | 2022/08/22 12:08:03 [INFO] error in remotedialer server [400]: websocket: close 1006 (abnormal closure): unexpected EOF
  |   | 2022/08/22 12:08:03 [INFO] error in remotedialer server [400]: websocket: close 1006 (abnormal closure): unexpected EOF
  |   | 2022/08/22 12:08:03 [INFO] error in remotedialer server [400]: websocket: close 1006 (abnormal closure): unexpected EOF
  |   | 2022/08/22 12:08:03 [INFO] error in remotedialer server [400]: websocket: close 1006 (abnormal closure): unexpected EOF
  |   | 2022/08/22 11:32:23 [INFO] error in remotedialer server [400]: read tcp 10.42.3.229:80->10.42.2.0:54940: i/o timeout
  |   | 2022/08/22 05:39:43 [INFO] error in remotedialer server [400]: read tcp 10.42.3.229:443->10.42.3.228:50982: read: connection reset by peer
  |   | 2022/08/22 03:17:22 [INFO] error in remotedialer server [400]: read tcp 10.42.3.228:80->10.42.1.0:36940: i/o timeout
  |   | 2022/08/22 03:17:22 [INFO] error in remotedialer server [400]: websocket: close 1006 (abnormal closure): unexpected EOF
  |   | 2022/08/21 21:41:52 [INFO] error in remotedialer server [400]: read tcp 10.42.3.228:443->10.42.3.224:58050: read: connection reset by peer
  |   | 2022/08/21 13:14:00 [INFO] error in remotedialer server [400]: read tcp 10.42.3.192:443->10.42.3.183:33576: read: connection reset by peer
  |   | 2022/08/20 13:02:37 [INFO] error in remotedialer server [400]: read tcp 10.42.3.183:443->10.42.3.182:55962: read: connection reset by peer
  |   | 2022/08/20 13:01:51 [INFO] error in remotedialer server [400]: read tcp 10.42.3.182:443->10.42.3.158:55118: read: connection reset by peer
```

As a workaround, we continuously check https://rancher<...>/k8s/clusters/<clusterid>/api?timeout=10s and restart Rancher if needed. Obviously, this is not a long-term solution.

**Comment by eumel8** [comment]
@medicol69 We were affected on this [remote dialer thing](https://github.com/rancher/remotedialer/pull/46) for a very long time with sporadic outages on downstream clusters (mostly with high load on Kube API). This is done in 2.6.6. If you facing this again, you should verify if all agents are really updated to 2.6.6. Or it's another incident.
