### ISSUE TITLE
rancher-cli v2.6.4 errors out trying to create an imported cluster.

### ISSUE THREAD

**Issue by nayrnet** [rancher/rancher#37574]
**Rancher Server Setup**
- Rancher version: 2.6.4
- Rancher CLI version: 2.6.4

**Information about the Cluster**
- Kubernetes version: All
- Cluster Type (Local/Downstream): Downstream
   - If downstream, what type of cluster?: Imported

**User Information**
- What is the role of the user logged in?: Admin
   
**Describe the bug**

The Rancher CLI is no longer able to create imported clusters, get an error saying its not found when trying to create it.

**To Reproduce**
Install Rancher CLI, Login to Rancher Managment Server with CLI, then try to create an imported cluster

**Result**
```
# rancher cluster create --import test
FATA[0000] Not found: test
```

**Expected Result**

Create should succeed, so then you can run a cluster import:
```
# rancher cluster create --import test
# rancher cluster import test
Run the following command in your cluster:
kubectl apply -f https://rancher/v3/import/<registration token>_<cluster_id>.yaml

If you get an error about 'certificate signed by unknown authority' because your Rancher installation is running with an untrusted/self-signed SSL certificate, run the command below instead to bypass the certificate check:
curl --insecure -sfL https://rancher/v3/import/<registration token>_<cluster_id>.yaml | kubectl apply -f -```
```

**Additional context**

Reverted back to Rancher CLI 2.6.0 and it works fine, I believe this change is what broke this feature: https://github.com/rancher/cli/compare/v2.6.0...v2.6.4#diff-80ae849bc4f26edd364d1b0d0d1a3ed7598d4bd546451e5671b82367582c57b5L755

**Comment by Tonur** [comment]
My team is experiencing this issue as well. 
Is it right to assume that it gets fixed in the next Rancher-cli version, most likely V. 2.6.7?

**Comment by bcdurden** [comment]
Confirming this is still an issue, appears the original problem was reported in May. Can we please re-open until it is addressed or link to an issue already open?
```console
╭─ ~ ······································································································································ 3 х  at 14:56:00 ─╮
╰─ rancher cluster create --import test                                                                                                                      ─╯
FATA[0000] Not found: test                              
╭─ ~ ······································································································································ 1 х  at 14:56:09 ─╮
╰─ rancher                                                                                                                                                   ─╯
Rancher CLI, managing containers one UTF-8 character at a time

Usage: rancher [OPTIONS] COMMAND [arg...]

Version: v2.6.5
```

**Comment by EmanueleGallone** [comment]
Still an issue today (using **Rancher-CLI** 2.6.7):
```
./rancher cluster create test-imported-cluster --import
FATA[0000] Not found: test-imported-cluster 
```

**Comment by spointecker** [comment]
Still an issue on 2.7.0.

Will this be fixed?

**Comment by euven** [comment]
Can we re-open this one? We're experiencing the same thing.

**Comment by mpas** [comment]
Would be great to have the PR merged. I am running into the same issue.

**Comment by snasovich** [comment]
This is now tracked in https://github.com/rancher/rancher/issues/41144 (even though it was created after this one).
