### ISSUE TITLE
[CLI] When logged in to the Rancher CLI as a standard user, performing operations such as `rancher clusters kf <NAME>` results in error `FATA[0000] Bad response statusCode [403]. Status [403 Forbidden]`

### ISSUE THREAD

**Issue by markusewalker** [rancher/rancher#37609]
**Rancher Server Setup**
- Rancher version: Rancher CLI `v2.6.5-rc1`
- Installation option (Docker install/Helm Chart): N/A
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): N/A
- Proxy/Cert Details: N/A
   
**Describe the bug**

When logged in as a standard user to the Rancher CLI, I noted that performing certain operations results in a 403 error message. 

For example, performing the cli command `rancher clusters kf`, you should expect to get the kubeconfig for the desired cluster. Indeed you do get this behavior....assuming you are logged in as an administrator user. However, if you are logged to the Rancher CLI as a standard user, you're unable to get the kubeconfig of clusters that standard user creates if you run `rancher clusters kf <NAME>`; running `rancher clusters kf <ID> does give the kubeconfig.

See the two clusters that my standard user created below:

```
$ rancher clusters ls
CURRENT   ID        STATE     NAME         PROVIDER                    NODES     CPU         RAM             PODS
*         c-pvfwc   active    test-76479   Rancher Kubernetes Engine   6         0.33/9.50   0.34/43.39 GB   12/440
          c-pxnc9   active    test-45231   Rancher Kubernetes Engine   6         0.33/9.50   0.34/43.39 GB   12/440
```
When trying to get the kubeconfig of one of them as the standard user, I get the following:

```
$ rancher clusters kf test-76479
FATA[0000] Bad response statusCode [403]. Status [403 Forbidden]. Body: [baseType=error, code=Forbidden, message=clusters.management.cattle.io "test-76479" is forbidden: User "u-7mdh7" cannot get resource "clusters" in API group "management.cattle.io" at the cluster scope] from [https://mew.qa.rancher.space/v3/clusters/test-76479]
```
However, if I log out and login as an administrator user, then I get the kubeconfig as expected, regardless if I use the `ID` or `NAME`. 

**To Reproduce**
 
1. Setup Rancher and navigate to Rancher UI in a browser.
2. Create a standard user and login to Rancher UI as that browser.
3. Create a new API key as the standard user; save this bearer-token, you will need it later.
4. In Cluster Management, create a downstream cluster as the standard user (the type of cluster does not matter).
5. On a client machine, download the Rancher CLI `v2.6.7-rc1`.
6. Run `rancher login -t <standard bearer-token> https://<FQDN of Rancher Server>` command.
7. Run `rancher clusters ls` command to get the `ID` and `NAME` of the cluster you created earlier.
8. Run `rancher clusters kf <NAME>` command and view the error.

**Result**
Running `rancher clusters kf <NAME>` as the standard user on a cluster it created fails to receive the kubeconfig.

**Expected Result**

Running `rancher clusters kf <NAME>` as the standard user SHOULD return the kubeconfig of the cluster it created.

**Comment by jakefhyde** [comment]
Requires some investigation: at first glance, it appears to be an RBAC issue but if it was, this functionality would also not work through the UI. We need to investigate how exactly the CLI is requesting the kubeconfig from rancher.

**Comment by HarrisonWAffel** [comment]
I've been able to reproduce this issue following the steps given by Markus. As far as I can tell, this issue does seem related to RBAC. The CLI is making its calls through Norman, and the issue only reproduces when passing a `CLUSTERNAME`, and not when passing a `CLUSTERID`. 

The help message for `rancher-cli clusters kf` states the following: 

```
Return the kube config used to access the cluster

Usage: 
  rancher clusters kubeconfig [CLUSTERID CLUSTERNAME]
```

It is expected that a user could input a `CLUSTERID` or a `CLUSTERNAME`. When passing either value, the CLI first tries to determine if it is a `CLUSTERID` by making a call to `/v3/clusters/<VALUE>`. The CLI will check for a `404` response and, if one is not found, marshal the response body into JSON and return the resource. Otherwise it will attempt to find the cluster by its name using a `list` operation. This logic of determining what value was passed to the CLI is most likely why this same functionality works in the UI, but not on the CLI.

This call to check if a `CLUSTERID` has been passed is what is producing the `403` error that Markus is reporting. However, I'm unable to determine why a `403` is returned and not the expected `404`. When the same request is made by an admin user, the response is `404`. I've tested this with a standard user who has no built-in permissions assigned to them, as well as a standard user with all built-in permissions assigned to them and they both encounter the `403` error.

The error message indicates that `User "u-f7n6g" cannot get resource "clusters" in API group "management.cattle.io" at the cluster scope`. I'm not an expert on Norman, but this seems odd, as a request using the `CLUSTERID` instead of `CLUSTERNAME` does return a valid response and not a `403`, and it appears that they are both querying the same resource (a cluster) at the same scope. It seems unlikely, but perhaps `403` and `404` have gotten mixed up somehow?

We could work around this problem and clean up the CLI code to better determine if a `CLUSTERNAME` or `CLUSTERID` has been passed so as to avoid the failing API call. But, from what I can see the failing call to `/v3/clusters/<CLUSTERNAME>` is due to some RBAC behavior I'm not aware of.

**Comment by markusewalker** [comment]
Circling back, this is actually a much broader issue than initially reported...for example, if I attempt to add a node to an existing cluster, I still see the same 403 issue. With what @HarrisonWAffel reported above, all of the other issues that uniquely the standard user faces should go away.

I'm going to rename the issue and issue description to be more broad as this is more of a broader issue.

**Comment by markusewalker** [comment]
While this issue is under investigation, here is the current QA test plan:

**TEST PLAN**
1. Setup Rancher and navigate to Rancher UI in a browser.
2. Create a standard user and login to Rancher UI as that browser.
3. Create a new API key as the standard user; save this bearer-token, you will need it later.
4. In Cluster Management, create a downstream cluster as the standard user (the type of cluster does not matter).
5. On a client machine, download the Rancher CLI.
6. Run `rancher login -t <standard bearer-token> https://<FQDN of Rancher Server>` command.
7. Run `rancher clusters ls` command to get the ID and NAME of the cluster you created earlier.
8. Run `rancher clusters kf <NAME>` command and view the error.

**Comment by samjustus** [comment]
@markusewalker what is the latest on this issue? Is my team supposed to be investigating anything? I want to move this out of 2.7.0 as we have other priority issues but let me know what you think

**Comment by markusewalker** [comment]
@samjustus I believe @HarrisonWAffel was taking a look into this whenever he had time, but I could be wrong. I do not believe at this time your team is supposed to be investigating anything.

**Comment by snasovich** [comment]
@HarrisonWAffel , when you have time, could you circle back to investigate this one?

**Comment by HarrisonWAffel** [comment]
The root cause of this issue seems to be a missing `GET` permission for `management.cattle.io` clusters within the Standard User role (which is the default role given to new users, unless otherwise configured). Adding the `GET` permission allows the CLI to return the `kubeconfig` as expected when running `cli clusters kf <CLUSTER_NAME>`. The exclusion of this permission in the standard user role  is likely due to the fact that the `GET` permission allows a user to see all clusters when running `cli clusters ls`, and not just the cluster of which they are a member of. 

A work around for this issue would be to create a new role for the user, which mirrors the existing standard user role with an additional `GET` permission on the `management.cattle.io` cluster resource. However, as stated previously, this gives users with this role access to all clusters.

**Comment by HarrisonWAffel** [comment]
https://github.com/rancher/cli/pull/325 changes the default behavior of this command to only accept a cluster-id, in which case this call will function as desired. Because of this I am going to close this ticket out, as the problematic scenario is no longer the default.

**Comment by cbron** [comment]
Revert complete. Next step is to re-add the code and get it QA'd: https://github.com/rancher/cli/pull/335

**Comment by markusewalker** [comment]
Validated that on `v2.13-head` https://github.com/rancher/rancher/commit/3189501a047776b4a3e5728beb93f1da464f942f and CLI `v2.13.1-rc.1`, this is addressed. See testing below considered:

|#|Scenario|Result|
|---|---|---|
|1|Validate standard user can view available clusters with `rancher clusters ls`|:white_check_mark:|
|2|Validate standard user can view kubeconfig with `rancher clusters kf <cluster ID>|:white_check_mark:|
|3|Validate standard user can delete a downstream cluster with `rancher clusters rm <cluster ID>|:white_check_mark:|

**Comment by Pandemonium1986** [comment]
I still continue to have the same pb using rancher-cli 2.14.3 and rancher 2.14.3.
It works with CLUSTEID but not with CLUSTERNAME
