### ISSUE TITLE
Proxied kubectl commands hanging

### ISSUE THREAD

**Issue by samjustus** [rancher/rancher#37707]
SURE-4337

**Rancher Server Setup**
Rancher version: 2.6.4
Number of nodes: 6 
Node OS version: Ubuntu 18.04

**Downstream Cluster:**
Number of Downstream clusters: 2
Node OS: Ubuntu 18.04
RKE/RKE2/K3S version: RKE
Kubernetes version: RKE 1.20.11
CNI: calico
   
**Describe the bug**
One of our Ranchers that was upgraded to 2.6.4 is experiencing time outs and/or slowness when using kubectl and proxying through rancher. This same issue was seen in 2.6.4-rc13 in another cluster so it feels like a bug was introduced in 2.6.4 as this did not happen in 2.6.3. If I point directly to the RKE kube-api everything works as expected.

**Result**
Time outs and/or slowness with kubectl commands

**Expected Result**
No excessive slowness or timeouts with regular kubectl operations

**Comment by ikogan** [comment]
Are there any more details or any workarounds? We just upgraded to 2.6.5 and k8s 1.21.12. The same version of Rancher works fine against our other 1.20.x clusters and a 2.6.4 sandbox clusters works against it's 1.21.10 downstream cluster.

We also see slowness in the Rancher UI when browsing this cluster, in particular when trying to get information about workload resources like Deployments.

**Comment by chofstede** [comment]
I experience the same problem on Rancher 2.6.4. System gets unresponsive and kubectl to certain clusters don't work anymore.

**Comment by ikogan** [comment]
So...we solved this by just restarting Rancher. We scaled down the Rancher deployment to 0, waited for it to shut all the way down, then scaled it back to 3. Obviously, we can't use the Rancher proxy while doing that. We did this on May 17th and it's been stable so far.

**Comment by jgerry2002** [comment]
Same issue here on 2.6.4. But its not all clusters. Only some clusters. This issue should be investigated. I kept blaming the managed cluster until I found this thread blaming Rancher itself.

**Comment by jgerry2002** [comment]
Yes restarting Rancher magically fixes the API and it worked for me as well

**Comment by EC-Sean** [comment]
@mohag I did not see high CPU usage for the agent on the clusters. I ever tried completely removing and reinstalling the agent and that particular cluster would still be unreachable through the proxy. It was only after restarting the Rancher server did it fix itself.

What are you all using for auth? I had Keycloak OIDC setup, and noticed from the rancher server logs when I pressed the sync groups button that the rancher server could not connect to the keycloak server. People could still login because their browsers could reach both services. I fixed it a few days ago, and haven't had anyone reporting problems since, but I think it is too early to know if this was the cause.

**Comment by mohag** [comment]
I'm using Azure AD.

Restarting Rancher did help for the speed (and the agent on its own did not)

(We have a large Rancher setup, around 90 or so clusters (all imported) (a mix between EKS, AKS and kubeadm clusters)

**Comment by jgerry2002** [comment]
This happened again yesterday. It may be related to pods that have excessively large logs. If you try to tail a few of them it seems to cause kubectl to hang after that. Another Rancher restart (killed all the pods) and the problem vanished. I'm on 2.6.4.

**Comment by ikogan** [comment]
We have 4 clusters including local and this just started happening to us again. @jgerry2002 do you have any more info about what you mean by "excessive"? Do you mean following the flogs or just dumping the entire log stream? Once again, restarting the Rancher pods seemed to fix it but it seems like this is indeed temporary.

**Comment by cbron** [comment]
Hello all, thanks for the information so far. We are trying to piece together the problem here. So far we have been unable to reproduce on the Rancher side. I believe it might be related to this issue, which also can be created by getting downstream logs: https://github.com/rancher/rancher/issues/37250

Some questions to tie threads together: 
* For those that see this on only some of your clusters, are there any common traits between those affected clusters ? This could be things like k8s distro, k8s version, or cluster usage.
* Is anyone seeing this issue below k8s 1.21 ?
* Has anyone seen this issue before Rancher 2.6.4 ?
* Are people seeing high CPU usage on the downstream agent when this happens ? 
* Does Rancher have high CPU or memory usage ?
* Does this only happen during high Rancher usage hours ? Meaning people updating things via Rancher or getting logs. Downstream workload activity shouldn't matter here.

**Comment by drpebcak** [comment]
@cbron if you'd like to schedule a call some time to look through my cluster, I can arrange that. This is happening so far to just one of my clusters, and there is another one with identical configuration that's working fine. This is a RKE cluster that was provisioned 'from custom nodes' by rancher. Currently its running v1.22.7 and I am on Rancher 2.6.5.

Started on 2.6.4 as far as I remember, and I was on 1.21 at that time. I'm not seeing particularly elevated cpu anywhere as far as I can tell.. and this happens constantly, not just when people are actively using Rancher.

My affected cluster has:
- 23 namespaces, 70 workloads, 113 rolebindings.. not a particularly busy cluster from the apiserver perspective.

**Comment by EC-Sean** [comment]
I am running Rancher 2.6.5 on Kubernetes v1.22.9-eks-a64ea69, using nginx-ingress.

I have found a way to reliably reproduce the issue on my server. First I created a pod on one of my clusters that generates a large amount of logs:

```yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: snowcrash
  name: snowcrash
spec:
  replicas: 1
  selector:
    matchLabels:
      app: snowcrash
  serviceName: snowcrash
  template:
    metadata:
      labels:
        app: snowcrash
    spec:
      containers:
        - command:
            - sh
            - -c
            - while true ; do sleep 1 ; dd if=/dev/zero bs=8M count=32 | xxd -c 1048576 ; done
          image: alpine
          name: snowcrash
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "100m"
```

Next, using a kubeconfig that utilizes Rancher's auth proxy, I leave the following command running:

```bash
kubectl logs -f snowcrash-0
```

One instance of `kubectl logs` would eventually (5m?) make that cluster unreachable through the auth proxy. Running three of those in parallel would kill it in about 1-3 minutes. Restarting Rancher fixes everything. If I connect directly to the cluster instead of going through Rancher server's proxy everything works fine.

I tried `kubectl attach` through the proxy, and could run several instances of that in parallel experiencing any issues. There must be something different about `kubectl logs` that breaks things.

**Comment by jgerry2002** [comment]
@EC-Sean - this was my same finding. I noticed the problem happened with a database pod that created a large log file. I can get Rancher to hang/crash by trying to tail the large log file. A restart always fixes it.

**Comment by Jellyfrog** [comment]
Same here, often hangs when tailing a large log and then aborting (ctrl+c) in the middle

**Comment by sennerholm** [comment]
Same problem, restart of the primary pod is fixing the problem. If it take time for the final fix it would be good with a liveness prob that restarts the failing pod

**Comment by kallomat** [comment]
We're also seeing this issue.

Clusters
* Started after update Rancher from 2.5.9 to 2.6.4
* Downstream clusters are rancher launched rke1, vSphere NodeProvider or custom nodes, k8s 1.23.6
* Downstream Cluster Size 3 Master, 5-8 Worker, 30-50 Namespaces, 150-500 Pods, rancher prometheus, additional own prometheus controlled by rancher prometheus-operator.

Symptom when the issue occours:
* Donwnstream cluster start page does not load in rancher gui, but sub pages work
* kubectl access does not work most of the time, but a few requests get answered
* kubectl in rancher gui works fine
* CPU usage on downstream agent was not checked, will be next time.
* Rancher Pod high CPU, mem usage was not checked, will be next time.
* Logs of rancher pod show nothing special that point to the issue

Trigger of the issue
* Getting larger logs of ingress-controller with kubectl triggered the bug several times in series during some minutes.
* In another case some colleague mentioned he had deleted serveral helm charts in short time which may triggered the bug. No more details are available to me here. 
* Unknown reasons.

Fix workaround
* kubectl -n cattle-system rollout restart deploy rancher
* cluster agent of affected cluster was not checked nor restarted, will check next time.

**Comment by samjustus** [comment]
we just released 2.6.6 and we think it might solve this. Issues seem quite similar #37250

please advise if this solves the issue on your end

**Comment by git-ival** [comment]
@chofstede @EC-Sean @Jellyfrog @jgerry2002 @ikogan @kallomat @sennerholm Hi all, just wanted to echo what samjustus mentioned, we think Rancher 2.6.6 may solve this issue any feedback here would be very helpful!

**Comment by jgerry2002** [comment]
2.6.6 tested and also has issues. I installed it yesterday and it was fine. Today I tried to run a few kubectl commands and the api slowly responds. Deleting the rancher pods did not solve it. Every single kubectl command pauses for two to 10 seconds or more when trying to communicate with the cluster. This is making it VERY difficult to manage clusters.

**Comment by mohag** [comment]
2.6.6 seems more responsive in general, I haven't seen any of the 11 minute responses with it yet... (It is possible that they take longer than the first day to show up or that shorter, but still longer than what should be present, delays are still there)

**Comment by kallomat** [comment]
> @chofstede @EC-Sean @Jellyfrog @jgerry2002 @ikogan @kallomat @sennerholm Hi all, just wanted to echo what samjustus mentioned, we think Rancher 2.6.6 may solve this issue. Any feedback here would be very helpful!

Short and sweet: It may be solved for us with 2.6.6 but we are not 100% shure and still keep an eye on it.

We updated from Rancher 2.6.4 to 2.6.6 a week ago. The bug doesn't show up since then. Before the update the bug did not show up for about 2 weeks but just before we did the update. We couldn't reproduce the bug clearly in out test systems.

**Comment by mohag** [comment]
> 2.6.6 seems more responsive in general, I haven't seen any of the 11 minute responses with it yet... (It is possible that they take longer than the first day to show up or that shorter, but still longer than what should be present, delays are still there)

The complete brokenness (responses that take multiple minutes to complete / don't complete at all from kubectl) is certainly gone on 2.6.6. (It is still slower than 2.5 (especially on the UI), but `kubectl` is much more usable than on 2.6.5)

**Comment by sknight-egio** [comment]
Been on v2.6.6 for almost a few weeks now and haven't seen the issue pop up.
