### ISSUE TITLE
"No service or pod" text is not centered for Kubernetes

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#3788]
Version - master 3/4

Steps to Reproduce: 
1.  Create a new namespace in kubernetes environment
2.  Go to Services or PODs page

Results: The "You do not have any Services (or Pods) yet." Text is not centered

Expected: Should be centered

**Comment by lvuch** [comment]
resolved in https://github.com/rancher/ui/pull/541

**Comment by tfiduccia** [comment]
Version - master 3/16
Verified fixed

**Comment by tfiduccia** [comment]
The "You do not have any Services" text is still not centered.  I deleted the kubernetes service, but it recreates to fast for me to get a picture.

**Comment by lvuch** [comment]
![screen shot 2016-03-16 at 2 34 35 pm](https://cloud.githubusercontent.com/assets/3013118/13829478/7b5075da-eb84-11e5-8d83-607b31be24a3.png)
![screen shot 2016-03-16 at 2 32 43 pm](https://cloud.githubusercontent.com/assets/3013118/13829479/7b539486-eb84-11e5-9a32-8633b6fc3b41.png)
now in https://github.com/rancher/ui/pull/542

**Comment by tfiduccia** [comment]
Version - master UI 3/18
Verified Fixed
