### ISSUE TITLE
Malformed RKE2 ETCD snapshot name causes Rancher memory leak

### ISSUE THREAD

**Issue by ADustyOldMuffin** [rancher/rancher#37904]
**Rancher Server Setup**
- Rancher version: 2.6.5 installed via Helm chart on RKE2.

**Information about the Cluster**
- Kubernetes version: v1.22.9+rke2r2
- Local cluster encountered the error, but is caused from a snapshot of a downstream cluster. Both clusters are the same rancher and K8s version.

**User Information**
- What is the role of the user logged in? Admin
   
**Describe the bug**

While setting up an RKE2 cluster a discovered snapshot in S3 had a malformed name, something similar to `something.something.-.s3-.com` even though all other snapshots were fine. All snapshots were created via RKE2 automated snapshots set to take one every hour and retain 72 of them. 

Rancher was attempting to cleanup old snapshots as they were discovered via the s3 bucket, and when it crossed this snapshot it would panic and stop the process. This would happen until the Rancher container consumed enough memory to start OOM killing processes on the node and crash the RKE2 service.

Once the service crashed the pod would be rescheduled and a different Rancher pod would take up the task and the process would continue.

Removing the malformed name from the snapshot configmap and removing the snapshot from S3 fixed this issue.

**To Reproduce**
 

Rename an etcd RKE2 snapshot to an unacceptable name that Rancher can't parse.

**Result**

Rancher panics when cleaning up old snapshots and causes a memory leak until Rancher pod reaches it's resource limits or crashes the host node.

**Expected Result**

Rancher handles not being able to parse a bad name (as they happen) and instead just skips it and moves on with a log or way to notify operators.

**Comment by Oats87** [comment]
In performing my reproduction of this, I created an RKE2 cluster in EC2 that backed up snapshots to S3.

I created a file in the bucket with the name `something.something.-.s3-.com` and got the following error in Rancher:

```
2022/06/13 22:18:34 [INFO] [snapshotbackpopulate] rkecluster fleet-default/testlol123: processing configmap kube-system/rke2-etcd-snapshots
2022/06/13 22:18:34 [DEBUG] [snapshotbackpopulate] rkecluster fleet-default/testlol123: creating s3 etcd snapshot fleet-default/testlol123-something.something.-.s3-.com-s3 as it differed from the actual snapshot config map
2022/06/13 22:18:34 [ERROR] error syncing 'kube-system/rke2-etcd-snapshots': handler snapshotbackpopulate: rkecluster fleet-default/testlol123: error while creating s3 etcd snapshot fleet-default/testlol123-something.something.-.s3-.com-s3: ETCDSnapshot.rke.cattle.io "testlol123-something.something.-.s3-.com-s3" is invalid: metadata.name: Invalid value: "testlol123-something.something.-.s3-.com-s3": a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*'), requeuing
```; however, I did not see a panic. 

@ADustyOldMuffin do you by chance remember the exact name that caused the panic in Rancher?

**Comment by brandond** [comment]
Just got a report of this today via @Brianalmeida :
```
Jun 03 20:29:23 ip-10-242-63-234.us-east-2.compute.internal rke2[13846]: time="2022-06-03T20:29:23Z" level=info msg="Reconciliation of snapshot data in rke2-etcd-snapshots ConfigMap complete"
Jun 03 20:29:23 ip-10-242-63-234.us-east-2.compute.internal rke2[13846]: time="2022-06-03T20:29:23Z" level=error msg="Failed to record snapshots for cluster: ConfigMap \"rke2-etcd-snapshots\" is invalid: [data[s3-c-9r7sc-rs-w2dks_2022-05-24T17:14:18Z.zip]: Invalid value: \"s3-c-9r7sc-rs-w2dks_2022-05-24T17:14:18Z.zip\": a valid config key must consist of alphanumeric characters, '-', '_' or '.' (e.g. 'key.name',  or 'KEY_NAME',  or 'key-name', regex used for validation is '[-._a-zA-Z0-9]+'), data[s3-c-9r7sc-rs-djzbw_2022-05-25T11:29:18Z.zip]: Invalid value: \"s3-c-9r7sc-rs-djzbw_2022-05-25T11:29:18Z.zip\": a valid config key must consist of alphanumeric characters, '-', '_' or '.' (e.g. 'key.name',  or 'KEY_NAME',  or 'key-name', regex used for validation is '[-._a-zA-Z0-9]+'), data[s3-c-9r7sc-rs-vpxkq_2022-05-26T23:59:18Z.zip]: Invalid value: \"s3-c-9r7sc-rs-vpxkq_2022-05-26T23:59:18Z.zip\": a valid config key must consist of alphanumeric characters, '-', '_' or '.' (e.g. 'key.name',  or 'KEY_NAME',  or 'key-name', regex used for validation is '[-._a-zA-Z0-9]+'), data[s3-c-29422-rs-2b8r8_2022-05-12T11:20:15Z.zip]: Invalid value: \"s3-c-29422-rs-2b8r8_2022-05-12T11:20:15Z.zip\": a valid config key must consist of alphanumeric characters, '-', '_' or '.' (e.g. 'key.name',  or 'KEY_NAME',  or 'key-name', regex used for validation is '[-._a-zA-Z0-9]+'), data[s3-c-zrjnb-rs-zbjln_2022-05-09T01:15:15Z.zip]: Invalid value: \"s3-c-zrjnb-rs-zbjln_2022-05-09T01:15:15Z.zip\": a valid config key must consist of alphanumeric characters, '-', '_' or '.' (e.g. 'key.name',  or 'KEY_NAME',  or 'key-name', regex used for validation is '[-._a-zA-Z0-9]+'), data[s3-c-zrjnb-rs-wtg5x_2022-05-06T00:15:15Z.zip]: Invalid value: \"s3-c-zrjnb-rs-wtg5x_2022-05-06T00:15:15Z.zip\": a valid config key must consist of alphanumeric characters, '-', '_' or '.' (e.g. 'key.name',  or 'KEY_NAME',  or 'key-name', regex used for validation is '[-._a-zA-Z0-9]+'), data[s3-c-9r7sc-rs-7xh47_2022-05-24T11:09:18Z.zip]: Invalid value: \"s3-c-9r7sc-rs-7xh47_2022-05-24T11:09:18Z.zip\": a valid config key must consist of alphanumeric characters, '-', '_' or '.' (e.g. 'key.name',  or 'KEY_NAME',  or 'key-name', regex used for validation is '[-._a-zA-Z0-9]+'), data[s3-c-29422-rs-b9s4g_2022-05-12T05:15:15Z.zip]: Invalid value: \"s3-c-29422-rs-b9s4g_2022-05-12T05:15:15Z.zip\": a valid config key must consist of alphanumeric characters, '-', '_' or '.' (e.g. 'key.name',  or 'KEY_NAME',  or 'key-name', regex used for validation is '[-._a-zA-Z0-9]+'), data[s3-c-9r7sc-rs-9gmrm_2022-05-21T10:09:18Z.zip]: Invalid value: \"s3-c-9r7sc-rs-9gmrm_2022-05-21T10:09:18Z.zip\": a valid config key must consist of alphanumeric characters, '-', '_' or '.' (e.g. 'key.name',  or 'KEY_NAME',  or 'key-name', regex used for validation is '[-._a-zA-Z0-9]+'), data[s3-c-9r7sc-rs-hcrnv_2022-05-21T04:04:18Z.zip]: Invalid value: \"s3-c-9r7sc-rs-hcrnv_2022-05-21T04:04:18Z.zip\": a valid config key must consist of alphanumeric characters, '-', '_' or '.' (e.g. 'key.name',  or 'KEY_NAME',  or 'key-name', regex used for validation is '[-._a-zA-Z0-9]+'), data[s3-c-9r7sc-rs-4vb72_2022-05-21T16:14:18Z.zip]: Invalid value: \"s3-c-9r7sc-rs-4vb72_2022-05-21T16:14:18Z.zip\": a valid config key must consist of alphanumeric characters, '-', '_' or '.' (e.g. 'key.name',  or 'KEY_NAME',  or 'key-name', regex used for validation is '[-._a-zA-Z0-9]+'), data[s3-c-9r7sc-rs-fqxvf_2022-05-22T10:29:18Z.zip]: Invalid value: \"s3-c-9r7sc-rs-fqxvf_2022-05-22T10:29:18Z.zip\": a valid config key must consist of alphanumeric characters, '-', '_' or '.' (e.g. 'key.name',  or 'KEY_NAME',  or 'key-name', regex used for validation is '[-._a-zA-Z0-9]+'), data[s3-c-9r7sc-rs-vnzq8_2022-05-23T04:44:18Z.zip]: Invalid value: \"s3-c-9r7sc-rs-vnzq8_2022-05-23T04:44:18Z.zip\": a valid config key must consist of alphanumeric characters, '-', '_' or '.' (e.g. 'key.name',  or 'KEY_NAME',  or 'key-name', regex used for validation is '[-._a-zA-Z0-9]+'), data[s3-c-zrjnb-rs-hvf99_2022-05-10T19:50:15Z.zip]: Invalid value: \"s3-c-zrjnb-rs-hvf99_2022-05-10T19:50:15Z.zip\": a valid config key must consist of alphanumeric characters, '-', '_' or '.' (e.g. 'key.name',  or 'KEY_NAME',  or 'key-name', regex used for validation is '[-._a-zA-Z0-9]+'), data[s3-c-9r7sc-rs-xxlkp_2022-05-27T18:14:18Z.zip]: Invalid value: \"s3-c-9r7sc-rs-xxlkp_2022-05-27T18:14:18Z.zip\": a valid config key must consist of alphanumeric characters, '-', '_' or '.' (e.g. 'key.name',  or 'KEY_NAME',  or 'key-name', regex used for validation is '[-._a-zA-Z0-9]+'), data[s3-c-9r7sc-rs-bdwwh_2022-05-20T21:59:18Z.zip]: Invalid value: \"s3-c-9r7sc-rs-bdwwh_2022-05-20T21:59:18Z.zip\": a valid config key must consist of alphanumeric characters, '-', '_' or '.' (e.g. 'key.name',  or 'KEY_NAME',  or 'key-name', regex used for validation is '[-._a-zA-Z0-9]+'), data[s3-c-9r7sc-rs-h45dc_2022-05-27T06:04:18Z.zip]: Invalid value: \"s3-c-9r7sc-rs-h45dc_2022-05-27T06:04:18Z.zip\": a valid config key must consist of alphanumeric characters, '-', '_' or '.' (e.g. 'key.name',  or 'KEY_NAME',  or 'key-name', regex used for validation is '[-._a-zA-Z0-9]+'), data[s3-c-9r7sc-rs-gqb94_2022-05-23T22:59:18Z.zip]: Invalid value: \"s3-c-9r7sc-rs-gqb94_2022-05-23T22:59:18Z.zip\": a valid config key must consist of alphanumeric characters, '-', '_' or '.' (e.g. 'key.name',  or 'KEY_NAME',  or 'key-name', regex used for validation is '[-._a-zA-Z0-9]+'), data[s3-c-9r7sc-rs-82kxn_2022-05-26T17:54:18Z.zip]: Invalid value: \"s3-c-9r7sc-rs-82kxn_2022-05-26T17:54:18Z.zip\": a valid config key must consist of alphanumeric characters, '-', '_' or '.' (e.g. 'key.name',  or 'KEY_NAME',  or 'key-name', regex used for validation is '[-._a-zA-Z0-9]+'), data[s3-c-zrjnb-rs-6pkh4_2022-05-06T06:20:17Z.zip]: Invalid value: \"s3-c-zrjnb-rs-6pkh4_2022-05-06T06:20:17Z.zip\": a valid config key must consist of alphanumeric characters, '-', '_' or '.' (e.g. 'key.name',  or 'KEY_NAME',  or 'key-name', regex used for validation is '[-._a-zA-Z0-9]+'), data[s3-c-9r7sc-rs-9b6qd_2022-05-21T22:19:18Z.zip]: Invalid value: \"s3-c-9r7sc-rs-9b6qd_2022-05-21T22:19:18Z.zip\": a valid config key must consist of alphanumeric characters, '-', '_' or '.' (e.g. 'key.name',  or 'KEY_NAME',  or 'key-name', regex used for validation is '[-._a-zA-Z0-9]+'), data[s3-c-zrjnb-rs-tdrcd_2022-05-11T14:05:15Z.zip]: Invalid value: \"s3-c-zrjnb-rs-tdrcd_2022-05-11T14:05:15Z.zip\": a valid config key must consist of alphanumeric characters, '-', '_' or '.' (e.g. 'key.name',  or 'KEY_NAME',  or 'key-name', regex used for validation is '[-._a-zA-Z0-9]+'), data[s3-c-zrjnb-rs-lxscc_2022-05-08T13:05:15Z.zip]: Invalid value: \"s3-c-zrjnb-rs-lxscc_2022-05-08T13:05:15Z.zip\": a valid config key must consist of alphanumeric characters, '-', '_' or '.' (e.g. 'key.name',  or 'KEY_NAME',  or 'key-name', regex used for validation is '[-._a-zA-Z0-9]+'), data[s3-c-zrjnb-rs-qtxx2_2022-05-11T08:00:15Z.zip]: Invalid value: \"s3-c-zrjnb-rs-qtxx2_2022-05-11T08:00:15Z.zip\": a valid config key must consist of alphanumeric characters, '-', '_' or '.' (e.g. 'key.name',  or 'KEY_NAME',  or 'key-name', regex used for validation is '[-._a-zA-Z0-9]+'), data[s3-c-zrjnb-rs-mvvgq_2022-05-05T06:00:15Z.zip]: Invalid value: \"s3-c-zrjnb-rs-mvvgq_2022-05-05T06:00:15Z.zip\": a valid config key must consist of alphanumeric characters, '-', '_' or '.' (e.g. 'key.name',  or 'KEY_NAME',  or 'key-name', regex used for validation is '[-._a-zA-Z0-9]+'), data[s3-c-zrjnb-rs-xndlb_2022-05-04T23:55:15Z.zip]: Invalid value: \"s3-c-zrjnb-rs-xndlb_2022-05-04T23:55:15Z.zip\": a valid config key must consist of alphanumeric characters, '-', '_' or '.' (e.g. 'key.name',  or 'KEY_NAME',  or 'key-name', regex used for validation is '[-._a-zA-Z0-9]+'), data[s3-c-zrjnb-rs-tjjz2_2022-05-10T13:45:15Z.zip]: Invalid value: \"s3-c-zrjnb-rs-tjjz2_2022-05-10T13:45:15Z.zip\": a valid config key must consist of alphanumeric characters, '-', '_' or '.' (e.g. 'key.name',  or 'KEY_NAME',  or 'key-name', regex used for validation is '[-._a-zA-Z0-9]+'), data[s3-c-29422-rs-m6nlb_2022-05-11T17:05:15Z.zip]: Invalid value: \"s3-c-29422-rs-m6nlb_2022-05-11T17:05:15Z.zip\": a valid config key must consist of alphanumeric characters, '-', '_' or '.' (e.g. 'key.name',  or 'KEY_NAME',  or 'key-name', regex used for validation is '[-._a-zA-Z0-9]+'), data[s3-c-9r7sc-rs-zzgtf_2022-05-23T10:49:18Z.zip]: Invalid value: \"s3-c-9r7sc-rs-zzgtf_2022-05-23T10:49:18Z.zip\": a valid config key must consist of alphanumeric characters, '-', '_' or '.' (e.g. 'key.name',  or 'KEY_NAME',  or 'key-name', regex used for validation is '[-._a-zA-Z0-9]+'), data[s3-c-zrjnb-rs-w8bsq_2022-05-10T01:35:15Z.zip]: Invalid value: \"s3-c-zrjnb-rs-w8bsq_2022-05-10T01:35:15Z.zip\": a valid config key must consist of alphanumeric characters, '-', '_' or '.' (e.g. 'key.name',  or 'KEY_NAME',  or 'key-name', regex used for validation is '[-._a-zA-Z0-9]+'), data[s3-c-9r7sc-rs-lm544_2022-05-24T05:04:18Z.zip]: Invalid value: \"s3-c-9r7sc-rs-lm544_2022-05-24T05:04:18Z.zip\": a valid config key must consist of alphanumeric characters, '-', '_' or '.' (e.g. 'key.name',  or 'KEY_NAME',  or 'key-name', regex used for validation is '[-._a-zA-Z0-9]+'), data[s3-c-29422-rs-tvdh5_2022-05-12T17:25:15Z.zip]: Invalid value: \"s3-c-29422-rs-tvdh5_2022-05-12T17:25:15Z.zip\": a valid config key must consist of alphanumeric characters, '-', '_' or '.' (e.g. 'key.name',  or 'KEY_NAME',  or 'key-name', regex used for validation is '[-._a-zA-Z0-9]+'), data[s3-c-zrjnb-rs-wm9bp_2022-05-09T19:30:15Z.zip]: Invalid value: \"s3-c-zrjnb-rs-wm9bp_2022-05-09T19:30:15Z.zip\": a valid config key must consist of alphanumeric characters, '-', '_' or '.' (e.g. 'key.name',  or 'KEY_NAME',  or 'key-name', regex used for validation is '[-._a-zA-Z0-9]+'), data[s3-c-zrjnb-rs-p57tf_2022-05-09T13:25:15Z.zip]: Invalid value: \"s3-c-zrjnb-rs-p57tf_2022-05-09T13:25:15Z.zip\": a valid config key must consist of alphanumeric characters, '-', '_' or '.' (e.g. 'key.name',  or 'KEY_NAME',  or 'key-name', regex used for validation is '[-._a-zA-Z0-9]+'), data[s3-c-zrjnb-rs-hs4cn_2022-05-07T18:50:15Z.zip]: Invalid value: \"s3-c-zrjnb-rs-hs4cn_2022-05-07T18:50:15Z.zip\": a valid config key must consist of alphanumeric characters, '-', '_' or '.' (e.g. 'key.name',  or 'KEY_NAME',  or 'key-name', regex used for validation is '[-._a-zA-Z0-9]+'), data[s3-c-9r7sc-rs-dkwmc_2022-05-20T15:54:18Z.zip]: Invalid value: \"s3-c-9r7sc-rs-dkwmc_2022-05-20T15:54:18Z.zip\": a valid config key must consist of alphanumeric characters, '-', '_' or '.' (e.g. 'key.name',  or 'KEY_NAME',  or 'key-name', regex used for validation is '[-._a-zA-Z0-9]+'), data[s3-c-zrjnb-rs-6hxpk_2022-05-05T12:05:15Z.zip]: Invalid value: \"s3-c-zrjnb-rs-6hxpk_2022-05-05T12:05:15Z.zip\": a valid config key must consist of alphanumeric characters, '-', '_' or '.' (e.g. 'key.name',  or 'KEY_NAME',  or 'key-name', regex used for validation is '[-._a-zA-Z0-9]+'), data[s3-c-zrjnb-rs-vgffw_2022-05-07T06:40:15Z.zip]: Invalid value: \"s3-c-zrjnb-rs-vgffw_2022-05-07T06:40:15Z.zip\": a valid config key must consist of alphanumeric characters, '-', '_' or '.' (e.g. 'key.name',  or 'KEY_NAME',  or 'key-name', regex used for validation is '[-._a-zA-Z0-9]+'), data[s3-c-zrjnb-rs-b9x6p_2022-05-04T11:45:15Z.zip]: Invalid value: \"s3-c-zrjnb-rs-b9x6p_2022-05-04T11:45:15Z.zip\": a valid config key must consist of alphanumeric characters, '-', '_' or '.' (e.g. 'key.name',  or 'KEY_NAME',  or 'key-name', regex used for validation is '[-._a-zA-Z0-9]+'), data[s3-c-9r7sc-rs-zcl99_2022-05-24T23:19:18Z.zip]: Invalid value: \"s3-c-9r7sc-rs-zcl99_2022-05-24T23:19:18Z.zip\": a valid config key must consist of alphanumeric characters, '-', '_' or '.' (e.g. 'key.name',  or 'KEY_NAME',  or 'key-name', regex used for validation is '[-._a-zA-Z0-9]+'), data[s3-c-9r7sc-rs-9hdkw_2022-05-25T17:34:18Z.zip]: Invalid value: \"s3-c-9r7sc-rs-9hdkw_2022-05-25T17:34:18Z.zip\": a valid config key must consist of alphanumeric characters, '-', '_' or '.' (e.g. 'key.name',  or 'KEY_NAME',  or 'key-name', regex used for validation is '[-._a-zA-Z0-9]+'), data[s3-c-zrjnb-rs-n6glm_2022-05-06T18:30:15Z.zip]: Invalid value: \"s3-c-zrjnb-rs-n6glm_2022-05-06T18:30:15Z.zip\": a valid config key must consist of alphanumeric characters, '-', '_' or '.' (e.g. 'key.name',  or 'KEY_NAME',  or 'key-name', regex used for validation is '[-._a-zA-Z0-9]+'), data[s3-c-zrjnb-rs-rpvsv_2022-05-06T12:25:15Z.zip]: Invalid value: \"s3-c-zrjnb-rs-rpvsv_2022-05-06T12:25:15Z.zip\": a valid config key must consist of alphanumeric characters, '-', '_' or '.' (e.g. 'key.name',  or 'KEY_NAME',  or 'key-name', regex used for validation is '[-._a-zA-Z0-9]+'), data[s3-c-zrjnb-rs-rhsjh_2022-05-07T00:35:15Z.zip]: Invalid value: \"s3-c-zrjnb-rs-rhsjh_2022-05-07T00:35:15Z.zip\": a valid config key must consist of alphanumeric characters, '-', '_' or '.' (e.g. 'key.name',  or 'KEY_NAME',  or 'key-name', regex used for validation is '[-._a-zA-Z0-9]+'), data[s3-c-9r7sc-rs-8ncrn_2022-05-28T00:19:18Z.zip]: Invalid value: \"s3-c-9r7sc-rs-8ncrn_2022-05-28T00:19:18Z.zip\": a valid config key must consist of alphanumeric characters, '-', '_' or '.' (e.g. 'key.name',  or 'KEY_NAME',  or 'key-name', regex used for validation is '[-._a-zA-Z0-9]+'), data[s3-c-9r7sc-rs-5tkkc_2022-05-26T05:44:18Z.zip]: Invalid value: \"s3-c-9r7sc-rs-5tkkc_2022-05-26T05:44:18Z.zip\": a valid config key must consist of alphanumeric characters, '-', '_' or '.' (e.g. 'key.name',  or 'KEY_NAME',  or 'key-name', regex used for validation is '[-._a-zA-Z0-9]+'), data[s3-c-zrjnb-rs-jnj2v_2022-05-05T18:10:15Z.zip]: Invalid value: \"s3-c-zrjnb-rs-jnj2v_2022-05-05T18:10:15Z.zip\": a valid config key must consist of alphanumeric characters, '-', '_' or '.' (e.g. 'key.name',  or 'KEY_NAME',  or 'key-name', regex used for validation is '[-._a-zA-Z0-9]+'), data[s3-c-9r7sc-rs-jdgbj_2022-05-23T16:54:18Z.zip]: Invalid value: \"s3-c-9r7sc-rs-jdgbj_2022-05-23T16:54:18Z.zip\": a valid config key must consist of alphanumeric characters, '-', '_' or '.' (e.g. 'key.name',  or 'KEY_NAME',  or 'key-name', regex used for validation is '[-._a-zA-Z0-9]+'), data[s3-c-29422-rs-gvwzz_2022-05-11T23:10:15Z.zip]: Invalid value: \"s3-c-29422-rs-gvwzz_2022-05-11T23:10:15Z.zip\": a valid config key must consist of alphanumeric characters, '-', '_' or '.' (e.g. 'key.name',  or 'KEY_NAME',  or 'key-name', regex used for validation is '[-._a-zA-Z0-9]+'), data[s3-c-9r7sc-rs-vzzn7_2022-05-22T22:39:18Z.zip]: Invalid value: \"s3-c-9r7sc-rs-vzzn7_2022-05-22T22:39:18Z.zip\": a valid config key must consist of alphanumeric characters, '-', '_' or '.' (e.g. 'key.name',  or 'KEY_NAME',  or 'key-name', regex used for validation is '[-._a-zA-Z0-9]+'), data[s3-c-9r7sc-rs-9t9vq_2022-05-26T11:49:18Z.zip]: Invalid value: \"s3-c-9r7sc-rs-9t9vq_2022-05-26T11:49:18Z.zip\": a valid config key must consist of alphanumeric characters, '-', '_' or '.' (e.g. 'key.name',  or 'KEY_NAME',  or 'key-name', regex used for validation is '[-._a-zA-Z0-9]+'), data[s3-c-9r7sc-rs-7phln_2022-05-22T16:34:18Z.zip]: Invalid value: \"s3-c-9r7sc-rs-7phln_2022-05-22T16:34:18Z.zip\": a valid config key must consist of alphanumeric characters, '-', '_' or '.' (e.g. 'key.name',  or 'KEY_NAME',  or 'key-name', regex used for validation is '[-._a-zA-Z0-9]+'), data[s3-c-zrjnb-rs-9hjwq_2022-05-08T07:00:15Z.zip]: Invalid value: \"s3-c-zrjnb-rs-9hjwq_2022-05-08T07:00:15Z.zip\": a valid config key must consist of alphanumeric characters, '-', '_' or '.' (e.g. 'key.name',  or 'KEY_NAME',  or 'key-name', regex used for validation is '[-._a-zA-Z0-9]+'), data[s3-c-zrjnb-rs-pqvfz_2022-05-09T07:20:15Z.zip]: Invalid value: \"s3-c-zrjnb-rs-pqvfz_2022-05-09T07:20:15Z.zip\": a valid config key must consist of alphanumeric characters, '-', '_' or '.' (e.g. 'key.name',  or 'KEY_NAME',  or 'key-name', regex used for validation is '[-._a-zA-Z0-9]+'), data[s3-c-zrjnb-rs-p4q5t_2022-05-08T19:10:15Z.zip]: Invalid value: \"s3-c-zrjnb-rs-p4q5t_2022-05-08T19:10:15Z.zip\": a valid config key must consist of alphanumeric characters, '-', '_' or '.' (e.g. 'key.name',  or 'KEY_NAME',  or 'key-name', regex used for validation is '[-._a-zA-Z0-9]+'), data[s3-c-zrjnb-rs-v2gl8_2022-05-10T07:40:15Z.zip]: Invalid value: \"s3-c-zrjnb-rs-v2gl8_2022-05-10T07:40:15Z.zip\": a valid config key must consist of alphanumeric characters, '-', '_' or '.' (e.g. 'key.name',  or 'KEY_NAME',  or 'key-name', regex used for validation is '[-._a-zA-Z0-9]+'), data[s3-c-zrjnb-rs-57fzg_2022-05-11T01:55:15Z.zip]: Invalid value: \"s3-c-zrjnb-rs-57fzg_2022-05-11T01:55:15Z.zip\": a valid config key must consist of alphanumeric characters, '-', '_' or '.' (e.g. 'key.name',  or 'KEY_NAME',  or 'key-name', regex used for validation is '[-._a-zA-Z0-9]+'), data[s3-c-zrjnb-rs-22h5c_2022-05-08T00:55:15Z.zip]: Invalid value: \"s3-c-zrjnb-rs-22h5c_2022-05-08T00:55:15Z.zip\": a valid config key must consist of alphanumeric characters, '-', '_' or '.' (e.g. 'key.name',  or 'KEY_NAME',  or 'key-name', regex used for validation is '[-._a-zA-Z0-9]+'), data[s3-c-zrjnb-rs-vcw6f_2022-05-04T17:50:15Z.zip]: Invalid value: \"s3-c-zrjnb-rs-vcw6f_2022-05-04T17:50:15Z.zip\": a valid config key must consist of alphanumeric characters, '-', '_' or '.' (e.g. 'key.name',  or 'KEY_NAME',  or 'key-name', regex used for validation is '[-._a-zA-Z0-9]+'), data[s3-c-9r7sc-rs-wg476_2022-05-25T23:39:18Z.zip]: Invalid value: \"s3-c-9r7sc-rs-wg476_2022-05-25T23:39:18Z.zip\": a valid config key must consist of alphanumeric characters, '-', '_' or '.' (e.g. 'key.name',  or 'KEY_NAME',  or 'key-name', regex used for validation is '[-._a-zA-Z0-9]+'), data[s3-c-zrjnb-rs-ttpk8_2022-05-04T05:40:15Z.zip]: Invalid value: \"s3-c-zrjnb-rs-ttpk8_2022-05-04T05:40:15Z.zip\": a valid config key must consist of alphanumeric characters, '-', '_' or '.' (e.g. 'key.name',  or 'KEY_NAME',  or 'key-name', regex used for validation is '[-._a-zA-Z0-9]+'), data[s3-c-9r7sc-rs-nbnsz_2022-05-25T05:24:18Z.zip]: Invalid value: \"s3-c-9r7sc-rs-nbnsz_2022-05-25T05:24:18Z.zip\": a valid config key must consist of alphanumeric characters, '-', '_' or '.' (e.g. 'key.name',  or 'KEY_NAME',  or 'key-name', regex used for validation is '[-._a-zA-Z0-9]+'), data[s3-c-zrjnb-rs-49m2w_2022-05-07T12:45:15Z.zip]: Invalid value: \"s3-c-zrjnb-rs-49m2w_2022-05-07T12:45:15Z.zip\": a valid config key must consist of alphanumeric characters, '-', '_' or '.' (e.g. 'key.name',  or 'KEY_NAME',  or 'key-name', regex used for validation is '[-._a-zA-Z0-9]+'), data[s3-c-9r7sc-rs-ltg9p_2022-05-22T04:24:18Z.zip]: Invalid value: \"s3-c-9r7sc-rs-ltg9p_2022-05-22T04:24:18Z.zip\": a valid config key must consist of alphanumeric characters, '-', '_' or '.' (e.g. 'key.name',  or 'KEY_NAME',  or 'key-name', regex used for validation is '[-._a-zA-Z0-9]+'), data[s3-c-9r7sc-rs-4wvrm_2022-05-27T12:09:18Z.zip]: Invalid value: \"s3-c-9r7sc-rs-4wvrm_2022-05-27T12:09:18Z.zip\": a valid config key must consist of alphanumeric characters, '-', '_' or '.' (e.g. 'key.name',  or 'KEY_NAME',  or 'key-name', regex used for validation is '[-._a-zA-Z0-9]+')]"
Jun 03 20:29:25 ip-10-242-63-234.us-east-2.compute.internal rke2[13846]: time="2022-06-03T20:29:25Z" level=info msg="Stopped tunnel to 127.0.0.1:9345"
Jun 03 20:29:25 ip-10-242-63-234.us-east-2.compute.internal rke2[13846]: time="2022-06-03T20:29:25Z" level=info msg="Connecting to proxy" url="wss://10.242.63.234:9345/v1-rke2/connect"
Jun 03 20:29:25 ip-10-242-63-234.us-east-2.compute.internal rke2[13846]: time="2022-06-03T20:29:25Z" level=info msg="Proxy done" err="context canceled" url="wss://127.0.0.1:9345/v1-rke2/connect"
Jun 03 20:29:25 ip-10-242-63-234.us-east-2.compute.internal rke2[13846]: time="2022-06-03T20:29:25Z" level=info msg="error in remotedialer server [400]: websocket: close 1006 (abnormal closure): unexpected EOF"
```

**Comment by brandond** [comment]
In the case above, I bet they’re using the same S3 bucket/prefix for a mix of RKE1 and RKE2 clusters, and RKE2 fails to stuff all the RKE1 snapshots found in the s3 bucket into the configmap because the filenames aren’t valid keys. We should fix this on the RKE2 side and/or document that users shouldn't point multiple clusters to the same bucket/prefix.

**Comment by snasovich** [comment]
Pushing this one out of 2.6.6, need follow-up response from @ADustyOldMuffin

**Comment by ADustyOldMuffin** [comment]
@Oats87 and @brandond Here are our exact logs from the issue. So the name in question has been removed and subbed for a non identifying one but it's the same format.

`fleet-default/our-cluster-name` is the cluster name, but the snapshot was `our-cluster-name-.-s3` for some reason (we didn't change it, and once removed from the config map it worked fine).

```
2022/05/23 20:57:02 [ERROR] error syncing 'kube-system/rke2-etcd-snapshots': handler snapshotbackpopulate: rkecluster fleet-default/our-cluster-name: error while creating s3 etcd snapshot fleet-default/our-cluster-name-.-s3: ETCDSnapshot.rke.cattle.io "our-cluster-name-.-s3" is invalid: metadata.name: Invalid value: "our-cluster-name-.-s3": a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*'), requeuing
```

**Comment by ADustyOldMuffin** [comment]
Ah okay, well that was the name causing the issue and I believe it was auto discovered.

**Comment by Oats87** [comment]
The necessary fix on the Rancher side is probably going to be to have to sanitize the `SnapshotFile.Name` in the `snapshotbackpopulate` controller, for generation of CRDs.

We'll schedule this for the next `2.6.x` release, and make sure to test with a snapshot in S3 formatted like the one you provided. 

Thanks for the response @ADustyOldMuffin

**Comment by ADustyOldMuffin** [comment]
Sounds good, we unfortunately will have to write automation to cleanse these values as they keep appearing in the config map and we're unsure why.

**Comment by brandond** [comment]
Have you checked the S3 bucket to see if there are still snapshots in there with the problematic file name? The snapshot controller on the rke2 side will keep re-adding those snapshots to the confimap as long as the files exist in the bucket or on disk on the nodes. Removing them from the bucket and/or nodes is probably the correct thing to do, as opposed to playing whack-a-mole with them as they reappear in the configmap.

**Comment by ADustyOldMuffin** [comment]
Alright, so I believe we've tracked down where this occurs possibly. All of the files in S3 are fine with no malformed names (even when the one in the configmap exists), but this seems to occur every time we either upgrade RKE2, or add a new cluster that uses RKE2. I'm thinking something on the initialization causes an incorrect name for the first snapshot possibly. 

Was the leak ever actually found inside of Rancher itself? The pods for Rancher were the ones causing issues where they'd grow in memory usage until they tipped the node over.

**Comment by brandond** [comment]
There was an issue in older versions of RKE2 where it would snapshot too early in the startup process, before all the node info was available - which would explain the empty fields in the filename template. This could happen any time a server is restarted, not just during upgrades. I believe that has been resolved though...

**Comment by ADustyOldMuffin** [comment]
Yeah this would be with version `v1.22.9+rke2r2` that we've seen this happening. Does anyone have a link handy to the area of code in Rancher that handles the processing of these snapshots?

**Comment by brandond** [comment]
https://github.com/rancher/rancher/blob/release/v2.6/pkg/controllers/managementuser/snapshotbackpopulate/snapshotbackpopulate.go I'm guessing?

**Comment by ADustyOldMuffin** [comment]
Cool, I'll dig through and see what I can find in terms of possible leaks.

**Comment by ratschance** [comment]
Just to add a bit more information as we have been investigating this further, when we see the previously mentioned log:

```
2022/05/23 20:57:02 [ERROR] error syncing 'kube-system/rke2-etcd-snapshots': handler snapshotbackpopulate: rkecluster fleet-default/our-cluster-name: error while creating s3 etcd snapshot fleet-default/our-cluster-name-.-s3: ETCDSnapshot.rke.cattle.io "our-cluster-name-.-s3" is invalid: metadata.name: Invalid value: "our-cluster-name-.-s3": a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*'), requeuing
```

we see that it is unhappy with a newly added entry in the `rke2-etcd-snapshots` configmap:

```
s3-.: '{"name":".","metadata":"SNIP","message":"SNIP","nodeName":"s3","createdAt":"2022-07-08T02:00:00Z","status":"failed","s3Config":{"endpoint":"SNIP","skipSSLVerify":true,"bucket":"SNIP","region":"SNIP","folder":"SNIP"},"compressed":false}'
```
where the `message` field is the base64 encoded string `Put "https://SNIP/etcd-snapshot-SNIP-1657245600": context deadline exceeded`

I believe that the root cause of the invalid name is https://github.com/k3s-io/k3s/blob/master/pkg/etcd/s3.go#L116 since it's reading from the `uploadInfo` that is returned from FPutObject with an `err` in this case, and if it were an empty string then `filepath.Base` would convert it to `.`.

However I believe the main issue here is that the default s3 timeout (30 seconds?) for downstream rke2 clusters is too small for the uncompressed rke2 snapshots in our case, and it would be nice if rke2's `etcd-s3-timeout` [configuration option](https://github.com/rancher/rke2/blob/v1.22.9%2Brke2r2/pkg/cli/cmds/server.go#L134) were bubbled up through rancher (potentially via https://github.com/rancher/rancher/blob/release/v2.6/pkg/apis/rke.cattle.io/v1/etcd.go#L16-L24 and https://github.com/rancher/rancher/blob/release/v2.6/pkg/provisioningv2/rke2/planner/s3args.go#L40)

**Comment by brandond** [comment]
It sounds like perhaps it's trying to process snapshots where the `"status":"failed"` as well, which would be incorrect?

There is also some evidence to suggest that compression isn't working properly for scheduled backups, see https://github.com/rancher/rke2/issues/3109 which may be compounding the issue for users that need compression in order to get snapshots uploaded in a timely manner.

**Comment by neurodrone** [comment]
Thank you for working on this @brandond! Can we expect this change to be a part of `v2.6.7` release?

**Comment by Oats87** [comment]
> It sounds like perhaps it's trying to process snapshots where `"status":"failed"` as well, which would be incorrect?

That's not incorrect. We want to process failed snapshots in order to "trickle" feedback to the user that there are failed snapshots.

**Comment by Oats87** [comment]
> However I believe the main issue here is that the default s3 timeout (30 seconds?) for downstream rke2 clusters is too small for the uncompressed rke2 snapshots in our case, and it would be nice if rke2's `etcd-s3-timeout` [configuration option](https://github.com/rancher/rke2/blob/v1.22.9%2Brke2r2/pkg/cli/cmds/server.go#L134) were bubbled up through rancher (potentially via https://github.com/rancher/rancher/blob/release/v2.6/pkg/apis/rke.cattle.io/v1/etcd.go#L16-L24 and https://github.com/rancher/rancher/blob/release/v2.6/pkg/provisioningv2/rke2/planner/s3args.go#L40)

Theoretically, you *can* bubble this down, through the use of a `machineSelectorConfig` + `machineSelector`. You can define an etcd-specific `machineSelectorConfig` that populates the `etcd-s3-config` in the config file, as K3s/RKE2 will just ignore the flag if it doesn't apply.

**Comment by jferrazbr** [comment]
Here is an update and closure note for this issue. The original panic came from malformed snapshot object keys flowing into Rancher’s cleanup logic. This was addressed in 2022 in two places: upstream in K3s by sanitizing snapshot filenames used in ConfigMap keys ([k3s-io/k3s#5702](https://github.com/k3s-io/k3s/pull/5702), referenced from [k3s-io/k3s#5754](https://github.com/k3s-io/k3s/issues/5754)), and in Rancher by replacing invalid characters during etcd-snapshots backpopulation ([rancher/rancher#38316](https://github.com/rancher/rancher/pull/38316), referenced from [rancher/rancher#38304](https://github.com/rancher/rancher/issues/38304)). With those fixes, malformed S3 keys are normalized instead of triggering panics; this was re-tested on latest version (v2.13-head) and the behavior remains stable.

**Additional Context:** in 2025 the etcd snapshot architecture was remodeled to eliminate the ConfigMap size bottleneck (see RKE2 report of 1 MiB limit: [rancher/rke2#4495](https://github.com/rancher/rke2/issues/4495)). As of Rancher v2.11.0, Rancher now populates snapshots by listing the `etcdsnapshotfile.k3s.cattle.io` CRs in downstream clusters rather than scraping the CLI/ConfigMap ([rancher/rancher#49158](https://github.com/rancher/rancher/pull/49158), referenced from [rancher/rancher#44452](https://github.com/rancher/rancher/issues/44452)). This resolves the scalability issue while preserving the 2022 sanitization fixes, so malformed names do not break the listing under the new model.

**Comment by snasovich** [comment]
@jferrazbr , thank you - sent to "Ready for QA" for QA to formally validate and close this issue.

**Comment by navsalehi** [comment]
I tested this issue on Rancher `v2.13-5c77a6ca078f389e58a1a465dc32ba4a44ed4b4d-head `and the problem is still reproducible.

**Steps I followed:**

1. Deployed Rancher on a fresh RKE2 cluster.
2. Created a downstream cluster.
3. Uploaded/renamed an etcd snapshot with an invalid name (containing unsupported characters).
4. Monitored the Rancher pod logs in the cattle-system namespace.

**Observed result:**
Rancher repeatedly logs the same error and keeps requeuing the invalid snapshot instead of ignoring it.

Example log:
```
ETCDSnapshot.rke.cattle.io "tst-something.something.-.s3-.com-s3" is invalid: metadata.name: Invalid value: ...
requeuing
```

So the issue is **still occurring** in the latest head version.

**Comment by brandond** [comment]
> Uploaded/renamed an etcd snapshot with an invalid name (containing unsupported characters).

Please provide more details on how you are doing this. Are you directly manipulating files in the S3 bucket?

What do you see in the downstream cluster's `kubectl get etcdsnapshotfile -o yaml` output after you create the oddly-named file?

**Comment by jferrazbr** [comment]
Quick mea culpa on my previous test: I had only appended invalid characters to a valid snapshot name, which didn't actually violate RFC-1123. When the entire filename is malformed, the controller derives an `ETCDSnapshot.rke.cattle.io` `metadata.name` that isn't RFC-1123 compliant. The Kubernetes API rejects the Lasso Create call, and the controller requeues, then we have the repeated log error rather than a panic.

In short: the panic is gone, but the malformed name can still produce an invalid RFC-1123 name from the S3 key, which causes the persistent error/requeue loop.

> Are you directly manipulating files in the S3 bucket?

Yes, to simulate the issue we are directly renaming a file in S3 with a malformed name

> What do you see in the downstream cluster's kubectl get etcdsnapshotfile -o yaml output after you create the oddly-named file?

```
- apiVersion: k3s.cattle.io/v1
  kind: ETCDSnapshotFile
  metadata:
    creationTimestamp: "2025-10-17T11:02:02Z"
    finalizers:
    - wrangler.cattle.io/managed-etcd-snapshots-controller
    generation: 1
    labels:
      etcd.rke2.cattle.io/snapshot-storage-node: s3
    name: s3-etcd-snapshot-jferraz-test-pool1-j97k8-8htm7-1760698915-78b151
    resourceVersion: "5555"
    uid: c4b958b7-35ed-4a9b-8820-423dc67be1d5
  spec:
    location: s3://my-bucket/etcd-snaps/something.something.-.s3-.com
    nodeName: jferraz-test-pool1-j97k8-8htm7
    s3:
      bucket: my-bucket
      endpoint: s3.amazonaws.com
      prefix: etcd-snaps
      region: us-east-2
      skipSSLVerify: true
    snapshotName: something.something.-.s3-.com
  status:
    creationTime: "2025-10-17T11:01:55Z"
    readyToUse: true
    size: "28512288"
```

Logs:

```
2025/10/17 08:02:02 [DEBUG] [snapshotbackpopulate] rkecluster fleet-default/jferraz-test: creating snapshot jferraz-test-something.something.-.s3-.com-s3
2025/10/17 08:02:02 [ERROR] error syncing 's3-etcd-snapshot-jferraz-test-pool1-j97k8-8htm7-1760698915-78b151': handler snapshotbackpopulate: ETCDSnapshot.rke.cattle.io "jferraz-test-something.something.-.s3-.com-s3" is invalid: metadata.name: Invalid value: "jferraz-test-something.something.-.s3-.com-s3": a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*'), requeuing

```

**Comment by brandond** [comment]
Here is the code that K3s and RKE2 use to generate a Kubernetes resource name for the snapshots, it sounds like perhaps Rancher needs to do something similar instead of just using the snapshotName (filename) as the resource name.

https://github.com/k3s-io/k3s/blob/517df31f65b836a43b1428684bf920bbfba18643/pkg/etcd/snapshot/types.go#L89-L115

**Comment by navsalehi** [comment]
Validated that this issue has been addressed in `v2.14-eaf0dd11d01fae4d3da8ab8a2212a5c99548f4c3-head`. The test results have been recorded in Qase test run 5736. See below the test scenarios tested:
|#|Scenario|Test Result|
|---|---|---|
|1|Verify Rancher Handles Malformed RKE2 ETCD Snapshot Names Without Memory Leak|:white_check_mark:
