### ISSUE TITLE
[BUG] Rancher panics when provisioning rke2/k3s cluster without associated dynamic schema

### ISSUE THREAD

**Issue by jakefhyde** [rancher/rancher#41145]
**Rancher Server Setup**
- Rancher version: v2.7.2

**Information about the Cluster**
- Cluster Type (Local/Downstream): downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): elemental

**Describe the bug**

On upgrade from v2.7.1 -> v2.7.2 with an elemental cluster provisioned, Rancher panics because the machine config does not have an associated dynamic schema.

**To Reproduce**

1. Provision elemental cluster on v2.7.1
2. Upgrade to v2.7.2

**Result**

Rancher panics

**Expected Result**

Rancher should not panic or try to migrate elemental cluster

**Screenshots**

**Additional context**

https://github.com/rancher/elemental/issues/780

A workaround exists, by defining a dynamic schema that maps to the expected machine config. This may also affect harvester setups.

There are logs like:

```
2023/04/13 15:46:17 [ERROR] failed to call leader func: [dynamicschemas.management.cattle.io](http://dynamicschemas.management.cattle.io/) “machineinventoryselectortemplate” not found

panic: indexer conflict: map[byPod:{}]

goroutine 2851 [running]:
k8s.io/apimachinery/pkg/util/runtime.Must(...)
	/go/pkg/mod/k8s.io/apimachinery@v0.25.4/pkg/util/runtime/runtime.go:172
github.com/rancher/rancher/pkg/generated/controllers/catalog.cattle.io/v1.(*operationCache).AddIndexer(0xc01c802a20, {0x3f0d10e, 0x5}, 0x41ebaa8)
	/go/src/github.com/rancher/rancher/pkg/generated/controllers/catalog.cattle.io/v1/operation.go:247 +0xe5
github.com/rancher/rancher/pkg/controllers/dashboard/helm.RegisterOperations({0x4830500, 0xc023d94fc0}, {0x4871610, 0xc0017e2780}, {0x48561a0, 0xc01e461c00}, {0x4853c38?, 0xc01e461c70?})
	/go/src/github.com/rancher/rancher/pkg/controllers/dashboard/helm/operations.go:42 +0x1c6
github.com/rancher/rancher/pkg/controllers/dashboard/helm.Register({0x4830500, 0xc023d94fc0}, 0xc0019f0500)
	/go/src/github.com/rancher/rancher/pkg/controllers/dashboard/helm/register.go:22 +0x2d8
github.com/rancher/rancher/pkg/controllers/dashboard.Register({0x4830500?, 0xc023d94fc0}, 0xc0019f0500, 0xa0?, {0x0, 0x0})
	/go/src/github.com/rancher/rancher/pkg/controllers/dashboard/controller.go:25 +0x65
github.com/rancher/rancher/pkg/rancher.(*Rancher).Start.func1.1({0x4830500?, 0xc023d94fc0?})
	/go/src/github.com/rancher/rancher/pkg/rancher/rancher.go:266 +0x45
github.com/rancher/rancher/pkg/wrangler.(*Context).StartWithTransaction(0xc0019f0500, {0x482fd90?, 0xc010e4a380}, 0xc01c567f58)
	/go/src/github.com/rancher/rancher/pkg/wrangler/context.go:182 +0xdf
github.com/rancher/rancher/pkg/rancher.(*Rancher).Start.func1({0x482fd90, 0xc010e4a380})
	/go/src/github.com/rancher/rancher/pkg/rancher/rancher.go:265 +0xd9
github.com/rancher/wrangler/pkg/leader.(*Manager).OnLeader.func1()
	/go/pkg/mod/github.com/rancher/wrangler@v1.1.0/pkg/leader/manager.go:51 +0x92
created by github.com/rancher/wrangler/pkg/leader.(*Manager).OnLeader
	/go/pkg/mod/github.com/rancher/wrangler@v1.1.0/pkg/leader/manager.go:48 +0x72
```

**Comment by janeczku** [comment]
To workaround this issue, create the following resource in the RMS cluster:

```
kubectl apply -f - <<EOF
kind: DynamicSchema
apiVersion: management.cattle.io/v3
metadata:
  name: machineinventoryselectortemplate
EOF
```

**Comment by markusewalker** [comment]
Tested this against RKE1, RKE2 and K3S downstream node driver clusters and was unable to reproduce. This appears to be specific to Elemental. Unassigning myself as this does not appear to be a team 2 issue.

**Comment by Sahota1225** [comment]
@kkaempf - can elemental team test this.

**Comment by roderickgreen** [comment]
i get this `panic: indexer conflict: map[byPod:{}]` too trying to upgrade a docker install from 2.7.1 to either 2.7.2 or 2.7.3.

**Comment by jakefhyde** [comment]
@juadk This is not released any version of rancher (2.7.2 or 2.7.3).

**Comment by juadk** [comment]
ah sorry, during the Elemental meeting, we though the fix was released in 2.7.3, sorry, we totally misunderstood...

**Comment by juadk** [comment]
I did the same test but this time, I directly updated the rancher deployment with `v2.7-64a851660dfb043b6a1621bfbc3b902385f56924-linux-amd64` and the pod stayed alive.
I think we are good now.

**Comment by roderickgreen** [comment]
i'm still getting `panic: indexer conflict: map[byPod:{}]` crashes when trying to update a docker install from 2.7.1 to 2.7.4.

**Comment by roderickgreen** [comment]
> @roderickgreen The fix for this will be in 2.7.5.

just confirming that the upgrade of our docker install to 2.7.5 succeeded.  thanks!

**Comment by furkatgofurov7** [comment]
I am still seeing this in 2.7.5 in Rancher installed using Helm
