### ISSUE TITLE
Ability to link rancher-server directly to rancher/agent

### ISSUE THREAD

**Issue by julianxhokaxhiu** [rancher/rancher#4149]
Hi,

first of all let me thank you for this amazing product. It's really awesome the way you born it, and I hope it will continue to shy like it's doing now.

I'm creating this issue because I found after a whole day of doing test and trying to follow all your [run.sh](https://github.com/rancher/rancher/blob/master/agent/run.sh) script, to understand what I was doing wrong.

First allow me to make it clear that my goal is to run Rancher behind a reverse proxy, which is working quite well since I can access the backend through [http://docker.lan/](http://docker.lan/), but the Agent registration does not. The Rancher Server is launched on purpose without a mapped port on the host, so because of this I'm linking the agent docker with the server one to share the hostname and make it pingable.

Unfortunately somehow something is going wrong on your setup script and the registration process cannot complete. If you could help on solving this I'll be very glad.

The backend url is configured correctly, so I guess or I am missing something, or something is missing in your script :)

![rancher](https://cloud.githubusercontent.com/assets/1237070/14057023/b7d1a44e-f2f4-11e5-9cfc-9ec7a4379348.png)

Thanks in advance,
Julian

P.S.: is there a way to set that field through an environment variable when I launch the Rancher Server? Or is it only configurable through the web panel? Would be awesome to have a CLI interface for that, so I could make it more automatic.

---

Rancher Version: 0.63.1

Docker Version: 1.10.3

OS: Arch Linux

Steps to Reproduce: 

``` bash
# Install Automatic Reverse proxy manager
docker run \
    --restart=always \
    --name=docker-auto-reverse-proxy \
    -d \
    -p 80:80 \
    -v /var/run/docker.sock:/tmp/docker.sock:ro \
    jwilder/nginx-proxy

# Install Rancher Server
docker run \
    --restart=always \
    --name=rancher-server \
    -d \
    -e "VIRTUAL_HOST=docker.lan" \
    -e "VIRTUAL_PORT=8080" \
    rancher/server

# Register Rancher Agent
docker run \
    --name=rancher-agent \
    --link=rancher-server \
    --privileged \
    -d \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -v /var/lib/rancher:/var/lib/rancher \
    rancher/agent http://rancher-server:8080/
```

Results: 

```
INFO: Running Agent Registration Process, CATTLE_URL=http://rancher-server:8080/
INFO: Checking for Docker version >= 1.6.0
INFO: Found Server version: 1.10.3
INFO: docker version: Client version: 1.6.0
INFO: docker version: Client API version: 1.18
INFO: docker version: Go version (client): go1.4.2
INFO: docker version: Git commit (client): 4749651
INFO: docker version: OS/Arch (client): linux/amd64
INFO: docker version: Server version: 1.10.3
INFO: docker version: Server API version: 1.22
INFO: docker version: Go version (server): go1.5.3
INFO: docker version: Git commit (server): 20f81dd
INFO: docker version: OS/Arch (server): linux/amd64
INFO: docker info: Containers: 3
INFO: docker info: Images: 4
INFO: docker info: Storage Driver: devicemapper
INFO: docker info: Pool Name: docker-8:1-1049510-pool
INFO: docker info: Pool Blocksize: 65.54 kB
INFO: docker info: Base Device Size: 10.74 GB
INFO: docker info: Backing Filesystem: xfs
INFO: docker info: Data file: /dev/loop0
INFO: docker info: Metadata file: /dev/loop1
INFO: docker info: Data Space Used: 2.194 GB
INFO: docker info: Data Space Total: 107.4 GB
INFO: docker info: Data Space Available: 101.8 GB
INFO: docker info: Metadata Space Used: 3.805 MB
INFO: docker info: Metadata Space Total: 2.147 GB
INFO: docker info: Metadata Space Available: 2.144 GB
INFO: docker info: Udev Sync Supported: true
INFO: docker info: Deferred Removal Enabled: false
INFO: docker info: Deferred Deletion Enabled: false
INFO: docker info: Deferred Deleted Device Count: 0
INFO: docker info: Data loop file: /var/lib/docker/devicemapper/devicemapper/data
INFO: docker info: Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
INFO: docker info: Library Version: 1.02.120 (2016-03-11)
INFO: docker info: Execution Driver: native-0.2
INFO: docker info: Kernel Version: 4.4.5-1-ARCH
INFO: docker info: Operating System: Arch Linux
INFO: docker info: CPUs: 1
INFO: docker info: Total Memory: 1.942 GiB
INFO: docker info: Name: dockerhost
INFO: docker info: ID: VOLY:AUCE:62AZ:S22V:A6EM:KP5L:QE3I:VKGY:2GFL:IFRT:CNNO:XPIW
INFO: docker info: Http Proxy:
INFO: docker info: Https Proxy:
INFO: docker info: No Proxy:
INFO: Attempting to connect to: http://rancher-server:8080/
INFO: http://rancher-server:8080/ is accessible
INFO: Inspecting host capabilities
INFO: System: true
INFO: Host writable: true
INFO: Token: xxxxxxxx
INFO: Running registration
INFO: Printing Environment
INFO: ENV: CATTLE_ACCESS_KEY=5FCA4B243CA245FA8FEC
INFO: ENV: CATTLE_AGENT_IP=172.17.0.4
INFO: ENV: CATTLE_HOME=/var/lib/cattle
INFO: ENV: CATTLE_REGISTRATION_ACCESS_KEY=registrationToken
INFO: ENV: CATTLE_REGISTRATION_SECRET_KEY=xxxxxxx
INFO: ENV: CATTLE_SECRET_KEY=xxxxxxx
INFO: ENV: CATTLE_SYSTEMD=true
INFO: ENV: CATTLE_URL=http://rancher-server:8080/v1
INFO: ENV: DETECTED_CATTLE_AGENT_IP=172.17.0.4
INFO: ENV: RANCHER_AGENT_IMAGE=rancher/agent
INFO: ENV: RANCHER_SERVER_ENV_CATTLE_CATTLE_VERSION=v0.155.1
INFO: ENV: RANCHER_SERVER_ENV_CATTLE_DB_CATTLE_DATABASE=mysql
INFO: ENV: RANCHER_SERVER_ENV_CATTLE_HOME=/var/lib/cattle
INFO: ENV: RANCHER_SERVER_ENV_CATTLE_HOST_API_PROXY_MODE=embedded
INFO: ENV: RANCHER_SERVER_ENV_CATTLE_RANCHER_COMPOSE_VERSION=v0.7.2
INFO: ENV: RANCHER_SERVER_ENV_CATTLE_RANCHER_SERVER_IMAGE=v0.63.1
INFO: ENV: RANCHER_SERVER_ENV_CATTLE_USE_LOCAL_ARTIFACTS=true
INFO: ENV: RANCHER_SERVER_ENV_DEBIAN_FRONTEND=noninteractive
INFO: ENV: RANCHER_SERVER_ENV_DEFAULT_CATTLE_API_UI_INDEX=//releases.rancher.com/ui/0.95.0
INFO: ENV: RANCHER_SERVER_ENV_DEFAULT_CATTLE_CATALOG_EXECUTE=true
INFO: ENV: RANCHER_SERVER_ENV_DEFAULT_CATTLE_COMPOSE_EXECUTOR_EXECUTE=true
INFO: ENV: RANCHER_SERVER_ENV_DEFAULT_CATTLE_MACHINE_EXECUTE=true
INFO: ENV: RANCHER_SERVER_ENV_DEFAULT_CATTLE_RANCHER_COMPOSE_DARWIN_URL=https://releases.rancher.com/compose/beta/v0.7.2/rancher-compose-darwin-amd64-v0.7.2.tar.gz
INFO: ENV: RANCHER_SERVER_ENV_DEFAULT_CATTLE_RANCHER_COMPOSE_LINUX_URL=https://releases.rancher.com/compose/beta/v0.7.2/rancher-compose-linux-amd64-v0.7.2.tar.gz
INFO: ENV: RANCHER_SERVER_ENV_DEFAULT_CATTLE_RANCHER_COMPOSE_WINDOWS_URL=https://releases.rancher.com/compose/beta/v0.7.2/rancher-compose-windows-386-v0.7.2.zip
INFO: ENV: RANCHER_SERVER_ENV_S6_SERVICE_DIR=/service
INFO: ENV: RANCHER_SERVER_ENV_VIRTUAL_HOST=docker.lan
INFO: ENV: RANCHER_SERVER_ENV_VIRTUAL_PORT=8080
INFO: ENV: RANCHER_SERVER_ENV_no_proxy=localhost,127.0.0.1,localaddress,.localdomain.com
INFO: ENV: RANCHER_SERVER_NAME=/rancher-agent/rancher-server
INFO: ENV: RANCHER_SERVER_PORT=tcp://172.17.0.3:3306
INFO: ENV: RANCHER_SERVER_PORT_3306_TCP=tcp://172.17.0.3:3306
INFO: ENV: RANCHER_SERVER_PORT_3306_TCP_ADDR=172.17.0.3
INFO: ENV: RANCHER_SERVER_PORT_3306_TCP_PORT=3306
INFO: ENV: RANCHER_SERVER_PORT_3306_TCP_PROTO=tcp
INFO: ENV: RANCHER_SERVER_PORT_8080_TCP=tcp://172.17.0.3:8080
INFO: ENV: RANCHER_SERVER_PORT_8080_TCP_ADDR=172.17.0.3
INFO: ENV: RANCHER_SERVER_PORT_8080_TCP_PORT=8080
INFO: ENV: RANCHER_SERVER_PORT_8080_TCP_PROTO=tcp
INFO: Deleting container rancher-agent
```

Expected:

The agent should just register fine and everything should work out-of-the-box

**Comment by deniseschannon** [comment]
You can't add in `--name rancher-agent` to the command because we end up launching a total of 3 rancher/agent containers. The first one is just a docker named rancher/agent, the second is a rancher-agent-state and the third one (only left running) is named rancher/agent. 

You'll also need to get the token that will affiliate which environment the host will be part of. If you go to **Add Host** in the Infrastructure section. The **Custom** option, will show you the token. 
Also, you should use the use the tagged version of the rancher/agent (also in the same command) when launching the host as we tag specific versions of rancher/agent based on which rancher/server. 

Have you taken a look at our troubleshooting docs? 

http://docs.rancher.com/rancher/faqs/troubleshooting/

**Comment by ibuildthecloud** [comment]
@julianxhokaxhiu Just to answer one of your questions.  You can set the "Host Registration URL" with `-e CATTLE_API_HOST=https://rancher-server`.

**Comment by julianxhokaxhiu** [comment]
First of all thank you very much for the pro-top @ibuildthecloud ! Really awesome and works amazing :)

@deniseschannon thank you too, I choose the same name by mistake, I didn't knew it was already used by you! Although now I fixed the script like this:

```
# Install Rancher Server
docker run \
    --restart=always \
    --name=rancher-server \
    -d \
    -e "CATTLE_API_HOST=http://rancher-server:8080" \
    -e "VIRTUAL_HOST=docker.lan" \
    -e "VIRTUAL_PORT=8080" \
    rancher/server:v0.63.1

# Register Rancher Agent
docker run \
    --name=register-rancher-agent \
    --link=rancher-server \
    --privileged \
    -d \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -v /var/lib/rancher:/var/lib/rancher \
    rancher/agent:v0.10.0 http://rancher-server:8080/
```

now as output I get 

```
~ # docker logs -f rancher-agent
INFO: Starting agent for 8B6F002EFD5A9DFB66E3
INFO: Starting agent for 8B6F002EFD5A9DFB66E3
INFO: Starting agent for 8B6F002EFD5A9DFB66E3
INFO: Starting agent for 8B6F002EFD5A9DFB66E3
INFO: Starting agent for 8B6F002EFD5A9DFB66E3
INFO: Starting agent for 8B6F002EFD5A9DFB66E3
INFO: Starting agent for 8B6F002EFD5A9DFB66E3
INFO: Starting agent for 8B6F002EFD5A9DFB66E3
INFO: Starting agent for 8B6F002EFD5A9DFB66E3
INFO: Starting agent for 8B6F002EFD5A9DFB66E3
```

What am I missing? I also fixed the version now ( hardcoded via tags ) but it still doesn't work :(

**Comment by julianxhokaxhiu** [comment]
I think I know what I am missing: the `rancher-agent` is not linked to `rancher-server` in my case so the host is not reachable from the agent. Is there a way to pass custom arguments to the `docker run` script inside `run.sh` ?

**Comment by deniseschannon** [comment]
You are still missing the registration token necessary to connect which environment the launch needs to be added. 

For example, when I click on "Add Host" and the custom option in one of my environment, my command looks like this:
```
sudo docker run -d --privileged -v /var/run/docker.sock:/var/run/docker.sock -v /var/lib/rancher:/var/lib/rancher rancher/agent:v0.11.0 http://<server_ip>:8080/v1/scripts/2FF1C29DCCEECD13CA68:1459051200000:yvlcYXtqR12V7Bnbg54TiACg0
```

You need the `/v1/scripts/2FF1C29DCCEECD13CA68:1459051200000:yvlcYXtqR12V7Bnbg54TiACg0` equivalent of your Rancher to put into your command.

**Comment by julianxhokaxhiu** [comment]
@deniseschannon What I am trying to accomplish is to register the agent without even touching the server, and looking at your script, If I pass a URL without a token ( or using the command `register` in conjunction with `RANCHER_URL` environment variable ), the Agent is proceeding to run the registration automatically, which is done since when I attach the bash CLI to the agent docker, I see using `printenv` that the secret token and everything is gotten (so the agent is registered).

What is only missing, is the ability to access the URL `http://rancher-server:8080/` which could not happen because the agent docker is not linked to the server, so the hostname `rancher-server` could not resolved.

This happens because in your [run.sh](https://github.com/rancher/rancher/blob/master/agent/run.sh#L124) you're running again the new docker which is preserving the registration side, without the ability to extends the arguments of the run command. So, what I am asking is: is it possible to add an environment variable to add custom arguments?
Something like: `-e "CUSTOM_LAUNCH_ARGUMENTS=--link=docker-server"`

**Comment by julianxhokaxhiu** [comment]
@ibuildthecloud any clue?

**Comment by cjellick** [comment]
@julianxhokaxhiu the short answer to your question is no, we don't have a way to pass custom arguments like that. We explicitly whitelist the environment variables that make it from the first rancher/agent container to the final one. [The code is here if you are curious](https://github.com/rancher/rancher/blob/master/agent/run.sh#L124-L154).

While I'm in no way the final voice on what we will or won't implement, I'd say it is unlikely that we will implement what you are asking for. Most of our users are comfortable with the current paradigm of exposing rancher/server on a host port and having agents connect to well known hostname, VIP, LB, or host IP. But, as always, if there is significant interest from the community, we'd pursue it. 

For what its worth, you could hypothetically build your own agent image based off of modifying the above code.

**Comment by julianxhokaxhiu** [comment]
Thank you very much for the reply @cjellick.

I was already thinking about building my own docker starting from your scripts, although I thought would be easier for you to provide an environment variable to pass custom arguments, rather than hard-coding one-single usage variable like `LINK_TO=`.

Sounds really curious to me the fact that really no one wanted to do what am I trying, which sounds honestly a normal thing, like, I want to make a local installation of an agent without exposing any public port. When I'll need to, I'll do it, but when I don't, let's just link them locally and that's it.

Please consider adding this feature, I'm not a big fan of forks, and this is just an environment variable which will hurt no one, but will provide big support for even new and great ideas :)

Thanks again!

**Comment by julianxhokaxhiu** [comment]
I found a really ugly method to make it working but...I hope you'll consider the `--link` option.

Meanwhile, for whoever I trying to accomplish my own setup, here the single CLI line that will fix the "link" between the two dockers. You just have to run it once, nor on startup or special hooks. Just one single time after you're sure that the `rancher-agent` is running.

```bash
echo "$(docker inspect --format '{{ .NetworkSettings.IPAddress }}' rancher-server) rancher-server" >> /var/lib/docker/containers/$(docker inspect --format '{{ .Id }}' rancher-agent)/hosts
```

**Comment by cjellick** [comment]
@julianxhokaxhiu we don't have a way to make that environment variable match a pattern. But, that environment variable is actually a setting, which can be set via the API at `http://<your host>:8080/v1/settings`. The name of the setting is `api.host`, so you probably script a solution that would discover the rancher server's container IP after it starts and then sets the setting via the API.

If you didn't know this already, note that you can go to the API in a browser and we provide a half-way decent UI for the API so that it is relatively useable in the browser.

**Comment by julianxhokaxhiu** [comment]
Thanks @cjellick, I think I'll go for the Unit for now, which is working in a cleaner way and it's faster and automated too, without any sort of "vodoo" behind.

Although I would like to see a link option for making sure that agents can talk locally to the server, I understand that this vision is not shared by you. So until, I hope, one day you'll change your mind, I'll live in peace with my solution :)

Best regards!

**Comment by zot24** [comment]
@cjellick I can not find any reference under the settings endpoint related to `api.host` if that still valid?

**Comment by cjellick** [comment]
yes @zot24 it is still valid. It is the seting that gets set when your asked for the "Host Registration URL" in the UI.

Perhaps if you are viewing the API as a non-admin, you aren't seeing it?

**Comment by zot24** [comment]
I got it thanks @cjellick 👍

**Comment by will-chan** [comment]
Closing due to inactivity, please reopen if you think this is still relevant to current releases & important.
