### ISSUE TITLE
href attributes missing from container orchestration links

### ISSUE THREAD

**Issue by ndarilek** [rancher/rancher#4193]
Rancher Version: 1.0.0

Docker Version: 1.10

OS: Linux

Steps to Reproduce: 
1. Click Manage Environments
2. Click Edit on an environment.

Results: 
The container orchestration icons/logos are missing href attributes in their links. This makes them non-keyboard-accessible.

Expected:
The Swarm/Cattle/Kubernetes links would have `href` attributes and be tab-focusable.

**Comment by lvuch** [comment]
resolved in https://github.com/rancher/ui/pull/578

**Comment by tfiduccia** [comment]
Version - v1.0.1-rc1
Not completely fixed - although the href have been added.  The blue outline for tabbing does not show up, so you don't know that the icons are actually in focus.  This is also true in the Add environment page.

**Comment by tfiduccia** [comment]
Version - master 4/28
Verified fixed
