### ISSUE TITLE
Extra space between grids and footer

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#4271]
Version - master 4/1

Steps to Reproduce: 
1.  Create a mysql service
2   Start the service
3.  Click on the container name to go to container details
4.  Click on any other page

Results: There is now extra space between grids on page and the footer
![image](https://cloud.githubusercontent.com/assets/11514927/14219638/3fab4fe4-f810-11e5-9eb5-a69874a4e304.png)

Expected: Extra space should not be there.  Refreshing browser fixes.
![image](https://cloud.githubusercontent.com/assets/11514927/14219658/5c1ef7c0-f810-11e5-8ff1-13d42772695b.png)

**Comment by lvuch** [comment]
resolved in https://github.com/rancher/ui/pull/578 the bottom pop up required extra margin on <main>, it's now adding margin to a <section> in main with a specific class "stracks-wrap"

**Comment by lvuch** [comment]
resolved in rancher/ui#578

**Comment by tfiduccia** [comment]
Version - v1.0.1-rc1
This is still broken.  The extra space is now created when I enter any container details page and doesn't go away.

**Comment by tfiduccia** [comment]
Version - v1.0.1-rc3
Verified fixed
