### ISSUE TITLE
UI issues in host details page

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#4409]
Version - v1.0.1-rc7

-[ ] Drop-down no longer resizes to name of host
![image](https://cloud.githubusercontent.com/assets/11514927/14540961/7b1c4228-023c-11e6-9e23-6aac3dec3e5b.png)

- [ ] Container restart/menu buttons on top of each other instead of next to each other at bottom of page.
![image](https://cloud.githubusercontent.com/assets/11514927/14540985/8e0640d2-023c-11e6-9470-a36f7db778c1.png)

**Comment by lvuch** [comment]
resolved in https://github.com/rancher/ui/pull/598

**Comment by tfiduccia** [comment]
master 4-19
Not fixed

![image](https://cloud.githubusercontent.com/assets/11514927/14651835/7c0fb726-0626-11e6-90ff-443d9b7dcb25.png)

![image](https://cloud.githubusercontent.com/assets/11514927/14651842/841094ae-0626-11e6-84bc-a9db649c929d.png)

**Comment by lvuch** [comment]
![screen shot 2016-06-22 at 12 15 10 pm](https://cloud.githubusercontent.com/assets/3013118/16280160/2bad7a78-3873-11e6-8b20-4bc78bc8ffba.png)
I'm not able to recreate stacked action menu issue

**Comment by lvuch** [comment]
https://github.com/rancher/ui/pull/763

**Comment by tfiduccia** [comment]
Version - master 7/8
Verified fixed
