### ISSUE TITLE
[BUG] No CPU / Memory metrics available for 

### ISSUE THREAD

**Issue by aDisplayName** [rancher/rancher#45132]
**Rancher Server Setup**
- Rancher version: 2.8.3
- Installation option (Docker install/Helm Chart):
   - Helm Chart
   - Cluster:1.26.14-gke.1133000
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version: k3s v1.27.11+k3s1
- Cluster Type (Local/Downstream): Downstream, Imported.

**User Information**
- What is the role of the user logged in? Cluster Owner

**Describe the bug**
There is no data for CPU and Memory usage chart in grafana for namespace scoped compute resource such as "General / Kubernetes / Compute Resources / Namespace (Pods)"

**To Reproduce**

- Setup downstream cluster using the following command on Ubuntu 22.04 LTS
  ```bash
  sudo /usr/local/bin/k3s-uninstall.sh; curl -sfL https://get.k3s.io/ | INSTALL_K3S_VERSION="v1.27.11+k3s1" sh -s - --write-kubeconfig-mode=644 --kubelet-arg=cgroup-driver=systemd --kube-apiserver-arg=service-node-port-range=1-60000 --disable=traefik,servicelb --docker --resolv-conf=/run/systemd/resolve/resolv.conf
  ```
- Import the downstream cluster to Rancher
- In Rancher dashboard, open the cluster explorer for the new cluster
- Go to Cluster Tools, click "Install" on Monitoring
  - Select version: `103.0.4+up45.31.1`, click `Next`. Leaving `Install into Project` empty.
  - Edit Options as:
    - Leave as default in `General` 
      > ![image](https://github.com/rancher/rancher/assets/19527258/4fe05a7e-d9a4-4e14-96de-153401b71272)
    - Enable Persistent Storage for Prometheus
      >  ![image](https://github.com/rancher/rancher/assets/19527258/d7123a09-f559-40d7-8dd2-8b168bda3822)
    - Leave `Alerting` as default
      > ![image](https://github.com/rancher/rancher/assets/19527258/e7ae0510-df08-41fa-bf57-6aad9bdbff0f)
    - Enable `Grafana Storage` using PVC Template
      > ![image](https://github.com/rancher/rancher/assets/19527258/f4d26886-8112-4972-83d6-28a61aca4bb8)
  - Click `Install`
- Once installed, reload the dashboard, we can already see the cluster level CPU, Memory and network metrics. 
  > ![image](https://github.com/rancher/rancher/assets/19527258/fcefd5ff-c614-47e7-aec5-fefccddb361a)
- Goes into Grafana, check Graph: `General / Rancher / Cluster (Nodes)`, same result.
  > ![image](https://github.com/rancher/rancher/assets/19527258/cfc7c586-3362-49b4-9e12-3b462068db77)
- But if we goes to Namespace scoped computing resources, no usage data is showed:
  - General / Kubernetes / Compute Resources / Namespace (Pods)
    > ![image](https://github.com/rancher/rancher/assets/19527258/fcda5fb7-2863-4792-87c2-674e55a6eac5)
  - General / Kubernetes / Compute Resources / Namespace (Workloads)
    > ![image](https://github.com/rancher/rancher/assets/19527258/7bd45666-4ac4-441a-b529-a3505b632cc9)

**Result**

Realtime CPU / Memory usage data was not available for pods / workloads by default after installing monitoring tools 

**Expected Result**

Realtime CPU / Memory usage data should be available for pods / workloads by default after installing monitoring tools 

**Screenshots**

**Additional context**

**Comment by MKlimuszka** [comment]
We have confirmed this is a bug. We will prioritize it appropriately.

**Comment by Skoucail** [comment]
Any update on this? We are having the same issue.

**Comment by Skoucail** [comment]
Still an issue in 105.1.2+up61.3.2

**Comment by Skoucail** [comment]
I believe i just found the cause.

In the Prometheus rulefile some of the rules include `job="kubelet"`.  
But when i checked those metrics in prometheus i noticed the metrics themself contain `job="k3s-server"`.  

Not sure who sets those labels on the metrics. But there is clearly a mismatch between the rule and the actual metrics.

Example:
Config: 
![Image](https://github.com/user-attachments/assets/8929e00b-01a5-4321-aab1-ca0260a0ecd9)

Prometheus pomsql:
![Image](https://github.com/user-attachments/assets/2d30fc5f-14fd-46a7-a052-8217cefb3b03)

Prometheus pomsql FIXED:
![Image](https://github.com/user-attachments/assets/b2a55d71-aebd-4b2a-a8eb-36ddef0133be)

@MKlimuszka I hope this can help you guys fix the issue.

**Comment by deepakpunia-suse** [comment]
Tested with the `45132-bug-fix` branch, but the issue still persists. The mention Grafana dashboards still show "No data":

  * `Compute Resources / Namespace (Pods)`
  * `Compute Resources / Namespace (Workloads)`


### Environment

  * **Rancher:** `v2.12-head`
  * **RKE2:** `v1.33.3+rke2r1`
  * **Downstream Cluster:** Imported K3s (`v1.33.3+k3s1`)
  * **Monitoring Chart:** `104.1.0+up6.8.2` (from the test branch)


### Steps to Reproduce

1.  **Add the test chart repository:**

    ```yaml
    apiVersion: catalog.cattle.io/v1
    kind: ClusterRepo
    metadata:
      name: susesamu-45132-bug-fix
    spec:
      gitRepo: https://github.com/susesamu/ob-team-charts
      gitBranch: 45132-bug-fix
    ```

2.  **Install or upgrade the `rancher-monitoring` chart with the following options:**

* Enable Persistent Storage for Prometheus.

<img width="1299" height="317" alt="Image" src="https://github.com/user-attachments/assets/addc4370-4de6-4726-88cb-2671a9fb8da6" />

* Enable Persistent Storage for Grafana.

<img width="1295" height="353" alt="Image" src="https://github.com/user-attachments/assets/ff4fc72a-85aa-4da4-a941-dbcae335d975" />

* Leave all other options as default.

<img width="1910" height="1049" alt="Image" src="https://github.com/user-attachments/assets/092ff0da-71e6-4055-bdcf-42d87816de93" />

3.  **Navigate to Grafana and check the following dashboards:**

* `General / Kubernetes / Compute Resources / Namespace (Pods)`

<img width="1919" height="1043" alt="Image" src="https://github.com/user-attachments/assets/38c1065d-ef3b-45b9-92ab-6e99e768f26c" />


* `General / Kubernetes / Compute Resources / Namespace (Workloads)`

<img width="1914" height="1052" alt="Image" src="https://github.com/user-attachments/assets/16ae22c5-6b21-4b6f-a07e-89109bf48910" />

**Comment by deepakpunia-suse** [comment]
I re-tested after another minor fix in the PR, using the k3s  installation command below with containerd since Docker is not recommended.

```
sudo /usr/local/bin/k3s-uninstall.sh; curl -sfL https://get.k3s.io/ | INSTALL_K3S_VERSION="v1.33.3+k3s1" sh -s - --write-kubeconfig-mode=644 --kubelet-arg=cgroup-driver=systemd --kube-apiserver-arg=service-node-port-range=1-60000 --resolv-conf=/run/systemd/resolve/resolv.conf
```

After installing the monitoring tools, real-time CPU/Memory usage data is now available by default for pods and workloads at the following locations:

* General / Kubernetes / Compute Resources / Namespace (Pods)

<img width="2508" height="1250" alt="Image" src="https://github.com/user-attachments/assets/01e1e95f-bc0f-40bb-a005-cdf5073f48a4" />

* General / Kubernetes / Compute Resources / Namespace (Workloads)

<img width="2497" height="1255" alt="Image" src="https://github.com/user-attachments/assets/cba910f2-75c2-40f0-aa09-542dd446dec2" />

**Comment by susesamu** [comment]
we got two bugs here:
one is the incorrect jobName on the prometheus rulefile for k3s (which is fixed here: https://github.com/rancher/ob-team-charts/pull/105).
The other is that when we use Docker as the container runtime for k3s, the image and container stats for cadvisor-metrics are missing. using cri-dockerd is not recommended and its there just for backwards compatibility, we encourage to use the default runtime (containerd), as @deepakpunia-suse  showed above.

**Comment by rmoreas** [comment]
On rancher-monitoring version 107.2.1+up69.8.2-rancher.23, the issue still remains on the "Kubernetes / Compute Resources / Cluster" dashboard. The CPU panel is working, but all other panels like Memory, Current Network Usage, etc. are not.

<img width="1610" height="1131" alt="Image" src="https://github.com/user-attachments/assets/26369d4c-c4e4-4e94-8656-51161d470eac" />

Seems that these panels are using job="kubelet" in their query. For example, the Memory panel uses:

```
sum(container_memory_rss{job="kubelet", metrics_path="/metrics/cadvisor", cluster="", container!=""}) by (namespace)
```

**Comment by rmoreas** [comment]
Dashboard "Kubernetes / Compute Resources / Cluster" seems to be fixed for K3s in 108.0.2+up77.9.1-rancher.11.

<img width="1478" height="208" alt="Image" src="https://github.com/user-attachments/assets/319deacd-fc6d-49a9-a85c-f0466caff750" />
