### ISSUE TITLE
[BUG] Slow response to list namespaces

### ISSUE THREAD

**Issue by xhejtman** [rancher/rancher#49749]
**Rancher Server Setup**
- Rancher version: 2.11.0
- Installation option (Docker install/Helm Chart): Helm Chart
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): RKE2 1.37.7
- Proxy/Cert Details:
  - squid proxy for external connectivity, cert-manager

**Information about the Cluster**
- Kubernetes version: 1.37.7
- Cluster Type (Local/Downstream): Local
   

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom): Admin

**Describe the bug**

When refreshing rancher dashboard, I can see that namespace list takes serious amount of time and maybe it is even loaded twice:

<img width="1183" alt="Image" src="https://github.com/user-attachments/assets/40dee562-44d9-46fe-a7f4-dc7ca5e22355" />

We have 1400 namespaces in the Local (Rancher) cluster. I believe it is a regression since 2.10.3

**Comment by xhejtman** [comment]
It seems that the same issue is with most other resources like Pods, Secrets, Ingresses..

**Comment by khushalchandak17** [comment]
I tested on my side by creating over 3,000 namespaces and loading them through the UI, in both scenario with and without the Squid proxy. I didn’t see any delay.  The namespace list loaded quickly in both cases.

Attaching a screenshot for reference.
![Image](https://github.com/user-attachments/assets/9935c3ef-03dd-440f-a010-a3ed08ea3892)

Could you share the HAR file from your side?  If possble, you can fetch  the browser performance recording as well
Ref: https://www.suse.com/support/kb/doc/?id=000021614

Also, please include some cluster and infrastructure details to help understand the environment.

**Comment by xhejtman** [comment]
<img width="1179" alt="Image" src="https://github.com/user-attachments/assets/1008181e-199a-47e8-a8f3-39098ab65164" />

I believe it has nothing to do with performance of the browser, because:
```
time curl -s -H "Authorization: Bearer $APIKEY" -H 'Accept: application/json' -H 'Content-Type: application/json' -X GET 'https://rancher.cloud.e-infra.cz/v1/namespaces?exclude=metadata.managedFields'
...
real	0m21.384s
user	0m0.063s
sys	0m0.051s
```

I tried the curl also directly to the rancher pod:
```
root@kub-r1:~# time curl -k -H "Authorization: Bearer $APIKEY" -H 'Accept: application/json' -H 'Content-Type: application/json' -X GET 'https://10.42.206.5/v1/namespaces?exclude=metadata.managedFields' > /dev/null
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 1666k    0 1666k    0     0  84526      0 --:--:--  0:00:20 --:--:--  528k

real	0m20.202s
user	0m0.017s
sys	0m0.020s
root@kub-r1:~#
```

This is how I upgrade the rancher:
```
helm upgrade rancher rancher-latest/rancher --namespace cattle-system --set hostname=rancher.cloud.e-infra.cz --set ingress.tls.source=secret --set ingress.tls.secretName=rancher-cloud-e-infra-cz --set bootstrapPassword=xxx --set ingress.extraAnnotations.'kubernetes\.io/ingress\.class'=nginx --set ingress.extraAnnotations.'kubernetes\.io/tls-acme'=\"true\" --set ingress.extraAnnotations.'cert-manager\.io/cluster-issuer'=letsencrypt-prod --set customLogos.enabled=true --set customLogos.volumeName=pvc-rancher  --set antiAffinity=preferred --set auditLog.level=3 --set global.cattle.psp.enabled=false --version 2.11.0 --set 'proxy=http://proxy.ics.muni.cz:3128' --set 'noProxy=127.0.0.0/8\,10.0.0.0/8\,cattle-system.svc\,.svc\,.cluster.local\,147.251.0.0/16\,2001:718:801::/48\,10.43.0.1\,10.43.0.0/16'
```

We have continual upgrades since 2.6.0.

<img width="1002" alt="Image" src="https://github.com/user-attachments/assets/79766f4f-a7ac-46f7-8273-7bddb7e2df34" />

Do you still want the HAR file?

**Comment by xhejtman** [comment]
Could it be related to the number of users? ~650.

**Comment by xhejtman** [comment]
maybe this is the issue? Can I clean it up somehow?
<img width="252" alt="Image" src="https://github.com/user-attachments/assets/825afa11-0ca0-492a-8307-eb28cfc3e601" />

top number of rolebidings:
```
    720 cattle-global-data
   1944 c-m-qvndqhf6
   2085 fleet-default
```

**Comment by khushalchandak17** [comment]
Well, we tried replicating a similar setup with a similiar high number of RBACs and users but didn’t observe much impact on the Rancher pod or APIs. For a closer look, could you please share the Rancher Diagnostic Package?

You can download it via: Rancher UI → Menu (☰) → About → Diagnostics → Click Generate Response Times and Download Diagnostic Package.

**Comment by xhejtman** [comment]
here it is:
[rancher-diagnostic-data.json](https://github.com/user-attachments/files/19763135/rancher-diagnostic-data.json)

**Comment by xhejtman** [comment]
And this is pprof while generating diagnostics response times (profiling for 60 seconds, same as above):
```
(pprof) top60
Showing nodes accounting for 751.64s, 67.82% of 1108.27s total
Dropped 5249 nodes (cum <= 5.54s)
Showing top 60 nodes out of 222
      flat  flat%   sum%        cum   cum%
   326.13s 29.43% 29.43%    326.13s 29.43%  runtime.(*lfstack).pop /usr/lib64/go/1.23/src/runtime/lfstack.go:48 (inline)
   173.41s 15.65% 45.07%    173.51s 15.66%  sync/atomic.(*Int32).Add /usr/lib64/go/1.23/src/sync/atomic/type.go:88 (inline)
    37.33s  3.37% 48.44%     37.43s  3.38%  runtime.(*gcBits).bitp /usr/lib64/go/1.23/src/runtime/mheap.go:2351 (inline)
    31.11s  2.81% 51.25%     31.11s  2.81%  runtime.scanobject /usr/lib64/go/1.23/src/runtime/mgcmark.go:1446
       28s  2.53% 53.78%     28.10s  2.54%  runtime.findObject /usr/lib64/go/1.23/src/runtime/mbitmap.go:1291
    14.79s  1.33% 55.11%     14.79s  1.33%  runtime.findObject /usr/lib64/go/1.23/src/runtime/mbitmap.go:1279
    14.70s  1.33% 56.44%     44.67s  4.03%  github.com/rancher/steve/pkg/accesscontrol.(*policyRuleIndex).getRoleBindings.func1 /go/pkg/mod/github.com/rancher/steve@v0.5.10/pkg/accesscontrol/policy_rule_index.go:160
    12.47s  1.13% 57.56%     12.47s  1.13%  cmpbody /usr/lib64/go/1.23/src/internal/bytealg/compare_amd64.s:59
    12.25s  1.11% 58.67%     12.25s  1.11%  runtime.gcDrain /usr/lib64/go/1.23/src/runtime/mgcmark.go:1161
    11.56s  1.04% 59.71%     11.56s  1.04%  runtime.memmove /usr/lib64/go/1.23/src/runtime/memmove_amd64.s:179
    11.32s  1.02% 60.73%     11.32s  1.02%  runtime.(*mspan).base /usr/lib64/go/1.23/src/runtime/mheap.go:492 (inline)
     9.05s  0.82% 61.55%      9.05s  0.82%  runtime.(*mspan).heapBitsSmallForAddr /usr/lib64/go/1.23/src/runtime/mbitmap.go:629
     8.98s  0.81% 62.36%      8.98s  0.81%  runtime.getempty /usr/lib64/go/1.23/src/runtime/mgcwork.go:354
     8.70s  0.79% 63.14%    231.78s 20.91%  github.com/rancher/steve/pkg/accesscontrol.(*policyRuleIndex).getRoleRefs /go/pkg/mod/github.com/rancher/steve@v0.5.10/pkg/accesscontrol/policy_rule_index.go:180
     6.42s  0.58% 63.72%      6.42s  0.58%  runtime.mapaccess1_faststr /usr/lib64/go/1.23/src/runtime/map_faststr.go:97
     6.31s  0.57% 64.29%      6.31s  0.57%  runtime.memmove /usr/lib64/go/1.23/src/runtime/memmove_amd64.s:185
     6.28s  0.57% 64.86%      6.28s  0.57%  memeqbody /usr/lib64/go/1.23/src/internal/bytealg/equal_amd64.s:115
     5.96s  0.54% 65.40%     24.19s  2.18%  sort.partition_func /usr/lib64/go/1.23/src/sort/zsortfunc.go:157
     5.71s  0.52% 65.91%      5.71s  0.52%  runtime.memmove /usr/lib64/go/1.23/src/runtime/memmove_amd64.s:168
     3.55s  0.32% 66.23%      8.03s  0.72%  runtime.scanobject /usr/lib64/go/1.23/src/runtime/mgcmark.go:1437
     2.18s   0.2% 66.43%     22.20s  2.00%  sort.partition_func /usr/lib64/go/1.23/src/sort/zsortfunc.go:154
     1.82s  0.16% 66.59%        23s  2.08%  k8s.io/client-go/tools/cache.(*threadSafeMap).ByIndex /go/pkg/mod/k8s.io/client-go@v0.32.2/tools/cache/thread_safe_store.go:323
     1.69s  0.15% 66.75%      6.79s  0.61%  internal/reflectlite.Swapper.func3 /usr/lib64/go/1.23/src/internal/reflectlite/swapper.go:42
     0.91s 0.082% 66.83%     39.94s  3.60%  runtime.scanobject /usr/lib64/go/1.23/src/runtime/mgcmark.go:1464
     0.82s 0.074% 66.90%      7.22s  0.65%  runtime.concatstrings /usr/lib64/go/1.23/src/runtime/string.go:53
     0.75s 0.068% 66.97%    192.84s 17.40%  github.com/rancher/wrangler/v3/pkg/generic.(*Cache[go.shape.*uint8]).Get /go/pkg/mod/github.com/rancher/wrangler/v3@v3.2.0/pkg/generic/cache.go:65
     0.72s 0.065% 67.03%      7.71s   0.7%  regexp.(*machine).match /usr/lib64/go/1.23/src/regexp/exec.go:222
     0.65s 0.059% 67.09%     18.03s  1.63%  regexp.(*machine).match /usr/lib64/go/1.23/src/regexp/exec.go:225
     0.60s 0.054% 67.15%      7.76s   0.7%  regexp.(*machine).step /usr/lib64/go/1.23/src/regexp/exec.go:304
     0.56s 0.051% 67.20%     16.10s  1.45%  runtime.stringtoslicebyte /usr/lib64/go/1.23/src/runtime/string.go:184
     0.53s 0.048% 67.25%     20.87s  1.88%  runtime.concatstring3 /usr/lib64/go/1.23/src/runtime/string.go:64
     0.45s 0.041% 67.29%      7.31s  0.66%  runtime.mapaccess2_faststr /usr/lib64/go/1.23/src/runtime/map_faststr.go:204
     0.41s 0.037% 67.32%      7.04s  0.64%  regexp.(*Regexp).tryBacktrack /usr/lib64/go/1.23/src/regexp/backtrack.go:159
     0.40s 0.036% 67.36%    214.10s 19.32%  github.com/rancher/steve/pkg/accesscontrol.(*policyRuleIndex).getRules /go/pkg/mod/github.com/rancher/steve@v0.5.10/pkg/accesscontrol/policy_rule_index.go:133
     0.40s 0.036% 67.40%     13.85s  1.25%  runtime.(*mspan).typePointersOfUnchecked /usr/lib64/go/1.23/src/runtime/mbitmap.go:184
     0.36s 0.032% 67.43%      5.95s  0.54%  k8s.io/client-go/tools/cache.(*threadSafeMap).ByIndex /go/pkg/mod/k8s.io/client-go@v0.32.2/tools/cache/thread_safe_store.go:322
     0.32s 0.029% 67.46%     45.50s  4.11%  github.com/rancher/steve/pkg/accesscontrol.(*policyRuleIndex).getRoleRefs /go/pkg/mod/github.com/rancher/steve@v0.5.10/pkg/accesscontrol/policy_rule_index.go:181
     0.32s 0.029% 67.49%      6.81s  0.61%  runtime.findObject /usr/lib64/go/1.23/src/runtime/mbitmap.go:1275
     0.30s 0.027% 67.51%    191.95s 17.32%  k8s.io/client-go/tools/cache.(*cache).GetByKey /go/pkg/mod/k8s.io/client-go@v0.32.2/tools/cache/store.go:256
     0.30s 0.027% 67.54%     18.01s  1.63%  k8s.io/client-go/tools/cache.(*threadSafeMap).Get /go/pkg/mod/k8s.io/client-go@v0.32.2/tools/cache/thread_safe_store.go:256
     0.28s 0.025% 67.56%     22.44s  2.02%  github.com/rancher/steve/pkg/accesscontrol.roleRef.writeTo /go/pkg/mod/github.com/rancher/steve@v0.5.10/pkg/accesscontrol/user_grants.go:66
     0.27s 0.024% 67.59%      8.04s  0.73%  runtime.mallocgc /usr/lib64/go/1.23/src/runtime/malloc.go:1265
     0.26s 0.023% 67.61%     99.41s  8.97%  github.com/rancher/steve/pkg/accesscontrol.(*policyRuleIndex).getRoleRefs /go/pkg/mod/github.com/rancher/steve@v0.5.10/pkg/accesscontrol/policy_rule_index.go:179
     0.19s 0.017% 67.63%     20.48s  1.85%  github.com/rancher/steve/pkg/accesscontrol.roleRef.writeTo /go/pkg/mod/github.com/rancher/steve@v0.5.10/pkg/accesscontrol/user_grants.go:70
     0.19s 0.017% 67.65%     57.28s  5.17%  k8s.io/client-go/tools/cache.(*threadSafeMap).Get /go/pkg/mod/k8s.io/client-go@v0.32.2/tools/cache/thread_safe_store.go:257
     0.18s 0.016% 67.66%     37.61s  3.39%  runtime.(*mspan).markBitsForIndex /usr/lib64/go/1.23/src/runtime/mbitmap.go:1162 (inline)
     0.18s 0.016% 67.68%     15.29s  1.38%  runtime.wbBufFlush1 /usr/lib64/go/1.23/src/runtime/mwbbuf.go:240
     0.17s 0.015% 67.69%     58.56s  5.28%  github.com/rancher/steve/pkg/accesscontrol.subjectGrants.writeTo /go/pkg/mod/github.com/rancher/steve@v0.5.10/pkg/accesscontrol/user_grants.go:42
     0.17s 0.015% 67.71%     12.24s  1.10%  runtime.mapaccess1_faststr /usr/lib64/go/1.23/src/runtime/map_faststr.go:80
     0.16s 0.014% 67.72%     29.78s  2.69%  regexp.(*Regexp).backtrack /usr/lib64/go/1.23/src/regexp/backtrack.go:351
     0.16s 0.014% 67.74%     27.56s  2.49%  runtime.mallocgc /usr/lib64/go/1.23/src/runtime/malloc.go:1037
     0.16s 0.014% 67.75%     56.83s  5.13%  runtime.scanobject /usr/lib64/go/1.23/src/runtime/mgcmark.go:1465
     0.14s 0.013% 67.77%      5.91s  0.53%  crypto/sha256.(*digest).Write /usr/lib64/go/1.23/src/crypto/sha256/sha256.go:182
     0.11s 0.0099% 67.78%      9.93s   0.9%  runtime.rawstringtmp /usr/lib64/go/1.23/src/runtime/string.go:141
     0.10s 0.009% 67.78%     15.19s  1.37%  github.com/rancher/steve/pkg/accesscontrol.roleRef.writeTo /go/pkg/mod/github.com/rancher/steve@v0.5.10/pkg/accesscontrol/user_grants.go:68
     0.10s 0.009% 67.79%     10.33s  0.93%  runtime.concatstrings /usr/lib64/go/1.23/src/runtime/string.go:51
     0.08s 0.0072% 67.80%      8.88s   0.8%  encoding/json.(*decodeState).objectInterface /usr/lib64/go/1.23/src/encoding/json/decode.go:1098
     0.08s 0.0072% 67.81%      9.60s  0.87%  runtime.rawstring /usr/lib64/go/1.23/src/runtime/string.go:277 (inline)
     0.07s 0.0063% 67.81%      8.97s  0.81%  encoding/json.(*encodeState).reflectValue /usr/lib64/go/1.23/src/encoding/json/encode.go:322
     0.07s 0.0063% 67.82%     21.05s  1.90%  github.com/rancher/wrangler/v3/pkg/generic.(*Cache[go.shape.*uint8]).Get /go/pkg/mod/github.com/rancher/wrangler/v3@v3.2.0/pkg/generic/cache.go:63
(pprof)
```

**Comment by xhejtman** [comment]
Hello,

unfortunately, the profile dump (if you mean that diagnostic page) does not produce complete output. If you mean pprof dump from profiling, no problem with that, just let me know.

As of backup objects - I removed all of them, but it did not help. 

As of rolebindings. It is not very fast even from api directly:
```
root@kub-r1:~# time kubectl  get rolebinding -A -o yaml > /dev/null

real	0m12.594s
```

I am not sure, if I can remove some of the rolebinding, these are top numbers:
```
root@kub-r1:~# kubectl  get rolebinding -A | awk '{ print $1}' | sort | uniq -c | sort -n | tail -5
     33 p-g48vt
     56 c-m-psjf5r7c
    720 cattle-global-data
   1956 c-m-qvndqhf6
   2098 fleet-default
root@kub-r1:~#
```

I can see basically three bindings per project such as:
```
r-cluster-kuba-cluster-view-p-rxrdf-creator-project-owner-2aa9f   Role/r-cluster-kuba-cluster-view          216d
r-cluster-kuba-cluster-view-p-rxrdf-creator-rt-w5w59-2in4m7mlhf   Role/r-cluster-kuba-cluster-view          216d
r-cluster-kuba-cluster-view-p-rxrdf-prtb-tbq7m-7s6qcboln2         Role/r-cluster-kuba-cluster-view          216d
```

we have about 747 projects, few of them probably do not exist anymore, I suppose that rancher or fleet controller restores these bindings even if they are removed.

Obviously, there is high conention on access rights verification. I do not think that anything in system has changed between 2.10.4 and 2.11.0 rancher versions, and it did not take so long to retrieve the objects.

**Comment by khushalchandak17** [comment]
Hello,
Yes, I was referring to a pprof dump from profiling. You can use the following script to run continuous profiling:

```
$ curl -OLs https://raw.githubusercontent.com/rancherlabs/support-tools/master/collection/rancher/v2.x/profile-collector/continuous_profiling.sh
$ bash continuous_profiling.sh
```

While the script is running in the background, reproduce the issue by executing the same API request to the Rancher pod both via the external URL and directly via the Rancher pod IP.

Once done, please share the generated log bundle with us for further analysis.

Well, post deleteing backup object, is there some improvement compared to earlier timing you mentioned (~21 seconds), though it’s still relatively slow?

Also, for your reference, you might find the following Rancher documentation helpful:
https://ranchermanager.docs.rancher.com/reference-guides/best-practices/rancher-server/tuning-and-best-practices-for-rancher-at-scale#managing-your-object-counts

**Comment by khushalchandak17** [comment]
Hello,

From a quick analysis of the provided profile bundles, it seems that secrets objects also seem to be causing high memory usage in the kube-apiserver.
I am assuming, if the kube-apiserver is slow or overloaded, Rancher queues up thousands of pending goroutines, which in turn increasing CPU, memory for Rancher.

~~~
flat flat% sum% cum cum%
246.49MB 25.53% 25.53% 258MB 26.72% k8s.io/api/core/v1.(*Secret).Unmarshal
67.57MB 7.00% 32.53% 101.59MB 10.52% k8s.io/apimachinery/pkg/apis/meta/v1.(*ObjectMeta).Unmarshal
67.03MB 6.94% 39.47% 67.03MB 6.94% reflect.New


flat flat% sum% cum cum%
16359 100% 100% 16359 100% runtime.gopark
1 0.0061% 100% 4300 26.28% runtime.selectgo
0 0% 100% 150 0.92% bufio.(*Reader).Peek



▶ cat top-pods.txt| sort -nrk4 | head -4
kube-system kube-apiserver-kub-r1.priv.cerit-sc.cz 1698m 3954Mi
kube-system kube-apiserver-kub-r2.priv.cerit-sc.cz 331m 3706Mi
kube-system kube-apiserver-kub-r3.priv.cerit-sc.cz 169m 3437Mi
cattle-system rancher-5d89fbddf8-75r5j 6552m 2599Mi


~~~

Additionally, during a very short timestamp window, I noticed argocd was actively accessing postgresql resources

~~~

◒
▶ grep -i argo rancher-5d89fbddf8-75r5j-audit.log | grep -i postgres
{"auditID":"482908d7-ac3a-416c-8f6b-ee7b05a9c250","requestURI":"/k8s/clusters/c-m-qvndqhf6/apis/postgresql.cnpg.io/v1/namespaces/csirtmu-authbro-example/clusters?allowWatchBookmarks=true\u0026resourceVersion=2857958677\u0026watch=true","user":{"name":"u-g7z4lxygfm","group":["shibboleth_group://urn:geant:cesnet.cz:group:meta#perun.cesnet.cz","shibboleth_group://urn:geant:muni.cz:group:MU:CSIRT-MU:k8s-infra-admins#idm.ics.muni.cz","shibboleth_group://urn:geant:muni.cz:res:k8s-cloud:csirt-mu-rancher#idm.ics.muni.cz","shibboleth_group://urn:geant:cesnet.cz:res:personal-project-kubernetes#perun.cesnet.cz","system:authenticated","system:cattle:authenticated"],"extra":{"principalid":["shibboleth_user://69a3e16c71e9eedf2136fbd0f564b6b0077fd44f@einfra.cesnet.cz"],"requesthost":["api.rancher.cloud.e-infra.cz"],"requesttokenid":["token-2jmmw"],"username":["tr-service@einfra.cesnet.cz"]}},"method":"GET","remoteAddr":"10.42.3.213:59006","requestTimestamp":"2025-04-22T21:53:12Z","responseTimestamp":"2025-04-22T21:53:12Z","responseCode":200,"requestHeader":{"Accept":["application/json"],"Accept-Encoding":["gzip"],"Impersonate-Extra-Principalid":["shibboleth_user://69a3e16c71e9eedf2136fbd0f564b6b0077fd44f@einfra.cesnet.cz"],"Impersonate-Extra-Requesthost":["api.rancher.cloud.e-infra.cz"],"Impersonate-Extra-Requesttokenid":["token-2jmmw"],"Impersonate-Extra-Username":["tr-service@einfra.cesnet.cz"],"Impersonate-Group":["shibboleth_group://urn:geant:cesnet.cz:group:meta#perun.cesnet.cz","shibboleth_group://urn:geant:muni.cz:group:MU:CSIRT-MU:k8s-infra-admins#idm.ics.muni.cz","shibboleth_group://urn:geant:muni.cz:res:k8s-cloud:csirt-mu-rancher#idm.ics.muni.cz","shibboleth_group://urn:geant:cesnet.cz:res:personal-project-kubernetes#perun.cesnet.cz","system:authenticated","system:cattle:authenticated"],"Impersonate-User":["u-g7z4lxygfm"],"User-Agent":["argocd-application-controller/v0.0.0 (linux/amd64) kubernetes/$Format"],"X-Forwarded-For":["10.16.20.148"],"X-Forwarded-Host":["api.rancher.cloud.e-infra.cz"],"X-Forwarded-Port":["443"],"X-Forwarded-Proto":["https"],"X-Forwarded-Scheme":["https"],"X-Real-Ip":["10.16.20.148"],"X-Request-Id":["7e843714d3897ca1c37b9a4047dfc4b2"],"X-Scheme":["https"]},"responseHeader":{"Audit-Id":["47f27dba-a382-42c7-b999-947fdeceaf26"],"Cache-Control":["no-cache, no-store, must-revalidate","no-cache, private"],"Content-Type":["application/json"],"Date":["Tue, 22 Apr 2025 21:53:12 GMT"],"X-Api-Cattle-Auth":["true"],"X-Content-Type-Options":["nosniff"],"X-Kubernetes-Pf-Flowschema-Uid":["2dd3a8b0-8fba-4c5f-8259-2f858ed87dcc"],"X-Kubernetes-Pf-Prioritylevel-Uid":["479a56c1-00de-4175-847f-9083ff994818"]},"responseBody":{"type":"ERROR","object":{"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"too old resource version: 2857958677 (2857959148)","reason":"Expired","code":410}}}
{"auditID":"3fcbe322-54cf-450b-8e78-764367f78eb5","requestURI":"/k8s/clusters/c-m-qvndqhf6/apis/postgresql.cnpg.io/v1/namespaces/csirtmu-authbro-example/clusters?limit=500","user":{"name":"u-g7z4lxygfm","group":["shibboleth_group://urn:geant:cesnet.cz:group:meta#perun.cesnet.cz","shibboleth_group://urn:geant:muni.cz:group:MU:CSIRT-MU:k8s-infra-admins#idm.ics.muni.cz","shibboleth_group://urn:geant:muni.cz:res:k8s-cloud:csirt-mu-rancher#idm.ics.muni.cz","shibboleth_group://urn:geant:cesnet.cz:res:personal-project-kubernetes#perun.cesnet.cz","system:authenticated","system:cattle:authenticated"],"extra":{"principalid":["shibboleth_user://69a3e16c71e9eedf2136fbd0f564b6b0077fd44f@einfra.cesnet.cz"],"requesthost":["api.rancher.cloud.e-infra.cz"],"requesttokenid":["token-2jmmw"],"username":["tr-service@einfra.cesnet.cz"]}},"method":"GET","remoteAddr":"10.42.3.213:59006","requestTimestamp":"2025-04-22T21:53:12Z","responseTimestamp":"2025-04-22T21:53:12Z","responseCode":200,"requestHeader":{"Accept":["application/json"],"Accept-Encoding":["gzip"],"Impersonate-Extra-Principalid":["shibboleth_user://69a3e16c71e9eedf2136fbd0f564b6b0077fd44f@einfra.cesnet.cz"],"Impersonate-Extra-Requesthost":["api.rancher.cloud.e-infra.cz"],"Impersonate-Extra-Requesttokenid":["token-2jmmw"],"Impersonate-Extra-Username":["tr-service@einfra.cesnet.cz"],"Impersonate-Group":["shibboleth_group://urn:geant:cesnet.cz:group:meta#perun.cesnet.cz","shibboleth_group://urn:geant:muni.cz:group:MU:CSIRT-MU:k8s-infra-admins#idm.ics.muni.cz","shibboleth_group://urn:geant:muni.cz:res:k8s-cloud:csirt-mu-rancher#idm.ics.muni.cz","shibboleth_group://urn:geant:cesnet.cz:res:personal-project-kubernetes#perun.cesnet.cz","system:authenticated","system:cattle:authenticated"],"Impersonate-User":["u-g7z4lxygfm"],"User-Agent":["argocd-application-controller/v0.0.0 (linux/amd64) kubernetes/$Format"],"X-Forwarded-For":["10.16.20.148"],"X-Forwarded-Host":["api.rancher.cloud.e-infra.cz"],"X-Forwarded-Port":["443"],"X-Forwarded-Proto":["https"],"X-Forwarded-Scheme":["https"],"X-Real-Ip":["10.16.20.148"],"X-Request-Id":["5029e6ef191792f1dbbfe3ef88ac232b"],"X-Scheme":["https"]},"responseHeader":{"Audit-Id":["427edbc5-6315-4cd4-a629-5be81a7362e0"],"Cache-Control":["no-cache, no-store, must-revalidate","no-cache, private"],"Content-Length":["129"],"Content-Type":["application/json"],"Date":["Tue, 22 Apr 2025 21:53:12 GMT"],"X-Api-Cattle-Auth":["true"],"X-Content-Type-Options":["nosniff"],"X-Kubernetes-Pf-Flowschema-Uid":["2dd3a8b0-8fba-4c5f-8259-2f858ed87dcc"],"X-Kubernetes-Pf-Prioritylevel-Uid":["479a56c1-00de-4175-847f-9083ff994818"]},"responseBody":{"apiVersion":"postgresql.cnpg.io/v1","items":[],"kind":"ClusterList","metadata":{"continue":"","resourceVersion":"2857963720"}}}
~~~

We had seen in the past, at scale,  argocd doent perform well with Rancher
Ref: https://ranchermanager.docs.rancher.com/reference-guides/best-practices/rancher-server/tuning-and-best-practices-for-rancher-at-scale#minimizing-third-party-software-on-the-upstream-cluster

Would it also be possible to check if argocd could be ruled out as a contributor to the load issues?


Can you share following data for further diagnosis:

- kube-apiserver audit logs
- kubectl get secret -n cattle-impersonation-system | wc -l
- fresh rancher-diagnstic.json

**Comment by xhejtman** [comment]
I tried to stop argo, but it had no impact on the issue. 
As of audit logs, I suppose, you want to know requests uri? If so, find it filtered, if need something more, I can provide, just let me also know, what level of audit shall I set?
```
grep 'requestURI":"' audit.log  | sed -e 's/.*requestURI":"//' -e 's/".*//' | sort | uniq -c | sort -n
      1 /api/v1/namespaces/cattle-fleet-system
      1 /api/v1/namespaces/cattle-impersonation-system/secrets?limit=500
      1 /api/v1/namespaces/cattle-monitoring-system
      1 /api/v1/namespaces/cattle-resources-system
      1 /api/v1/namespaces/cloudnativepg
      1 /api/v1/namespaces/cloudnativepg/secrets/cnpg-ca-secret
      1 /api/v1/namespaces/cloudnativepg/secrets/cnpg-webhook-cert
      1 /api/v1/namespaces/janitor
      1 /api/v1/namespaces/projectoperator
      1 /api/v1/namespaces/projectoperator/pods/kerberos-cronjob-29099485-mlhw5
      1 /api/v1/namespaces/projectoperator/pods/kerberos-cronjob-29099500-w58lv
      1 /api/v1/namespaces/tigera-operator
      2 /api/v1/namespaces/cattle-system/configmaps/rancher-partner-charts-0-9f29aa6e-38d4-4fd9-85be-bb2da6121ae6
      2 /api/v1/namespaces/cattle-system/configmaps/rancher-rke2-charts-0-f03308f6-57be-48c9-aadf-5b2df1485043
      2 /api/v1/namespaces/cattle-system/secrets/imperative-api-sni-provider-cert-ca
      2 /api/v1/namespaces/harbor
      2 /api/v1/namespaces/logging-system
      2 /api/v1/namespaces/projectoperator/pods/kerberos-cronjob-29099490-zfz5b
      2 /api/v1/namespaces/projectoperator/pods/kerberos-cronjob-29099505-7rp58
      2 /api/v1/namespaces/rancher-ldap
      2 /api/v1/secrets
      3 /api/v1/namespaces/csi-storage
      3 /api/v1/namespaces/kube-system
      3 /api/v1/namespaces/kube-system/configmaps/rke2-etcd-snapshots
      3 /api/v1/namespaces/projectoperator/pods/kerberos-cronjob-29099510-nj7j8
      4 /api/v1/namespaces/cattle-system
      4 /api/v1/namespaces/cluster-fleet-default-kuba-cluster-0e3a85e89a06/secrets/alphafold-alphafold
      4 /api/v1/namespaces/cluster-fleet-default-kuba-cluster-0e3a85e89a06/secrets/alphafolddev-alphafold-dev
      4 /api/v1/namespaces/cluster-fleet-default-kuba-cluster-0e3a85e89a06/secrets/binder-binder
      4 /api/v1/namespaces/cluster-fleet-default-kuba-cluster-0e3a85e89a06/secrets/binder-binder-overlays
      4 /api/v1/namespaces/cluster-fleet-default-kuba-cluster-0e3a85e89a06/secrets/binder-dev-binder-dev
      4 /api/v1/namespaces/cluster-fleet-default-kuba-cluster-0e3a85e89a06/secrets/biomedai-mlflow-mlflow
      4 /api/v1/namespaces/cluster-fleet-default-kuba-cluster-0e3a85e89a06/secrets/biomedai-summer-hub-biomedai-school
      4 /api/v1/namespaces/cluster-fleet-default-kuba-cluster-0e3a85e89a06/secrets/biomedai-summer-hub-biomedai-school-overlays
      4 /api/v1/namespaces/cluster-fleet-default-kuba-cluster-0e3a85e89a06/secrets/biomedai-xopat-xopat
      4 /api/v1/namespaces/cluster-fleet-default-kuba-cluster-0e3a85e89a06/secrets/c9088hub-c9088-hub
      4 /api/v1/namespaces/cluster-fleet-default-kuba-cluster-0e3a85e89a06/secrets/c9088hub-c9088-hub-overlays
      4 /api/v1/namespaces/cluster-fleet-default-kuba-cluster-0e3a85e89a06/secrets/cashub-cashub
      4 /api/v1/namespaces/cluster-fleet-default-kuba-cluster-0e3a85e89a06/secrets/cashub-cashub-overlays
      4 /api/v1/namespaces/cluster-fleet-default-kuba-cluster-0e3a85e89a06/secrets/cashubresguard-cashubresguard
      4 /api/v1/namespaces/cluster-fleet-default-kuba-cluster-0e3a85e89a06/secrets/cloudnative-pg-cloudnativepg
      4 /api/v1/namespaces/cluster-fleet-default-kuba-cluster-0e3a85e89a06/secrets/csi-onedata-csi-onedata
      4 /api/v1/namespaces/cluster-fleet-default-kuba-cluster-0e3a85e89a06/secrets/datalabs-datalabs
      4 /api/v1/namespaces/cluster-fleet-default-kuba-cluster-0e3a85e89a06/secrets/datalabs-datalabs-overlays
      4 /api/v1/namespaces/cluster-fleet-default-kuba-cluster-0e3a85e89a06/secrets/democratic-zfs-democratic-zfs
      4 /api/v1/namespaces/cluster-fleet-default-kuba-cluster-0e3a85e89a06/secrets/dragonfly-operator-dragonfly
      4 /api/v1/namespaces/cluster-fleet-default-kuba-cluster-0e3a85e89a06/secrets/fleet-agent-kuba-cluster
      4 /api/v1/namespaces/cluster-fleet-default-kuba-cluster-0e3a85e89a06/secrets/hub-grafana-hub-grafana
      4 /api/v1/namespaces/cluster-fleet-default-kuba-cluster-0e3a85e89a06/secrets/hub-hub
      4 /api/v1/namespaces/cluster-fleet-default-kuba-cluster-0e3a85e89a06/secrets/hub-prometheus-proxy-hub-prometheus-proxy
      4 /api/v1/namespaces/cluster-fleet-default-kuba-cluster-0e3a85e89a06/secrets/hubresguard-hubresguard
      4 /api/v1/namespaces/cluster-fleet-default-kuba-cluster-0e3a85e89a06/secrets/iirhub-iirhub
      4 /api/v1/namespaces/cluster-fleet-default-kuba-cluster-0e3a85e89a06/secrets/iirhub-iirhub-overlays
      4 /api/v1/namespaces/cluster-fleet-default-kuba-cluster-0e3a85e89a06/secrets/ipcei-hub-ipcei-hub
      4 /api/v1/namespaces/cluster-fleet-default-kuba-cluster-0e3a85e89a06/secrets/ipcei-hub-ipcei-hub-overlays
      4 /api/v1/namespaces/cluster-fleet-default-kuba-cluster-0e3a85e89a06/secrets/ipcei-mlflow-mlflow-ipcei
      4 /api/v1/namespaces/cluster-fleet-default-kuba-cluster-0e3a85e89a06/secrets/jupytulhub-jupytulhub
      4 /api/v1/namespaces/cluster-fleet-default-kuba-cluster-0e3a85e89a06/secrets/jupytulhub-jupytulhub-overlays
      4 /api/v1/namespaces/cluster-fleet-default-kuba-cluster-0e3a85e89a06/secrets/kube-janitor-janitor
      4 /api/v1/namespaces/cluster-fleet-default-kuba-cluster-0e3a85e89a06/secrets/logging-logging
      4 /api/v1/namespaces/cluster-fleet-default-kuba-cluster-0e3a85e89a06/secrets/logging-logging-overlays
      4 /api/v1/namespaces/cluster-fleet-default-kuba-cluster-0e3a85e89a06/secrets/minio-operator-kuba-minio-operator
      4 /api/v1/namespaces/cluster-fleet-default-kuba-cluster-0e3a85e89a06/secrets/mlflow-fi-mlflow-fi
      4 /api/v1/namespaces/cluster-fleet-default-kuba-cluster-0e3a85e89a06/secrets/monitoring-overlays-monitoring-kuba-overlays
      4 /api/v1/namespaces/cluster-fleet-default-kuba-cluster-0e3a85e89a06/secrets/neurohub-jupyterhub-neuro
      4 /api/v1/namespaces/cluster-fleet-default-kuba-cluster-0e3a85e89a06/secrets/neurohub-jupyterhub-neuro-overlays
      4 /api/v1/namespaces/cluster-fleet-default-kuba-cluster-0e3a85e89a06/secrets/oauth2-proxy-oauth2-proxy
      4 /api/v1/namespaces/cluster-fleet-default-kuba-cluster-0e3a85e89a06/secrets/oom-detector-oom-detector
      4 /api/v1/namespaces/cluster-fleet-default-kuba-cluster-0e3a85e89a06/secrets/postgres-postgres
      4 /api/v1/namespaces/cluster-fleet-default-kuba-cluster-0e3a85e89a06/secrets/ray-operator-ray-operator
      4 /api/v1/namespaces/cluster-fleet-default-kuba-cluster-0e3a85e89a06/secrets/scaphandre-scaphandre
      4 /api/v1/namespaces/cluster-fleet-default-kuba-cluster-0e3a85e89a06/secrets/sealed-secrets-sealed-secrets
      4 /api/v1/namespaces/cluster-fleet-default-kuba-cluster-0e3a85e89a06/secrets/spark-spark
      4 /api/v1/namespaces/cluster-fleet-default-kuba-cluster-0e3a85e89a06/secrets/tesk-auth-tesk-tesk-auth
      4 /api/v1/namespaces/cluster-fleet-default-kuba-cluster-0e3a85e89a06/secrets/tesk-ma-tesk-tesk-ma
      4 /api/v1/namespaces/cluster-fleet-default-kuba-cluster-0e3a85e89a06/secrets/tesk-nauth-tesk-tesk-nauth
      4 /api/v1/namespaces/cluster-fleet-default-kuba-cluster-0e3a85e89a06/secrets/wes-auth-wes-wes-auth
      4 /api/v1/namespaces/cluster-fleet-default-kuba-cluster-0e3a85e89a06/secrets/wes-nauth-wes-wes-nauth
      4 /api/v1/namespaces/cluster-fleet-default-kubh-cluster-726e6cc29756/secrets/cloudnative-pg-kubh-cloudnativepg
      4 /api/v1/namespaces/cluster-fleet-default-kubh-cluster-726e6cc29756/secrets/dragonfly-operator-kubh-dragonfly
      4 /api/v1/namespaces/cluster-fleet-default-kubh-cluster-726e6cc29756/secrets/fleet-agent-kubh-cluster
      4 /api/v1/namespaces/cluster-fleet-default-kubh-cluster-726e6cc29756/secrets/harbor-copas-kubh-harbor-copas
      4 /api/v1/namespaces/cluster-fleet-default-kubh-cluster-726e6cc29756/secrets/harbor-egi-harbor-egi
      4 /api/v1/namespaces/cluster-fleet-default-kubh-cluster-726e6cc29756/secrets/kube-janitor-kubh-janitor-kubh
      4 /api/v1/namespaces/cluster-fleet-default-kubh-cluster-726e6cc29756/secrets/logging-kubh-logging-kubh
      4 /api/v1/namespaces/cluster-fleet-default-kubh-cluster-726e6cc29756/secrets/logging-kubh-logging-kubh-overlays
      4 /api/v1/namespaces/cluster-fleet-default-kubh-cluster-726e6cc29756/secrets/minio-operator-kubh-minio-operator
      4 /api/v1/namespaces/cluster-fleet-default-kubh-cluster-726e6cc29756/secrets/sealed-secrets-kubh-sealed-secrets
      4 /api/v1/namespaces/cluster-fleet-default-nma-cluster-d73b0dbab601/secrets/fleet-agent-nma-cluster
      4 /api/v1/namespaces/cluster-fleet-local-local-1a3d67d0a899/secrets/cdn-rancher-cdn
      4 /api/v1/namespaces/cluster-fleet-local-local-1a3d67d0a899/secrets/cloudnative-pg-rancher-cloudnativepg
      4 /api/v1/namespaces/cluster-fleet-local-local-1a3d67d0a899/secrets/fleet-agent-local
      4 /api/v1/namespaces/cluster-fleet-local-local-1a3d67d0a899/secrets/kube-janitor-rancher-janitor-rancher
      6 /api/v1/namespaces/calico-system/configmaps/cni-config
      6 /api/v1/namespaces/calico-system/configmaps/tigera-ca-bundle
      6 /api/v1/namespaces/calico-system/secrets/node-certs
      6 /api/v1/namespaces/calico-system/secrets/typha-certs
      6 /api/v1/namespaces/calico-system/services/calico-kube-controllers-metrics
      6 /api/v1/namespaces/calico-system/services/calico-typha
      6 /api/v1/namespaces/tigera-operator/secrets/node-certs
      6 /api/v1/namespaces/tigera-operator/secrets/tigera-ca-private
      6 /api/v1/namespaces/tigera-operator/secrets/typha-certs
      6 /apis/apps/v1/namespaces/calico-system/daemonsets/calico-node
      6 /apis/apps/v1/namespaces/calico-system/daemonsets/csi-node-driver
      6 /apis/apps/v1/namespaces/calico-system/deployments/calico-kube-controllers
      6 /apis/apps/v1/namespaces/calico-system/deployments/calico-typha
      7 /api/v1/namespaces/calico-system
      8 /api/v1/namespaces/cluster-fleet-default-kuba-cluster-0e3a85e89a06/secrets/envinjector-envinjector
      8 /api/v1/namespaces/cluster-fleet-default-kuba-cluster-0e3a85e89a06/secrets/ingress-vw-ingress-vw
      8 /api/v1/namespaces/cluster-fleet-default-kuba-cluster-0e3a85e89a06/secrets/pod-banking-pod-banking
      8 /api/v1/namespaces/cluster-fleet-default-kubh-cluster-726e6cc29756/secrets/envinjector-envinjector
      8 /api/v1/namespaces/cluster-fleet-default-kubh-cluster-726e6cc29756/secrets/ingress-vw-ingress-vw
      8 /api/v1/namespaces/cluster-fleet-default-kubh-cluster-726e6cc29756/secrets/pod-banking-pod-banking
      9 /apis/batch/v1/jobs
     18 /api/v1/namespaces/kube-system/services/rancher-monitoring-kubelet
     18 /api/v1/services
     23 /api/v1/namespaces/cattle-provisioning-capi-system/secrets?labelSelector=owner%3Dhelm
     23 /api/v1/namespaces/cattle-system/configmaps/rancher-charts-0-fa61d99b-61ae-4495-a179-553535e7e4bd
     23 /api/v1/namespaces/rancher-operator-system
     23 /api/v1/namespaces/rancher-operator-system/secrets?labelSelector=owner%3Dhelm
     24 /api/v1/namespaces/fleet-local/secrets/local-kubeconfig
     24 /api/v1/namespaces/fleet-system/secrets?labelSelector=owner%3Dhelm
     25 /api/v1/namespaces/kube-system/configmaps/full-cluster-state?timeout=15m0s
     25 /api/v1/namespaces/kube-system/secrets/full-cluster-state?timeout=15m0s
     25 /apis/batch/v1/namespaces/fleet-default/cronjobs?labelSelector=objectset.rio.cattle.io%2Fhash%3Ddd9dbcfd7c38885d30e78acb65a58e5962640802\u0026timeout=15m0s
     42 /api/v1/namespaces/cdn-ns/persistentvolumeclaims/cdn1
     42 /api/v1/namespaces/proxy-idp/persistentvolumeclaims/pvc-proxy-idp-config
     42 /api/v1/namespaces/proxy-idp/persistentvolumeclaims/pvc-proxy-idp-logs
     42 /api/v1/namespaces/proxy-idp/persistentvolumeclaims/pvc-proxy-idp-theme
     42 /api/v1/namespaces/rancher-ldap/persistentvolumeclaims/data-openldap-0
     42 /api/v1/persistentvolumes/pv-cdn1
     42 /api/v1/persistentvolumes/pv-openldap-0
     42 /api/v1/persistentvolumes/pv-proxy-idp-config
     42 /api/v1/persistentvolumes/pv-proxy-idp-logs
     42 /api/v1/persistentvolumes/pv-proxy-idp-theme
     43 /api/v1/namespaces/harbor/persistentvolumeclaims/harbor
     43 /api/v1/namespaces/rancher-ldap/persistentvolumeclaims/data-openldap-2
     43 /api/v1/persistentvolumes/pv-harbor
     43 /api/v1/persistentvolumes/pv-openldap-2
     44 /api/v1/namespaces/cattle-system/secrets?labelSelector=owner%3Dhelm
     44 /api/v1/namespaces/harbor/persistentvolumeclaims/harbor-db-1
     44 /api/v1/persistentvolumes/pv-harbor-db
     47 /api/v1/namespaces/cattle-fleet-system/secrets?labelSelector=owner%3Dhelm
     88 /api/v1/namespaces/cattle-system/persistentvolumeclaims/pvc-rancher
     88 /api/v1/persistentvolumes/pv-rancher
    125 /api/v1/namespaces/kube-system?timeout=15m0s
  23133 /api/v1/namespaces/cattle-global-data/secrets/shibbolethconfig-spkey
```

First timestamp in the audit.log is: 2025-04-29T23:25:05.677183Z, the last one is 2025-04-29T23:54:45.573978Z. 
Maybe something has been changed in the shibboleth and it now hits high rate of secret query?

> kubectl get secret -n cattle-impersonation-system | wc -l

Was this requested for the rancher cluster?

```
kubectl get secret -n cattle-impersonation-system | wc -l
No resources found in cattle-impersonation-system namespace.
0
```

Largest downstream cluster:
```
kubectl get secret -n cattle-impersonation-system | wc -l
      68
```

**Comment by xhejtman** [comment]
Hello, attaching required files - diag.zip contains both audit.log and new rancher profile. I stopped argo for this test. And also, attaching diagnostic json. 

[rancher-diagnostic-data (1).json](https://github.com/user-attachments/files/20022839/rancher-diagnostic-data.1.json)

[diag.zip](https://github.com/user-attachments/files/20022840/diag.zip)

**Comment by khushalchandak17** [comment]
Hello,
Thanks for sharing the Rancher profile data. After reviewing it, we believe the issue you’re facing is related to a known bug: [Rancher Issue #49667](https://github.com/rancher/rancher/issues/49667).

This issue has been fixed in Rancher version v2.11.1, so we recommend upgrading to that version.

Please try the upgrade and let us know if the problem still continues.

**Comment by xhejtman** [comment]
Hello, 

thank you for support. Unfortunately, we are on v2.11.1 and the issue is still present.

**Comment by xhejtman** [comment]
could this be the reason? I do not think we need so many tokens, they are probably not cleaned.

```
kubectl get tokens.management.cattle.io -A | wc -l
7028
```

**Comment by khushalchandak17** [comment]
Well. first thanks for reporting this issue. We have been able to successfully reproduce the behavior in our environment, and we are now tracking the issue and fix in [50484](https://github.com/rancher/rancher/issues/50484). We will be sharing all updates and progress there, so closing this one to consolidate the discussion.
You can find the RCA and fix in this  [PR](https://github.com/rancher/steve/pull/647).
