### ISSUE TITLE
generated /etc/resolv.conf in containers not compatible with alpine:3.4

### ISSUE THREAD

**Issue by giabao** [rancher/rancher#5041]
**Rancher Version:**
1.0.2
**Docker Version:**
1.11.2
**OS and where are the hosts located? (cloud, bare metal, etc):**
Ubuntu 16.04 on digital ocean
**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node, internal DB
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle
**Steps to Reproduce:**
- Add a service with image = `alpine:3.4`, CMD = `ping rancher-metadata.rancher.internal`, using default for all other options.
- _Execute Shell_ from the container.
- run `ping rancher-metadata`

**Results:** 
`ping: bad address 'rancher-metadata'`

**Expected:**
pingable to `rancher-metadata`, similar to `rancher-metadata.rancher.internal`:

```
PING rancher-metadata.rancher.internal (169.254.169.250): 56 data bytes
64 bytes from 169.254.169.250: seq=0 ttl=64 time=0.220 ms
64 bytes from 169.254.169.250: seq=1 ttl=64 time=0.236 ms

```

**Comment by giabao** [comment]
Other useful info:
+ related issue on alpine: gliderlabs/docker-alpine/issues/8
+ musl version of alpine:3.4
```
ldd --version
musl libc (x86_64)
Version 1.1.14
Dynamic Program Loader
```
+ search domain resolving [is supported](gliderlabs/docker-alpine/issues/8#issuecomment-178884867) from [musl 1.1.13+](http://git.musl-libc.org/cgit/musl/tree/WHATSNEW?h=v1.1.14#n1624)
+ inside alpine:3.4 container:
```
# cat /etc/resolv.conf
search mosquitto.rancher.internal alpine.mosquitto.rancher.internal rancher.internal
nameserver 169.254.169.250
```
`mosquitto` is stack name, `alpine` is service name.
If I change /etc/resolv.conf to (move `rancher.internal` to first search domain):
```
search rancher.internal mosquitto.rancher.internal alpine.mosquitto.rancher.internal
nameserver 169.254.169.250
```
Then I can ping rancher-metadata as expected:
```
# ping rancher-metadata
PING rancher-metadata (169.254.169.250): 56 data bytes
64 bytes from 169.254.169.250: seq=0 ttl=64 time=0.338 ms
```

**Comment by giabao** [comment]
maybe resolv.conf is setup in [start_handler](https://github.com/rancher/host-api/blob/b9d6c1e/events/start_handler.go#L65).
I wonder whether we can move `rancher.internal` to be the first search domain (so rancher dns can work with alpine:3.4+)?

**Comment by guiguan** [comment]
@giabao This problem is fixed in alpine:edge

**Comment by guiguan** [comment]
@giabao yes, you are right. the rancher.internal needs to be the first

**Comment by guiguan** [comment]
Alpine Linux uses musl lib to handle resolv.conf, which behaves differently than glibc's implementation in several ways. If rancher.internal is the third item in resolv.conf's search definition, 'rancher-metadata' will not get searched against rancher.internal, and dns resolution will fail.

**Comment by Joeasaurus** [comment]
I see the same in `ubuntu:14.04.3` with my internal domains (which I think come from `ros config get rancher.network.dns.search`?)

Moving the `rancher.internal` to the front makes it work:

```
search rancher.internal myinternal.domain.com
nameserver 169.254.169.250
```

**Comment by cgiraldo** [comment]
My workaround:

I manually set "internal.rancher" as a search domain for my services, and it is now the first search domain.

It works by changing the configuration in Networking Tab of the UI, 
or including in your docker-compose file this:

`
alpine:
  image: alpine:3.4
  dns_search:
  - rancher.internal
`

**Comment by weikinhuang** [comment]
Has there been any movement on this?

**Comment by LoicMahieu** [comment]
I am also concerned by the problem. I run CI build in Kubernetes and I am using the `docker` image which is based on Alpine 3:4...

**Comment by Flowman** [comment]
Could this be related to the issue #7160 I have?

**Comment by LoicMahieu** [comment]
Has there been any progress on that?

**Comment by richfelker** [comment]
The problem seems to be that rancher's dns is returning "name exists but has no RRs of the requested type" (RCODE=0, Success) instead of "name does not exist" (RCODE=3, NxDomain), for nonexistent names. Fixing this should solve all compatibility problems with musl libc/Alpine.

**Comment by JakeWarner** [comment]
@richfelker The solution you just described conflicts with https://www.ietf.org/rfc/rfc4074.txt where the current return is proper.

**Comment by richfelker** [comment]
@JakeWarner You need to be more specific about what part of the RFC you claim supports the current behavior. My reading of it is the opposite; it explains why the nameserver needs to behave the way I suggested fixing it to behave, and why musl's resolver behaves the way it does, in order to ensure consistency when you have existent names that have just one or the other (but not both) of A and AAAA records. It does not in any way imply that you should return RCODE=0 for names that do not exist at all.

**Comment by JakeWarner** [comment]
Oh, my bad -- for nonexistent names you're correct.

I was doing a ton of research on services return IPv6 vs IPv4 and how musl is different than the others in resolution. My initial message was based on the assumption this thread was talking about ipv4 (type A) results existing but not ipv6 (type AAAA) which would have referenced section 3 on RFC 4074:

> 3.  Expected Behavior
>
>   Suppose that an authoritative server has an A RR but has no AAAA RR
>   for a host name.  Then, the server should return a response to a
>   query for an AAAA RR of the name with the response code (RCODE) being
>   0 (indicating no error) and with an empty answer section (see
>   Sections 4.3.2 and 6.2.4 of [1]).  Such a response indicates that
>   there is at least one RR of a different type than AAAA for the
>   queried name, and the stub resolver can then look for A RRs.
>
>   This way, the caching server can cache the fact that the queried name
>   has no AAAA RR (but may have other types of RRs), and thus improve
>   the response time to further queries for an AAAA RR of the name.

**Comment by janeczku** [comment]
Agree with @richfelker's assessment on what's the root cause here. The specialty of the musl resolver seems to be that when it does the search it "takes none for an answer" (NODATA) and stops trying the other search domains. glibc's resolver on the contrary will continue searching the other domains and thus find the record with the data. That probably also means that with musl you should under no circumstances have a wildcard domain in your domain tree as this might mask the actual record.

**Comment by leodotcloud** [comment]
Fixed by `network-services: v0.2.0` and `rancher/dns:v0.15.0`.

**Comment by sangeethah** [comment]
Tested with network-services: v0.2.0 and  rancher/dns:v0.15.0
Able to ping rancher-metadata from within containers deployed with image = alpine:3.4 and command ping rancher-metadata.rancher.internal.

<img width="1248" alt="screen shot 2017-04-20 at 10 38 56 am" src="https://cloud.githubusercontent.com/assets/4266958/25244451/acf41288-25b5-11e7-84ef-3e3524cab9e2.png">


Was able to reproduce this issue with 1.2.4 rancher server which has network-services: v0.0.8 and rancher/dns:v0.13.0

<img width="680" alt="screen shot 2017-04-20 at 10 40 33 am" src="https://cloud.githubusercontent.com/assets/4266958/25244510/eb3aecb0-25b5-11e7-9efd-d0e26ae79055.png">

**Comment by frol** [comment]
It seems that it is still an issue with Alpine when services are in different stacks.
