### ISSUE TITLE
[BUG] SQLite backed cache: Requests to filter/sort on entries in an array fail

### ISSUE THREAD

**Issue by richard-cox** [rancher/rancher#50526]
**Rancher Server Setup**
- Rancher version: v2.12.0 (dev of) - v2.12-62362dfd905a75f77865a47aff683a195cc6ac66-head

**Describe the bug**
- filter/sort is broken for the following properties
  - `networking.k8s.io.ingresses` `spec.rules[0].host`
    - Request - `/v1/networking.k8s.io.ingresses?sort=spec.rules[0].host`
    - Response - 422 InvalidBodyContent `column is invalid [spec.rules[0].hos]]: supplied column is invalid`
    - Field is indexed - https://github.com/rancher/steve/blob/main/pkg/stores/sqlproxy/proxy_store.go#L156-L159
  -  `apps.deployments` `spec.template.spec.containers.image`
     - given a deployment with two contains, one with image `nginx` and another with `nginx:latest`
     - Request - `/v1/apps.deployments?filter=spec.template.spec.containers.image=nginx`
     - Response - 200 no results - expected 200 1 result
     - Field is resources - https://github.com/rancher/steve/blob/main/pkg/stores/sqlproxy/proxy_store.go#L101
     - Notes
       - partial match with `~` correctly returns a result
       - same issue applies to `/v1/networking.k8s.io.ingresses?filter=spec.rules.host=aaa.com`, where a resource contains a spec rule with host `aaa.com`. no results, but changing from exact `=` to partial `~` works
- It would be worth double checking the feature set in #49116 is working

**To Reproduce**
- enable vai ff, make requests above

**Result**
- as per description

**Expected Result**
- 200 response, correctly filtered/sorted

**Comment by ericpromislow** [comment]
The two bug reports are contradictory in respect to what we've discussed before.

To recap:

vai recognizes explicit arrays, currently only for `metadata.fields[0]`, `metadata.fields[1]`, etc. These come from each GVK's schema. You can't filter/sort on `metadata.fields` -- you have to specify an explicit index.

vai also has implicit arrays. These come from sources like from this JSON:
```
{...
  spec: {
    rules: [ 
     {
       host: "host1",
       data: "other data for host1..."
    },
     {
       host: "host2",
       data: "other data for host2..."
    },
    ... // other rules
  ]
 } // end spec
}
```

This data is stored in a database string field `spec.rules.host` with value `host1|host2|...`

The first request above:

`Request - /v1/networking.k8s.io.ingresses?sort=spec.rules[0].host`

can be done, and I've implemented that.  `filter=spec.rules[0].host=host1` will succeed, but `filter=spec.rules[1].host=host1` will fail.

You can also do `filter=spec.rules.host~host1` or `filter=spec.rules.host~host2`.  There are also perverse filters that will succeed in this instance, like `filter=spec.rules.host~st1|ho` and even `filter=spec.rules.host=host1|host2|...` if you know what all the values are. There is little to be gained in forbidding these.

The second request above:
Given a pseudo-array db field `spec.template.spec.containers.image` in `apps.deployments` with value `nginx|nginx:latest`, you're asking why `filter=spec.template.spec.containers.image=nginx`failed. This is for the same reason that `filter=spec.rules[1].host=host1` fails in the previous example.

I actually implemented a variant where this value would succeed, but it was rejected because if we have a pseudo-array with a string like `...|true|false|...` then both
`filter=FIELD=true` and
`filter=FIELD=false` would succeed.
Of course if we implement a `CONTAINS` operator then there's nothing wrong having both `filter=FIELD CONTAINS true` and`filter=FIELD CONTAINS false` succeed.

**Comment by ericpromislow** [comment]
Also from issue 49116:

> The big one atm is [PodTemplateSpec](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.32/#podtemplatespec-v1-core) spec.containers.image for workload like types (deployments, pods, jobs, etc)
> 
> containers is an array and we're trying to either match exact (does a deployment with a container with a specific image exist) or partial (searching pods for an image)

This requirement sure sounds like a `CONTAINS` operator to me. Whether it's explicit or not is up to you.

In the meantime yesterday I implemented array indexing on fields like `spec.template.spec.containers.image`

**Comment by richard-cox** [comment]
v2.12-097a9b540ac81a496f7b8c1210e2cc53d3939b0c-head

> part 1 - networking.k8s.io.ingresses spec.rules[0].host

- was the filtering in a pr? i still see this failing
  - Request `/v1/networking.k8s.io.ingresses?filtering=spec.rules[0].host=aaa`
  - Response `{ "code": "InvalidBodyContent", "message": "column is invalid [spec.rules[0].hos]]: supplied column is invalid","status": 422}`
- without the index also fails (though this will be connected to part 2 i guess)
  - Resources  `/v1/networking.k8s.io.ingresses?filtering=spec.rules.host`
     ```
     1... spec": { "rules": [ {"host": "bbb"},{"host": "ddd"}]}
     2... spec": { "rules": [ {"host": "ccc"},{"host": "aaa"}]}
     ```
  - Request `/v1/networking.k8s.io.ingresses?filtering=spec.rules.host=aaa`
  - Response - neither
  - Expected - 2
- sorting does not work
  - Request `/v1/networking.k8s.io.ingresses?sort=spec.rules[0].host`
  - Response `{ "code": "InvalidBodyContent", "message": "column is invalid [spec.rules[0].hos]]: supplied column is invalid","status": 422}`

> part 2 apps.deployments spec.template.spec.containers.image

I'm not sure on the implementation detail (how it's stored or the sql statement), just the the same ask has been around for many months now - filtering (exact and partial) and sorting on properties in an array needs to be supported. There was discussion in https://github.com/rancher/rancher/issues/49116, however the issue was closed without the original ask or resulting discussion being resolved (there's an open comment there).

Will exact matching on properties in arrays be supported in 2.12.0?

**Comment by ericpromislow** [comment]
It looks like steve PR 673 addresses both this issue and 49116.

But if a field is acting like a |-separated multi-value string, like `spec.template.spec.containers.image`, you can no longer do an equality check on a single value unless the string contains only one value. You can use the partial-match `~` operator do match if the field contains a particular value, but that can return false positives.

A bit of programming philosophy here: arrays are often ordered values, and sets are unordered. We don't have sets here, but many of the array-like things in k8s objects are more like sets-with-duplicates -- i.e., order doesn't matter. And the examples you've given above are more set-like than array-like, and that's why I think we should provide a `CONTAINS` operator. But that can happen later, and let's ensure the VAI backend can accomodate the front-end's needs.

**Comment by brudnak** [comment]
<details>
    <summary>🧪 Test Environment... CLICK TO EXPAND! ⬅️</summary>
<br>


| Component                        | Version / Type                                      |
| -------------------------------- | --------------------------------------------------- |
| Rancher version                  | v2.12-b178abf7900f76a07ae940301e21305d53a6ad99-head |
| Installation option              | Helm (high availability)                            |
| If Helm Chart k8s cluster        | v1.30.11+k3s1                                       |
| Cert Details                     | external tls `aws acm`                              |
| k3s ha external db               | Aurora MySQL 5.7.mysql_aurora.2.11.1                |
| Downstream cluster type          | n/a                                                 |
| Downstream K8s version           | n/a                                                 |
| Authentication providers enabled | local                                               |
| Logged in user role              | admin                                               |
| Webhook version                  | rancher/rancher-webhook:v0.8.0-rc.12                |

test data: `data.yaml`

```yaml
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress1
  namespace: default
  labels:
    test-group: "array-filtering"
spec:
  rules:
    - host: aaa.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: test-service
                port:
                  number: 80
    - host: bbb.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: test-service
                port:
                  number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress2
  namespace: default
  labels:
    test-group: "array-filtering"
spec:
  rules:
    - host: ccc.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: test-service
                port:
                  number: 80
    - host: aaa.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: test-service
                port:
                  number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress3
  namespace: default
  labels:
    test-group: "array-filtering"
spec:
  rules:
    - host: ddd.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: test-service
                port:
                  number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress4
  namespace: default
  labels:
    test-group: "array-filtering"
spec:
  rules:
    - host: aaa-prod.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: test-service
                port:
                  number: 80
    - host: aaa-dev.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: test-service
                port:
                  number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress5-empty
  namespace: default
  labels:
    test-group: "array-filtering"
spec:
  defaultBackend:
    service:
      name: test-service
      port:
        number: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment1
  namespace: default
  labels:
    test-group: "array-filtering"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-deployment1
  template:
    metadata:
      labels:
        app: test-deployment1
    spec:
      containers:
        - name: nginx
          image: nginx:1.19
          ports:
            - containerPort: 80
        - name: redis
          image: redis:6.0
          ports:
            - containerPort: 6379
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment2
  namespace: default
  labels:
    test-group: "array-filtering"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-deployment2
  template:
    metadata:
      labels:
        app: test-deployment2
    spec:
      containers:
        - name: nginx
          image: nginx:1.20
          ports:
            - containerPort: 80
        - name: postgres
          image: postgres:13
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_PASSWORD
              value: testpassword
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment3
  namespace: default
  labels:
    test-group: "array-filtering"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-deployment3
  template:
    metadata:
      labels:
        app: test-deployment3
    spec:
      containers:
        - name: nginx-old
          image: nginx:1.19
          ports:
            - containerPort: 80
        - name: nginx-new
          image: nginx:1.20
          ports:
            - containerPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment4
  namespace: default
  labels:
    test-group: "array-filtering"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-deployment4
  template:
    metadata:
      labels:
        app: test-deployment4
    spec:
      containers:
        - name: myapp
          image: myapp:v1.0-feature
          ports:
            - containerPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment5-special-chars
  namespace: default
  labels:
    test-group: "array-filtering"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-deployment5
  template:
    metadata:
      labels:
        app: test-deployment5
    spec:
      containers:
        - name: special-app
          image: my-app:v1.0-beta-test
          ports:
            - containerPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment6-many-containers
  namespace: default
  labels:
    test-group: "array-filtering"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-deployment6
  template:
    metadata:
      labels:
        app: test-deployment6
    spec:
      containers:
        - name: container1
          image: busybox:1.35
          command: ["sleep", "3600"]
        - name: container2
          image: alpine:3.17
          command: ["sleep", "3600"]
        - name: container3
          image: ubuntu:22.04
          command: ["sleep", "3600"]
        - name: container4
          image: centos:8
          command: ["sleep", "3600"]
        - name: container5
          image: debian:11
          command: ["sleep", "3600"]
        - name: container6
          image: fedora:37
          command: ["sleep", "3600"]
---
apiVersion: v1
kind: Service
metadata:
  name: test-service
  namespace: default
  labels:
    test-group: "array-filtering"
spec:
  selector:
    app: test-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-backend
  namespace: default
  labels:
    test-group: "array-filtering"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-backend
  template:
    metadata:
      labels:
        app: test-backend
    spec:
      containers:
        - name: nginx
          image: nginx:alpine
          ports:
            - containerPort: 80
```

apply with: `k apply -f data.yaml`

</details>

<a name="top"></a>

### 🧪 Test Cases

| \#  | Priority | Description & Link                                          | PASS/FAIL |
| --- | -------- | ----------------------------------------------------------- | --------- |
| 1   | P0       | [Find ingresses with "aaa" in any host](#test-1)            | ✅ PASS    |
| 2   | P0       | [Find ingresses with exact host "aaa.example.com"](#test-2) | ✅ PASS    |
| 3   | P0       | [Find ingresses with "bbb" in any host](#test-3)            | ✅ PASS    |
| 4   | P0       | [Find deployments with nginx containers](#test-4)           | ✅ PASS    |
| 5   | P0       | [Find deployments with specific nginx:1.19](#test-5)        | ✅ PASS    |
| 6   | P0       | [Find deployments with redis](#test-6)                      | ✅ PASS    |
| 7   | P0       | [Indexed access works for metadata.fields](#test-7)         | ✅ PASS    |
| 8   | P0       | [Filter by specific field index](#test-8)                   | ✅ PASS    |
| 9   | P0       | [Basic metadata filtering](#test-9)                         | ✅ PASS    |
| 10  | P0       | [Label filtering](#test-10)                                 | ✅ PASS    |

<details>
    <summary>🚨 10 test cases... CLICK TO EXPAND! (For table links to work) ⬅️</summary>
<br>

# 1 / Find ingresses with "aaa" in any host Status: ✅ PASS

<a name="test-1"></a>

**:small_red_triangle: [back to top](#top)**

<details>
    <summary>Test 1 details... Click to expand</summary>

**Test Steps for Validation**

1. `/v1/networking.k8s.io.ingresses?filter=spec.rules.host~aaa`

**✅ Expected Outcome**

Expected: ingress1, ingress2, ingress4

**✅ Actual Outcome**

Got: ingress1, ingress2, ingress4

</details>
<hr>

# 2 / Find ingresses with exact host "aaa.example.com" Status: ✅ PASS

<a name="test-2"></a>

**:small_red_triangle: [back to top](#top)**

<details>
    <summary>Test 2 details... Click to expand</summary>

**Test Steps for Validation**

1. `v1/networking.k8s.io.ingresses?filter=spec.rules.host~aaa.example.com`

**✅ Expected Outcome**

Expected: ingress1, ingress2

**✅ Actual Outcome**

Got: ingress1, ingress2

</details>
<hr>

# 3 / Find ingresses with "bbb" in any host Status: ✅ PASS

<a name="test-3"></a>

**:small_red_triangle: [back to top](#top)**

<details>
    <summary>Test 3 details... Click to expand</summary>

**Test Steps for Validation**

1. `/v1/networking.k8s.io.ingresses?filter=spec.rules.host~bbb`

**✅ Expected Outcome**

Expected: ingress1 only

**✅ Actual Outcome**

Got: ingress1 only

</details>
<hr>

# 4 / Find deployments with nginx containers Status: ✅ PASS

<a name="test-4"></a>

**:small_red_triangle: [back to top](#top)**

<details>
    <summary>Test 4 details... Click to expand</summary>

**Test Steps for Validation**

1. `/v1/apps.deployments?filter=spec.template.spec.containers.image~nginx`

**✅ Expected Outcome**

Expected: deployment1, deployment2, deployment3, test-backend

**✅ Actual Outcome**

Got: deployment1, deployment2, deployment3, test-backend

</details>
<hr>

# 5 / Find deployments with specific nginx:1.19 Status: ✅ PASS

<a name="test-5"></a>

**:small_red_triangle: [back to top](#top)**

<details>
    <summary>Test 5 details... Click to expand</summary>

**Test Steps for Validation**

1. `/v1/apps.deployments?filter=spec.template.spec.containers.image~nginx:1.19`

**✅ Expected Outcome**

Expected: deployment1, deployment3

**✅ Actual Outcome**

Got: deployment1, deployment3

</details>
<hr>

# 6 / Find deployments with redis Status: ✅ PASS

<a name="test-6"></a>

**:small_red_triangle: [back to top](#top)**

<details>
    <summary>Test 6 details... Click to expand</summary>

**Test Steps for Validation**

1. `/v1/apps.deployments?filter=spec.template.spec.containers.image~redis`

**✅ Expected Outcome**

Expected: deployment1 only

**✅ Actual Outcome**

Got: deployment1 only

</details>
<hr>

# 7 / Indexed access works for metadata.fields Status: ✅ PASS

<a name="test-7"></a>

**:small_red_triangle: [back to top](#top)**

<details>
    <summary>Test 7 details... Click to expand</summary>

**Test Steps for Validation**

1. `/v1/networking.k8s.io.ingresses?filter=metadata.fields[0]=ingress1`

**✅ Expected Outcome**

Expected: ingress1 (metadata.fields[0] echoes metadata.name)

**✅ Actual Outcome**

Got: ingress1 (metadata.fields[0] echoes metadata.name)

</details>
<hr>

# 8 / Filter by specific field index Status: ✅ PASS

<a name="test-8"></a>

**:small_red_triangle: [back to top](#top)**

<details>
    <summary>Test 8 details... Click to expand</summary>

**Test Steps for Validation**

1. `/v1/networking.k8s.io.ingresses?filter=metadata.fields[2]~aaa`

**✅ Expected Outcome**

Expected: ingress1, ingress2, ingress4 (field 2 contains hosts with "aaa")

**✅ Actual Outcome**

Got: ingress1, ingress2, ingress4 (field 2 contains hosts with "aaa")

</details>
<hr>

# 9 / Basic metadata filtering Status: ✅ PASS

<a name="test-9"></a>

**:small_red_triangle: [back to top](#top)**

<details>
    <summary>Test 9 details... Click to expand</summary>

**Test Steps for Validation**

1. `/v1/networking.k8s.io.ingresses?filter=metadata.name=ingress1`

**✅ Expected Outcome**

Expected: ingress1 only

**✅ Actual Outcome**

Got: ingress1 only

</details>
<hr>

# 10 / Label filtering Status: ✅ PASS

<a name="test-10"></a>

**:small_red_triangle: [back to top](#top)**

<details>
    <summary>Test 10 details... Click to expand</summary>

**Test Steps for Validation**

1. `/v1/apps.deployments?filter=metadata.labels.test-group=array-filtering`

**✅ Expected Outcome**

Expected: All test deployments

**✅ Actual Outcome**

Got: All test deployments

</details>
<hr>

</details>
