### ISSUE TITLE
Kubernetes hostPort is not working

### ISSUE THREAD

**Issue by bonifaido** [rancher/rancher#5857]
**Rancher Version:**
1.2.0-pre2
**Docker Version:**
1.12
**OS and where are the hosts located? (cloud, bare metal, etc):**
Ubuntu 14.04 AWS
**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single node rancher with 3 agents in the Kubernetes environment
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Kubernetes (1.3.0-rancher3)
**Steps to Reproduce:**
Create a pod with a hostPort defined:

```
apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80
          hostPort: 8888
```

**Results:** 
You can't access the pod from outside the cluster on the hostPort
**Expected:**
The opposite.

**Comment by wlan0** [comment]
@bonifaido Kuberentes abstracts the hostport - this is a feature, not a bug. If you need to access the port, then you need to create a nodeport service. 

refer: https://github.com/kubernetes/kubernetes/issues/3267

**Comment by wlan0** [comment]
@bonifaido This seems to be a legit bug. I'm looking into it.

**Comment by wlan0** [comment]
@bonifaido This is because we use CNI. CNI does not support hostport configuration, and since we use CNI, we cannot use hostport in rancher kubernetes. Once this bug - https://github.com/kubernetes/kubernetes/issues/31307 is resolved, we'll be able to make our CNI plugin configure hostport.

**Comment by bonifaido** [comment]
Thank you for the clarification!

**Comment by tkrille** [comment]
I assume that this will still not work if one uses VXLAN instead of IPSec. Is this right?

**Comment by meggarr** [comment]
I am trying to use the [Node Exporter](https://github.com/coreos/prometheus-operator/tree/master/contrib/kube-prometheus/manifests/node-exporter) with Prometheus, it requires the `hostPort`, if it cannot work, will there be a workaround?

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.

**Comment by Joeasaurus** [comment]
Hi, I'm seeing this issue on Kubernetes Rancher v2.0. Is there a different bug for it?

**Comment by xulis** [comment]
I'm seeing this issue on Kubernetes Rancher v2.4.5

**Comment by Filz0r** [comment]
Hello, I'm seeing this issue on Rancher 2.5 running with docker as a single node

**Comment by occamsRZR** [comment]
I am also seeing this issue on Rancher v2.3.3 as a single node using v1.18.8+k3s1.

**Comment by raulmontemayor** [comment]
I'm seeing same issue Rancher v2.5.3, does anyone have a workaround?

**Comment by eltonk** [comment]
Rancher v2.5.5 also is presenting this issue.
