### ISSUE TITLE
Scheduled jobs not working in Kubernetes 1.4

### ISSUE THREAD

**Issue by galal-hussein** [rancher/rancher#6120]
**Rancher Version:**
rancher/server:master
**Docker Version:**
1.11.2
**OS and where are the hosts located? (cloud, bare metal, etc):**
Ubuntu
**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
single node rancher
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Kubernetes 1.4

The scheduled jobs has a perquisite of turning on batch v2alpha1 by passing the following option `--runtime-config=batch/v2alpha1` to the kube-api server.

**Comment by alena1108** [comment]
We should enable this api endpoint in the template: v2alpha1

**Comment by wlan0** [comment]
Fixed by: https://github.com/rancher/infra-catalog/pull/19

**Comment by weikinhuang** [comment]
@wlan0 Looks like the issue is not resolved. rancher/infra-catalog#19 was closed without merge

**Comment by wlan0** [comment]
We merged kubectl 1.4.4, now this bug is actually "resolved"

**Comment by weikinhuang** [comment]
@wlan0 however `v2alpha1` api is not enabled in the `1.2` branch

**Comment by galal-hussein** [comment]
@wlan0 Testing on master and rc6 builds still failing:

```
kubectl create -f scheduledjobs.yml 
error validating "scheduledjobs.yml": error validating data: couldn't find type: v2alpha1.ScheduledJob; if you choose to ignore these errors, turn validation off with --validate=false
```

**Comment by galal-hussein** [comment]
Scheduled jobs tested and worked on rc6 (rancher-catalog branch 1.2)

```
apiVersion: batch/v2alpha1
kind: ScheduledJob
metadata:
  name: hello
spec:
  schedule: 0/1 * * * ?
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello
            image: busybox
            args:
            - /bin/sh
            - -c
            - date; echo Hello from the Kubernetes cluster
          restartPolicy: OnFailure
```
```
> kubectl get scheduledjobs
NAME      SCHEDULE      SUSPEND   ACTIVE    LAST-SCHEDULE
hello     0/1 * * * ?   False     0         <none>

> kubectl get pods --show-all
NAME                     READY     STATUS      RESTARTS   AGE
hello-1858897738-4e2s1   0/1       Completed   0          6m
hello-1934722893-dt9h2   0/1       Completed   0          7m
hello-1934853965-z78b3   0/1       Completed   0          4m
hello-1934985037-l1yup   0/1       Completed   0          59s
hello-2010548048-matnf   0/1       Completed   0          8m
hello-2010679120-zcdqg   0/1       Completed   0          5m
hello-2010810192-02ti0   0/1       Completed   0          2m
hello-2086635347-ap5in   0/1       Completed   0          3m
```
