### ISSUE TITLE
All Info level logging gets reported in "Standard Error" tab and error logs are also reported as level=info

### ISSUE THREAD

**Issue by sangeethah** [rancher/rancher#6504]
Rancher server - Build from master

Steps to reproduce the problem:
Create a lb service by providing an invalid value in config parameter.
When haproxy fails to load the config , Lb container's logs have error messages relating to this.

The error messages are also logged with log level info.
Also all Info level logging gets reported in "Standard Error" tab.

<img width="996" alt="screen shot 2016-11-03 at 4 14 58 pm" src="https://cloud.githubusercontent.com/assets/4266958/19989012/db6ba170-a1e0-11e6-892d-0635468698cb.png">

**Comment by alena1108** [comment]
should be fixed by @StrongMonkey in the latest haproxy release

**Comment by sangeethah** [comment]
Tested with rancher server version - v1.2.1-rc1 with rancher/lb-service-haproxy:v0.4.5

I still see some Info level logging  reported in "Standard Error" tab and "Error" level log not reported in "Standard Error" tab.

<img width="1091" alt="screen shot 2016-12-13 at 2 22 45 pm" src="https://cloud.githubusercontent.com/assets/4266958/21161966/e15a38d4-c13f-11e6-8678-ab438a2bb2fc.png">

**Comment by StrongMonkey** [comment]
@alena1108 the log is from init function by other go files, which happens before we set stdout in main.go.

**Comment by alena1108** [comment]
@StrongMonkey understood about the init. But what about error log that goes to standard out (check the last line)

**Comment by StrongMonkey** [comment]
@alena1108 No idea, it seems like the logrus didn't separate the logs automatically. There might be a solution by using two separate loggers(one for stdout, one for stdin) to log different levels(info or error), but that might take too much efforts.

**Comment by aemneina** [comment]
Can we get an option to send haproxy logs to stdout, and errors to stderr, that way theyre visible within the rancher UI logs screen.

**Comment by alena1108** [comment]
@aemneina I've created https://github.com/rancher/rancher/issues/9616 to keep track of your request as it is quite different from the original bug.
