### ISSUE TITLE
During upgrade, tool tip says Current: Undefined

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#6653]
**Rancher Version:** master 11/16

**Steps to Reproduce:**
1.  Add a catalog item that has more than 1 version
2. Upgrade but don't finish
3.  Hover over the Upgraded: Finish Upgrade button

**Results:** Says Current: Undefined
![image](https://cloud.githubusercontent.com/assets/11514927/20371127/d461d7a2-ac1f-11e6-8ce7-31cf875e5e6d.png)

**Expected:**  Since in this case the newest version is running, it should probably reflect that.

**Comment by tfiduccia** [comment]
During Upgrade - the Upgrade in Progress button says Current: undefined.

**Comment by deniseschannon** [comment]
This should be fixed with the update in catalog-service.

**Comment by tfiduccia** [comment]
Version - v1.2.0-pre4-rc11
This is not fixed

**Comment by tfiduccia** [comment]
Version - 1.2.0-pre4-rc12
this is still not fixed..  Steps:
1.  add catalog
2.  use lower version
3.  upgrade..

results:
![image](https://cloud.githubusercontent.com/assets/11514927/20575863/63ca1cd0-b178-11e6-86eb-b4d574f859ec.png)

expected: a version number

**Comment by tfiduccia** [comment]
Version - v1.2.0-pre4-rc15
Verified fixed
