### ISSUE TITLE
Microservices containers are not starting correctly on RHEL hosts

### ISSUE THREAD

**Issue by galal-hussein** [rancher/rancher#6658]
**Rancher Version:**
master build (17 Nov)
**Docker Version:**
1.12.2
**OS and where are the hosts located? (cloud, bare metal, etc):**
RHEL 7 
**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single node rancher
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Kubernetes 1.4.6
**Steps to Reproduce:**
- Install master build Rancher server
- Add RHEL hosts
- Add rancher-catalog with branch 1.2
- Run kubernetes 1.4.6

**Results:** 
ipsec, healthcheck, and scheduler containers keep restarting.
**Expected:**
Stacks to be up and running.

**Comment by andreimc** [comment]
I have the same issue

**Comment by galal-hussein** [comment]
The same issue happens on normal cattle environment without Kubernetes:

healthcheck, ipsec, and scheduler containers are not starting correctly.

**Comment by galal-hussein** [comment]
I used storage pool option for docker when running rhel  instead of the default loopback device option:

```
DOCKER_STORAGE_OPTIONS=--storage-driver=devicemapper --storage-opt=dm.thinpooldev=/dev/mapper/docker-thinpool --storage-opt dm.use_deferred_removal=true
```

I am still seeing the dns, healthcheck, and ipsec containers failing.

**Comment by deniseschannon** [comment]
Fixed in network-manager - v0.2.6

**Comment by galal-hussein** [comment]
The microservices containers are still failing on RHEL setup 

Rancher version: v1.2.0-pre4-rc11
docker version: tested with (1.10, 1.11, 1.12)
storage driver: Devicemapper

healthcheck, ipsec, and scheduler containers are failing to start.

**Comment by galal-hussein** [comment]
Rancher version: v1.2.0-pre4-rc12
docker version: 1.12
storage driver: Devicemapper
OS: RHEL 7.2

The healthcheck containers are stuck in Initializing state:

`healthcheck`
```
11/23/2016 2:46:53 AMtime="2016-11-23T00:46:53Z" level=info msg="ab8c6137-c322-4f2f-b2df-c6dfa854987f_3b748753-5300-4dc4-b4d2-adc1de0831ee_1=DOWN"
11/23/2016 2:46:54 AMtime="2016-11-23T00:46:54Z" level=info msg="Scheduling apply config"
11/23/2016 2:46:54 AMtime="2016-11-23T00:46:54Z" level=info msg="healthCheck -- no changes in haproxy config\n"
11/23/2016 2:57:19 AMtime="2016-11-23T00:57:19Z" level=info msg="Scheduling apply config"
11/23/2016 2:57:20 AMtime="2016-11-23T00:57:20Z" level=info msg="healthCheck -- no changes in haproxy config\n"
11/23/2016 2:57:30 AMtime="2016-11-23T00:57:30Z" level=info msg="Scheduling apply config"
11/23/2016 2:57:30 AMtime="2016-11-23T00:57:30Z" level=info msg="healthCheck -- no changes in haproxy config\n"
11/23/2016 2:57:35 AMtime="2016-11-23T00:57:35Z" level=info msg="Scheduling apply config"
11/23/2016 2:57:35 AMtime="2016-11-23T00:57:35Z" level=info msg="healthCheck -- no changes in haproxy config\n"
11/23/2016 3:08:00 AMtime="2016-11-23T01:08:00Z" level=info msg="Scheduling apply config"
11/23/2016 3:08:00 AMtime="2016-11-23T01:08:00Z" level=info msg="healthCheck -- no changes in haproxy config\n"
11/23/2016 3:08:06 AMtime="2016-11-23T01:08:05Z" level=info msg="Scheduling apply config"
11/23/2016 3:08:06 AMtime="2016-11-23T01:08:05Z" level=info msg="healthCheck -- no changes in haproxy config\n"
11/23/2016 3:08:45 AMtime="2016-11-23T01:08:45Z" level=info msg="Scheduling apply config"
11/23/2016 3:08:45 AMtime="2016-11-23T01:08:45Z" level=info msg="healthCheck -- no changes in haproxy config\n"
11/23/2016 3:08:50 AMtime="2016-11-23T01:08:50Z" level=info msg="Scheduling apply config"
11/23/2016 3:08:51 AMtime="2016-11-23T01:08:51Z" level=info msg="healthCheck -- no changes in haproxy config\n"
11/23/2016 3:09:26 AMtime="2016-11-23T01:09:26Z" level=info msg="Scheduling apply config"
11/23/2016 3:09:26 AMtime="2016-11-23T01:09:26Z" level=info msg="healthCheck -- no changes in haproxy config\n"
11/23/2016 3:09:26 AMtime="2016-11-23T01:09:26Z" level=info msg="Scheduling apply config"
11/23/2016 3:09:27 AMtime="2016-11-23T01:09:27Z" level=info msg="healthCheck -- no changes in haproxy config\n"
11/23/2016 3:09:32 AMtime="2016-11-23T01:09:32Z" level=info msg="Scheduling apply config"
11/23/2016 3:09:32 AMtime="2016-11-23T01:09:32Z" level=info msg="healthCheck -- no changes in haproxy config\n"
11/23/2016 3:10:02 AMtime="2016-11-23T01:10:02Z" level=info msg="Scheduling apply config"
11/23/2016 3:10:02 AMtime="2016-11-23T01:10:02Z" level=info msg="healthCheck -- no changes in haproxy config\n"
11/23/2016 3:10:07 AMtime="2016-11-23T01:10:07Z" level=info msg="Scheduling apply config"
11/23/2016 3:10:07 AMtime="2016-11-23T01:10:07Z" level=info msg="healthCheck -- no changes in haproxy config\n"
11/23/2016 3:10:22 AMtime="2016-11-23T01:10:22Z" level=info msg="Scheduling apply config"
11/23/2016 3:10:22 AMtime="2016-11-23T01:10:22Z" level=info msg="healthCheck -- no changes in haproxy config\n"
```

Also scheduler container is stuck in the same state:

`scheduler`
```

11/23/2016 2:46:41 AMtime="2016-11-23T00:46:41Z" level=info msg="Listening for health checks on 0.0.0.0:80/healthcheck"
11/23/2016 2:46:41 AMtime="2016-11-23T00:46:41Z" level=info msg="Connecting to cattle event stream."
11/23/2016 2:46:41 AMtime="2016-11-23T00:46:41Z" level=info msg="Subscribing to metadata changes."
11/23/2016 2:46:41 AMtime="2016-11-23T00:46:41Z" level=info msg="Adding resource pool [instanceReservation] with total 1000000 and used 8 for host ab8c6137-c322-4f2f-b2df-c6dfa854987f"
11/23/2016 2:46:41 AMtime="2016-11-23T00:46:41Z" level=info msg="Adding resource pool [cpuReservation] with total 1000 and used 0 for host ab8c6137-c322-4f2f-b2df-c6dfa854987f"
11/23/2016 2:46:41 AMtime="2016-11-23T00:46:41Z" level=info msg="Adding resource pool [memoryReservation] with total 1779433472 and used 0 for host ab8c6137-c322-4f2f-b2df-c6dfa854987f"
11/23/2016 2:46:41 AMtime="2016-11-23T00:46:41Z" level=info msg="Adding resource pool [storageSize] with total 8505163 and used 0 for host ab8c6137-c322-4f2f-b2df-c6dfa854987f"
11/23/2016 2:46:41 AMtime="2016-11-23T00:46:41Z" level=info msg="Adding resource pool [storageSize] with total 8505389 and used 0 for host a8f219d9-9428-4491-afb5-8c28471216b6"
11/23/2016 2:46:41 AMtime="2016-11-23T00:46:41Z" level=info msg="Adding resource pool [instanceReservation] with total 1000000 and used 7 for host a8f219d9-9428-4491-afb5-8c28471216b6"
11/23/2016 2:46:41 AMtime="2016-11-23T00:46:41Z" level=info msg="Adding resource pool [cpuReservation] with total 1000 and used 0 for host a8f219d9-9428-4491-afb5-8c28471216b6"
11/23/2016 2:46:41 AMtime="2016-11-23T00:46:41Z" level=info msg="Adding resource pool [memoryReservation] with total 1779433472 and used 0 for host a8f219d9-9428-4491-afb5-8c28471216b6"
11/23/2016 2:46:41 AMtime="2016-11-23T00:46:41Z" level=info msg="Adding resource pool [instanceReservation] with total 1000000 and used 6 for host d960c645-2b00-4ce3-b85e-12b5be42d941"
11/23/2016 2:46:41 AMtime="2016-11-23T00:46:41Z" level=info msg="Adding resource pool [cpuReservation] with total 1000 and used 0 for host d960c645-2b00-4ce3-b85e-12b5be42d941"
11/23/2016 2:46:41 AMtime="2016-11-23T00:46:41Z" level=info msg="Adding resource pool [memoryReservation] with total 1779433472 and used 0 for host d960c645-2b00-4ce3-b85e-12b5be42d941"
11/23/2016 2:46:41 AMtime="2016-11-23T00:46:41Z" level=info msg="Adding resource pool [storageSize] with total 8176074 and used 0 for host d960c645-2b00-4ce3-b85e-12b5be42d941"
11/23/2016 2:46:41 AMtime="2016-11-23T00:46:41Z" level=info msg="Initializing event router" workerCount=100
11/23/2016 2:46:41 AMtime="2016-11-23T00:46:41Z" level=info msg="Connection established"
11/23/2016 2:46:41 AMtime="2016-11-23T00:46:41Z" level=info msg="Starting websocket pings"
```

**Comment by deniseschannon** [comment]
@galal-hussein I thought this was cause your host had registered the Docker bridge IP instead of the actual IP of the host?

it seemed like your second attempt worked?

**Comment by galal-hussein** [comment]
Testing with Rancher version: v1.2.0-pre4-rc14 and Docker 1.10 and 1.12 seems to be working without any problems, all the infra containers were up and running, closing the issue.

**Comment by khmai** [comment]
Rancher Version: Rancher v1.2.0
Docker Version:
1.12.3
OS and where are the hosts located? (cloud, bare metal, etc):
CentOS Linux release 7.2.1511 (Core)
Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)
FULL ACTIVE/ACTIVE HA
Environment Type: (Cattle/Kubernetes/Swarm/Mesos)
Cattle v0.174.3
Steps to Reproduce:

Install 3 master build Rancher server
Add CentOS hosts
Results:
ipsec, healthcheck , and scheduler containers keep restarting.

**Comment by adrianovieira** [comment]
```
Components version:
  Rancher v1.2.2
  Cattle v0.174.13
  User Interface v1.2.40
  Rancher Compose v0.12.1

Docker Version: 1.12.5
OS and where are the hosts located? (cloud, bare metal, etc):
two Vagrant VMs, CentOS Linux release 7.3.1611 (Core). all behind a proxy

Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)
one node rancher server with internal DB , another one as rancher agent

Environment Type: (Cattle/Kubernetes/Swarm/Mesos)
Cattle

Steps to Reproduce:

1. install and run one Rancher server
2. Add one node

Results:
healthcheck and scheduler containers keeps restarting.

```

_command I've used to start rancher server_
```
docker run \
            -e NO_PROXY='localhost,.hacklab,192.168.33.100,192.168.33.101,102,192.168.33.0/24' \
            -e no_proxy='localhost,.hacklab,192.168.33.100,192.168.33.101,102,192.168.33.0/24' \
            -e HTTPS_PROXY=http://10.122.19.137:5865/ \
            -e HTTP_PROXY=http://10.122.19.137:5865/ \
            -d --restart=unless-stopped -p 80:8080 rancher/server
```

_command I've used to start rancher node_
```
docker run \
            -e NO_PROXY='localhost,.hacklab,192.168.33.100,192.168.33.101,102,192.168.33.0/24' \
            -e no_proxy='localhost,.hacklab,192.168.33.100,192.168.33.101,102,192.168.33.0/24' \
            -e HTTPS_PROXY=http://10.122.19.137:5865/ \
            -e HTTP_PROXY=http://10.122.19.137:5865/ \
            -d --privileged \
            -v /var/run/docker.sock:/var/run/docker.sock \
            -v /var/lib/rancher:/var/lib/rancher rancher/agent:v1.1.2 \
                 http://192.168.33.100/v1/scripts/881572FBF8F0B054CFC8:1482948000000:gFZuQwrdBnfLf0byJKEEM0QXdo
```
