### ISSUE TITLE
Registry does not work if more than one

### ISSUE THREAD

**Issue by danielschlegel** [rancher/rancher#6758]
I have images from two different private registries. 
1. Only one Registry added in rancher.example/env/1a7/infra/registries
-> All ok
2. Adding second registry 
-> Only first registry work
3. Rebooting Ranger
-> Only second registry work

Always the last added registry seam to work after rancher reboot but not the other ones.

---
| Useful | Info |
| :-- | :-- |
|Versions|Rancher `v1.1.4` Cattle: `v0.165.8.4` UI: `v1.1.14` |
|Access|`github` `admin`|
|Orchestration|`Kubernetes`|
|Route|`k8s-tab.namespace.pods.index`|

**Comment by deniseschannon** [comment]
Is the registry the same (ie. is it 2 dockerhub registries?)

We only support 1 username/password for each registry type.

**Comment by danielschlegel** [comment]
No i have two private registries with different urls.

**Comment by danielschlegel** [comment]
rancher 1.2 did not solve the problem.

**Comment by ekristen** [comment]
@danielschlegel do registry pulls work at all for you? There seems to be 3 other issues open now saying that private registry pulls don't work in 1.2.x anymore ...

https://github.com/rancher/rancher/issues/7088 (ecr)
https://github.com/rancher/rancher/issues/7048 (gitlab)
https://github.com/rancher/rancher/issues/6947 (other private)

**Comment by danielschlegel** [comment]
yes they do work if i have only one registry configured and restart rancher after adding it.
if i add a second one the first one still work but not the second one. 
after restart again the first one does not work anymore but the second does.

**Comment by ekristen** [comment]
@danielschlegel which rancher services do you have to restart?

**Comment by danielschlegel** [comment]
i restart the rancher docker container.

**Comment by vincent99** [comment]
AFAIK these were resolved in later 1.2.x builds.

**Comment by danielschlegel** [comment]
i still have the same issue on all my rancher setups. Currently with newly created 1.5.3 setup.

**Comment by StrongMonkey** [comment]
@danielschlegel Are you using Kubernetes? There is a known issue which you add a registry after host is added, rancher will not read it immediately (https://github.com/rancher/rancher/issues/7461). This is fixed in rancher 1.5.4 k8s.

**Comment by danielschlegel** [comment]
Yes i use kubernetes and im on rancher/k8s:v1.5.4-rancher1-3
But still have the issue. This just happens if i add a second registry. if there is only one it works.
