### ISSUE TITLE
Container cannot ping its own hostname

### ISSUE THREAD

**Issue by darrenscerri** [rancher/rancher#6855]
**Rancher Version:**
1.2.0

**Docker Version:**
1.12.2

**OS and where are the hosts located? (cloud, bare metal, etc):**
Centos 7.2 VM Hyper-V

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single Node Rancher

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
Create container and try to ping self hostname

**Results:** 
Hostname does not resolve

**Expected:**
Hostname should resolve to container's own ip address

**Comment by darrenscerri** [comment]
### Rancher 1.2.0-pre3 - busybox container

<img width="525" alt="screen shot 2016-12-01 at 11 59 35" src="https://cloud.githubusercontent.com/assets/729230/20791524/adb80834-b7bd-11e6-8984-7951e10dde49.png">

### Rancher 1.2.0 - busybox container

<img width="495" alt="screen shot 2016-12-01 at 11 59 41" src="https://cloud.githubusercontent.com/assets/729230/20791532/b20b14c6-b7bd-11e6-929a-4e263ef9d644.png">

**Comment by salvax86** [comment]
I have the same issue in a different way: when kafka was calling getLocalHost, it was trying to find the IP Address for the container_id, which I did not have in my /etc/hosts file.

**Comment by ias-gmckeever** [comment]
Does anyone know of a workaround for this issue?  I'd use a prior version of Rancher but I'm storing the Rancher config in a native mysql server and I'm aware that there are significant changes to the db objects associated with 1.2.0.  Therefore, I'd rather not revert back to an old version of Rancher and configure the db for the old version just to have to do that all over again when this bug is fixed.  Any help is appreciated!

**Comment by aemneina** [comment]
can you try something like the following as a workaround:
```
ping `curl rancher-metadata/latest/self/container/name`
```

**Comment by nicholasdille** [comment]
In my case, the application (Java based) dies due to this issue:

```
Caused by: java.net.UnknownHostException: b7ec36aecdab: Name does not resolve
        at java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
        at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:928)
        at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:132
3)
        at java.net.InetAddress.getLocalHost(InetAddress.java:1500)
        ... 16 more
```

**Comment by ias-gmckeever** [comment]
@aemneina Your suggestion won't work since my use case is similar to the one of @nicholasdille.

**Comment by AndreasSundstrom** [comment]
Workaround: Use container name as hostname.

**Comment by ias-gmckeever** [comment]
@AndreasSundstrom Pinging the container name does not work either.  Even if it did, I wouldn't be able to easily implement a solution since the component that is failing is coming from the Java code `InetAddress.getLocalHost().getHostAddress()`.  Can you think of a solution that would work without having to modify Java code to get it to work?  If not, does anyone know the root cause of the issue that could explain it so that we can come up with a creative solution?

**Comment by AndreasSundstrom** [comment]
@ias-gmckeever Pinging the hostname inside the container works for me when the service is configured to use container name as hostname.

**Comment by salvax86** [comment]
@ias-gmckeever  I had the same problem with Kafka implementation and `InetAddress.getLocalHost().getHostAddress()`. I can find the localhost with `io.rancher.container.hostname_override: container_name`.

**Comment by aemneina** [comment]
@ias-gmckeever take a look [here](https://github.com/rancher/rancher/issues/5499#issuecomment-241498813) on how people overcome the problem. It involves modifying the entrypoint.sh or similar

**Comment by aemneina** [comment]
There's also labels which should force the hostname for the container to be the container name: https://docs.rancher.com/rancher/v1.2/zh/cattle/labels/#rancher-compose-labels-for-services

**Comment by ias-gmckeever** [comment]
@aemneina That worked - thank you!

**Comment by nicholasdille** [comment]
In my case, the issue was solved by overriding the hostname (`io.rancher.container.hostname_override: container_name`) and explicitly adding `rancher.internal` as search domain. I tried the latter after I noticed that name resolution worked for the FQDN (hostname.rancher.internal).

This is my original `/etc/resolv.conf` in the container when the Java application throws UnknownHostException:
```
bash-4.3$ cat /etc/resolv.conf
search eu-west-1.compute.internal gocd-oss.rancher.internal ser
ver.gocd-oss.rancher.internal rancher.internal
nameserver 169.254.169.250
```

And this is my `/etc/resolv.conf` in the container after the above changes:
```
search eu-west-1.compute.internal rancher.internal gocd-oss.rancher.internal ser
ver.gocd-oss.rancher.internal
nameserver 169.254.169.250
```

**Comment by sdelrio** [comment]
Rancher server 1.2.0 here too and also fails when using jenkins-swarm-agent giving this error:

```
Failed to lookup the canonical hostname of this slave, please check system settings
If not possible to resolve please specify a node name using the '-name' option
```
Looking the java [code of jenkins swarm-plugin](https://github.com/jenkinsci/swarm-plugin/blob/master/client/src/main/java/hudson/plugins/swarm/Client.java) the behaveiour is the same that you commented there. And also `ping hostname` fails. 

```java
 client.options.name = InetAddress.getLocalHost().getCanonicalHostName();
```
Changing the hostname to "user the contianer name" doesn't fix anything.

Looking at `/etc/hosts` I can't see the cointaner ID with the Rancher IP

Executing the same jenkins-swarm image but on a a swarm cluster without Rancher, I got somethign like this on the `/etc/hosts`:

```
127.0.0.1 localhost
::1     localhost ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
172.17.0.2      4baa2f1c287a
```

Inside rancher container, same image of jenkins-swarm is just this:

```
127.0.0.1 localhost
::1     localhost ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
```

**Comment by AndreasSundstrom** [comment]
@sdelrio It doesn't fix anything regarding /etc/hosts, but since the container name resolves to the container's IP, it does fix the problem of not being able to resolv the container's hostname. At least it works for our use cases.

**Comment by sangeethah** [comment]
Test with rancher/network-manager:v0.2.15.

Containers can ping its own hostname

```
10.42.233.253   f3a3cf5f25c7
root@f3a3cf5f25c7:/# ping `hostname`
PING f3a3cf5f25c7 (10.42.233.253) 56(84) bytes of data.
64 bytes from f3a3cf5f25c7 (10.42.233.253): icmp_seq=1 ttl=64 time=0.090 ms
64 bytes from f3a3cf5f25c7 (10.42.233.253): icmp_seq=2 ttl=64 time=0.071 ms
64 bytes from f3a3cf5f25c7 (10.42.233.253): icmp_seq=3 ttl=64 time=0.069 ms
^C
--- f3a3cf5f25c7 ping statistics ---
3 packets transmitted, 3 received, 0% packet loss, time 1999ms
```

@darrenscerri  , this fix will be available in rancher server - v1.2.1 release.

**Comment by sdelrio** [comment]
Perfect now,  fix on rancher server v1.2.1, `rancher/network-manager:v0.2.15`.
```bash
/ # ping $(hostname) -c 3
PING 344b457e2888 (10.42.207.229): 56 data bytes
64 bytes from 10.42.207.229: seq=0 ttl=64 time=0.055 ms
64 bytes from 10.42.207.229: seq=1 ttl=64 time=0.051 ms
64 bytes from 10.42.207.229: seq=2 ttl=64 time=0.058 ms

--- 344b457e2888 ping statistics ---
3 packets transmitted, 3 packets received, 0% packet loss
round-trip min/avg/max = 0.051/0.054/0.058 ms
/ # tail -n 1 /etc/hosts
10.42.207.229   344b457e2888
```
