### ISSUE TITLE
cannot exec a container that has run and stopped

### ISSUE THREAD

**Issue by psyhonut** [rancher/rancher#6922]
**Rancher Version:** 1.2.0

**Docker Version:** 1.12.3

**OS and where are the hosts located? (cloud, bare metal, etc):** 3.10.0-327.36.2.el7.x86_64

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)** single node rancher, internal DB

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)** Cattle

**Steps to Reproduce:** Create service in stack. Open service in UI, trying to Execute Shell.

**Results:** Popup window opens and closes.

**Expected:** Popup window is opened and you can work in container Bash.

When I ssh to host and try to: 
`docker exec -it r-icms-postgresql-1-b347541b bash`
I got:
`rpc error: code = 13 desc = invalid header field value "oci runtime error: exec failed: cannot exec a container that has run and stopped\n"`

**Comment by psyhonut** [comment]
I found something strange behavior. Even if I did not upgrade service (fresh create) - same error.

**Comment by psyhonut** [comment]
It's strange that I can exec bash to some containers, and can't in others.
Containers created either from local registry and RegistryHub.
Neither console mode helps.

**Comment by Sturgelose** [comment]
@psyhonut This is expected behaviour of Docker. When a container is running, you can execute inside it any command. If a container is stopped, it's not running and thus you can't execute anything inside. To access the container it needs to be running , so you should restart it!

**Comment by superseb** [comment]
See https://github.com/rancher/rancher/issues/6861

**Comment by pulberg** [comment]
@Sturgelose the container is running, I have the same issue on a running container - 

```
CONTAINER ID        IMAGE                              COMMAND                  CREATED             STATUS              PORTS               NAMES
851e33ee22c6        centos:latest                      "/.r/r /bin/bash"        21 hours ago        Up About an hour                        r-centos-b10e7cfb
```

```
docker exec -it r-centos-b10e7cfb bash
rpc error: code = 13 desc = invalid header field value "oci runtime error: exec failed: cannot exec a container that has run and stopped\n"
```

**Comment by bay007** [comment]
I have the same issue; 
![captura](https://cloud.githubusercontent.com/assets/8164038/21292538/8bc4a5ac-c4ce-11e6-8353-a2f0a74d2ed8.PNG)

My environment is 

**# docker version
Client:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        Wed Oct 26 23:26:11 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.2
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   bb80604
 Built:        Tue Oct 11 18:29:41 2016
 OS/Arch:      linux/amd64**

**Comment by vincent99** [comment]
This is a docker bug marked fixed in 1.12.3 (the server version is the relevant one here, not client).  https://github.com/docker/docker/issues/27540

**Comment by yeruisen** [comment]
@vincent99 
It seems that the 1.12.3 version does not fix this bug
```
[root@manager ~]# docker version
Client:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        
 OS/Arch:      linux/amd64
[root@manager ~]# docker exec -it a0c540de91bc /bin/bash
rpc error: code = 13 desc = invalid header field value "oci runtime error: exec failed: cannot exec a container that has run and stopped\n"
```

```
docker exec -it a0c540de91bc /bin/bash
rpc error: code = 13 desc = invalid header field value "oci runtime error: exec failed: cannot exec a container that has run and stopped\n"
```

**Comment by vincent99** [comment]
@yeruisen OK, but regardless there's not much we can do about it when the docker daemon isn't working.  `docker exec` on the host will fail with the same message.

**Comment by tobowers** [comment]
I'm seeing the same thing in docker v1.13.0

**Comment by zhangyongsu** [comment]
reproducted in v1.13.0
```
~# docker exec -it fc114db9dca4 bash
rpc error: code = 2 desc = oci runtime error: exec failed: cannot exec a container that has run and stopped
```
```
~# docker info
Containers: 13
 Running: 9
 Paused: 0
 Stopped: 4
Images: 26
Server Version: 1.13.0
Storage Driver: aufs
 Root Dir: /data00/docker/aufs
 Backing Filesystem: extfs
 Dirs: 125
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 03e5862ec0d8d3b3f750e19fca3ee367e13c090e
runc version: 2f7393a47307a16f8cee44a37b262e8b81021e3e
init version: 949e6fa
Kernel Version: 3.16.0-4-amd64
Operating System: Debian GNU/Linux 8 (jessie)
OSType: linux
Architecture: x86_64
CPUs: 32
Total Memory: 62.69 GiB
Name: n6-027-107
ID: RHPD:ZDXK:SFXG:D4QD:YXNG:KCAG:GZMJ:6RJY:YTNG:OZTD:VAHJ:CRYA
Docker Root Dir: /data00/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No kernel memory limit support
Experimental: false
Insecure Registries:
 127.0.0.0/8
Registry Mirrors:
 http://67a95a0b.m.daocloud.io/
Live Restore Enabled: false

~# docker version
Client:
 Version:      1.13.0
 API version:  1.25
 Go version:   go1.7.3
 Git commit:   49bf474
 Built:        Tue Jan 17 09:44:08 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.13.0
 API version:  1.25 (minimum version 1.12)
 Go version:   go1.7.3
 Git commit:   49bf474
 Built:        Tue Jan 17 09:44:08 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Comment by superseb** [comment]
@tobowers What Linux distro and what container are you trying to exec into? (Infrastructure? And if so, which one?)

@zhangyongsu I see Debian 8, what container are you trying to exec into?

**Comment by tobowers** [comment]
@superseb it was centos 7.1 and the container was "any container" I believe, but it's been some time since I did that. We since gave up on upgrading rancher. I can't remember, but I have a "suspicion" that upgrading to centos 7.2 fixed the problem.

**Comment by superseb** [comment]
@tobowers Sort of, it's a new kernel which fixes the problem. So 7.2 with a updated kernel will also fix this, see https://github.com/rancher/rancher/issues/6861#issuecomment-270408235

**Comment by zhangyongsu** [comment]
@superseb it likes python:3.5 builded for our own. 
is it kernel relevant ? the kernel version is : Linux n6-027-107 3.16.0-4-amd64 #2 SMP Debian 3.16.7-ckt20-1+deb8u4 (2016-03-10) x86_64 GNU/Linux

**Comment by superseb** [comment]
@zhangyongsu Can you describe the steps to reproduce? Running a single container through Rancher GUI (python:3.5) and Execute shell after?

**Comment by zhangyongsu** [comment]
@superseb I think it is hard to reproduce it. 
the container is one of the docker-compose.yml. and this issue only happened on one of containers. 
I restarted dockerd, and can not reproduce it again. ;(
the docker-compose.yml as below(marked some info). the problem container is 'passport'

```
version: "2"
services:
 im-server:
  image: hub.xxxx.org/xx/python:3.5
  links:
   - mysql
   - redis
   - cassandra
   - passport
  environment:
   ENV: test
   PROJECT_ROOT: /repos/xxxx/im-server
  volumes:
   - /etc/localtime:/etc/localtime:ro
   - ../../..:/repos
   - ./test/web_run:/etc/service/web/run
   - ./test/service_run:/etc/service/service/run
   - ./test/celery_run:/etc/service/celery/run
   - ./test/receiver_run:/etc/service/receiver/run
  ports:
   - "xxxx:xxxx"
 passport:
  image: hub.xxxx.org/xx/python:3.5
  ports:
   - "xxxx:xxxx"
  links:
   - mysql
   - redis
  environment:
   ENV: test
   PROJECT_ROOT: /repos/xxxx/passport
  volumes:
   - /etc/localtime:/etc/localtime:ro
   - ../../..:/repos
   - ./test/passport_run:/etc/service/web/run
   - ./test/passport_service_run:/etc/service/service/run
 mysql:
  image: mysql
  volumes:
   - /etc/localtime:/etc/localtime:ro
  environment:
   MYSQL_DATABASE: xxxx_im
   MYSQL_ROOT_PASSWORD: dev
 redis:
  image: redis:alpine
  volumes:
   - /etc/localtime:/etc/localtime:ro
 cassandra:
  image: cassandra
  volumes:
   - /etc/localtime:/etc/localtime:ro
 es:
  image: elasticsearch
  volumes:
   - /etc/localtime:/etc/localtime:ro
```

**Comment by allencloud** [comment]
I am suffering this in docker 17.03.1-ce.

**Comment by superseb** [comment]
@allencloud Can you provide some more details on your setup and how to reproduce?

**Comment by zoobab** [comment]
I have the same issue on 17.05.0-ce redhat 7.2.

**Comment by zhxqgithub** [comment]
+1 have the same issue on 17.03.2-ce

**Comment by netbeen** [comment]
+1 have the same issue on 17.06.2-ce
```
#docker ps -a
CONTAINER ID        IMAGE                                                         COMMAND                  CREATED             STATUS                        PORTS               NAMES
cd432e7515cf        aegis-paas.aliyun.com:5000/ak-my:20180406003259_unit-output   "/.r/r /bin/sh /ho..."   42 seconds ago      Up 40 seconds                                     r-project-ak-my3-1-49e5cab1

#docker exec -it cd432e7515cf bash
rpc error: code = 2 desc = oci runtime error: exec failed: cannot exec a container that has stopped

```

**Comment by jaiviksth** [comment]
This is a docker bug. But if you go to the Rancher Server VM and do "docker attach 'container_name' will be get in the container. But if you exit from the container then it will restart. However it won't take more than just a blink to start the container back. 

But this seems like a bug with rancher which has not ever been solved. And now the docker version 2.0 is there where I can just see build for Kubernetes.

**Comment by maZahaca** [comment]
@superseb Thanks for spotting this!
Can you please specify a link where did you get this for referring? I mean something is wrong in the OS kernel compatibility with docker?

**Comment by superseb** [comment]
https://rancher.com/docs/rancher/v1.6/en/hosts/
https://access.redhat.com/articles/3078
https://github.com/rancher/rancher/issues/6861#issuecomment-270408235
