### ISSUE TITLE
Kubernetes: rancher trying to start 3 etcd instance in 2 host kubernetes environment.

### ISSUE THREAD

**Issue by omegarus** [rancher/rancher#7201]
**Rancher Version:**
Server v1.2.2 Agent v1.1.2
**Docker Version:**
1.11.2
**OS and where are the hosts located? (cloud, bare metal, etc):**
Ubuntu14.04 VMware
**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Fresh install: single node rancher with **two hosts**
**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Kuberenetes 1.4.6-rancher2-4
**Steps to Reproduce:**
Create environment from kubernetes template. Add two hosts to this environment.
**Results:** 
Kubernetes stack is being deployed, but rancher server trying to start 3 instances of etcd service.
![untitled](https://cloud.githubusercontent.com/assets/16287353/21471370/27932536-cab9-11e6-91bf-f375201e5754.png)

**Expected:**
Number of etcd instances = number of hosts in environment.

**Comment by austinnichols101** [comment]
I saw a similar issue - 2 instances on a single host (test) environment.

**Comment by omegarus** [comment]
Looks like it fixed in 1.3.0 release.

**Comment by Dmitry1987** [comment]
I have this issue with Rancher 1.4.0 and K8s 1.5.2.   I had 3 masters on staging cluster, but we removed 2 and kept 1.  etcd was recreated, stack "upgraded" (just to refresh itself with defaults)  but still tries to bring 3 etcd on 1 master host. How do I force it to stay with 1 etcd container?

**Comment by toandph** [comment]
This still happened in Rancher 1.5.10. I have 3 host, and reduce 1 host, but etcd just keeping 3 container. It continue fails because each node can only had 1 etcd.

**Comment by strowi** [comment]
same with latest 1.6.23..
