### ISSUE TITLE
Failed to evaluate networking: failed to find plugin \"rancher-bridge\" when metadata container's bridge IP is equal to another hosts docker0 IP (bip)

### ISSUE THREAD

**Issue by ciokan** [rancher/rancher#8383]
**Rancher Versions:**
Server: 1.5.2
healthcheck: 0.2.3
ipsec: rancher/net:holder
network-services: rancher/network-manager:v0.5.3
scheduler: rancher/scheduler:v0.7.5
kubernetes (if applicable):

**Docker Version:**
1.12.6

**OS and where are the hosts located? (cloud, bare metal, etc):**
Ubuntu 16.04/Bare Metal/Multiple locations

**Setup Details: (single node rancher vs. HA rancher, internal DB vs. external DB)**
Single node rancher, external DB

**Environment Type: (Cattle/Kubernetes/Swarm/Mesos)**
Cattle

**Steps to Reproduce:**
I have about 100 hosts running 4 containers. On 5-6 of them ipsec runs ok, on every other host the `ipsec` stack fails (also the `healthcheck`) with `Timeout getting ip`. Inside the network-manager logs I can see:

```
nsenter: cannot open /proc/26034/ns/ipc: No such file or directory
time="2017-04-01T02:31:01Z" level=error msg="Failed to evaluate network state for 059fae587888cf4a80bc7020e0ab684927783790703d73591edf07fdf0f6e769: netplugin failed but error parsing its diagnostic message \"\": unexpected end of JSON input" 
time="2017-04-01T02:31:01Z" level=error msg="Error processing event &docker.APIEvents{Action:\"start\", Type:\"container\", Actor:docker.APIActor{ID:\"059fae587888cf4a80bc7020e0ab684927783790703d73591edf07fdf0f6e769\", Attributes:map[string]string{\"io.rancher.container.agent_id\":\"58465\", \"io.rancher.project_service.name\":\"healthcheck/healthcheck\", \"io.rancher.service.hash\":\"d0a8fd4061d3b2a8c5782f5563db6df0b25655cb\", \"io.rancher.stack_service.name\":\"healthcheck/healthcheck\", \"io.rancher.cni.network\":\"ipsec\", \"io.rancher.scheduler.global\":\"true\", \"io.rancher.service.requested.host.id\":\"209\", \"io.rancher.stack.name\":\"healthcheck\", \"name\":\"r-healthcheck-healthcheck-28-2576d08e\", \"image\":\"rancher/healthcheck:v0.2.3\", \"io.rancher.container.create_agent\":\"true\", \"io.rancher.container.ip\":\"10.42.112.234/16\", \"io.rancher.container.mac_address\":\"02:4f:71:44:58:1a\", \"io.rancher.service.launch.config\":\"io.rancher.service.primary.launch.config\", \"io.rancher.cni.wait\":\"true\", \"io.rancher.container.system\":\"true\", \"io.rancher.container.uuid\":\"2576d08e-3100-4935-aa34-3ecb73da302a\", \"io.rancher.project.name\":\"healthcheck\", \"io.rancher.service.deployment.unit\":\"8a360a36-5ff6-497f-a7db-92193ecf2415\", \"io.rancher.container.name\":\"healthcheck-healthcheck-28\"}}, Status:\"start\", ID:\"059fae587888cf4a80bc7020e0ab684927783790703d73591edf07fdf0f6e769\", From:\"rancher/healthcheck:v0.2.3\", Time:1491013861, TimeNano:1491013861288487613}. Error: netplugin failed but error parsing its diagnostic message \"\": unexpected end of JSON input" 
```

**Comment by snipking** [comment]
Can you provide the `ipsec` log or can you try `http://rancher-metadata/2015-12-19/self` in a container which use `Managed` network and `ipsec` failed on the same host.

Have you tried delete the network stack and re-run them, then restart the failed `ipsec` container.

Maybe it's related to #8368

**Comment by ciokan** [comment]
No container uses managed network. All 4 are running with `network_mode: host`.  I just deactivated all my hosts in rancher because it was causing one host (where the scheduler is apparently running) to go at 400Mb/s and also my rancher server to stay 100% at all times with 8 cores and 16gb of RAM. One of the 4 containers is a healthchecker of mine designed to keep the other 3 alive so my services are running even with hosts deactivated in rancher.

I just wish I could get rid of this ipsec thing and clustering features as I'm not interested in them.

I only picked rancher because it was the only one supporting the `run one container on each host` feature and allowed you to *NOT* treat all your machines as a single block. Things are moving in the other direction it seems and it's giving me all sorts of issues. I can't even disable ipsec at all.

`ipsec` does not produce any logs, it doesn't even start.

**Comment by ciokan** [comment]
Tried adding a dummy ubuntu (with the managed network) container that just sleeps and prints something to the console. It fails to start, with the same error saying it failed to bring up the network.

**Comment by spawnthink** [comment]
I have the same issue, reproducible with 1.5.2, 1.5.3 and 1.5.4 `Error (Couldn't bring up network: failed to find plugin "rancher-bridge" in path [/opt/cni/bin /var/lib/cni/bin /usr/local/sbin /usr/sbin /sbin /usr/local/bin /usr/bin /bin])`

**Comment by asg1612** [comment]
I had the same issue because I used a virtualbox host rancher within a host rancher :-S. When I removed the virtualbox machine from the cluster the error disappear. 

Are you using a similar config?

**Comment by OneB1t** [comment]
same issue happens to us on physical hardware  :-(

**Comment by ciokan** [comment]
@asg1612 you can read the ticket and see it's not the same config - at all.

**Comment by OneB1t** [comment]
do someone managed some sort of workaround? this is really annoying issue as we cannot use more than 1 host for now (out of 4 which we are using normally)

**Comment by maltyxx** [comment]
me too

**Comment by ciokan** [comment]
> do someone managed some sort of workaround? this is really annoying issue as we cannot use more than 1 host for now (out of 4 which we are using normally)

Nope...and noone is responding from the devs either. I upgraded to 1.5.4 and 1.5.5 without luck. Bug is still present and it affects 90% of all our servers. I can't pinpoint the fault at all. I checked, re-installed, deleted, upgraded, downgraded ..you name it, nothing pops out.

We may have to roll our own custom solution as this is not a production ready setup for us unfortunately.

**Comment by snipking** [comment]
I've reproduce and solve a similar issue #8276 . Hope this helps.

**Comment by ciokan** [comment]
@snipking I believe that's required when you run the agent on the same host with the server. Can you confirm?

**Comment by fedya** [comment]
same issue

**Comment by fedya** [comment]
@snipking 
i'm investigating a bit here
there is no binaries in /opt/cni/bin dir in rancher/network-manager:v0.6.6

And all of my servers today show such messages like in first message.

**Comment by tpgxyz** [comment]
Ok this is not funny anymore. Looks like healthcheck and ipsec are constantly failing
http://i.share.pho.to/dda8108c_o.png

Any docker container executed from rancher fails. Doing same thing from console works without issues.

**Comment by Emil983** [comment]
Same issue on fresh, clean machine with Ubuntu 16

**Comment by snipking** [comment]
@ciokan Actually, I've reproduced the #8276 in two env which means it happen both when agent and server on the same host or not. **Even one host in a rancher env with the wrong IP will cause this issue on other hosts in this env.** This may not happen immediately because you may add a host with the wrong IP to an env which already have hosts working fine. But it may happen after you reboot some of your working hosts. 

I'm not sure your problem same as me. But it worth a try.

**Comment by snipking** [comment]
@fedya I'm using rancher/network-manager:v0.6.6 and there's only `rancher-bridge` in `/opt/cni/bin`. In my case I didn't see any error message relevant with it.

**Comment by fedya** [comment]
if bad instance of rancher agent is up
i can't run containers until flush firewall rules commited by rancher.

Issue still exist and very annoying me

**Comment by fedya** [comment]
Still not working
docker 17.03.1

```
time="2017-04-20T11:12:02Z" level=info msg="Evaluating state from retry" cid=eac88e13f505ba0362c49601f269e758a8cf4bb4d2cec434eccdbce0ca908d6e count=14 
time="2017-04-20T11:12:02Z" level=info msg="CNI up" cid=eac88e13f505ba0362c49601f269e758a8cf4bb4d2cec434eccdbce0ca908d6e networkMode=ipsec 
time="2017-04-20T11:12:02Z" level=error msg="Failed to evaluate networking: failed to find plugin \"rancher-bridge\" in path [/opt/cni/bin /var/lib/cni/bin /usr/local/sbin /usr/sbin /sbin /usr/local/bin /usr/bin /bin]"
```

**Comment by penguinxr2** [comment]
Something similar is happening to me after updating to 1.5.5. I've even tried creating a while new environment to try and get the ipsec stack to start, but it still exhibits the same error. `"Failed to evaluate networking: netplugin failed but error parsing its diagnostic message \"\": unexpected end of JSON input"`

**Comment by fedya** [comment]
@penguinxr2 yes, same issue, there is no network interface in container.

**Comment by ZGF4** [comment]
Same issue here, anyone have any updates?

**Comment by ZGF4** [comment]
My issues went away once I switched to Ubuntu 16.04 instead of Debian

**Comment by kaos** [comment]
We've been struggling all day with ipsec issues on one of the nodes after upgrading a rancher environment running 1.4 to 1.5.6 (in other words, we have several nodes where ipsec was working).

After a lot of headscratching and cussing, we got ipsec working following these simple steps: 

* copy `/var/lib/docker/volumes/rancher-cni-driver/_data/bin/rancher-bridge` from one of the working nodes (we were missing this file on the node with ipsec issues).
* the file is tiny, a one line script calling `nsenter`, and needs the PID of the target process it should enter. _this needs to be adjusted for each host and time_.
* so, replace the pid for the `-t` option to `nsenter` with the pid of `ps ax | grep rancher-cni` (it should be the sidekick tailing the log file:
````
[root@xxx bin]# ps ax | grep rancher-cni
2754 ?        Ss     0:00 tail ---disable-inotify -F /var/log/rancher-cni.log
````
* contents of `/var/lib/docker/volumes/rancher-cni-driver/_data/bin/rancher-bridge` after patching:
```
[root@xxx bin]# cat rancher-bridge 
#!/bin/sh
exec /usr/bin/nsenter -m -u -i -n -p -t 2754 -- $0 "$@"
```
* now, restart `network-manager` and things starts rolling!! ;)


So, in conclusion, it seems like the process responsible for updating this file is failing, for some to us yet unknown reason (haven't had time to look into that yet).

**Comment by aemneina** [comment]
tagging @leodotcloud into this ticket. Expert sleuthing @kaos

**Comment by ciokan** [comment]
@kaos that seems to work. I have to play "catch" since rancher is constantly changing the pid since it restarts the cni service and, once I'm fast enough with setting the pid, `ipsec` starts rolling. With so many servers though (and with many of them being restarted through the day) that's quite a lot to manage so I'll try to deploy a container that constantly monitors the pids and does just that...at lest until rancher devs fix this.

**Comment by kaos** [comment]
Indeed, if I was digging in the right place, the plugin-manager updates stuff every 5 minutes, or when triggered by a change in the metadata.. I'm guess it's in there some where something's broken.

**Comment by ciokan** [comment]
Here's my "working" code to fix this:

```
import time
import subprocess

bridge_tpl = """#!/bin/sh
exec /usr/bin/nsenter -m -u -i -n -p -t {} -- \$0 \"\$@\"
"""


def cmd(command):
    try:
        return subprocess.check_output(command, shell=True).decode('utf-8').strip()
    except subprocess.CalledProcessError:
        return ''


def watch():
    ipsec_pid = cmd("docker ps --filter \"name=ipsec-cni\" --format {{.ID}} | xargs docker inspect  --format '{{.State.Pid}}'").strip()

    if ipsec_pid:
        bridge_contents = cmd("cat /var/lib/docker/volumes/rancher-cni-driver/_data/bin/rancher-bridge")

        if ipsec_pid not in bridge_contents:
            cmd('truncate -s0 /var/lib/docker/volumes/rancher-cni-driver/_data/bin/rancher-bridge')

            code = bridge_tpl.format(int(ipsec_pid))

            cmd('echo "%s" >> /var/lib/docker/volumes/rancher-cni-driver/_data/bin/rancher-bridge' % code)


if __name__ == "__main__":
    while True:
        watch()
        time.sleep(1)
```

This one runs inside a container that has the following volumes:

```
/usr/bin/docker:/usr/bin/docker
/var/run/docker.sock:/var/run/docker.sock
/var/log/:/var/log/
```

It constantly monitors the pid and `nsenter` file for a mismatch. Not the prettiest one but it works for now.

**Comment by ibuildthecloud** [comment]
@ciokan can you ping me on our users slack? I'd gladly troubleshoot this with you

**Comment by ibuildthecloud** [comment]
Let me explain how things work so maybe people can troubleshoot this better.  The "network-manager" container looks at metadata and looks for services with kind "networkDriverService" and then look for local container for that service.  Once it find the container it writes a small nsenter shell script that works as the CNI plugin.   The code is here, it's pretty straight forward https://github.com/rancher/plugin-manager/blob/master/binexec/watcher.go.   So a couple things that could go wrong

1. Metadata isn't working: Look at the docker logs output of metadata and see if anything is fishy
2. Metadata has the wrong info in it: Go into the network-manager container and run `curl -H "Accept: application/json " http://169.254.169.250/latest`.  Then send me the output darren@rancher.com.

I'm guessing there could be some issue if there is some crufty data around that is causing issues.  Sorry this issue went unnoticed for so long, the couple weeks before and after DockerCon are pretty hectic for us.  Thanks!

**Comment by lkm** [comment]
Any eta on this? We're seeing this in production too, post upgrade the entire environment goes down. Nothing to see in the metadata logs, but healthcheck seems to not work either.

**Comment by ciokan** [comment]
@lkm please try the image I linked above. I have it working in production with 100+ servers. Until an official fix, this is the only thing that worked. It incorporates what @kaos provided earlier.

**Comment by leodotcloud** [comment]
@ciokan @kaos @lkm @spawnthink @asg1612 @OneB1t @maltyxx @snipking @fedya @tpgxyz @Emil983 
Can you please ping me on https://slack.rancher.io so that I can take a look at your setup and debug what's going on?

Also could you please collect the logs and share them with me?
https://github.com/leodotcloud/rancher-logs-collector ==> this will make it easier to collect the logs.

**Comment by ingardm** [comment]
We have the same issue and will help with logs if wanted

**Comment by leodotcloud** [comment]
@ingardm Thank you. The logs might be more than the allowed limit of email attachment size. Please share them with me on slack.

**Comment by ingardm** [comment]
@leodotcloud which logs are you after specifically? The logs of the r-ipsec-ipsec containers are empty

**Comment by superseb** [comment]
@ingardm Please use https://github.com/leodotcloud/rancher-logs-collector to collect the logs :)

**Comment by ingardm** [comment]
@leodotcloud @superseb Aight. I've got the logs collected from the environment having problems. Please contact me on slack for details

**Comment by superseb** [comment]
Thanks for all the digging and fixes, we need to get to the bottom of this. Does anyone have the steps to reproduce please, I think there have been some log digging and troubleshooting on/offline but there is no reproducible plan yet. I've tried multiple big clusters running Debian/Ubuntu, rebooting/resetting nodes, host networked/managed, killing/restarting infra containers.

**Comment by ciokan** [comment]
@superseb I can't provide any steps to reproduce it (if I knew exactly what's the cause of it I would probably avoid it entirely) but I can tell you that it's affecting 95% of all our hosts/servers. I can provide a share screen or even ssh into a non working host if you want to take a look at it.

**Comment by tpgxyz** [comment]
@superseb  Any news on this ? Whole orchestration on rancher is not working.
healthcheck, ipsec are failing.
healthcheck (Expected state running but got error: Couldn't bring up network: failed to find plugin "rancher-bridge" in path [/opt/cni/bin /var/lib/cni/bin /usr/local/sbin /usr/sbin /sbin /usr/local/bin /usr/bin /bin])

**Comment by superseb** [comment]
@tpgxyz Not yet, working to reproduce. Will update soon.

@ciokan Ping me on Rancher Users Slack, would love to check at the hosts to locate the problem and get this out of the way for a lot of users.

**Comment by tpgxyz** [comment]
@superseb Can you please provide step-by-step procedure how to get all the needed logs ?

**Comment by superseb** [comment]
@tpgxyz Logging can be collected using: https://github.com/leodotcloud/rancher-logs-collector

As we are trying to reproduce, I would love to find the common denominator in this case. So if you could post the following:

```
Current Rancher version:
Upgraded from Rancher version:
Infrastructure rancher/network-manager version:
Docker version: (`docker version`,`docker info` preferred)
Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)
Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)
```

**Comment by tpgxyz** [comment]
Basically we are running rancher to manage de-centralized RPM build system around globe. Each machine is running different operating system (fedora, centos, openmandriva etc.)
We had to disable rancher, due this bug, on all machines and run all the needed docker by hand.

Below you can find information about system where rancher server is running:
Current Rancher version: 1.6.0
Upgraded from Rancher version: 1.5.5
Infrastructure rancher/network-manager version:
Docker version: (`docker version`,`docker info` preferred)
abf.openmandriva.org@root[0]:[~] # docker version
Client:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.1
 Git commit:   c3959b1
 Built:        
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.1
 Git commit:   c3959b1
 Built:        
 OS/Arch:      linux/amd64

Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)
abf.openmandriva.org@root[0]:[~] # cat /etc/os-release
NAME="OpenMandriva Lx"
VERSION="2014.0 (Phosphorus)"
ID="openmandriva_association"
VERSION_ID=2014.0
BUILD_ID=20160709.21
PRETTY_NAME="OpenMandriva Lx 2014.0 (Phosphorus)"
ANSI_COLOR="1;43"
CPE_NAME="cpe:/o:openmandriva_association:openmandriva_lx:2014.0"
HOME_URL="http://openmandriva.org/"
BUG_REPORT_URL="https://issues.openmandriva.org/

abf.openmandriva.org@root[0]:[~] # uname -r
**4.9.0-server-1omv**

Type/provider of hosts: (VirtualBox/Bare-metal/AWS/GCE/DO)
Bare-metal


I've set up CLI and run that script, well there's nothing interesing inside:

rancher_host.log and rancher_ps_c_a.log are empty - wtf ?

[tpg@lazur rancher.Qz1X]$ cat rancher_ps_s_a.log 
ID        TYPE                   NAME                               IMAGE                            STATE       SCALE     SYSTEM    ENDPOINTS   DETAIL
1s21      service                healthcheck/healthcheck            rancher/healthcheck:v0.2.3       inactive    0/1       true                  
1s22      service                network-services/network-manager   rancher/network-manager:v0.7.0   unhealthy   0/1       true                  
1s23      service                network-services/metadata          rancher/metadata:v0.9.1          unhealthy   0/1       true                  
1s23      sidekick               network-services/metadata/dns      rancher/dns:v0.15.0              unhealthy   0/1       true                  
1s24      networkDriverService   ipsec/ipsec                        rancher/net:holder               inactive    0/1       true                  
1s24      sidekick               ipsec/ipsec/router                 rancher/net:v0.11.2              inactive    0/1       true                  
1s24      sidekick               ipsec/ipsec/cni-driver             rancher/net:v0.11.2              inactive    0/1       true                  
1s25      service                scheduler/scheduler                rancher/scheduler:v0.7.5         inactive    0/1       true

**Comment by emcniece** [comment]
@superseb I have a fresh environment with this problem, and I can provide full access for debug. 3 host nodes in HA, each running a MySQL container (1 master, 2 slave), each running a Rancher/Server container, each added as a host within Rancher.

- Current Rancher version: 1.6.0
- Upgraded from Rancher version: none (fresh install)
- Infrastructure rancher/network-manager version: v0.7.0
- Docker version: 17.03.1-ce, build c6d412e
- Operating system and kernel: (`cat /etc/os-release`, `uname -r` preferred)
    ```
    [rancher@rancher-ha1 ~]$ cat /etc/os-release
    NAME="RancherOS"
    VERSION=v1.0.1
    ID=rancheros
    ID_LIKE=
    VERSION_ID=v1.0.1
    PRETTY_NAME="RancherOS v1.0.1"
    HOME_URL="http://rancher.com/rancher-os/"
    SUPPORT_URL="https://forums.rancher.com/c/rancher-os"
    BUG_REPORT_URL="https://github.com/rancher/os/issues"
    BUILD_ID=
    [rancher@rancher-ha1 ~]$ uname -r
    4.9.24-rancher
    ```
- Type/provider of hosts: [Vultr](https://www.vultr.com/) (DO)

# Steps to reproduce:

1. Provision 3 nodes with [iPXE script](https://www.vultr.com/docs/install-rancher-os-via-ipxe)
1. On one node, set MySQL master via `/home/rancher/mysql/config/master.cnf`
    ```
    [mysqld]
    bind-address = 0.0.0.0
    server-id = 1

    log_bin = /var/log/mysql/mysql-bin.log
    binlog_do_db = rancher
    ```
1. On remaining 2 nodes, set MySQL slave via `/home/rancher/mysql/config/slave.cnf`
    ```
    [mysqld]
    bind-address = 0.0.0.0
    server-id = 2 # or 3

    log_bin = /var/log/mysql/mysql-bin.log
    binlog_do_db = rancher
    ```
1. Start MySQL containers on each node with the following script:
    ```
    docker run -td --restart=unless-stopped \
      -v /home/rancher/mysql/config:/etc/mysql/conf.d \
      -v /home/rancher/mysql/data:/var/lib/mysql \
      -p 3306:3306 \
      -e MYSQL_DATABASE=rancher \
      -e MYSQL_USER=rancher \
      -e MYSQL_PASSWORD=userpass \
      -e MYSQL_INITDB_SKIP_TZINFO=yes \
      -e MYSQL_ROOT_PASSWORD=rootpass \
      --name rancher-mysql \
      mysql:5.7
    ```
1. On MySQL master node: set master mode
    ```
    docker exec -it rancher-mysql mysql -u root -prootpass
    GRANT REPLICATION SLAVE ON *.* TO 'slave_user'@'%' IDENTIFIED BY 'userpass';
    FLUSH PRIVILEGES;
    USE rancher;
    FLUSH TABLES WITH READ LOCK;
    SHOW MASTER STATUS;

    +------------------+----------+--------------+------------------+-------------------+
    | File             | Position | Binlog_Do_DB | Binlog_Ignore_DB | Executed_Gtid_Set |
    +------------------+----------+--------------+------------------+-------------------+
    | mysql-bin.000004 |      595 | rancher      |                  |                   |
    +------------------+----------+--------------+------------------+-------------------+
    1 row in set (0.00 sec)

    UNLOCK TABLES;
    QUIT;
    ```
1. On MySQL slave nodes: set slave mode (using master IP address)
    ```
    docker exec -it rancher-mysql mysql -u root -prootpass
    CHANGE MASTER TO MASTER_HOST='12.34.567.890',MASTER_USER='slave_user', MASTER_PASSWORD='userpass', MASTER_LOG_FILE='mysql-bin.000004', MASTER_LOG_POS=595;
    START SLAVE;
    SHOW SLAVE STATUS\G
    ```
1. Start Rancher on first node (MySQL master)
    ```
    # Ensure db-host is IP of master mysql node
    docker run -td --restart=unless-stopped \
      -p 8080:8080 \
      -p 9345:9345 \
      --name rancher-server \
      rancher/server:v1.6.0 \
      --db-host 12.34.567.890 --db-port 3306 --db-user rancher --db-name rancher --db-pass userpass
    ```
1. Start Rancher on nodes 2 & 3 (repeat last step)
1. Watch IPSEC/Healthcheck chaos 🍿

**Comment by emcniece** [comment]
Just finished a debug session with @superseb (**super** indeed!) and he managed to identify that one of the host nodes was reporting the `docker0` bridge network as its IP address. This is obviously incorrect, as the `docker0` bridge is internal and does not represent the external IP address.

We analyzed the HA 4-host stack as it sat on Rancher 1.5.1, then tore it down and built it back up on Rancher 1.6.0. This time, each host was added with a specified external IP address. Stability has been achieved.

I'm not convinced that this issue thread is related to my problem, but I did experience the symptoms described here. Either way, it might not hurt to confirm that your hosts are reporting the correct IP address.

Many thanks for your time and effort, @superseb!

**Comment by nheinemans** [comment]
This issue started showing up in our environment since last week. We recently upgraded from Rancher 1.5.3 to 1.5.9. Luckily, most environments are created correctly, however some experience the Timeout getting IP address issue.

We are running Rancheros 1.0.1 on VMware. I will try to find some time later today to debug this further.

**Comment by tpgxyz** [comment]
@superseb  or anyone can resolve this issue ?

**Comment by tpgxyz** [comment]
Found this
    id": "1i33627",
    "type": "container",
    "links": {
        "self": "…/v2-beta/projects/1a5/containers/1i33627",
        "account": "…/v2-beta/projects/1a5/containers/1i33627/account",
        "credentials": "…/v2-beta/projects/1a5/containers/1i33627/credentials",
        "healthcheckInstanceHostMaps": "…/v2-beta/projects/1a5/containers/1i33627/healthcheckinstancehostmaps",
        "hosts": "…/v2-beta/projects/1a5/containers/1i33627/hosts",
        "instanceLabels": "…/v2-beta/projects/1a5/containers/1i33627/instancelabels",
        "instanceLinks": "…/v2-beta/projects/1a5/containers/1i33627/instancelinks",
        "instances": "…/v2-beta/projects/1a5/containers/1i33627/instances",
        "mounts": "…/v2-beta/projects/1a5/containers/1i33627/mounts",
        "ports": "…/v2-beta/projects/1a5/containers/1i33627/ports",
        "serviceEvents": "…/v2-beta/projects/1a5/containers/1i33627/serviceevents",
        "serviceExposeMaps": "…/v2-beta/projects/1a5/containers/1i33627/serviceexposemaps",
        "serviceLogs": "…/v2-beta/projects/1a5/containers/1i33627/servicelogs",
        "services": "…/v2-beta/projects/1a5/containers/1i33627/services",
        "targetInstanceLinks": "…/v2-beta/projects/1a5/containers/1i33627/targetinstancelinks",
        "volumes": "…/v2-beta/projects/1a5/containers/1i33627/volumes",
        "stats": "…/v2-beta/projects/1a5/containers/1i33627/stats",
        "containerStats": "…/v2-beta/projects/1a5/containers/1i33627/containerstats"
    },
    "actions": {
        "remove": "…/v2-beta/projects/1a5/containers/1i33627/?action=remove"
    },
    "baseType": "instance",
    "name": "network-services-network-manager-3",
    "state": "error",
    "accountId": "1a5",
    "blkioDeviceOptions": null,
    "blkioWeight": null,
    "build": null,
    "capAdd": null,
    "capDrop": null,
    "cgroupParent": null,
    "command": [ 3 items
        "plugin-manager",
        "--metadata-url",
        "http://169.254.169.250/2016-07-29"
    ],
    "cpuCount": null,
    "cpuPercent": null,
    "cpuPeriod": null,
    "cpuQuota": null,
    "cpuSet": null,
    "cpuSetMems": null,
    "cpuShares": null,
    "createIndex": 5,
    "created": "2017-05-24T19:05:46Z",
    "createdTS": 1495652746000,
    "dataVolumeMounts": { },
    "dataVolumes": [ 8 items
        "/var/run/docker.sock:/var/run/docker.sock",
        "/var/lib/docker:/var/lib/docker",
        "/var/lib/rancher/state:/var/lib/rancher/state",
        "/lib/modules:/lib/modules:ro",
        "/run:/run:ro",
        "/var/run:/var/run:ro",
        "rancher-cni-driver:/etc/cni",
        "rancher-cni-driver:/opt/cni"
    ],
    "dataVolumesFrom": null,
    "deploymentUnitUuid": "ae43589e-e1cd-4c88-bc83-e346a3b2bad5",
    "description": null,
    "devices": null,
    "diskQuota": null,
    "dns": null,
    "dnsOpt": null,
    "dnsSearch": [ 2 items
        "network-services.rancher.internal",
        "network-manager.network-services.rancher.internal"
    ],
    "domainName": null,
    "entryPoint": null,
    "environment": {
        "DOCKER_BRIDGE": "docker0",
        "METADATA_IP": "169.254.169.250"
    },
    "expose": null,
    "externalId": "",
    "extraHosts": null,
    "firstRunning": null,
    "groupAdd": null,
    "healthCheck": null,
    "healthCmd": null,
    "healthInterval": null,
    "healthRetries": null,
    "healthState": null,
    "healthTimeout": null,
    "hostId": "1h4",
    "hostname": null,
    "imageUuid": "docker:rancher/network-manager:v0.7.0",
    "instanceTriggeredStop": "stop",
    "ioMaximumBandwidth": null,
    "ioMaximumIOps": null,
    "ip": null,
    "ip6": null,
    "ipcMode": null,
    "isolation": null,
    "kernelMemory": null,
    "kind": "container",
    "labels": {
        "io.rancher.service.deployment.unit": "ae43589e-e1cd-4c88-bc83-e346a3b2bad5",
        "io.rancher.service.requested.host.id": "4",
        "io.rancher.stack_service.name": "network-services/network-manager",
        "io.rancher.service.launch.config": "io.rancher.service.primary.launch.config",
        "io.rancher.project.name": "network-services",
        "io.rancher.project_service.name": "network-services/network-manager",
        "io.rancher.stack.name": "network-services",
        "io.rancher.service.hash": "f3bf3137ed558867efb7108874cd42cf5baea9a3",
        "io.rancher.scheduler.global": "true",
        "io.rancher.container.system": "true"
    },
    "logConfig": {
        "type": "logConfig",
        "config": {
            "max-file": "2",
            "max-size": "25m"
        },
        "driver": "json-file"
    },
    "lxcConf": null,
    "memory": null,
    "memoryReservation": null,
    "memorySwap": null,
    "memorySwappiness": null,
    "milliCpuReservation": null,
    "mounts": null,
    "nativeContainer": false,
    "netAlias": null,
    "networkContainerId": null,
    "networkMode": "host",
    "oomKillDisable": null,
    "oomScoreAdj": null,
    "pidMode": "host",
    "pidsLimit": null,
    "ports": null,
    "primaryIpAddress": null,
    "primaryNetworkId": "1n1",
    "privileged": true,
    "publishAllPorts": false,
    "readOnly": false,
    "registryCredentialId": null,
    "removed": null,
    "requestedHostId": "1h4",
    "restartPolicy": null,
    "secrets": null,
    "securityOpt": null,
    "serviceId": null,
    "serviceIds": [
        "1s30"
    ],
    "shmSize": null,
    "stackId": null,
    "startCount": 0,
    "startOnCreate": true,
    "stdinOpen": false,
    "stopSignal": null,
    "storageOpt": null,
    "sysctls": null,
    "system": true,
    "tmpfs": null,
    "transitioning": "error",
    "transitioningMessage": "Error response from daemon: invalid header field value \"oci runtime error: container_linux.go:247: starting container process caused \\\"process_linux.go:359: container init caused \\\\\\\"rootfs_linux.go:54: mounting \\\\\\\\\\\\\\\"/var/lib/docker/containers/f2e9fb35fdcd937a51839746cae0542a80632d120c8892061863e41c344a1814/secrets\\\\\\\\\\\\\\\" to rootfs \\\\\\\\\\\\\\\"/var/lib/docker/overlay/50978fadaf02d2e29421737ee02290920d62e56904c240bab5e824f44b360077/merged\\\\\\\\\\\\\\\" at \\\\\\\\\\\\\\\"/var/lib/docker/overlay/50978fadaf02d2e29421737ee02290920d62e56904c240bab5e824f44b360077/merged/run/secrets\\\\\\\\\\\\\\\" caused \\\\\\\\\\\\\\\"mkdir /var/lib/docker/overlay/50978fadaf02d2e29421737ee02290920d62e56904c240bab5e824f44b360077/merged/run/secrets: read-only file system\\\\\\\\\\\\\\\"\\\\\\\"\\\"\\n\"",
    "transitioningProgress": 84,
    "tty": false,
    "ulimits": null,
    "user": null,
    "userPorts": null,
    "usernsMode": null,
    "uts": null,
    "uuid": "850e5929-05ad-449d-b27e-f385c5f9d62d",
    "version": "0",
    "volumeDriver": null,
    "workingDir": null

}

**Comment by tpgxyz** [comment]
Again output form healtcheck

{

    "id": "1i36522",
    "type": "container",
    "links": {
        "self": "…/v2-beta/projects/1a5/containers/1i36522",
        "account": "…/v2-beta/projects/1a5/containers/1i36522/account",
        "credentials": "…/v2-beta/projects/1a5/containers/1i36522/credentials",
        "healthcheckInstanceHostMaps": "…/v2-beta/projects/1a5/containers/1i36522/healthcheckinstancehostmaps",
        "hosts": "…/v2-beta/projects/1a5/containers/1i36522/hosts",
        "instanceLabels": "…/v2-beta/projects/1a5/containers/1i36522/instancelabels",
        "instanceLinks": "…/v2-beta/projects/1a5/containers/1i36522/instancelinks",
        "instances": "…/v2-beta/projects/1a5/containers/1i36522/instances",
        "mounts": "…/v2-beta/projects/1a5/containers/1i36522/mounts",
        "ports": "…/v2-beta/projects/1a5/containers/1i36522/ports",
        "serviceEvents": "…/v2-beta/projects/1a5/containers/1i36522/serviceevents",
        "serviceExposeMaps": "…/v2-beta/projects/1a5/containers/1i36522/serviceexposemaps",
        "serviceLogs": "…/v2-beta/projects/1a5/containers/1i36522/servicelogs",
        "services": "…/v2-beta/projects/1a5/containers/1i36522/services",
        "targetInstanceLinks": "…/v2-beta/projects/1a5/containers/1i36522/targetinstancelinks",
        "volumes": "…/v2-beta/projects/1a5/containers/1i36522/volumes",
        "stats": "…/v2-beta/projects/1a5/containers/1i36522/stats",
        "containerStats": "…/v2-beta/projects/1a5/containers/1i36522/containerstats"
    },
    "actions": {
        "remove": "…/v2-beta/projects/1a5/containers/1i36522/?action=remove"
    },
    "baseType": "instance",
    "name": "healthcheck-healthcheck-2",
    "state": "error",
    "accountId": "1a5",
    "blkioDeviceOptions": null,
    "blkioWeight": null,
    "build": null,
    "capAdd": null,
    "capDrop": null,
    "cgroupParent": null,
    "command": null,
    "cpuCount": null,
    "cpuPercent": null,
    "cpuPeriod": null,
    "cpuQuota": null,
    "cpuSet": null,
    "cpuSetMems": null,
    "cpuShares": null,
    "createIndex": 700,
    "created": "2017-05-29T08:08:00Z",
    "createdTS": 1496045280000,
    "dataVolumeMounts": { },
    "dataVolumes": [
        "/var/lib/rancher/etc:/var/lib/rancher/etc:ro"
    ],
    "dataVolumesFrom": null,
    "deploymentUnitUuid": "9ebfbcef-5316-48cd-a544-e0755259f9f1",
    "description": null,
    "devices": null,
    "diskQuota": null,
    "dns": [
        "169.254.169.250"
    ],
    "dnsOpt": null,
    "dnsSearch": [ 3 items
        "healthcheck.rancher.internal",
        "healthcheck.healthcheck.rancher.internal",
        "rancher.internal"
    ],
    "dockerPorts": [ ],
    "domainName": null,
    "entryPoint": null,
    "environment": null,
    "expose": null,
    "externalId": "97d2206b6778fe1d71ae0eb64deabf15b2ed289f67293f09ea2acd48afd6a004",
    "extraHosts": null,
    "firstRunning": null,
    "groupAdd": null,
    "healthCheck": {
        "type": "instanceHealthCheck",
        "healthyThreshold": 2,
        "interval": 2000,
        "port": 42,
        "responseTimeout": 2000,
        "strategy": "recreate",
        "unhealthyThreshold": 3
    },
    "healthCmd": null,
    "healthInterval": null,
    "healthRetries": null,
    "healthState": null,
    "healthTimeout": null,
    "hostId": "1h7",
    "hostname": null,
    "imageUuid": "docker:rancher/healthcheck:v0.3.1",
    "instanceTriggeredStop": "stop",
    "internalVolumes": [ ],
    "ioMaximumBandwidth": null,
    "ioMaximumIOps": null,
    "ip": null,
    "ip6": null,
    "ipcMode": null,
    "isolation": null,
    "kernelMemory": null,
    "kind": "container",
    "labels": {
        "io.rancher.service.deployment.unit": "9ebfbcef-5316-48cd-a544-e0755259f9f1",
        "io.rancher.service.requested.host.id": "7",
        "io.rancher.stack_service.name": "healthcheck/healthcheck",
        "io.rancher.service.launch.config": "io.rancher.service.primary.launch.config",
        "io.rancher.project.name": "healthcheck",
        "io.rancher.project_service.name": "healthcheck/healthcheck",
        "io.rancher.container.create_agent": "true",
        "io.rancher.stack.name": "healthcheck",
        "io.rancher.service.hash": "7f8d78bdc5e48b52d1821bdfa68b774c0b74d456",
        "io.rancher.scheduler.global": "true",
        "io.rancher.container.system": "true"
    },
    "logConfig": {
        "type": "logConfig",
        "config": {
            "max-file": "2",
            "max-size": "25m"
        },
        "driver": "json-file"
    },
    "lxcConf": null,
    "memory": null,
    "memoryReservation": null,
    "memorySwap": null,
    "memorySwappiness": null,
    "milliCpuReservation": null,
    "mounts": null,
    "nativeContainer": false,
    "netAlias": null,
    "networkContainerId": null,
    "networkMode": "managed",
    "oomKillDisable": null,
    "oomScoreAdj": null,
    "pidMode": null,
    "pidsLimit": null,
    "ports": null,
    "primaryIpAddress": null,
    "primaryNetworkId": "1n5",
    "privileged": false,
    "publishAllPorts": false,
    "readOnly": false,
    "registryCredentialId": null,
    "removed": null,
    "requestedHostId": "1h7",
    "restartPolicy": null,
    "secrets": null,
    "securityOpt": null,
    "serviceId": null,
    "serviceIds": [
        "1s26"
    ],
    "shmSize": null,
    "stackId": null,
    "startCount": 0,
    "startOnCreate": true,
    "stdinOpen": false,
    "stopSignal": null,
    "storageOpt": null,
    "sysctls": null,
    "system": true,
    "tmpfs": null,
    "transitioning": "error",
    "transitioningMessage": "Couldn't bring up network: failed to find plugin \"rancher-bridge\" in path [/opt/cni/bin /var/lib/cni/bin /usr/local/sbin /usr/sbin /sbin /usr/local/bin /usr/bin /bin]",
    "transitioningProgress": 84,
    "tty": false,
    "ulimits": null,
    "user": null,
    "userPorts": null,
    "usernsMode": null,
    "uts": null,
    "uuid": "ef09b71e-7326-4e7a-b1ca-089015765387",
    "version": "0",
    "volumeDriver": null,
    "workingDir": null

}

**Comment by fedya** [comment]
`time="2017-05-31T11:44:48Z" level=error msg="Failed to evaluate networking: failed to find plugin \"rancher-bridge\" in path [/opt/cni/bin /var/lib/cni/bin /usr/local/sbin /usr/sbin /sbin /usr/local/bin /usr/bin /bin]"`


Issue still not resolved.

**Comment by superseb** [comment]
Had the time to look around @ciokan systems, thanks a lot for that. Great to get an insight into the actual running problem. So as all the logs hint to a network problem, the root cause seems to be metadata returning inconsistent results. So quering `169.254.169.250/latest/self/host/uuid` would return different results, and this output is actually used to setup networking. We have a lead and are investigating why this is happening.

**Comment by maciekciolek** [comment]
@superseb do you have any plans to fix it? Is it fixed in 1.6.1?

**Comment by tpgxyz** [comment]
@superseb @maciekciolek Hi, looks like 1.6.1 did not fixed this issue.

**Comment by superseb** [comment]
As long as this is open we are working on it, if a fix is there we will definitely share it here to let people try it. Let me get you an update today on our investigation. In the meantime, if you can confirm you are seeing the same issue as described in https://github.com/rancher/rancher/issues/8383#issuecomment-305400907 that would be great.

**Comment by tpgxyz** [comment]
@superseb  How to confirm #8383 (comment) ? Can you please share with me a step-by-step procedure ?

**Comment by brunocascio** [comment]
I face the same issue

**Comment by superseb** [comment]
@maciekciolek @tpgxyz On the host experiencing issues, you can `Execute shell` on a container (i.e. network-manager or healthcheck) and execute `curl http://169.254.169.250/latest/self/host/uuid` repeatedly. This would result in random results.

**Comment by maciekciolek** [comment]
@superseb I am getting same results while executing this repeatedly. The only fix which works for me is this script: https://github.com/rancher/rancher/issues/8383#issuecomment-298100234

**Comment by maciekciolek** [comment]
@superseb @tpgxyz I have just solved the problem on our environment.

In our case the problem was, that we have 3 NICs per host and when I was starting the agent, it was auto-detecting wrong agent host IP (IP address of local docker network) which was not accessible from server and the other hosts. **The solution which works** for me is just providing IP address in 4th step of "Add host" which is accessible from server and the other hosts. 

In other words, you need to **manually provide CATTLE_AGENT_IP env** variable while you are starting an agent. It also means that you need to do it event for host (agent) which will be run on the same host as the server.

`sudo docker run -e CATTLE_AGENT_IP="192.168.0.30"  --rm --privileged -v /var/run/docker.sock:/var/run/docker.sock -v /var/lib/rancher:/var/lib/rancher rancher/agent:v1.2.2 http://192.168.0.87:7000/v1/scripts/***`

After this fix ipsec, healthcheck, cni erros disappear. 

Tested on: 1.5.1 and 1.5.10

**Comment by tpgxyz** [comment]
@maciekciolek Many thanks! It works now.

@fedya \o/

**Comment by brunocascio** [comment]
It works on 1.6.2 as well :1st_place_medal:

**Comment by ciokan** [comment]
@maciekciolek Where is that `CATTLE_AGENT_IP` supposed to point when having multiple servers? The rancher ip address?

**Comment by fedya** [comment]
It is already stable branch?

**Comment by maciekciolek** [comment]
@ciokan as far as I understand you have one (or more) rancher servers S{x} and many instances on which you want to run rancher agents (worker) - let`s say  I1, I2, I3. If you are adding new host (rancher agent / worker), which will run on instance I1 you should provided the value of CATTLE_AGENT_IP which is the IP address of the instance I1. If you are adding host which runs on I2, then use the IP address of I2.

The most important thing is, that value of CATTLE_AGENT_IP should be IP of an interface, which is accessible (eg. same network) by other instances and servers.

**Comment by fedya** [comment]
@maciekciolek i'm right understood it that CATTLE_AGENT_IP must be server IP not docker0 interface?

**Comment by maciekciolek** [comment]
@fedya CATTLE_AGENT_IP must be the IP of agent which you are starting. The value will be propagated by this agent to the server and other agents and will be used by them to communicate with this agent. So, if you have multiple host in the local network, the value of  should be the IP of host on which you are starting an agent. 

CATTLE_AGENT_IP is not server IP. The server IP is attached in starting command, eg.:
`sudo docker run -e CATTLE_AGENT_IP="192.168.0.30" --rm --privileged -v /var/run/docker.sock:/var/run/docker.sock -v /var/lib/rancher:/var/lib/rancher rancher/agent:v1.2.2 http://192.168.0.87:7000/v1/scripts/**`

192.168.0.30 - IP of host on which I am starting the agent
192.168.0.87:7000 - IP and port of Rancher server

**Comment by fedya** [comment]
Well.
how i run node

`docker run --rm -e CATTLE_AGENT_IP="192.168.1.165" --privileged -v /var/run/docker.sock:/var/run/docker.sock -v /var/lib/rancher:/var/lib/rancher rancher/agent:v1.2.2 http://abf.openmandriva.org:8080/v1/scripts/xxxxxxx`

CATTLE_AGENT_IP = ip from my node

And i got same results as above in this thread

```
nsenter: failed to execute /opt/cni/bin/rancher-bridge: No such file or directory
time="2017-06-26T14:05:46Z" level=error msg="Failed to evaluate networking: netplugin failed but error parsing its diagnostic message \"\": unexpected end of JSON input" 
time="2017-06-26T14:05:47Z" level=info msg="Evaluating state from retry" cid=63e6008665a6b764541593ecfa9fba465674b8c420714e39752d83fe7392de75 count=11 
time="2017-06-26T14:05:47Z" level=info msg="CNI up" cid=63e6008665a6b764541593ecfa9fba465674b8c420714e39752d83fe7392de75 networkMode=ipsec 
nsenter: failed to execute /opt/cni/bin/rancher-bridge: No such file or directory
time="2017-06-26T14:05:47Z" level=error msg="Failed to evaluate networking: netplugin failed but error parsing its diagnostic message \"\": unexpected end of JSON input" 
```

**Comment by janeczku** [comment]
Metadata returning inconsistent results (exposed ports of container).
Rancher v1.6.2
Network Services v0.2.2

```
root@92e5bd7ca9cf:/# curl rancher-metadata/2015-12-19/stacks/lb-test/serv
containers/0/ports
root@92e5bd7ca9cf:/# curl rancher-metadata/2015-12-19/stacks/lb-test/services/1/
containers/0/ports
0
```

**Comment by fedya** [comment]
yes, still not working

2017-07-10 16:17 GMT+03:00 Jan B <notifications@github.com>:

**Comment by ciokan** [comment]
Is there any progress from the dev team regarding this issue? It has almost 4 months and 71 comments so far. I keep delaying my team from going fully with rancher due to this bug.

**Comment by fedya** [comment]
We are too. Very annoying issue.
Btw i tested it with stable CoreOS, same bug.

2017-07-10 21:52 GMT+03:00 Romeo Mihalcea <notifications@github.com>:

**Comment by brunocascio** [comment]
Setting `CATTLE_AGENT_IP = ip from my node` works for me. I've tested on the cloud not local.

**Comment by fedya** [comment]
i tried with CATTLE_AGENT_IP no success

2017-07-11 1:01 GMT+03:00 Bruno <notifications@github.com>:

**Comment by brunocascio** [comment]
@fedya 
Try with the latest version of the agent: `rancher/agent:v1.2.5`

**Comment by fedya** [comment]
still no success

docker run --rm --privileged -e CATTLE_AGENT_IP=rancher_server_ip_here -v /var/run/docker.sock:/var/run/docker.sock -v /var/lib/rancher:/var/lib/rancher rancher/agent:v1.2.5 http://rancher_server_ip_here:8080/v1/scripts/KEY

```
 Time:1499874158, TimeNano:1499874158521952432}. Error: failed to find plugin \"rancher-bridge\" in path [/opt/cni/bin /var/lib/cni/bin /usr/local/sbin /usr/sbin /sbin /usr/local/bin /usr/bin /bin]" 
time="2017-07-12T15:42:40Z" level=info msg="Evaluating state from retry" cid=eadbd8bf8bf74677e15e2d7b6d04d744e841ec3cc94ee421fa8291820cfba211 count=10 
time="2017-07-12T15:42:40Z" level=info msg="CNI up" cid=eadbd8bf8bf74677e15e2d7b6d04d744e841ec3cc94ee421fa8291820cfba211 networkMode=ipsec 
time="2017-07-12T15:42:40Z" level=error msg="Failed to evaluate networking: failed to find plugin \"rancher-bridge\" in path [/opt/cni/bin /var/lib/cni/bin /usr/local/sbin /usr/sbin /sbin /usr/local/bin /usr/bin /bin]" 

```

**Comment by brunocascio** [comment]
Which docker version are you using on your rancher server and agents?

**Comment by ciokan** [comment]
1.12.6

**Comment by brunocascio** [comment]
Are agents able to ping the rancher server? Are you using a firewall?

**Comment by pasikarkkainen** [comment]
@fedya: in your commannd.. "CATTLE_AGENT_IP=rancher_server_ip_here" .. that doesn't sound right. CATTLE_AGENT_IP should be IP of the docker *host*, not the IP of the rancher server .. or did I miss something?

**Comment by ciokan** [comment]
@pasikarkkainen yes I tried with the ip of the client running the agent. Same error: `Couldn't bring up network: failed to find plugin "rancher-bridge" in path [/opt/cni/bin /var/lib/cni/bin /usr/local/sbin /usr/sbin /sbin /usr/local/bin /usr/bin /bin]`. Docker version doesn't matter as I see the same error on different hosts running the same engine version. Rancher server picks up the correct agent ip address so I don't believe `CATTLE_AGENT_IP` has anything to do here (tried and tested). I managed to repair 80% of the hosts using my above image but the rest of them refuse to work properly even with it.

I wouldn't be bothered with this bug as it's no affecting my services but, with it present, my rancher server stays at 100% on all cores (8 of them). If I deactivate the clients with the bug present my rancher server CPU goes down to normal 10% - 20%. With the clients deactivated in rancher server services work ok but, if a client gets restarted, they don't start any more.

This is the second "most discussed" ticket on this project and we still don't have a clue, roadmap, timeline or official answer regarding this bug. Everyone involved here provided everything requested, I even collaborated with the dev team and provided SSH access to multiple boxes including rancher server. The culprit seems to be tracked but after that...silence.

We need an official answer as I don't have a single clue regarding how much we're supposed to keep waiting. If it's 1 year I can re-route my team and build something custom. If it's 1-2 months we can probably wait but the lack of feedback generates a lot of frustration within our office and, I'm sure, other teams affected by this thing.

I can see over 1700 tickets being open which must be overwhelming. I'm happy to pay for support knowing this will get the bug fixed. I'm sure others are holding cash in hand for this.

TL; DR: Give us something. We're barking at trees here.

**Comment by leodotcloud** [comment]
@ciokan @fedya and everyone who are having this problem, can you please ping me on https://slack.rancher.io? I would like to schedule a debug session with you guys. I work in PST timezone so please give me a couple of time slots that work for both us. @superseb @janeczku Can you please coordinate too?

We have not been able to reproduce this issue on our end in a reliable way, hence the delay in root causing the issue. Our QA team puts in a lot of effort testing various scenarios on different operating systems and also different rancher versions. Our team also test rancher/server upgrade scenarios as well. Along with these efforts, we also have a bunch on tag automation runs triggered on a daily basis. In the past few months we have never been able to hit this issue.

TL;DR: We are not ignoring anyone or this issue and would like to fix it if we can find a way to reproduce it.

**Comment by leodotcloud** [comment]
To avoid confusion regarding CATTLE_AGENT_IP, this has to be set to the IP address of the host where the command is being run. And also this IP address should be reachable by all other nodes in the cluster.
For example, in AWS if you have two hosts in two different VPCs and you have used the private IP addresses of these hosts to register them with rancher/server you might have a problem if inter VPC communication is not configured properly.

Setting this variable is not needed for all environments but only on setups/clouds where the auto IP detection doesn't work due to the cloud provider/network topology limitations.

**Comment by fedya** [comment]
Okay, i will do.
My timezone is MSK, but usually i'm online for 14-17 hours per day

12 июля 2017 г. 21:22 пользователь "leodotcloud" <notifications@github.com>
написал:

**Comment by ciokan** [comment]
woah...after all this time...my stack is green. I'll have to thank @leodotcloud and @superseb for taking the time to get to the bottom of it. From the looks of it (leo might step in with more updates) the docker daemon was running on a different ip address than expected, an old one actually. They managed to fix my setup, I can't give a fix right now because I have bits of it but they fixed about 12 - 15 machines and I'm sure the team now has an idea and can push a fix soon. It' def a hard thing to reproduce in their testing setup that's why the long wait over here.

Thank you guys!

**Comment by leodotcloud** [comment]
@ciokan Thank you for taking time to share your setup for debugging.

The error message: `Failed to evaluate networking: failed to find plugin \"rancher-bridge\"` could be due to a variety of problems. One of the reasons is as below:

## **Summary:**
**TL; DR version:** If the IP address of the `docker0` bridge on any host is same as the IP address assigned to any container, especially metadata container, in the cluster this problem surfaces.

**Long version:**
All of Rancher's infra microservices/containers running on any host of the cluster rely on metadata to fetch the information needed to do their jobs. `rancher-metadata` answers the queries in an intelligent fashion, giving out information based on the source IP address of the request. So `169.254.169.250/latest/self/container/` will yield different answers for various containers. If the source IP address lookup fails in `rancher-metadata` only parts of the information which are common to all the containers on that host are available while querying. Ex: Only `169.254.169.250/latest/self/host` is available but not `169.254.169.250/latest/self/container` as we cannot determine from where the request is coming from.

When a new host is added to rancher, the first microservice to start would be `rancher-metadata` along with it's sidekick `rancher-dns`. This microservice is on docker's bridge network and gets an IP address from the subnet configured for docker. Example: If the bridge subnet is `172.17.0.0/16`, an IP address in the range `172.17.0.1` to `172.17.255.254` is allocated for this container. In general the first IP address of this container, i.e., `172.17.0.1` is configured on the bridge, `rancher-metadata` generally/most of the times gets `172.17.0.2`. While debugging @ciokan's setup, we noticed that some of the `rancher-metadata` containers in the cluster had an IP address of `172.17.0.1`, which was quite unusual and upon further investigation we found `docker0` bridge had an IP: `172.17.42.1`. 

Now let's understand how `network-manager` works. The microservice `network-manager` is responsible for setting up the CNI executable, CNI config so that IPSec stack can start properly. `network-manager` queries `169.254.169.250/latest/containers`, `169.254.169.250/latest/services`, `169.254.169.250/latest/stacks` to figure out what containers, services, stacks are running in the cluster. Now to figure out local containers, it relies on the information returned by `169.254.169.250/latest/self/host`. Since `network-manager` runs on the host network (`--net=host`) all the requests reaching the metadata container have the IP address of `docker0` bridge as the source IP. This means the source IP seen by metadata is `172.17.0.1` in most of the use cases and there is no hit for this IP while looking up metadata's internal info. But in @ciokan's setup there are few containers with this IP address, the lookup didn't miss and metadata was returning information which was incorrect in this context. Since there are multiple entries with the same lookup key, the information from metadata was flapping as observed/mentioned in a previous debugging session with a different user.

**Workaround:**
On hosts where the IP address of the `docker0` bridge is not `172.17.0.1`, change the docker config and restart docker. 

Here are steps for a Ubuntu:
```
cat > /etc/docker/daemon.json << EOF
{
    "bip": "172.17.0.1/16",
    "fixed-cidr": "172.17.0.0/16"
}
EOF

service docker stop
rm -rf /var/run/docker.sock
ps -ef | grep docker 
# make sure none of the old docker processes are running.
# if yes do kill -9 ____
service docker start
docker ps
ip addr show docker0
```

**Why docker0 bridge has this IP address?**
May be the host was running an older version of docker when the default IP used for the bridge used to be `172.17.42.1` and later the docker version was upgraded? Not sure.

**Comment by leodotcloud** [comment]
Just got off the call with @fedya ... The reason for his problem was different than above.

**Summary:**
Host 1: Running both `rancher/server` and `rancher/agent` ... And this caused the IP detected for this host in Cattle as `172.17.0.1`. 
Host 2: This is the host having problem "Error .... "

When running both server and agent, it's needed to pass `CATTLE_AGENT_IP` as the public IP address of the host while registering the host.

Fix:
- Delete rancher-agent container on Host1 
- Start rancher-agent again on Host1, but this time pass CATTLE_AGENT_IP=PUBLIC_IP_OF_HOST_1
- Things started fine.

**Comment by fedya** [comment]
Tonight we were fixed this issue on my servers. 
Thanks to @leodotcloud for his time.

Main culrpit was rancher agent that running on rancher server, in such case need to pass CATTLE_AGENT_IP when you deploy agent on the server.

**Comment by leodotcloud** [comment]
One more reason: https://github.com/rancher/rancher/issues/9367

**Comment by cwash** [comment]
My devops team approached me with this behavior yesterday when applying an upgrade to rancher-server **1.6.5**

I've double checked CATTLE_AGENT_IP is properly set when adding all of the hosts.

After doing some digging, I found that two of the hosts had docker0 as the 'old' 172.17.42.1

Applying this [fix](https://github.com/rancher/rancher/issues/8383#issuecomment-314937769) from @leodotcloud seemed to clear up the problems for them.

But there is still one other host that is in a bad state where its IPsec containers will not start up and complains about not finding rancher-bridge on the path.

I have tried the [workaround](https://github.com/rancher/rancher/issues/8383#issuecomment-297996995) mentioned by @kaos where we try to write the file ourselves.  I just wrote a script to to get it to pull the right PID in for me as the stack appears.

Here's what the script looks like if anyone else is interested:

`
root@o1:/var/lib/docker/volumes/rancher-cni-driver/_data/bin # ls .
patch*  rancher-bridge*

root@o1:/var/lib/docker/volumes/rancher-cni-driver/_data/bin # cat patch
echo "#!/bin/sh" > rancher-bridge
echo "exec /usr/bin/nsenter -m -u -i -n -p -t $(pgrep -f rancher-cni.log) -- \$0 \"\$@\"" >> rancher-bridge
chmod +x rancher-bridge
`

This seems to change the message away from any mention of rancher-bridge - but it still fails to start up.  

I tried the whole process a few times, and then tried to restart network-manager right after running my patch script as well, but I still can't get IPsec to start on this host.

What I can see in the logs leads me to believe there is something screwed up more deeply with the networking (like maybe iptables) on this box.

`
7/22/2017 7:18:08 PMtime="2017-07-22T23:18:08Z" level=info msg="routesync: DOCKER_BRIDGE=docker0, METADATA_IP=169.254.169.250"
7/22/2017 7:18:08 PMtime="2017-07-22T23:18:08Z" level=info msg="routesync: starting monitoring on bridge: docker0, for metadataIP: 169.254.169.250 every 60 seconds"
7/22/2017 7:18:08 PMtime="2017-07-22T23:18:08Z" level=info msg="Waiting for metadata"
7/22/2017 7:18:08 PMtime="2017-07-22T23:18:08Z" level=info msg="Inspecting on start" cid=c7ef46e9e9460071d743df6e537f281b322bc163918a7a7c50cd180dbbfaaa2b running=true startedAt="2017-07-22T23:17:57.908299925Z"
7/22/2017 7:18:08 PMtime="2017-07-22T23:18:08Z" level=info msg="Recording previously started" cid=c7ef46e9e9460071d743df6e537f281b322bc163918a7a7c50cd180dbbfaaa2b startedAt="2017-07-22T23:17:57.908299925Z"
7/22/2017 7:18:08 PMtime="2017-07-22T23:18:08Z" level=info msg="Inspecting on start" cid=f941b2e1dd4583705e96b6d152f3fa3524e1444831f476301a28828dc673f04b running=true startedAt="2017-07-22T23:17:57.489328691Z"
7/22/2017 7:18:08 PMtime="2017-07-22T23:18:08Z" level=info msg="Recording previously started" cid=f941b2e1dd4583705e96b6d152f3fa3524e1444831f476301a28828dc673f04b startedAt="2017-07-22T23:17:57.489328691Z"
7/22/2017 7:18:08 PMtime="2017-07-22T23:18:08Z" level=info msg="Inspecting on start" cid=09cc4d7f1ee925431cb750e75109f60f76a300c65dcf1b1481990414ae66cf1c running=true startedAt="2017-07-22T23:16:40.734314734Z"
7/22/2017 7:18:08 PMtime="2017-07-22T23:18:08Z" level=info msg="Recording previously started" cid=09cc4d7f1ee925431cb750e75109f60f76a300c65dcf1b1481990414ae66cf1c startedAt="2017-07-22T23:16:40.734314734Z"
7/22/2017 7:18:08 PMtime="2017-07-22T23:18:08Z" level=info msg="Inspecting on start" cid=3ba8a7fdd11b0d4cac3a0f832a1ca51d54b6ce35171f9066810ac3a0e4b11942 running=true startedAt="2017-07-22T23:16:28.621030996Z"
7/22/2017 7:18:08 PMtime="2017-07-22T23:18:08Z" level=info msg="Recording previously started" cid=3ba8a7fdd11b0d4cac3a0f832a1ca51d54b6ce35171f9066810ac3a0e4b11942 startedAt="2017-07-22T23:16:28.621030996Z"
7/22/2017 7:18:08 PMtime="2017-07-22T23:18:08Z" level=info msg="Inspecting on start" cid=5a449b793e2964413b560cedacc13e294a4761b5d15a0c5664b024d651c30e76 running=true startedAt="2017-07-22T23:18:08.507012556Z"
7/22/2017 7:18:08 PMtime="2017-07-22T23:18:08Z" level=info msg="Recording previously started" cid=5a449b793e2964413b560cedacc13e294a4761b5d15a0c5664b024d651c30e76 startedAt="2017-07-22T23:18:08.507012556Z"
7/22/2017 7:18:08 PMtime="2017-07-22T23:18:08Z" level=info msg="Inspecting on start" cid=1225ef04618c2219494cdf8f12220f7a18c3cdba799a2a691c4f8b98431c5045 running=true startedAt="2017-07-22T22:41:02.63298098Z"
7/22/2017 7:18:08 PMtime="2017-07-22T23:18:08Z" level=info msg="Recording previously started" cid=1225ef04618c2219494cdf8f12220f7a18c3cdba799a2a691c4f8b98431c5045 startedAt="2017-07-22T22:41:02.63298098Z"
7/22/2017 7:18:08 PMnet.bridge.bridge-nf-call-iptables = 1
7/22/2017 7:18:08 PMtime="2017-07-22T23:18:08Z" level=info msg="Applying new nat rules"
7/22/2017 7:18:08 PMnet.ipv4.conf.docker0.route_localnet = 1
7/22/2017 7:18:08 PMtime="2017-07-22T23:18:08Z" level=info msg="Setting up binaries for: map[rancher-bridge:6d8147bf17e4581110a250e22fd7c3419c8ef85b36a06808b55ec14a3f9ef71f]"
7/22/2017 7:18:08 PMtime="2017-07-22T23:18:08Z" level=info msg="Starting event router."
7/22/2017 7:18:08 PMtime="2017-07-22T23:18:08Z" level=info msg="Applying new port rules"
7/22/2017 7:18:09 PMtime="2017-07-22T23:18:09Z" level=error msg="macsync: error syncing MAC addresses for the first tiime: inspecting container: 4c65b32cb3ee2a4f1d7c0fd9bc27103e9bd6955765db713d084057df5751ad36: Error: No such container: 4c65b32cb3ee2a4f1d7c0fd9bc27103e9bd6955765db713d084057df5751ad36"
7/22/2017 7:18:09 PMtime="2017-07-22T23:18:09Z" level=info msg="Setting up binaries for: map[rancher-bridge:6d8147bf17e4581110a250e22fd7c3419c8ef85b36a06808b55ec14a3f9ef71f]"
7/22/2017 7:18:09 PMtime="2017-07-22T23:18:09Z" level=error msg="Failed to apply cni conf: Error: No such container: 6d8147bf17e4581110a250e22fd7c3419c8ef85b36a06808b55ec14a3f9ef71f"
7/22/2017 7:18:09 PMtime="2017-07-22T23:18:09Z" level=info msg="Setting up resolv.conf for ContainerId [c7ef46e9e9460071d743df6e537f281b322bc163918a7a7c50cd180dbbfaaa2b]"
7/22/2017 7:18:09 PMtime="2017-07-22T23:18:09Z" level=info msg="Setting up resolv.conf for ContainerId [f941b2e1dd4583705e96b6d152f3fa3524e1444831f476301a28828dc673f04b]"
7/22/2017 7:18:09 PMtime="2017-07-22T23:18:09Z" level=info msg="arpsync: (host) wrong ARP entry found={LinkIndex:3 Family:2 State:32 Type:1 Flags:0 IP:10.42.59.81 HardwareAddr:}(expected: 02:73:10:e6:78:a8) for local container, fixing it"
7/22/2017 7:18:09 PMtime="2017-07-22T23:18:09Z" level=info msg="Network router changed, syncing ARP tables 1/10 in containers, new MAC: 02:73:10:e6:78:a8"
7/22/2017 7:18:09 PMtime="2017-07-22T23:18:09Z" level=error msg="arpsync: while syncing, got error: inspecting container: 4c65b32cb3ee2a4f1d7c0fd9bc27103e9bd6955765db713d084057df5751ad36: Error: No such container: 4c65b32cb3ee2a4f1d7c0fd9bc27103e9bd6955765db713d084057df5751ad36"
7/22/2017 7:18:24 PMtime="2017-07-22T23:18:24Z" level=error msg="macsync: error syncing MAC addresses for the first tiime: inspecting container: 4c65b32cb3ee2a4f1d7c0fd9bc27103e9bd6955765db713d084057df5751ad36: Error: No such container: 4c65b32cb3ee2a4f1d7c0fd9bc27103e9bd6955765db713d084057df5751ad36"
`

I also think there's that in combination with having [crufty](https://github.com/rancher/rancher/issues/8383#issuecomment-298136603) values somewhere in the metadata as mentioned in @ibuildthecloud described.  I can see that there is a message still getting spammed in the network-manager log for that host:
`level=error msg="macsync: error syncing MAC addresses for the first tiime: inspecting container: 4c65b32cb3ee2a4f1d7c0fd9bc27103e9bd6955765db713d084057df5751ad36: Error: No such container: 4c65b32cb3ee2a4f1d7c0fd9bc27103e9bd6955765db713d084057df5751ad36"`

**Comment by cwash** [comment]
@leodotcloud helped me troubleshoot our setup.  We discovered a veth that was showing up on the host in question that was being returned if you did an `ip addr`

After verifying this particular one looked off and should not be there, we tried removing it.  It seems that it was not being cleaned up for whatever reason, and had some values for the host from the "old" setup before the upgrade.  

Removing manually via an `ip link delete veth...` seemed to fix things on the next go 'round, IPSec started up correctly, then healthcheck, etc.

Thanks, @leodotcloud and other users on this thread.

**Comment by kaos** [comment]
I could pitch in another case of netw interface issues that relates to this that we found out.

It was something with the `docker0` interface that apparently was causing issues for us on some occasions, as it got resolved by stopping docker, wiping all docker state (`/var/lib/docker`, `/var/run/docker`, and recreating storage volumes) in addition to actually removing the `docker0` interface. Then start docker again. It was that last piece with removing the docker0 interface that fixed it for us.

**Comment by aemneina** [comment]
@kaos do you happen to know what the docker bridge link address was? Just ran into this today where metadata was stealing docker's bridge ip of '172.17.0.1', possibly because post upgrade of docker it came up with a '172.42.x.x' address...

**Comment by kaos** [comment]
@aemneina IIRC it was `172.17.0.2`. It had just incremented one octet by one.

**Comment by calexandre** [comment]
Guys I'm being overwhelmed with this error.
We started the upgrade from version 1.5.5 to rancher 1.6.10. 
We followed the recommendations to upgrade the network-services before ipsec. After successfully upgrading network-services we started to upgrade the ipsec stack...it started failing on the first host with the following error:

`
Rancher managed network not work with error 'Couldn't bring up network: netplugin failed but error parsing its diagnostic message "": unexpected end of JSON input'
`

**Comment by fedya** [comment]
@calexandre rancher server and rancher node is same pc?

**Comment by calexandre** [comment]
Nope, separate hosts.

I've created a forum post with more detail here: https://forums.rancher.com/t/ipsec-stack-upgrade-problems-when-upgrading-from-rancher-1-5-5-to-1-6-10/7476

Let me know if you want me to bring the issue to to github.

**Comment by guilhermefernandes1** [comment]
I had the same issue yesterday. I have two hosts, and one of them in the same machine of my Rancher. The node I've created in the same PC of the server worked well but the other one was giving me the rancher-bridge error. 
I resolved this removing both hosts and reinstalling them. But first I've installed the host from another machine and then the other one (the one in the same machine of the server).

**Comment by cashlalala** [comment]
I do the same steps as @guilhermefernandes1 said above and solve the issue.

**Comment by deniseschannon** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.
