### ISSUE TITLE
Add host randomly fails

### ISSUE THREAD

**Issue by tfiduccia** [rancher/rancher#9244]
**Rancher versions:** console

**Steps to Reproduce:**
1.  Create a new environment
2.  Add host

**Results:**  Host fails with a Error getting connection config: exit status 1

**Comment:** Looks to be some sort of timing issue as if I have start a bunch at the same time, 1/2 of them will actually succeed.
![image](https://user-images.githubusercontent.com/11514927/27880994-dc8811aa-617b-11e7-89c2-8af297584716.png)

**Comment by vincent99** [comment]
```time="2017-07-05T18:36:53Z" level=info msg="Creating Machine" eventId=4b195f07-3e79-4886-918d-746a99199aa4 resourceId=1ph85 service=gms
time="2017-07-05T18:36:53Z" level=info msg="Cmd slice: [create -d digitalocean --engine-install-url https://releases.rancher.com/install-docker/1.12.sh --digitalocean-access-token ugh-why-is-this-logged --digitalocean-image ubuntu-16-04-x64 --digitalocean-region nyc3 --digitalocean-size 1gb --digitalocean-ssh-port 22 --digitalocean-ssh-user root vjf-a-new-env]" service=gms
time="2017-07-05T18:36:53Z" level=info msg="stdout: Creating CA: /var/lib/cattle/machine/machines/79071dac-855f-477c-bdad-90800c1a3ae4/certs/ca.pem" resourceId: =1ph85 service=gms
time="2017-07-05T18:36:53Z" level=info msg="stdout: Creating client certificate: /var/lib/cattle/machine/machines/79071dac-855f-477c-bdad-90800c1a3ae4/certs/cert.pem" resourceId: =1ph85 service=gms
time="2017-07-05T18:36:54Z" level=info msg="stdout: Running pre-create checks..." resourceId: =1ph85 service=gms
time="2017-07-05T18:36:55Z" level=info msg="stdout: Creating machine..." resourceId: =1ph85 service=gms
time="2017-07-05T18:36:55Z" level=info msg="stdout: (vjf-a-new-env) Creating SSH key..." resourceId: =1ph85 service=gms
time="2017-07-05T18:36:55Z" level=info msg="stdout: (vjf-a-new-env) Creating Digital Ocean droplet..." resourceId: =1ph85 service=gms
time="2017-07-05T18:36:57Z" level=info msg="stdout: (vjf-a-new-env) Waiting for IP address to be assigned to the Droplet..." resourceId: =1ph85 service=gms
time="2017-07-05T18:36:57Z" level=info msg="stdout: Waiting for machine to be running, this may take a few minutes..." resourceId: =1ph85 service=gms
time="2017-07-05T18:37:13Z" level=info msg="stdout: Detecting operating system of created instance..." resourceId: =1ph85 service=gms
time="2017-07-05T18:37:13Z" level=info msg="stdout: Waiting for SSH to be available..." resourceId: =1ph85 service=gms
time="2017-07-05T18:37:32Z" level=info msg="stdout: Detecting the provisioner..." resourceId: =1ph85 service=gms
time="2017-07-05T18:37:33Z" level=info msg="stdout: Provisioning with ubuntu(systemd)..." resourceId: =1ph85 service=gms
time="2017-07-05T18:37:54Z" level=info msg="stdout: Installing Docker..." resourceId: =1ph85 service=gms
time="2017-07-05T18:38:30Z" level=info msg="stdout: Copying certs to the local machine directory..." resourceId: =1ph85 service=gms
time="2017-07-05T18:38:32Z" level=info msg="stdout: Copying certs to the remote machine..." resourceId: =1ph85 service=gms
time="2017-07-05T18:38:37Z" level=info msg="stdout: Setting Docker configuration on the remote daemon..." resourceId: =1ph85 service=gms
time="2017-07-05T18:38:44Z" level=info msg="stdout: Checking connection to Docker..." resourceId: =1ph85 service=gms
time="2017-07-05T18:38:45Z" level=info msg="stdout: Docker is up and running!" resourceId: =1ph85 service=gms
time="2017-07-05T18:38:45Z" level=info msg="stdout: To see how to connect your Docker Client to the Docker Engine running on this virtual machine, run: docker-machine env vjf-a-new-env" resourceId: =1ph85 service=gms
time="2017-07-05T18:38:45Z" level=info msg="Machine Created" eventId=4b195f07-3e79-4886-918d-746a99199aa4 resourceId=1ph85 service=gms
time="2017-07-05T18:38:45Z" level=info msg="Creating and uploading extracted machine config" resourceId=1ph85 service=gms
time="2017-07-05T18:38:45Z" level=info msg="Machine config file saved." eventId=4b195f07-3e79-4886-918d-746a99199aa4 resourceId=1ph85 service=gms
time="2017-07-05T18:38:45Z" level=info msg="Activating Machine" eventId=3909c7d9-20e4-448f-a1a3-e3811d1d3d26 resourceId=1ph85 service=gms
time="2017-07-05T18:38:46Z" level=error msg="Error processing event" err="Error getting connection config: exit status 1" eventId=3909c7d9-20e4-448f-a1a3-e3811d1d3d26 eventName="physicalhost.bootstrap;handler=goMachineService" resourceId=1ph85

7/5/2017 11:38:46 AM2017-07-05 18:38:46,096 ERROR [d6c91a9a-d4f0-4be2-9eaf-78cce3c7cd5c:2974145] [physicalHost:85] [physicalhost.bootstrap] [] [cutorService-22] [c.p.e.p.i.DefaultProcessInstanceImpl] Agent error for [physicalhost.bootstrap.reply;handler=goMachineService]: Error getting connection config: exit status 1
7/5/2017 11:38:46 AM2017-07-05 18:38:46,127 ERROR [:] [] [] [] [cutorService-22] [.e.s.i.ProcessInstanceDispatcherImpl] Agent error for [physicalhost.bootstrap.reply;handler=goMachineService]: Error getting connection config: exit status 1
7/5/2017 11:38:46 AM2017-07-05 18:38:46,879 ERROR [e839f636-3e40-4228-ae1a-0709fce60dcb:2974138] [host:86] [host.provision] [] [cutorService-18] [c.p.e.p.i.DefaultProcessInstanceImpl] Unknown exception io.cattle.platform.util.exception.ExecutionException: Error getting connection config: exit status 1

7/5/2017 11:38:46 AM	at io.cattle.platform.process.host.HostProvision.handle(HostProvision.java:77)
7/5/2017 11:38:46 AM	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.runHandler(DefaultProcessInstanceImpl.java:440)
7/5/2017 11:38:46 AM	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl$3.execute(DefaultProcessInstanceImpl.java:422)
7/5/2017 11:38:46 AM	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl$3.execute(DefaultProcessInstanceImpl.java:416)
7/5/2017 11:38:46 AM	at io.cattle.platform.engine.idempotent.Idempotent.execute(Idempotent.java:42)
7/5/2017 11:38:46 AM	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.idempotentRunHandler(DefaultProcessInstanceImpl.java:416)
7/5/2017 11:38:46 AM	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.runHandlers(DefaultProcessInstanceImpl.java:379)
7/5/2017 11:38:46 AM	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.runLogic(DefaultProcessInstanceImpl.java:491)
7/5/2017 11:38:46 AM	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.runWithProcessLock(DefaultProcessInstanceImpl.java:310)
7/5/2017 11:38:46 AM	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl$1.doWithLockNoResult(DefaultProcessInstanceImpl.java:225)
7/5/2017 11:38:46 AM	at io.cattle.platform.lock.LockCallbackNoReturn.doWithLock(LockCallbackNoReturn.java:7)
7/5/2017 11:38:46 AM	at io.cattle.platform.lock.LockCallbackNoReturn.doWithLock(LockCallbackNoReturn.java:3)
7/5/2017 11:38:46 AM	at io.cattle.platform.lock.impl.AbstractLockManagerImpl$3.doWithLock(AbstractLockManagerImpl.java:40)
7/5/2017 11:38:46 AM	at io.cattle.platform.lock.impl.LockManagerImpl.doLock(LockManagerImpl.java:33)
7/5/2017 11:38:46 AM	at io.cattle.platform.lock.impl.AbstractLockManagerImpl.lock(AbstractLockManagerImpl.java:13)
7/5/2017 11:38:46 AM	at io.cattle.platform.lock.impl.AbstractLockManagerImpl.lock(AbstractLockManagerImpl.java:37)
7/5/2017 11:38:46 AM	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.acquireLockAndRun(DefaultProcessInstanceImpl.java:222)
7/5/2017 11:38:46 AM	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.runAndHandleExceptions(DefaultProcessInstanceImpl.java:187)
7/5/2017 11:38:46 AM	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.executeWithProcessInstanceLock(DefaultProcessInstanceImpl.java:151)
7/5/2017 11:38:46 AM	at io.cattle.platform.engine.process.impl.DefaultProcessInstanceImpl.execute(DefaultProcessInstanceImpl.java:120)
7/5/2017 11:38:46 AM	at io.cattle.platform.engine.server.impl.ProcessInstanceDispatcherImpl.execute(ProcessInstanceDispatcherImpl.java:42)
7/5/2017 11:38:46 AM	at io.cattle.platform.engine.server.impl.ProcessInstanceDispatcherImpl.execute(ProcessInstanceDispatcherImpl.java:28)
7/5/2017 11:38:46 AM	at io.cattle.platform.engine.server.ProcessServer.execute(ProcessServer.java:148)
7/5/2017 11:38:46 AM	at io.cattle.platform.engine.model.ProcessInstanceWrapper.doRun(ProcessInstanceWrapper.java:78)
7/5/2017 11:38:46 AM	at org.apache.cloudstack.managed.context.NoExceptionRunnable.runInContext(NoExceptionRunnable.java:15)
7/5/2017 11:38:46 AM	at org.apache.cloudstack.managed.context.ManagedContextRunnable$1.run(ManagedContextRunnable.java:49)
7/5/2017 11:38:46 AM	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext$1.call(DefaultManagedContext.java:55)
7/5/2017 11:38:46 AM	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.callWithContext(DefaultManagedContext.java:108)
7/5/2017 11:38:46 AM	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.runWithContext(DefaultManagedContext.java:52)
7/5/2017 11:38:46 AM	at org.apache.cloudstack.managed.context.ManagedContextRunnable.run(ManagedContextRunnable.java:46)
7/5/2017 11:38:46 AM	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
7/5/2017 11:38:46 AM	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
7/5/2017 11:38:46 AM	at java.lang.Thread.run(Thread.java:745)
```

**Comment by vincent99** [comment]
What's happening is:
  1. The host is created and docker installed
  2. GMS PUTs to the machine to store the certs and such as extractedConfig
  3. Cattle returns OK and has the right config in the response
  4. The create event ends and registering the agent event starts
  5. GMS immediately GETs the machine again.
  6. Cattle returns OK, but **sometimes** with a null extractedConfig
  7. GMS can't restore the machine dir, makes a call to docker-machine, which exits 1 because it's operating on an empty folder.
  8. The event fails and error is shown to the user.
  9. Bonus: On delete of the host, the underlying VM isn't cleaned up for the same reason (there's no config for docker-machine to operate on)

Cleaned up tcpdump of communication between GMS <-> Cattle:

```PUT /v2-beta/machines/1ph131 HTTP/1.1
Host: localhost:8080
User-Agent: Go-http-client/1.1
Content-Length: 11602
Authorization: Basic <redacted>
Content-Type: application/json
Accept-Encoding: gzip

{
  "links": null,
  "actions": null,
  "extractedConfig": "<redacted correct config>"
}

HTTP/1.1 200 OK
Content-Type: application/json; charset=utf-8
Date: Thu, 06 Jul 2017 00:36:48 GMT
Expires: Thu, 01 Jan 1970 00:00:00 GMT
Server: Jetty(9.2.11.v20150529)
Set-Cookie: PL=rancher;Path=/
X-Api-Account-Id: 1a6
X-Api-Client-Ip: ::1
X-Api-Schemas: http://localhost:8080/v2-beta/schemas
X-Api-User-Id: 1a6
Transfer-Encoding: chunked

{
  "id": "1ph131",
  "type": "machine",
  "links": {
    "self": "http://localhost:8080/v2-beta/machines/1ph131",
    "account": "http://localhost:8080/v2-beta/machines/1ph131/account",
    "hosts": "http://localhost:8080/v2-beta/machines/1ph131/hosts",
    "config": "http://localhost:8080/v2-beta/machines/1ph131/config"
  },
  "actions": {
    "bootstrap": "http://localhost:8080/v2-beta/machines/1ph131/?action=bootstrap",
    "error": "http://localhost:8080/v2-beta/machines/1ph131/?action=error",
    "remove": "http://localhost:8080/v2-beta/machines/1ph131/?action=remove"
  },
  "baseType": "physicalHost",
  "name": "vjf-32",
  "state": "creating",
  "accountId": "1a48544",
  "amazonec2Config": null,
  "authCertificateAuthority": null,
  "authKey": null,
  "azureConfig": null,
  "created": "2017-07-06T00:35:01Z",
  "createdTS": 1499301301000,
  "data": {
    "fields": {
      "hostname": "vjf-32",
      "labels": {},
      "transitioningMessage": "Checking connection to Docker...",
      "extractedConfig": "<redacted encrypted config>"
    }
  },
  "description": null,
  "digitaloceanConfig": null,
  "dockerVersion": null,
  "driver": "digitalocean",
  "engineEnv": null,
  "engineInsecureRegistry": null,
  "engineInstallUrl": null,
  "engineLabel": null,
  "engineOpt": null,
  "engineRegistryMirror": null,
  "engineStorageDriver": null,
  "externalId": "c790d375-3983-4257-bc7b-4fa887bcd07c",
  "extractedConfig": "<redacted correct config>",
  "hostTemplateId": null,
  "kind": "machine",
  "labels": {},
  "packetConfig": null,
  "removeTime": null,
  "removed": null,
  "transitioning": "yes",
  "transitioningMessage": "Checking connection to Docker...",
  "transitioningProgress": null,
  "uuid": "f5e9961f-b279-4fa4-929b-5593a3744709"
}

POST /v2-beta/publish HTTP/1.1
Host: localhost:8080
User-Agent: Go-http-client/1.1
Content-Length: 119
Authorization: Basic <redacted>
Content-Type: application/json
Accept-Encoding: gzip

{"links":null,"actions":null,"name":"reply.6014174101131954537","previousIds":["7c0a5f12-013f-46ae-a064-51c2b2773607"]}

HTTP/1.1 201 Created
Content-Length: 0
Date: Thu, 06 Jul 2017 00:36:48 GMT
Expires: Thu, 01 Jan 1970 00:00:00 GMT
Server: Jetty(9.2.11.v20150529)
Set-Cookie: PL=rancher;Path=/
X-Api-Account-Id: 1a6
X-Api-Client-Ip: ::1
X-Api-Schemas: http://localhost:8080/v2-beta/schemas
X-Api-User-Id: 1a6
Content-Type: text/plain; charset=utf-8

GET /v2-beta/machines/1ph131 HTTP/1.1
Host: localhost:8080
User-Agent: Go-http-client/1.1
Authorization: Basic <redacted>
Accept-Encoding: gzip

HTTP/1.1 200 OK
Content-Encoding: gzip
Content-Type: application/json; charset=utf-8
Date: Thu, 06 Jul 2017 00:36:48 GMT
Expires: Thu, 01 Jan 1970 00:00:00 GMT
Server: Jetty(9.2.11.v20150529)
Set-Cookie: PL=rancher;Path=/
Vary: Accept-Encoding, User-Agent
X-Api-Account-Id: 1a6
X-Api-Client-Ip: ::1
X-Api-Schemas: http://localhost:8080/v2-beta/schemas
X-Api-User-Id: 1a6
Content-Length: 561

{
  "id": "1ph131",
  "type": "machine",
  "links": {
    "self": "http://localhost:8080/v2-beta/machines/1ph131",
    "account": "http://localhost:8080/v2-beta/machines/1ph131/account",
    "hosts": "http://localhost:8080/v2-beta/machines/1ph131/hosts"
  },
  "actions": {
    "error": "http://localhost:8080/v2-beta/machines/1ph131/?action=error",
    "remove": "http://localhost:8080/v2-beta/machines/1ph131/?action=remove"
  },
  "baseType": "physicalHost",
  "name": "vjf-32",
  "state": "bootstrapping",
  "accountId": "1a48544",
  "amazonec2Config": null,
  "authCertificateAuthority": null,
  "authKey": null,
  "azureConfig": null,
  "created": "2017-07-06T00:35:01Z",
  "createdTS": 1499301301000,
  "data": {
    "fields": {
      "hostname": "vjf-32",
      "labels": {}
    }
  },
  "description": null,
  "digitaloceanConfig": null,
  "dockerVersion": null,
  "driver": "digitalocean",
  "engineEnv": null,
  "engineInsecureRegistry": null,
  "engineInstallUrl": null,
  "engineLabel": null,
  "engineOpt": null,
  "engineRegistryMirror": null,
  "engineStorageDriver": null,
  "externalId": "c790d375-3983-4257-bc7b-4fa887bcd07c",
  "extractedConfig": null,
  "hostTemplateId": null,
  "kind": "machine",
  "labels": {},
  "packetConfig": null,
  "removeTime": null,
  "removed": null,
  "transitioning": "yes",
  "transitioningMessage": "In Progress",
  "transitioningProgress": null,
  "uuid": "f5e9961f-b279-4fa4-929b-5593a3744709"
}

GET /v2-beta/hosts?physicalHostId=1ph131 HTTP/1.1
Host: localhost:8080
User-Agent: Go-http-client/1.1
Authorization: Basic <redacted>
Accept-Encoding: gzip

HTTP/1.1 200 OK
Content-Encoding: gzip
Content-Type: application/json; charset=utf-8
Date: Thu, 06 Jul 2017 00:36:48 GMT
Expires: Thu, 01 Jan 1970 00:00:00 GMT
Server: Jetty(9.2.11.v20150529)
Set-Cookie: PL=rancher;Path=/
Vary: Accept-Encoding, User-Agent
X-Api-Account-Id: 1a6
X-Api-Client-Ip: ::1
X-Api-Schemas: http://localhost:8080/v2-beta/schemas
X-Api-User-Id: 1a6
Content-Length: 1220

{
  "type": "collection",
  "resourceType": "host",
  "links": {
    "self": "http://localhost:8080/v2-beta/hosts"
  },
  "createTypes": {},
  "actions": {},
  "data": [
    {
      "id": "1h132",
      "type": "host",
      "links": {
        "self": "http://localhost:8080/v2-beta/hosts/1h132",
        "account": "http://localhost:8080/v2-beta/hosts/1h132/account",
        "clusters": "http://localhost:8080/v2-beta/hosts/1h132/clusters",
        "configItemStatuses": "http://localhost:8080/v2-beta/hosts/1h132/configitemstatuses",
        "containerEvents": "http://localhost:8080/v2-beta/hosts/1h132/containerevents",
        "deploymentUnits": "http://localhost:8080/v2-beta/hosts/1h132/deploymentunits",
        "healthcheckInstanceHostMaps": "http://localhost:8080/v2-beta/hosts/1h132/healthcheckinstancehostmaps",
        "hostLabels": "http://localhost:8080/v2-beta/hosts/1h132/hostlabels",
        "hostTemplate": "http://localhost:8080/v2-beta/hosts/1h132/hosttemplate",
        "hosts": "http://localhost:8080/v2-beta/hosts/1h132/hosts",
        "instances": "http://localhost:8080/v2-beta/hosts/1h132/instances",
        "ipAddresses": "http://localhost:8080/v2-beta/hosts/1h132/ipaddresses",
        "physicalHost": "http://localhost:8080/v2-beta/hosts/1h132/physicalhost",
        "serviceEvents": "http://localhost:8080/v2-beta/hosts/1h132/serviceevents",
        "storagePools": "http://localhost:8080/v2-beta/hosts/1h132/storagepools",
        "volumes": "http://localhost:8080/v2-beta/hosts/1h132/volumes",
        "config": "http://localhost:8080/v2-beta/hosts/1h132/config"
      },
      "actions": {
        "error": "http://localhost:8080/v2-beta/hosts/1h132/?action=error",
        "remove": "http://localhost:8080/v2-beta/hosts/1h132/?action=remove"
      },
      "baseType": "host",
      "name": "vjf-32",
      "state": "provisioning",
      "accountId": "1a48544",
      "agentId": null,
      "agentIpAddress": null,
      "agentState": null,
      "amazonec2Config": null,
      "apiProxy": null,
      "authCertificateAuthority": null,
      "authKey": null,
      "azureConfig": null,
      "computeTotal": 1000000,
      "created": "2017-07-06T00:35:00Z",
      "createdTS": 1499301300000,
      "data": {
        "fields": {
          "hostname": "vjf-32",
          "labels": {},
          "reportedUuid": "c790d375-3983-4257-bc7b-4fa887bcd07c",
          "driver": "digitalocean",
          "transitioningMessage": "Checking connection to Docker..."
        }
      },
      "description": null,
      "digitaloceanConfig": null,
      "dockerVersion": null,
      "driver": "digitalocean",
      "engineEnv": null,
      "engineInsecureRegistry": null,
      "engineInstallUrl": null,
      "engineLabel": null,
      "engineOpt": null,
      "engineRegistryMirror": null,
      "engineStorageDriver": null,
      "extractedConfig": null,
      "hostTemplateId": "1ht32",
      "hostname": "vjf-32",
      "info": null,
      "instanceIds": null,
      "kind": "host",
      "labels": {},
      "localStorageMb": null,
      "memory": null,
      "milliCpu": null,
      "packetConfig": null,
      "physicalHostId": "1ph131",
      "publicEndpoints": null,
      "removeTime": null,
      "removed": null,
      "stackId": null,
      "transitioning": "yes",
      "transitioningMessage": "Checking connection to Docker...",
      "transitioningProgress": null,
      "uuid": "8fc274e8-e058-4c75-8e50-43a66d0ba819"
    }
  ],
  "sortLinks": {
    "accountId": "http://localhost:8080/v2-beta/hosts?physicalHostId=1ph131&sort=accountId",
    "agentId": "http://localhost:8080/v2-beta/hosts?physicalHostId=1ph131&sort=agentId",
    "agentState": "http://localhost:8080/v2-beta/hosts?physicalHostId=1ph131&sort=agentState",
    "computeFree": "http://localhost:8080/v2-beta/hosts?physicalHostId=1ph131&sort=computeFree",
    "computeTotal": "http://localhost:8080/v2-beta/hosts?physicalHostId=1ph131&sort=computeTotal",
    "created": "http://localhost:8080/v2-beta/hosts?physicalHostId=1ph131&sort=created",
    "description": "http://localhost:8080/v2-beta/hosts?physicalHostId=1ph131&sort=description",
    "hostTemplateId": "http://localhost:8080/v2-beta/hosts?physicalHostId=1ph131&sort=hostTemplateId",
    "id": "http://localhost:8080/v2-beta/hosts?physicalHostId=1ph131&sort=id",
    "isPublic": "http://localhost:8080/v2-beta/hosts?physicalHostId=1ph131&sort=isPublic",
    "kind": "http://localhost:8080/v2-beta/hosts?physicalHostId=1ph131&sort=kind",
    "localStorageMb": "http://localhost:8080/v2-beta/hosts?physicalHostId=1ph131&sort=localStorageMb",
    "memory": "http://localhost:8080/v2-beta/hosts?physicalHostId=1ph131&sort=memory",
    "milliCpu": "http://localhost:8080/v2-beta/hosts?physicalHostId=1ph131&sort=milliCpu",
    "name": "http://localhost:8080/v2-beta/hosts?physicalHostId=1ph131&sort=name",
    "physicalHostId": "http://localhost:8080/v2-beta/hosts?physicalHostId=1ph131&sort=physicalHostId",
    "removeAfter": "http://localhost:8080/v2-beta/hosts?physicalHostId=1ph131&sort=removeAfter",
    "removeTime": "http://localhost:8080/v2-beta/hosts?physicalHostId=1ph131&sort=removeTime",
    "removed": "http://localhost:8080/v2-beta/hosts?physicalHostId=1ph131&sort=removed",
    "stackId": "http://localhost:8080/v2-beta/hosts?physicalHostId=1ph131&sort=stackId",
    "state": "http://localhost:8080/v2-beta/hosts?physicalHostId=1ph131&sort=state",
    "uri": "http://localhost:8080/v2-beta/hosts?physicalHostId=1ph131&sort=uri",
    "uuid": "http://localhost:8080/v2-beta/hosts?physicalHostId=1ph131&sort=uuid"
  },
  "pagination": {
    "first": null,
    "previous": null,
    "next": null,
    "limit": 100,
    "total": null,
    "partial": false
  },
  "sort": null,
  "filters": {
    "accountId": null,
    "agentId": null,
    "agentState": null,
    "computeFree": null,
    "computeTotal": null,
    "created": null,
    "description": null,
    "hostTemplateId": null,
    "id": null,
    "isPublic": null,
    "kind": null,
    "localStorageMb": null,
    "memory": null,
    "milliCpu": null,
    "name": null,
    "physicalHostId": [
      {
        "modifier": "eq",
        "value": "131"
      }
    ],
    "removeAfter": null,
    "removeTime": null,
    "removed": null,
    "stackId": null,
    "state": null,
    "uri": null,
    "uuid": null
  },
  "createDefaults": {}
}

GET /v2-beta/hosttemplates/1ht32 HTTP/1.1
Host: localhost:8080
User-Agent: Go-http-client/1.1
Authorization: Basic <redacted>
Accept-Encoding: gzip

HTTP/1.1 200 OK
Content-Encoding: gzip
Content-Type: application/json; charset=utf-8
Date: Thu, 06 Jul 2017 00:36:48 GMT
Expires: Thu, 01 Jan 1970 00:00:00 GMT
Server: Jetty(9.2.11.v20150529)
Set-Cookie: PL=rancher;Path=/
Vary: Accept-Encoding, User-Agent
X-Api-Account-Id: 1a6
X-Api-Client-Ip: ::1
X-Api-Schemas: http://localhost:8080/v2-beta/schemas
X-Api-User-Id: 1a6
Content-Length: 1025

{
  "id": "1ht32",
  "type": "hostTemplate",
  "links": {
    "self": "http://localhost:8080/v2-beta/hosttemplates/1ht32",
    "account": "http://localhost:8080/v2-beta/hosttemplates/1ht32/account",
    "hosts": "http://localhost:8080/v2-beta/hosttemplates/1ht32/hosts",
    "secretValues": "http://localhost:8080/v2-beta/hosttemplates/1ht32/secretvalues"
  },
  "actions": {
    "remove": "http://localhost:8080/v2-beta/hosttemplates/1ht32/?action=remove"
  },
  "baseType": "hostTemplate",
  "name": "vjf-a-new-env",
  "state": "active",
  "accountId": "1a48544",
  "created": "2017-07-05T18:36:38Z",
  "createdTS": 1499279798000,
  "data": {
    "fields": {
      "publicValues": {
        "digitaloceanConfig": {
          "accessToken": "",
          "image": "ubuntu-16-04-x64",
          "region": "nyc3",
          "size": "1gb",
          "sshKeyFingerprint": "",
          "sshKeyPath": "",
          "sshPort": "22",
          "sshUser": "root",
          "userdata": "",
          "type": "digitaloceanConfig"
        },
        "engineInstallUrl": "https://releases.rancher.com/install-docker/1.12.sh",
        "engineOpt": {},
        "engineLabel": {},
        "engineEnv": {},
        "labels": {
          "a": "label"
        }
      },
      "secretValues": "<redacted>",
      "secretValuesEmpty": {
        "digitaloceanConfig": {
          "accessToken": null
        }
      }
    }
  },
  "description": "nyc3 / 1gb",
  "driver": "digitalocean",
  "flavorPrefix": null,
  "kind": "hostTemplate",
  "publicValues": {
    "digitaloceanConfig": {
      "accessToken": "",
      "image": "ubuntu-16-04-x64",
      "region": "nyc3",
      "size": "1gb",
      "sshKeyFingerprint": "",
      "sshKeyPath": "",
      "sshPort": "22",
      "sshUser": "root",
      "userdata": "",
      "type": "digitaloceanConfig"
    },
    "engineInstallUrl": "https://releases.rancher.com/install-docker/1.12.sh",
    "engineOpt": {},
    "engineLabel": {},
    "engineEnv": {},
    "labels": {
      "a": "label"
    }
  },
  "removeTime": null,
  "removed": null,
  "secretValues": {
    "digitaloceanConfig": {
      "accessToken": null
    }
  },
  "transitioning": "no",
  "transitioningMessage": null,
  "transitioningProgress": null,
  "uuid": "8f09149f-693c-4309-a7a0-968878b68f75"
}

GET /v2-beta/hosttemplates/1ht32/secretvalues HTTP/1.1
Host: localhost:8080
User-Agent: Go-http-client/1.1
Authorization: Basic <redacted>
Accept-Encoding: gzip

HTTP/1.1 200 OK
Content-Encoding: gzip
Content-Length: 112
Content-Type: application/json
Date: Thu, 06 Jul 2017 00:36:48 GMT
Expires: Thu, 01 Jan 1970 00:00:00 GMT
Server: Jetty(9.2.11.v20150529)
Set-Cookie: PL=rancher;Path=/
Vary: Accept-Encoding, User-Agent
X-Api-Account-Id: 1a6
X-Api-Client-Ip: ::1
X-Api-Schemas: http://localhost:8080/v2-beta/schemas
X-Api-User-Id: 1a6

{"digitaloceanConfig":{"accessToken":"<redacted>"}}

GET /v2-beta/registrationtokens?accountId=1a48544&state=active HTTP/1.1
Host: localhost:8080
User-Agent: Go-http-client/1.1
Authorization: Basic <redacted>
Accept-Encoding: gzip

HTTP/1.1 200 OK
Content-Encoding: gzip
Content-Type: application/json; charset=utf-8
Date: Thu, 06 Jul 2017 00:36:48 GMT
Expires: Thu, 01 Jan 1970 00:00:00 GMT
Server: Jetty(9.2.11.v20150529)
Set-Cookie: PL=rancher;Path=/
Vary: Accept-Encoding, User-Agent
X-Api-Account-Id: 1a6
X-Api-Client-Ip: ::1
X-Api-Schemas: http://localhost:8080/v2-beta/schemas
X-Api-User-Id: 1a6
Content-Length: 843

{
  "type": "collection",
  "resourceType": "registrationToken",
  "links": {
    "self": "http://localhost:8080/v2-beta/registrationtokens"
  },
  "createTypes": {},
  "actions": {},
  "data": [
    {
      "id": "1c48556",
      "type": "registrationToken",
      "links": {
        "self": "http://localhost:8080/v2-beta/registrationtokens/1c48556",
        "account": "http://localhost:8080/v2-beta/registrationtokens/1c48556/account",
        "instances": "http://localhost:8080/v2-beta/registrationtokens/1c48556/instances",
        "registrationUrl": "<redacted>"
      },
      "actions": {
        "update": "http://localhost:8080/v2-beta/registrationtokens/1c48556/?action=update",
        "deactivate": "http://localhost:8080/v2-beta/registrationtokens/1c48556/?action=deactivate"
      },
      "baseType": "credential",
      "name": null,
      "state": "active",
      "accountId": "1a48544",
      "command": "<redacted>",
      "created": "2017-07-05T18:38:45Z",
      "createdTS": 1499279925000,
      "data": {},
      "description": null,
      "image": "rancher/agent:v1.2.3-rc2",
      "kind": "registrationToken",
      "registrationUrl": "<redacted>",
      "removeTime": null,
      "removed": null,
      "token": "<redacted>",
      "transitioning": "no",
      "transitioningMessage": null,
      "transitioningProgress": null,
      "uuid": "3a89957d-f00c-4139-98d9-bc32716d04fe"
    }
  ],
  "sortLinks": {
    "accountId": "http://localhost:8080/v2-beta/registrationtokens?accountId=1a48544&state=active&sort=accountId",
    "created": "http://localhost:8080/v2-beta/registrationtokens?accountId=1a48544&state=active&sort=created",
    "description": "http://localhost:8080/v2-beta/registrationtokens?accountId=1a48544&state=active&sort=description",
    "id": "http://localhost:8080/v2-beta/registrationtokens?accountId=1a48544&state=active&sort=id",
    "kind": "http://localhost:8080/v2-beta/registrationtokens?accountId=1a48544&state=active&sort=kind",
    "name": "http://localhost:8080/v2-beta/registrationtokens?accountId=1a48544&state=active&sort=name",
    "publicValue": "http://localhost:8080/v2-beta/registrationtokens?accountId=1a48544&state=active&sort=publicValue",
    "registryId": "http://localhost:8080/v2-beta/registrationtokens?accountId=1a48544&state=active&sort=registryId",
    "removeTime": "http://localhost:8080/v2-beta/registrationtokens?accountId=1a48544&state=active&sort=removeTime",
    "removed": "http://localhost:8080/v2-beta/registrationtokens?accountId=1a48544&state=active&sort=removed",
    "secretValue": "http://localhost:8080/v2-beta/registrationtokens?accountId=1a48544&state=active&sort=secretValue",
    "state": "http://localhost:8080/v2-beta/registrationtokens?accountId=1a48544&state=active&sort=state",
    "uuid": "http://localhost:8080/v2-beta/registrationtokens?accountId=1a48544&state=active&sort=uuid"
  },
  "pagination": {
    "first": null,
    "previous": null,
    "next": null,
    "limit": 100,
    "total": null,
    "partial": false
  },
  "sort": null,
  "filters": {
    "accountId": [
      {
        "modifier": "eq",
        "value": "48544"
      }
    ],
    "created": null,
    "description": null,
    "id": null,
    "kind": null,
    "name": null,
    "publicValue": null,
    "registryId": null,
    "removeTime": null,
    "removed": null,
    "secretValue": null,
    "state": [
      {
        "modifier": "eq",
        "value": "active"
      }
    ],
    "uuid": null
  },
  "createDefaults": {}
}

POST /v2-beta/publish HTTP/1.1
Host: localhost:8080
User-Agent: Go-http-client/1.1
Content-Length: 215
Authorization: Basic <redacted>
Content-Type: application/json
Accept-Encoding: gzip

{
  "links": null,
  "actions": null,
  "name": "reply.6014174101131954537",
  "previousIds": [
    "bdf1f9e5-4b1f-4c98-91e3-2f34425674ca"
  ],
  "transitioning": "error",
  "transitioningMessage": "Error getting connection config: exit status 1"
}

HTTP/1.1 201 Created
Content-Length: 0
Date: Thu, 06 Jul 2017 00:36:48 GMT
Expires: Thu, 01 Jan 1970 00:00:00 GMT
Server: Jetty(9.2.11.v20150529)
Set-Cookie: PL=rancher;Path=/
X-Api-Account-Id: 1a6
X-Api-Client-Ip: ::1
X-Api-Schemas: http://localhost:8080/v2-beta/schemas
X-Api-User-Id: 1a6
Content-Type: text/plain; charset=utf-8
```

**Comment by deniseschannon** [comment]
@StrongMonkey I think this is fixed, but can you double check it before assigning to-test?

**Comment by StrongMonkey** [comment]
@deniseschannon yes, this shouldn't happen as we changed the whole implementation.

**Comment by tfiduccia** [comment]
This is still not working.  I still have a host that will randomly fail.

**Comment by StrongMonkey** [comment]
This issue is due to a conflict on saving host's credential into rancher database. This should be unrelated to adding host randomly failure. We still need to figure out why the random failure happens. Related issue: https://github.com/rancher/rancher/issues/9712

**Comment by dgaffney-dorado** [comment]
FYI this issue is still occurring in Rancher 1.6.18.
It appears to be a race condition caused when provisioning multiple EC2 instances with the rancher aws provider at a time.

> Comment: Looks to be some sort of timing issue as if I have start a bunch at the same time, 1/2 of them will actually succeed.
