### ISSUE TITLE
[machine driver page] Click the "up to date" button, enter the error page.

### ISSUE THREAD

**Issue by Tracy1994** [rancher/rancher#9786]
**Rancher versions:**
rancher/server: stable

**Steps to Reproduce:**
1. ADMIN tab -> Machine driver
2.Click the "up to date" button.
![image](https://user-images.githubusercontent.com/18595707/29829704-acef5e40-8d12-11e7-8135-605a9c4a57d9.png)

**Results:**
1. Enter an error page.
2. Aliyun icon cannot be seen.

**expectation**
1. "Up to date" button cannot be click.
2. Aliyun icon can been seen.

@yasker

**Comment by yasker** [comment]
Icon issue has been fixed at https://github.com/rancher/community-catalog/pull/619

**Comment by yasker** [comment]
@n313893254 where is the PR? And if it's `status/resolved`, you need to move it to `Review` pipeline. Refer to the process flowchart.

**Comment by vincent99** [comment]
I think I closed it because I didn't notice it was an employee and it didn't fix the problem the right way or explain what it was for the machine page vs stack upgrade.

**Comment by yasker** [comment]
@vincent99 I will ask him to fix that.

**Comment by yasker** [comment]
@n313893254 1.6 fix merged. Please open another PR for 2.0 UI fix if needed as @vincent99 commented in the PR.

**Comment by n313893254** [comment]
ok

**Comment by tfiduccia** [comment]
Version - 2.0 master 10/16 - this is fixed
Version - 1.6 master 10/16 - Not fixed, still going to error page when I click on Up to date.

**Comment by tfiduccia** [comment]
Sorry this is actually fixed in 1.6.  I had the wrong UI tag.
